### ISSUE TITLE
DWSIM6 compilation issue

### ISSUE THREAD

**Issue by mauro-galbiati** [DanWBR/dwsim6#1]
Hi Daniel, just wanted to let you know that the solution won't flawlessly compile on Visual Studio 2017.
Here is the error list after a 'Build>clean'.

Keep up coding!
![list](https://user-images.githubusercontent.com/16943433/81426439-7e948180-9159-11ea-8ffe-5bf9059609f5.png)

**Comment by DanWBR** [comment]
I could never guess that you are 'jijua'. :D

**Comment by DanWBR** [comment]
As I've wrote in the ticket, supported build configurations are Debug/x64, Release WinMac/x64 and Release Linux/x64.

**Comment by mauro-galbiati** [comment]
Debug/x64 config is working, Win release one is not. Not tested the Linux release yet

**Comment by DanWBR** [comment]
Sometimes you need to restart VS after restoring all NuGet packages, due to issues with CefSharp.
