### ISSUE TITLE
Inconsistent big icons and blurry toolbar DWSIM 6 Update 1

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#10]
**Describe the bug**
Update 1 for DWSIM 6 brings some fix for high resolution screens but it seems unintentionally most of icons on toolbar and local menu and menu bar got inconsistent big size. I have attached some images. I did not such issue in DWSIM 6. or 6.1

Tested on
Windows 10
Screen 1920x1080 Full HD
DWSIM 6 Update 1

Look at the last three icons (right)

![image-199](https://user-images.githubusercontent.com/830394/89498392-66bdaf80-d7d3-11ea-83f0-9e24d85e188e.png)

![image-200](https://user-images.githubusercontent.com/830394/89498368-5c9bb100-d7d3-11ea-8b79-0d8af69faf6c.png)

**Comment by DanWBR** [comment]
Fixed. Please re-download the installer 👍🏻

**Comment by kookma** [comment]
Thanks Daniel
