### ISSUE TITLE
[Bug] OptimizationForm; Index out of bounds error types.

### ISSUE THREAD

**Issue by JarlPed** [DanWBR/dwsim6#101]
I have discovered some code typos for the optimization routines for variable sensitivity regarding index out of bounds errors in the function evaluation and gradients. I have a branch that fixes the problem (for the moment tested for constrained BFGS 2). I may issue an PR, but I dont know where to sign the CLA.

**Comment by DanWBR** [comment]
@JarlPed the CLA link will be shown in the PR after you create it. Thanks
