### ISSUE TITLE
The field is not updated correctly after the method converges

### ISSUE THREAD

**Issue by JohnEEng** [DanWBR/dwsim6#111]
Hi, 

The value of the energy flow is different from that shown in the Master Property Table after the system converges to the solution. Please see attached screenshot.

![image](https://user-images.githubusercontent.com/78353746/106451785-f9879000-647e-11eb-9620-64d20beb5654.png)

Thanks.

IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS]
 - Version [e.g. v6.4.1]

**Additional context**

**Comment by DanWBR** [comment]
Which DWSIM version are you running?

**Comment by JohnEEng** [comment]
> Which DWSIM version are you running?
Hi @DanWBR, I am using version  6.4.2

**Comment by DanWBR** [comment]
@JohnEEng can you attach a sample case? I could not reproduce this bug. Thanks

**Comment by JohnEEng** [comment]
@DanWBR, this happens when I disable the Solve Globally option in the Controller Block Parameter and solve the system using one of the numerical methods (Secant, Brent) within the Controller Block Control Panel. 
[Sim.zip](https://github.com/DanWBR/dwsim6/files/5912348/Sim.zip)
