### ISSUE TITLE
Multiple Bugs

### ISSUE THREAD

**Issue by Jamesincolorado** [DanWBR/dwsim6#113]
1. The attached file does not calculate the liquid stream from separator sep-3. 
2. The outlet of the saturator is hotter than the inlet. 
3. Splitter splt-01 does not solve. 

Thank you.
[FGC.zip](https://github.com/DanWBR/dwsim6/files/5935625/FGC.zip)

**Comment by DanWBR** [comment]
1. A liquid stream appears in v6.4.3
2. You need a more elaborate saturator script at such conditions, as the current result doesn't seem right
3. You need to connect a stream to the outlet port #1.
