### ISSUE TITLE
No Elements

### ISSUE THREAD

**Issue by Jamesincolorado** [DanWBR/dwsim6#115]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
Heat Exchanger will not run. Error: "no elements."

**To Reproduce**
1. Run file
2. See error

**Expected behavior**
The heat exchanger should solve based on the configuration provided. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 
[FGC.zip](https://github.com/DanWBR/dwsim6/files/5937739/FGC.zip)
37

**Additional context**

**Comment by DanWBR** [comment]
I'm not able to run the heat exchanger in the attached file because it is not connected to any stream.

**Comment by Jamesincolorado** [comment]
Yes it does! Why are they red and not blue? I run into this all the time. It's liking hitting a brick wall and renders the software useless.

**Comment by DanWBR** [comment]
This is how your flowsheet appears to me. The two heat exchangers are not connected to anything.

<img width="1472" alt="Captura de Tela 2021-02-18 às 14 22 33" src="https://user-images.githubusercontent.com/2669419/108403165-ce2dd080-71f4-11eb-9555-0ca7e26ef64c.png">

**Comment by Jamesincolorado** [comment]
Try this one.

[no elements.zip](https://github.com/DanWBR/dwsim6/files/6005017/no.elements.zip)

**Comment by DanWBR** [comment]
Calculating normally in v6.4.3:

<img width="1536" alt="Captura de Tela 2021-02-18 às 14 38 19" src="https://user-images.githubusercontent.com/2669419/108405033-fcacab00-71f6-11eb-9da8-63a801ca2208.png">

**Comment by Jamesincolorado** [comment]
Fix confirmed in v6.4.3. Thank you!

James

**Comment by Jamesincolorado** [comment]
"no elements" message in heat exchanger rating mode. 
[shell and tube rating -- no elements.zip](https://github.com/DanWBR/dwsim6/files/6005953/shell.and.tube.rating.--.no.elements.zip)

**Comment by DanWBR** [comment]
check the dimensions of the exchanger.

**Comment by Jamesincolorado** [comment]
This is a simple double pipe heat exchanger: 3" shell with a single 2" tube. Will DWSIM accommodate this configuration? Perhaps you could provide guidance on the entries for the tube spacing (there is only one tube) and the baffle spacing (there aren't any). 

Thank you.

**Comment by DanWBR** [comment]
@Jamesincolorado I think that this configuration is not supported.
