### ISSUE TITLE
Issue with recycling mixed streams

### ISSUE THREAD

**Issue by mirutoyoshi** [DanWBR/dwsim6#117]
Hi, 
Version 6.4.3, Windows 10 64bit.

I'm seeing an issue in multiple flowsheets when using stream mixing and recycle loops. 
I've tried LKP and Coolprop packages - both fail. 

Images below are a simple example of the issue, created fresh. 

When I attatch a recycle loop to a stream that has been mixed, I get an incorrect result in the outlet temperature of the mixer block ~77K (note this happens at MSTR--06 (3) even if there is another block between it and the REC block):
![image](https://user-images.githubusercontent.com/39650740/108547639-a9178b80-72e2-11eb-97c1-7ef5254b97ff.png)

If the recycle loop is disabled, The calculation is correct ~310K:
![image](https://user-images.githubusercontent.com/39650740/108547803-debc7480-72e2-11eb-9db1-a0e400fdb304.png)

Example is here:
[Mixer_bug.zip](https://github.com/DanWBR/dwsim6/files/6012362/Mixer_bug.zip)

I tried some earlier DWSIM versions I had available: 
v640, v63u7 both exhibit this issue for me
v61u10 I get the expected behaviour.

Thanks

**Comment by DanWBR** [comment]
This was a critical bug. Thank you very much!
