### ISSUE TITLE
UNIFAC-LL

### ISSUE THREAD

**Issue by eliasjr70** [DanWBR/dwsim6#118]
Dear Daniel, I have been trying for some time to use the UNIFAC model with parameters for liquid-liquid equilibrium (UNIFAC-LL) but I always get a error "parameter not found". The curious thing is that this occurs for subgroups within the same main group ... A short video of the error is attached. Using another UNIFAC, either original one or UNIFAC-NIST, there is no problem. A file with the simulation prepared in the video is also attached. If I can provide any more useful information, please let me know.
Regards,
Elias.
[teste_LL.zip](https://github.com/DanWBR/dwsim6/files/6038172/teste_LL.zip)
https://user-images.githubusercontent.com/79600458/109049018-87d5e700-76b6-11eb-8643-41f1c921d944.mp4
[https://youtu.be/xjszz6RgF-o](url)

**Comment by DanWBR** [comment]
@eliasjr70, this is because UNIFAC-LL doesn't have many parameters. You can use one of the Modified UNIFAC methods as their parameters were regressed from LLE data too, so it is safe to use.

**Comment by eliasjr70** [comment]
Thanks for the quick answer!.  But shouldn't we expect any interaction between CH / CH2 groups and other ordinary groups such as H2O and OH?  Moreover, they seem to be present:
![image](https://user-images.githubusercontent.com/79600458/109059789-64656900-76c3-11eb-83bf-c82faab0bf0d.png)
These are the parameters of MAGNUSSEN et al. (1981), right?
Regards!

**Comment by DanWBR** [comment]
@eliasjr70 that's a hard question. This is one of the oldest property packages in DWSIM, I remember reading the original paper, I probably have it here in one of my backups.

**Comment by eliasjr70** [comment]
No worry about the reference, @DanWBR.  My concern is about the proper functioning of the package.  I tried to illustrate the use of different models in LLE calculations to my Thermodynamics students, then I got the error.  Then I tried to edit the parameter table to fill up the missing ones, but they're already there as you can see in my previous message.

**Comment by DanWBR** [comment]
I've fixed the error but it seems that UNIFAC-LL is not suitable for anything other than LLE, that is, it won't generate a nice-looking VLE binary diagram...

**Comment by eliasjr70** [comment]
Dear @DanWBR, thank you for the help!  My interest now is LLE, so it will be very useful.  Hope I can keep helping to find bugs.
My best regards,
Elias.

**Comment by eliasjr70** [comment]
Dear @DanWBR, I have recently donwnloaded the 6.4.5 version and it's working just fine.  Thank you!
