### ISSUE TITLE
[Enhancement] Export pure compound properties in a excel file

### ISSUE THREAD

**Issue by Hyguys** [DanWBR/dwsim6#120]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Is there any way I can export all the pure compound data of the compounds in my simulation to an excel file so I can compare those values with the ones in Aspen Plus? Going one by one when you have 50+ compounds in the simulation is a chore...

**Comment by DanWBR** [comment]
@Hyguys unfortunately not.
