### ISSUE TITLE
Problem to calculate stream

### ISSUE THREAD

**Issue by vitcbra** [DanWBR/dwsim6#121]
I have a material stream with 2 substancies(a hipothetical+water). When I calculate i have a problem like this:
"Calculation spec: Temperature_and_Pressure

Input variables: T = 298,15 K, P = 101325 Pa

Checking mixture composition. Sum must be higher than zero. Sum = 1

Checking flow definition. Mass flow specified, will calculate molar and volumetric flow.

Property Package: NRTL

Flash Algorithm: UniversalFlash

Calculating phase equilibria...

Exception raised from file , at method Multiply_V64fS64f_V64f, line 0:

Referência de objeto não definida para uma instância de um objeto."

How can i fix it?  

[Problem.zip](https://github.com/DanWBR/dwsim6/files/6085734/Problem.zip)

**Comment by vitcbra** [comment]
i Need to work with solid substancies

**Comment by DanWBR** [comment]
Disable CPU SIMD acceleration in Global Settings.
