### ISSUE TITLE
I can't calculate anything

### ISSUE THREAD

**Issue by vitcbra** [DanWBR/dwsim6#122]
I can't calculate anything but when i force a calculation (SHIFT+F5) show me this error:

"System.Exception: Infinite loop detected while obtaining flowsheet object calculation order. Please insert recycle blocks where needed.
   em DWSIM.FlowsheetSolver.FlowsheetSolver.GetSolvingList(Object fobj, Boolean frompgrid) na C:\Users\Daniel\source\repos\DanWBR\dwsim6\DWSIM.FlowsheetSolver\FlowsheetSolver.vb:linha 937
   em DWSIM.FlowsheetSolver.FlowsheetSolver.SolveFlowsheet(Object fobj, Int32 mode, CancellationTokenSource ts, Boolean frompgrid, Boolean Adjusting, Action FinishSuccess, Action FinishWithErrors, Action FinishAny, Boolean ChangeCalcOrder) na C:\Users\Daniel\source\repos\DanWBR\dwsim6\DWSIM.FlowsheetSolver\FlowsheetSolver.vb:linha 1049
   em DWSIM.FormFlowsheet.tsbCalcF_Click(Object sender, EventArgs e) na C:\Users\Daniel\source\repos\DanWBR\dwsim6\DWSIM\Forms\Flowsheet\FormFlowsheet.vb:linha 774
   em System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   em System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   em System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   em System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   em System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   em System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   em System.Windows.Forms.Control.WndProc(Message& m)
   em System.Windows.Forms.ToolStrip.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)"
[Simulação 0.zip](https://github.com/DanWBR/dwsim6/files/6087413/Simulacao.0.zip)

**Comment by DanWBR** [comment]
@vitcbra the first line tells you what's wrong with your model.

**Comment by vitcbra** [comment]
Where in the model the software need it? I tried but i didn't fix it.

**Comment by DanWBR** [comment]
You must have a material stream going backwards on your flowsheet. You must connect a recycle block to it, because if you don't the solver would enter in an infinite loop, calculating the flowsheet again and again.

**Comment by vitcbra** [comment]
Ahhh...I understand now. I will try. Thanks.
