### ISSUE TITLE
Mixed languages appearson the interface

### ISSUE THREAD

**Issue by branch171** [DanWBR/dwsim6#124]
Hi this should be a quick answer.

I have compiled DWSIM 6.4.5 but the user interface comes up with a mixture of English and Portuguese. So I see "Modo Dinamico" 
 for example. Is there a place to set the overall language used for the interface and forms.

Most are correct its just the top menu that I see wrong.

Thanks

**Comment by DanWBR** [comment]
@branch171 what was the compiled solution configuration?
