### ISSUE TITLE
Problem in resulting XML file when saving with SaveFlowsheet automation method

### ISSUE THREAD

**Issue by jmacias552** [DanWBR/dwsim6#125]
---
Problem in resulting XML file when saving with SaveFlowsheet automation
---
**Describe the bug**
In Python opening a simulation, exploring it and saving without any modifications produce a format destruction of the XML and cannot be open in the DWSIM GUI.
Everything seems to works fine except this SaveFlowsheet function from Automation.
The differences appears after line 1534 where it is missing the tags **petroleumassays** and the last part is out of order.
Attached the jupyter notebook, XML of the original simulation and the Simulation after being save with a different name.

**To Reproduce**
1. Open the original simulation SimCreada.dwxml with Automation LoadFlowSheet
2. Save it con SaveFlowsheet in a diferent file name like SimCreada_output.dwxml
3. Chack the attached files XML after line 1534
4. See the different format and that it can not be open with other simulation

**Expected behavior**
The format if nothing is added in the simulation, the file should have the same info and format.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v6.4.6

**Additional context**

[DWSIM Simulaciones.zip](https://github.com/DanWBR/dwsim6/files/6216202/DWSIM.Simulaciones.zip)

**Comment by DanWBR** [comment]
Petroleum Assays and Watch items are Classic UI objects only. They are not loaded in an IFlowsheet instance, though this should not be the cause of the error.

**Comment by DanWBR** [comment]
When I run SaveFlowsheet() from VB/C# code, it works normally. It must be something with Python interacting badly with the FileStream in this part of the code:

https://github.com/DanWBR/dwsim6/blob/16bb37c67d7cd13a04666b92c402981b1efac1c3/DWSIM.UI.Desktop.Forms/Forms/Flowsheet/Flowsheet.eto.cs#L1638-L1641

**Comment by DanWBR** [comment]
It seems to be an issue specific to Python + FileStream, and I have no idea why it happens. You can try, alternatively, save the file with:

`sim.SaveToXML().Save("path_to_dwxml_file")`

I've tested it here and it produces a valid XML file.

**Comment by jmacias552** [comment]
Thank you Daniel, I Will try and I will get back yo you.

**Comment by jmacias552** [comment]
The alternative method works without any problem.
Thanks

**Comment by DanWBR** [comment]
@jmacias552 in the next version you should be able to use the normal SaveFlowsheet() function.
