### ISSUE TITLE
Inconsistencies in Heat Exchanger Rating Mode[Bug] 

### ISSUE THREAD

**Issue by eon660522** [DanWBR/dwsim6#127]
Using Heat Exchanger in Shell Tube Exchanger Rating mode appears to have some inconsistencies in units.   After capturing fouling factor for tubes of 0.00018, it is using 0.18 instead.   I had to capture the fouling factor as 1.8E-7 in order to use the correct value of 0.00018.

When creating a Master Property Table for the exchanger, dimension of the shell and baffle spacing are reported with a factor of 1000.   Rating form asks for these dimensions in mm  and when reporting appears if they were given in meters and reported in mm.   

Attached file for these simulation.    Calculations by hand gives about 250 m2 of area with an U of around 220 W/m2 K using this exchanger.    I had to capture fouling factor as 1.8E-7 in order to have the desired value of 0.00018  (when reopening the Shell and Tube form).  If you capture 0.00018 it will appear as 0.18 next time you open the shell and tube edit form.

[Sol_Ejemplo3_Tubo_Coraza_Rating.zip](https://github.com/DanWBR/dwsim6/files/6258767/Sol_Ejemplo3_Tubo_Coraza_Rating.zip)

**Comment by DanWBR** [comment]
@eon660522 what is the version that you're running?
