### ISSUE TITLE
[Bug] DWSIM doesn't take into account regional settings on macOS

### ISSUE THREAD

**Issue by luciana2021** [DanWBR/dwsim6#128]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
When I create a new compound on DWSIM for Mac, I have to type the boiling point and other properties in scientific notation otherwise the software does not consider the numbers after comma. 

**To Reproduce**
Create a new compound using the compound wizard and type the property values using comma. 

**Expected behavior**
Some properties won't show the numbers after comma. If I use this data, the reaction stoichiometry gives an error message.

**Screenshots**

**Desktop (please complete the following information):**
 macOS, version 6.4.7

**Additional context**

**Comment by DanWBR** [comment]
This seems to be a bug with Xamarin/Mono on macOS: https://github.com/mono/mono/issues/16827

There is no solution for this at the moment, so you must use the dot as the decimal separator.
