### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by luciana2021** [DanWBR/dwsim6#131]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
DWSIM version 6.4.7 for Mac suddenly closes. 

**To Reproduce**
I start a simulation and create a unit operation. When I set the operating conditions DWSIM closes.

**Expected behavior**
DWSIM closes.

**Screenshots**

**Desktop (please complete the following information):**
 DWSIM version 6.4.7. for Mac.

**Additional context**

**Comment by DanWBR** [comment]
@luciana2021 how can I reproduce this? Can you record a video?

**Comment by luciana2021** [comment]
I sent you the video.

**Comment by DanWBR** [comment]
Fixed in https://github.com/DanWBR/dwsim6/commit/ab04c2301063d6e3853d10e6275f1032ee7671e8
