### ISSUE TITLE
[Bug] Flowsheet window becomes black after opening a second simulation

### ISSUE THREAD

**Issue by byryepez** [DanWBR/dwsim6#132]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
When you open or create a second simulation with one open, the flowsheet on the first opened simulation becomes black. 

**To Reproduce**
1. Open a simulation
2. Open another simulation
3. Open the window for the first simulation
4. See error: black flowsheet

**Expected behavior**
To see the flowsheet

**Screenshots**
![image](https://user-images.githubusercontent.com/4457757/113942203-b23eb800-97bd-11eb-831d-4483a9dcad5c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: v6.4.7

**Comment by DanWBR** [comment]
Go to General Settings and change the Flowsheet Renderer to "Software (CPU)".

**Comment by byryepez** [comment]
Thanks @DanWBR . That fixes the issue.

**Comment by DanWBR** [comment]
@byryepez you're welcome!
