### ISSUE TITLE
[Enhancement] Allowing the user to force the stream phase to, liquid, gas, liquid-gas, etc

### ISSUE THREAD

**Issue by AdrianDietz** [DanWBR/dwsim6#134]
**Is your feature request related to a problem? Please describe.**
No, it is an Enhancement : will allow to deal with data reconciliation and real time optimization, similar to aveva and aspentech

**Describe the solution you'd like**
Allowing the user to force the stream phase to, liquid, gas, liquid-gas, etc
Example: a G-L separator for a pure component will have the same T and P at top/gas and bottom/liquid. When dealing with the liquid stream using real data, a sensor, with the even smallest error, could make my liquid stream to be gas is this is a positive error on T for example, while I know that the stream is 100% liquid and most probably I am not modelling te separator itself as there are not enough sensors around to characterize or validate it. 

**Describe alternatives you've considered**
No real robust option. by the way aspentech is not robust either. Hoping that DWSIM will be one step further that the other, at least on some practical applications.

**Additional context**
N/A

**Comment by DanWBR** [comment]
@AdrianDietz that's doable. Please comment here in a few days from now just in case I forget to do it.

**Comment by AdrianDietz** [comment]
Great!
