### ISSUE TITLE
[Bug]  CAPE-OPEN package configuration doesn't show Equilibrium Calculation settings

### ISSUE THREAD

**Issue by byryepez** [DanWBR/dwsim6#136]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
While trying to configure a CAPE-OPEN property package, the option to set the equilibrium calculation settings is not available. It was on the previous version.

**To Reproduce**
1. Go to Settings / Thermodynamics
2. Add a CAPE-OPEN property package
3. Click on "Configure"
4. Only 3 tabs available: Thermo & Properties, Component mapping, Phase Mapping
5. No option for changing Equilibrium Calculation Settings

**Expected behavior**
To have a tab to change Equilibrium Calculation settings

**Screenshots**
![image](https://user-images.githubusercontent.com/4457757/115094646-8fa65080-9edb-11eb-9c31-a4091a21f243.png)
![image](https://user-images.githubusercontent.com/4457757/115094663-98972200-9edb-11eb-8de9-8bf6ecb3e2c0.png)

**Desktop (please complete the following information):**
 - OS: Windows  10 
 - Version: 6.4.8

**Additional context**

**Comment by DanWBR** [comment]
@byryepez this is not a bug. The equilibrium calculation settings must be set directly through the CAPE-OPEN Property Package editor, if the PP provides one.
