### ISSUE TITLE
Pipe. Estimate Overall Heat Transfer Coefficient[Bug] 

### ISSUE THREAD

**Issue by denissps** [DanWBR/dwsim6#137]
When trying to **Estimate Overall Heat Transfer Coefficient** of a pipe, it gives me ridiculous results.

For example 30 m of saturated steam pipe (165 *C), OD 76 mm, Inside diameter is 65 mm, insulation thickness is 50 mm, External Temperature 15 *C, Gradient 0, Insulation material Foam PVC (0,04 W/mK), External HTC (Air, 1 m/s), Internal HTC enabled  ---  will lose **14,2 kW** of heat! 

I used other software to calculate heat loss, and it gives me results around 1 kW, which is more realistic.

I think this problem has something to do with units. If I multiply insulation thickness by 1000 (use 50 000 mm) it will give me somewhat realistic results.

**Comment by DanWBR** [comment]
@denissps running latest version (6.4.8)?

**Comment by denissps** [comment]
Yes, version 6.4.8, Classic UI

**Comment by DanWBR** [comment]
@denissps can you confirm that this issue was fixed in the latest version (6.4.9)? thanks

**Comment by denissps** [comment]
@DanWBR Yes, it seems that issue is fixed! Now heat loss is in expected range! Thank you for a great software!
