### ISSUE TITLE
[Bug] Bulk C7+ Petroleum Characterization Utility

### ISSUE THREAD

**Issue by Danita-Puq** [DanWBR/dwsim6#139]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
The Bulk C7+ Petroleum Characterization Utility does not calculate the physical properties of a petroleum pseudo component correctly.

**To Reproduce**
1. Go to 'Bulk C7+ Petroleum Characterization Utility'
2. Enter the Input Data Molecular Weight 105.3, Specific Gravity is 0.737 and Avg. The boiling temperature is 383 K.
3. Scroll down to select "1" to create one pseudo component
2. Click on 'Characterize Oil'
4. You'll see that the properties table result will show a cero in the Molar Fraction column.
5. Click on 'Create and Add oil Stream'
6. A report will show out indicated that the properties have not been calculated with 100% error.

**Expected behavior**
The Molar Fraction for 1 pseudocomponent is should be 1 and not zero. The correlation should have been executed and the error should be close to 1%.

**Screenshots**
![image](https://user-images.githubusercontent.com/78652590/117481093-62891300-af5a-11eb-8832-09a41887cd53.png)
![image](https://user-images.githubusercontent.com/78652590/117481115-67e65d80-af5a-11eb-9c74-c415657767c8.png)

**Desktop (please complete the following information):**
 - OS:  Windows 64-bit
 - Version [e.g. v6.4.1]

**Additional context**
We follow the youtube tutorial link
https://www.youtube.com/watch?v=a8nV0n4ZWeo&t=12s

**Comment by andr1976** [comment]
Actually the properties are calculated fine. If you investigate your stream you will find that MW and density, as well as boiling point is reproduced. The problem lies in the Quality Check report. The tool was originally intended for several components (not single components) by Daniel, I made some changes to it to better handle single component, but it seems that I haven't gone all the way.

**Comment by DanWBR** [comment]
I do not recommend creating only a single pseudocompound from bulk data. All source papers I used to create the utility and property calculation methods refer to a distribution of pseudos with at least 5 compounds.

**Comment by andr1976** [comment]
I agree Daniel, however, sometimes characterisation has already been made using PVT data outside DWSIM to generate a number of pseudos for the C7+ fractions, that you want to replicate. You can potentially do this one by one in the C7+ char utility (although not elegant I agree) - alternatively you can go the direct JSON way

**Comment by DanWBR** [comment]
@andr1976 in this case it is better to use the compound creator, where you'll be able to input all properties individually.

**Comment by andr1976** [comment]
Yes, but sometimes all you have is maybe MW, Pc, Tc and still what to use the Riazi and Lee-Kessler estimations. Can you do that in the compund creator?

**Comment by DanWBR** [comment]
@andr1976 the minimum required properties in the compound creator are MW, NBP, Tc, Pc and w.

**Comment by andr1976** [comment]
Hmmm, I don't think that works as easy - e.g. some properties are not calculated/modelled like thermal conductivity. Further, it seems that boiling point is not matched that well either, but maybe I did something wrong.

**Comment by Danita-Puq** [comment]
Hi to all!
Many thanks for the replies and clarifications.
When we create a natural gas stream, preferably we also add a
hypothetical component to represent the heavy petroleum fractions as one
(C7+), we do this frequently in Aspen HYSYS.
I totally get Daniel's point of view regarding how many pseudo components
typically are created. However, for simplicity, we preferably create 1
compound by using the hypothetical compound creator in HYSYS.
We will use the Compound Creator tool instead.

Daniela.

**Comment by DanWBR** [comment]
@Danita-Puq I also worked with petroleum fluids in HYSYS for years and I believe that it is very dangerous to represent the whole C7+ fraction as a single compound. As I wrote above, all property estimation methods for C7+ assume that you have a distribution of compounds, with at least five of them. Imagine that you have a stream with a single C7+ compound. In this case you can't even generate a phase envelope for the heavy part of the whole fluid.

**Comment by Danita-Puq** [comment]
Hi Daniel, totally agreed.
