### ISSUE TITLE
Turbocharger Simulation

### ISSUE THREAD

**Issue by Jamesneedshelp** [DanWBR/dwsim6#143]
[Trial 2.zip](https://github.com/DanWBR/dwsim6/files/6490198/Trial.2.zip)
![image](https://user-images.githubusercontent.com/84292985/118418364-29e9e780-b686-11eb-8201-2f9574481de6.png)

Hello,
I'm new to DWSIM and Cape Open in general but I'm trying to model a closed loop system with a turbocharger.
I have spent a couple of days trying to simulate and lots many tutorials and can't seem to make progress. 
Do you know of any previous examples of have any guidance?
Many Thanks,
James

**Comment by DanWBR** [comment]
@Jamesneedshelp use CoolProp Property Package and do not force the phase of any stream. The outlet pressure of the pump is set to zero.

**Comment by Jamesneedshelp** [comment]
Hi Daniel, thanks very much for the prompt response. I tried the suggestions but it still wont solve? 
I tried to set the temperature to 300k but it keeps changing and states there is an error in the pump set up.
Any suggestions would be appreciated? Is it possible to screengrab or update the file so I know how to complete for future simulations? 
Many thanks for your support,
James

**Comment by DanWBR** [comment]
@Jamesneedshelp don't you need a cooler between the compressor and the pump?

**Comment by Jamesneedshelp** [comment]
[Trial 2 (2).zip](https://github.com/DanWBR/dwsim6/files/6505151/Trial.2.2.zip)

@DanWBR Thanks for suggestion, I added the cooler and it seemed to help. However I still seem to have some issues getting the specified values to hold? 

![image](https://user-images.githubusercontent.com/84292985/118741603-9ac30800-b81c-11eb-9779-30a2c19577f8.png)
