### ISSUE TITLE
[Bug] Missing UNIQUAC/NRTL Interaction Parameters are not ignored by default

### ISSUE THREAD

**Issue by nayakpriyam** [DanWBR/dwsim6#144]
**Bug Description**
Missing UNIQUAC/NRTL interaction parameters are not ignored by default.

**Steps To Reproduce**
1. Add components: Acetic Acid and Water
2. Select Thermo package: NRTL
3. Finish setting up the simulation
4. Drag and drop a material stream

**Expected behavior**
The material stream should be successfully simulated with the default P & T values.

**Actual behavior**
Getting error as missing interaction parameters for binary pair Acetic Acid/Water. 
Although this can be resolved by going to Configure >> Property Calculation Settings >> Checking the checkbox against "Ignore Missing UNIQUAC/NRTL Interaction Parameters", however, this feature was on by default till the last version.

**Screenshots**
![image](https://user-images.githubusercontent.com/34299789/118797112-de1f8400-b8b9-11eb-8f52-a7ec1c17524d.png)

**Desktop**
 - OS: Windows 10
 - DWSIM v6.5.0

**Comment by DanWBR** [comment]
@nayakpriyam this should be the correct behavior since the beginning. Modeling mixtures with NRTL and UNIQUAC without interaction parameters will lead to unexpected results. If binary interaction parameters are not available, switch to a UNIFAC-type Property Package.

**Comment by nayakpriyam** [comment]
In that case, I am closing the issue.
