### ISSUE TITLE
[Bug] Inspector could not be started

### ISSUE THREAD

**Issue by einhander** [DanWBR/dwsim6#147]
**Describe the bug**
Inspector could not be started.

**To Reproduce**
1. Click on  'View inspector Window' icon
2. See error

**Expected behavior**
Shows inspector Window .

**Desktop (please complete the following information):**
 - OS: Debian testing 64-bit
 - Version: 6.5.0 deb package

**Additional context**

Seems that WebKit 1 is no longer supported by Linux distros and removed from repositories.

Error log:
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'webkit-sharp, Version=1.1.15.0, Culture=neutral, PublicKeyToken=eaa1d335d2e19745' or one of its dependencies.
>   at Eto.Widget..ctor () [0x0006a] in <23bf6400f02d49eba883a8238fbdb959>:0 
>   at Eto.Forms.BindableWidget..ctor () [0x00000] in <23bf6400f02d49eba883a8238fbdb959>:0 
>   at Eto.Forms.Control..ctor () [0x00000] in <23bf6400f02d49eba883a8238fbdb959>:0 
>   at Eto.Forms.WebView..ctor () [0x00000] in <23bf6400f02d49eba883a8238fbdb959>:0 
>   at DWSIM.Inspector.Window_Eto.GetInspectorWindow () [0x002e9] in <59bc16e9c6524d90bfb131467ab34117>:0 
>   at DWSIM.UI.Forms.Flowsheet+<>c__DisplayClass55_0.<InitializeComponent>b__17 () [0x00000] in <8a4eab12c85a4bd08d9ddf0b38a03abd>:0 
>   at DWSIM.UI.Forms.Flowsheet+<>c__DisplayClass55_0.<InitializeComponent>b__22 (System.Object sender, System.EventArgs e) [0x00000] in <8a4eab12c85a4bd08d9ddf0b38a03abd>:0 
>   at Eto.Forms.ToolItem.OnClick (System.EventArgs e) [0x00008] in <23bf6400f02d49eba883a8238fbdb959>:0 
>   at Eto.GtkSharp.Forms.ToolBar.ButtonToolItemHandler+ButtonToolItemConnector.HandleClicked (System.Object sender, System.EventArgs e) [0x0000b] in <2084ba8256c9420ea60ad1e5f1df14e5>:0 
>   at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
>   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0007c] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
>    --- End of inner exception stack trace ---
>   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0009a] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
>   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
>   at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x0010d] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
>   at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x0000b] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
>   at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
>   at GLib.Signal.ClosureInvokedCB (System.Object o, GLib.ClosureInvokedArgs args) [0x0006d] in <918680a31aa84cb89cfa7cab56ea29b8>:0 
>   at GLib.SignalClosure.Invoke (GLib.ClosureInvokedArgs args) [0x0000c] in <918680a31aa84cb89cfa7cab56ea29b8>:0 
>   at GLib.SignalClosure.MarshalCallback (System.IntPtr raw_closure, System.IntPtr return_val, System.UInt32 n_param_vals, System.IntPtr param_values, System.IntPtr invocation_hint, System.IntPtr marshal_data) [0x0006c] in <918680a31aa84cb89cfa7cab56ea29b8>:0

**Comment by DanWBR** [comment]
@einhander so we don't have libwebkit1.1-cil anymore?

**Comment by einhander** [comment]
@DanWBR  yes, last debian with libwebkit1.1-cil was stretch, it's oldstable now.  And a new stable release will be in few month.

**Comment by DanWBR** [comment]
@einhander this can take some time to be "fixed" as I'll have to update other important libraries in order for this to work.

**Comment by DanWBR** [comment]
@einhander could you please test this build? https://drive.google.com/drive/folders/10yeNTYwrB_Fi88m8t3Sj2ZpPFrG6RTuI?usp=sharing

run it with the following command to check if the .so files are being loaded correctly:

`MONO_LOG_LEVEL=debug MONO_LOG_MASK=dll mono DWSIM.UI.Desktop.exe`

the inspector must be activated from the global settings window as its check button in the toolbar doesn't work in GTK.

**Comment by einhander** [comment]
@DanWBR thank you, it works ok

**Comment by einhander** [comment]
I have to reopen this issue, because in deb version 6.5.2 Inspector can't be started.

> MONO_LOG_LEVEL=debug MONO_LOG_MASK=dll mono DWSIM.UI.Desktop.exe
...
Mono: DllImport attempting to load: 'webkit-1.0'.
Mono: DllImport error loading library '/usr/local/lib/dwsim/webkit-1.0': '/usr/local/lib/dwsim/webkit-1.0: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога'.
Mono: DllImport error loading library '/usr/local/lib/dwsim/libwebkit-1.0.so': 'libgeoclue.so.0: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога'.
Mono: DllImport error loading library '/usr/local/lib/dwsim/libwebkit-1.0.so': 'libgeoclue.so.0: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога'.
Mono: DllImport error loading library '/usr/lib/webkit-1.0': '/usr/lib/webkit-1.0: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога'.
Mono: DllImport error loading library '/usr/lib/libwebkit-1.0.so': '/usr/lib/libwebkit-1.0.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога'.
Mono: DllImport error loading library '/usr/lib/libwebkit-1.0.so': '/usr/lib/libwebkit-1.0.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога'.
Mono: DllImport error loading library 'webkit-1.0': 'webkit-1.0: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога'.
Mono: DllImport error loading library 'libwebkit-1.0.so': 'libwebkit-1.0.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога'.
Mono: DllImport error loading library 'libwebkit-1.0.so': 'libwebkit-1.0.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога'.
Mono: DllImport error loading library 'webkit-1.0': 'webkit-1.0: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога'.
Mono: DllImport error loading library '/usr/local/lib/dwsim/libwebkit-1.0': '/usr/local/lib/dwsim/libwebkit-1.0: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога'.
Mono: DllImport error loading library '/usr/local/lib/dwsim/libwebkit-1.0.so': 'libgeoclue.so.0: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога'.
Mono: DllImport error loading library '/usr/local/lib/dwsim/libwebkit-1.0.so': 'libgeoclue.so.0: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога'.
Mono: DllImport error loading library '/usr/lib/libwebkit-1.0': '/usr/lib/libwebkit-1.0: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога'.
Mono: DllImport error loading library '/usr/lib/libwebkit-1.0.so': '/usr/lib/libwebkit-1.0.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога'.
Mono: DllImport error loading library '/usr/lib/libwebkit-1.0.so': '/usr/lib/libwebkit-1.0.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога'.
Mono: DllImport error loading library 'libwebkit-1.0': 'libwebkit-1.0: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога'.
Mono: DllImport error loading library 'libwebkit-1.0.so': 'libwebkit-1.0.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога'.
Mono: DllImport error loading library 'libwebkit-1.0.so': 'libwebkit-1.0.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога'.
Mono: DllImport error loading library 'libwebkit-1.0': 'libwebkit-1.0: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога'.
Mono: DllImport unable to load library 'libwebkit-1.0: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога'.
Marshaling clicked signal
...

libgeoclue.so.0 presents in /usr/local/lib/dwsim/

P.S. LANG=C variable prevents start of dwsim, I don't know why.

**Comment by DanWBR** [comment]
@einhander somehow libwebkit lost the static links twice during copying... I've now did it again for the third time...

**Comment by einhander** [comment]
@DanWBR version 6.5.3 the same. But I've found workaround, I changed start script a bit:
```
#!/bin/sh
export DYLD_LIBRARY_PATH=/usr/local/lib/dwsim:/usr/local/lib/dwsim/ThermoCS:$DYLD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/lib/dwsim:/usr/local/lib/dwsim/ThermoCS:$LD_LIBRARY_PATH
cd /usr/local/lib/dwsim/
exec /usr/bin/mono ./DWSIM.UI.Desktop.exe "$@"
```
Seems that LD_LIBRARY_PATH is not working.

**Comment by DanWBR** [comment]
can you type

`ldd libwebkit-1.0.so` in /usr/local/lib/dwsim so we can see what's missing?

**Comment by einhander** [comment]
```
$ldd libwebkit-1.0.so
	linux-vdso.so.1 (0x00007ffd07f81000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4df03ed000)
	./libjavascriptcoregtk-1.0.so.0 (0x00007f4def5d2000)
	libenchant.so.1 => /usr/lib/x86_64-linux-gnu/libenchant.so.1 (0x00007f4def5c4000)
	libharfbuzz-icu.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz-icu.so.0 (0x00007f4def5bf000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f4def4d7000)
	./libgeoclue.so.0 (0x00007f4def2c0000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f4def2b8000)
	libgstapp-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstapp-1.0.so.0 (0x00007f4def2a6000)
	libgstaudio-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstaudio-1.0.so.0 (0x00007f4def229000)
	libgstfft-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstfft-1.0.so.0 (0x00007f4def21c000)
	libgstpbutils-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstpbutils-1.0.so.0 (0x00007f4def1de000)
	libgstvideo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so.0 (0x00007f4def125000)
	libgstbase-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0 (0x00007f4def0a3000)
	libgstreamer-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0 (0x00007f4deef5a000)
	libgtk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007f4deeafc000)
	libgdk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0 (0x00007f4deea40000)
	libatk-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007f4deea16000)
	libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f4dee8f1000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007f4dee8c9000)
	./libjpeg.so.8 (0x00007f4dee670000)
	libsecret-1.so.0 => /usr/lib/x86_64-linux-gnu/libsecret-1.so.0 (0x00007f4dee610000)
	libsoup-2.4.so.1 => /usr/lib/x86_64-linux-gnu/libsoup-2.4.so.1 (0x00007f4dee571000)
	libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f4dee393000)
	libxslt.so.1 => /usr/lib/x86_64-linux-gnu/libxslt.so.1 (0x00007f4dee351000)
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f4dee1a1000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f4dee11a000)
	libEGL.so.1 => /usr/lib/x86_64-linux-gnu/libEGL.so.1 (0x00007f4dee105000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4dee0ff000)
	libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007f4dee0ad000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f4dee053000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f4dedf22000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f4dededc000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f4dede19000)
	./libpng12.so.0 (0x00007f4dedbf4000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f4dedab1000)
	./libicui18n.so.55.1 (0x00007f4ded64f000)
	./libicuuc.so.55.1 (0x00007f4ded2b9000)
	./libwebp.so.5.0.4 (0x00007f4ded05d000)
	libXcomposite.so.1 => /usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007f4ded058000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f4ded053000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f4dece49000)
	libXt.so.6 => /usr/lib/x86_64-linux-gnu/libXt.so.6 (0x00007f4decddf000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f4decc9a000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f4decc7d000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4decab0000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4dec96c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4dec7a7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4df2708000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4dec78d000)
	./libicudata.so.55.1 (0x00007f4deacd4000)
	libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007f4deaccf000)
	libicuuc.so.67 => /usr/lib/x86_64-linux-gnu/libicuuc.so.67 (0x00007f4deaae6000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f4deaaba000)
	libdbus-glib-1.so.2 => /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2 (0x00007f4deaa8f000)
	libgsttag-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgsttag-1.0.so.0 (0x00007f4deaa4d000)
	liborc-0.4.so.0 => /usr/lib/x86_64-linux-gnu/liborc-0.4.so.0 (0x00007f4dea9c9000)
	libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007f4dea9ae000)
	libdw.so.1 => /usr/lib/x86_64-linux-gnu/libdw.so.1 (0x00007f4dea905000)
	libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007f4dea8f4000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f4dea8ea000)
	libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007f4dea8d1000)
	libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007f4dea8cc000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f4dea8ba000)
	libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f4dea6af000)
	libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007f4dea6a2000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f4dea68b000)
	libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f4dea5e0000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f4dea5a6000)
	libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f4dea5a1000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f4dea576000)
	libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f4dea567000)
	libgcrypt.so.20 => /usr/lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f4dea445000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f4dea3f2000)
	libpsl.so.5 => /usr/lib/x86_64-linux-gnu/libpsl.so.5 (0x00007f4dea3de000)
	libbrotlidec.so.1 => /usr/lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007f4dea3d0000)
	libmount.so.1 => /usr/lib/x86_64-linux-gnu/libmount.so.1 (0x00007f4dea373000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f4dea345000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f4dea32b000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f4dea303000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f4dea24b000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f4dea217000)
	libfribidi.so.0 => /usr/lib/x86_64-linux-gnu/libfribidi.so.0 (0x00007f4dea1f9000)
	libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007f4dea1ee000)
	libffi.so.7 => /usr/lib/x86_64-linux-gnu/libffi.so.7 (0x00007f4dea1e2000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f4dea16f000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f4dea140000)
	libuuid.so.1 => /usr/lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f4dea137000)
	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007f4dea12a000)
	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007f4dea10c000)
	libicudata.so.67 => /usr/lib/x86_64-linux-gnu/libicudata.so.67 (0x00007f4de85f3000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f4de859e000)
	libelf.so.1 => /usr/lib/x86_64-linux-gnu/libelf.so.1 (0x00007f4de8581000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f4de856e000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f4de8569000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f4de8363000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f4de833d000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f4de8261000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f4de8231000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f4de822b000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f4de821c000)
	libunistring.so.2 => /usr/lib/x86_64-linux-gnu/libunistring.so.2 (0x00007f4de809a000)
	libidn2.so.0 => /usr/lib/x86_64-linux-gnu/libidn2.so.0 (0x00007f4de8079000)
	libbrotlicommon.so.1 => /usr/lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007f4de8054000)
	libblkid.so.1 => /usr/lib/x86_64-linux-gnu/libblkid.so.1 (0x00007f4de8003000)
	libpcre2-8.so.0 => /usr/lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007f4de7f6b000)
	libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007f4de7f61000)
	libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f4de7f4a000)
	libsystemd.so.0 => /usr/lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f4de7e93000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f4de7e8c000)
	libmd.so.0 => /usr/lib/x86_64-linux-gnu/libmd.so.0 (0x00007f4de7e7f000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4de7e74000)
	libzstd.so.1 => /usr/lib/x86_64-linux-gnu/libzstd.so.1 (0x00007f4de7d99000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f4de7d74000)
```

**Comment by DanWBR** [comment]
the script had an error at the end of the LD path setter:

LD_LIBARRY_PATH

should be 

LD_LIBRARY_PATH

maybe that's the reason.

**Comment by einhander** [comment]
> LD_LIBRARY_PATH

Already fixed this, but didn't help.
I think that `./libjavascriptcoregtk-1.0.so.0 (0x00007f4def5d2000)` should be something like 
```libjavascriptcoregtk-1.0.so.0 =>  /usr/local/lib/dwsim/libjavascriptcoregtk-1.0.so.0 (0x00007f4def5d2000)```
If I run 
```
ldd /usr/local/lib/dwsim/libwebkit-1.0.so
./libjavascriptcoregtk-1.0.so.0 => not found
```
It's the same case if I run `$dwsim` from terminal.

**Comment by DanWBR** [comment]
found the issue in libjavascript... the mappings I had set for this file were lost just as in libwebkit, and I ended up forgetting about resetting them. Hopefully, this will work once and for all in v6.5.4.

**Comment by DanWBR** [comment]
@einhander if we cd to dwsim dir then it works, as you suggested with your script. do you see any problem with this?

**Comment by einhander** [comment]
@DanWBR I'm not libraries linking expert but I think It's very hackish way. Normally, libs should be in  `/usr/lib/dwsim` for platform independent libs or `/usr/lib/x86_64-linux-gnu/` for platform dependent libraries , like other linux program do. Include other outdated libs also not good. But for now it's ok. It can be done latter.

**Comment by DanWBR** [comment]
@einhander yes, totally non-standard. the problem is that the component that I use to create the GUI on Linux will not change its dependency from webkit 1 to display web pages. Without this solution, we'll have nothing.

**Comment by DanWBR** [comment]
I've spent some days trying to update DWSIM on Linux to GTK 3, but I hit a wall. Some components stopped working, like the script editor and other editors which use Windows Forms controls. System.Windows.Forms on Linux depends on GTK 2, and this dependency will not change as the library is not being maintained anymore.

**Comment by einhander** [comment]
@DanWBR can you build libwebkit-1.0.so with static linking?

**Comment by DanWBR** [comment]
@einhander I don't know how to do it...

**Comment by einhander** [comment]
@DanWBR Oh, I see... I'll try to figure out how to load necessary  libraries for libwebkit-1.0.so.

**Comment by einhander** [comment]
I've found that on debian 11 there no libenchant1c2a and libhunspell-1.4-0 available. I think that dwsim package should have them like libwebkit-1.0.
You can get them from debian stretch repo.
