### ISSUE TITLE
[Enhancement]  Provide  AppImage instead of deb package

### ISSUE THREAD

**Issue by einhander** [DanWBR/dwsim6#148]
**Is your feature request related to a problem? Please describe.**
Linux distributives use many format of packages, debian-like use deb and redhat based - rpm, also there is gento, arch linux and other that is source based. Different versions of distributive can supply different version of system libraries. So provide only a deb package cuts-of rest of linux distributive users.

**Describe the solution you'd like**
Provide linux package in AppImage format. In basic it's one file that can be executed on any modern linux system.
It's already used in Freecad.
More about AppImage https://appimage.org/

**Comment by einhander** [comment]
I'm trying to create appimage from deb package, but without any success. It seems that appimage creation should be made during compile stage using `dotnet publish`. There is example of how to deploy .NET Core (Mono) applications as an AppImage using `dotnet publish -f netcoreapp3.1 -r linux-x64` from within a .cs program. https://github.com/ppy/osu-deploy/blob/697a49e9602502a2b7a899c0dff5383f6512d5d2/Program.cs#L207-L243

**Comment by DanWBR** [comment]
closing as I won't work on this. If anyone comes with a working solution, feel free to reopen the issue.
