### ISSUE TITLE
[Bug] Carbon combustion bug

### ISSUE THREAD

**Issue by einhander** [DanWBR/dwsim6#150]
**Describe the bug**
In carbon combustion simulation, after a switch conversion reactor into adiobatic mode temperature of products are lower than temperature of input reagents.  
Don't sure is't bug or not.

**To Reproduce**
1. Go to 'Samples->carbon combustion'
2. Click on 'RC-000'
3. Change calculation mode  to 'Adiabatic'
4. See temperatures of products are lower then input reagents

**Expected behavior**
Temperature of products are grater then input reagents because combustion is exothermic reaction.

**Desktop (please complete the following information):**
 - OS: Debian 64-bit
 - Version 6.5.0

**Comment by DanWBR** [comment]
@einhander the reaction is exothermic but not spontaneous. the energy must come from somewhere else in form of a high temperature or a catalyst, otherwise the stream will freeze because it gave up energy (=temperature) for the reaction to occur.

**Comment by einhander** [comment]
Thank you very much! I'm confused with old hysys version that gave me about 2k degrees on same setup.

**Comment by DanWBR** [comment]
@einhander I may be wrong too, but I couldn't find a better explanation for this. Maybe the energy required to gasify solid carbon is higher than the released by the combustion?

**Comment by einhander** [comment]
@DanWBR I think you are wright about initial energy, if I rise temperature of carbon to 100 C degrees, temperature of gases increases significantly.
