### ISSUE TITLE
[Bug] DWSIM.Thermodynamics\Assets\Databases\electrolyte.xml unit compiling

### ISSUE THREAD

**Issue by JarlPed** [DanWBR/dwsim6#151]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
When loading Electrolyte compounds, there's no difference between "Standard State Gibbs Energy of Formation at 298 K" and "Standard State Enthalpy of Formation at 298 K" when converting from KJ/mol to KJ/kg when compiling dwsim6\DWSIM.Thermodynamics\Assets\Databases\electrolyte.xml file. Perhaps this can be fixed by applying a conversion?

**To Reproduce**
Using SI units;
Add for example "Sulfate (ion)" to the component list, and view the selected compound, browse to "[Electrolyte] Standard State Gibbs Energy of Formation at 298 K". View "DelGF_kJ_mol" for the compound with "Name" property "Sulfate (ion)" in file dwsim6\DWSIM.Thermodynamics\Assets\Databases\electrolyte.xm. The numbers are the same, but has different units.

**Expected behavior**
I would have expected different numbers; e.g. for "Sulfate (ion)" where "[Electrolyte] Standard State Gibbs Energy of Formation at 298 K" == -7750,7 kJ/kg  ; when considering <DelGF_kJ_mol>-744.53</DelGF_kJ_mol> and <MW>96.06</MW> fields.

**Screenshots**
![image](https://user-images.githubusercontent.com/23384537/119486945-195a0100-bd59-11eb-99eb-de64b45b424c.png)
![image](https://user-images.githubusercontent.com/23384537/119487059-3a225680-bd59-11eb-8aec-1527b409a88c.png)

**Desktop (please complete the following information):**
 - OS: Windows,
 - Version v6.5.0

**Additional context**

**Comment by JarlPed** [comment]
Update:

It appears that at least that Standard State Enthalpy of Formation is passed correctly to the reaction editing forms:
![image](https://user-images.githubusercontent.com/23384537/119491194-efefa400-bd5d-11eb-9f36-44f9b211e2d4.png)
Is this bug only an issue for the compound viewer?

**Comment by DanWBR** [comment]
@JarlPed yes, the units in the compound viewer should have been hard-coded to kJ/mol, and not converted to the currently selected units.
