### ISSUE TITLE
DWSIM 6.5.2 crashed Windows on opening Edit > General Settings

### ISSUE THREAD

**Issue by pkrulz** [DanWBR/dwsim6#154]
**Describe the bug**
After installation of new DWSIM in Windows, opening of General System caused the system to shutdown

**To Reproduce**
1. Install a fresh copy of DWSIM
2. Start DWSIM 
3. Before opening any files, Click on Edit
3. Click General Settings
4. Entire System Crashed and Windows ShutsDown Immediately

**Expected behavior**
The system should show General Settings

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Classic UI 6.5.2

**Additional context**
 I installed the newly released DWSIM 6.5.2 without uninstalling 6.5.0.
While installing it gave me an option to uninstall older version first. I clicked yes.

At the end of installation a cmd prompt showed a warning about something to do with "choose a strong name" which I could not read completely since it disappeared fast.
The bug is only seen when DWSIM is fresh installed and no files have been opened. Although it repeats till no files have been opened and I crashed my system thrice.
Once a file has been opened, this behaviour stops

**Comment by DanWBR** [comment]
This is something related to CUDA/OpenCL devices on your computer. Can you update your display driver?

**Comment by pkrulz** [comment]
The CUDA issue seems unlikely since the behaviour stops after opening any file in DWSIM. If that was a driver issue it should have repeated itself. Nevertheless, I understand that I am on my latest drivers but my machine is over 7 years old

**Comment by DanWBR** [comment]
@pkrulz I didn't express myself correctly, sorry. When you open the general settings, DWSIM tries to get a list of CUDA/OpenCL devices on your computer. In some machines, it can crash DWSIM, but I don't know exactly what happens because the query is done by an external component (CUDAfy.NET). In the next version, the query will not be automatic in order to avoid such crashes.

**Comment by pkrulz** [comment]
Thanks Daniel. I get it now.
On an additional note I opened General Setting to put DWSIM on auto update but I was not able to find any settings to be able to do that. Are such settings present in the current version ?

**Comment by DanWBR** [comment]
@pkrulz auto-update was removed years ago because it only worked on Windows.

**Comment by DanWBR** [comment]
@pkrulz I'll close this issue, feel free to re-open it if you're still experiencing the crash.

**Comment by pkrulz** [comment]
Before DWSIM 6.5 I was able to open About DWSIM without crashing my system.
Now doing that crashes my system and leads to immediate shutdown. 

I am on 6.5.2 Classic UI on Windows 10 64 bit

**Comment by pkrulz** [comment]
I am not sure how to reopen this issue

**Comment by DanWBR** [comment]
Nothing was changed in this regard since DWSIM 4-5... it was probably something that changed on your system (new device/driver, windows update, etc)
