### ISSUE TITLE
[Bug]  Pressure-Enthalpy Flash with CAPE-OPEN Property Package fail for some Operation Units

### ISSUE THREAD

**Issue by byryepez** [DanWBR/dwsim6#155]
**Describe the bug**
Some Unit operations cannot perform a PH flash to calculate the outlet temperature because outlet enthalpy is NaN.  So far, I replicated this issue in a valve, cooler, and compressor. I'm using a property package created externally and proved in other process simulators like COCO.  The problem appears when the stream is vapor only. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4457757/120369205-2f733e80-c2d0-11eb-92fd-2923b4fa9d41.png)
![image](https://user-images.githubusercontent.com/4457757/120369311-516cc100-c2d0-11eb-9edf-bf3b8ff6f8ff.png)
![image](https://user-images.githubusercontent.com/4457757/120369429-7d884200-c2d0-11eb-8c21-d6ddbe55d815.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version : 6.5.2

**Comment by DanWBR** [comment]
@byryepez please re-download the 6.5.3 installer, which contains this fix.

**Comment by byryepez** [comment]
Thanks @DanWBR. Reinstalling the newer 6.5.3 installer fixed the issue.
