### ISSUE TITLE
Bug in calculation of internal energy and Helmholtz energy

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#156]
[test_internal_energy (2).zip](https://github.com/DanWBR/dwsim6/files/6591971/test_internal_energy.2.zip)

IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
Error in calculation of Internal energy and Helmholt energy in the properties view

**Expected behavior**
For the gas stream approx U = -3300 kJ/mol, DWSIM calculates -2.2e-6 kJ/mol 

Apparently DWSIM calculates U as

U = H - PV

however H is taken as kJ/mol and PV as J/mol therefore the PV term dominates by a factor of 1000. A similar (yet diffferent) error applies to Helmholtz energy calculation. 

**Screenshots**
![image](https://user-images.githubusercontent.com/58475535/120653538-0e058480-c481-11eb-9cc0-41b172dba774.png)

**Desktop (please complete the following information):**
 - Windows 10 x64
 - Version 6.5.0

**Additional context**
I am suspect this is a bug in the internal calculation of U and A, and not just the representation in the properties view

**Comment by DanWBR** [comment]
@andr1976 can you test the fix?

**Comment by andr1976** [comment]
@DanWBR  Worked for the pure phases, but fails for mixed phases, but that is a
separate issue, and I have made a fix and a pull request for that
