### ISSUE TITLE
Nelder-Mead Simplex Constrained optimization solver not constrained [Bug] 

### ISSUE THREAD

**Issue by byryepez** [DanWBR/dwsim6#158]
**Describe the bug**
While using a Nelder-Mead Simplex Constrained to perform an optimization study, the method utilizes a value for independent variables out of the constrained range (lower than the lower limit, higher than upper limit)

**Screenshots**
The screenshot was taken after the optimization crashed, updating variables and verify expression.
Notice that the current value for the independent variable P2 is negative, even setting the lower limit at 5. Of course, that cause an error. From a mathematical point of view, the current value for the expression is smaller than the values reported in the optimization progress, so basically is doing its job.  
![image](https://user-images.githubusercontent.com/4457757/120713625-6a67a480-c47f-11eb-8cf8-14edccfc2e22.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/4457757/120713044-a0585900-c47e-11eb-9f77-ae8e19fa38cc.png)

**Comment by DanWBR** [comment]
@byryepez unfortunately this is a limitation (or bug) of the external library that provides the method, and I can't fix it.

**Comment by byryepez** [comment]
Thanks, @DanWBR. Maybe it is a good idea to pass the information to the external developers.

**Comment by DanWBR** [comment]
@byryepez unfortunately the library is not developed anymore, and I couldn't find an open source alternative to it...

**Comment by byryepez** [comment]
Dear @DanWBR :  I have a question regarding this issue. I was checking the file where is defined to the case for the bounded Nelder-Mead:

https://github.com/DanWBR/dwsim6/blob/cdd14bc0694d967d29babdd9ae84b877e0949c0c/DWSIM/Forms/Flowsheet%20Analysis/FormOptimization.vb#L437

https://github.com/DanWBR/dwsim6/blob/cdd14bc0694d967d29babdd9ae84b877e0949c0c/DWSIM/Forms/Flowsheet%20Analysis/FormOptimization.vb#L438

I think this variable should be defined as:

`Dim variables(keysind.Count - 1) As Optimization.OptSimplexBoundVariable`

because:

https://github.com/DanWBR/dwsim6/blob/cdd14bc0694d967d29babdd9ae84b877e0949c0c/DWSIM.Math.DotNumerics/Optimization/Simplex.cs#L295

Maybe I'm wrong (I don't have too much experience with .NET or C#), but I wanted to know your thoughts about it.

Cheers,

**Comment by byryepez** [comment]
> Dear @DanWBR : I have a question regarding this issue. I was checking the file where is defined to the case for the bounded Nelder-Mead:
> 
> https://github.com/DanWBR/dwsim6/blob/cdd14bc0694d967d29babdd9ae84b877e0949c0c/DWSIM/Forms/Flowsheet%20Analysis/FormOptimization.vb#L437
> 
> https://github.com/DanWBR/dwsim6/blob/cdd14bc0694d967d29babdd9ae84b877e0949c0c/DWSIM/Forms/Flowsheet%20Analysis/FormOptimization.vb#L438
> 
> I think this variable should be defined as:
> 
> `Dim variables(keysind.Count - 1) As Optimization.OptSimplexBoundVariable`
> 
> because:
> 
> https://github.com/DanWBR/dwsim6/blob/cdd14bc0694d967d29babdd9ae84b877e0949c0c/DWSIM.Math.DotNumerics/Optimization/Simplex.cs#L295
> 
> Maybe I'm wrong (I don't have too much experience with .NET or C#), but I wanted to know your thoughts about it.
> 
> Cheers,

**Comment by DanWBR** [comment]
@byryepez it makes no difference, as OptSimplexBoundVariable is converted to OptBoundVariable internally.

**Comment by pkrulz** [comment]
Is this an opensource alternative for this problem ? Its written in C
https://github.com/huttmf/nelder-mead
