### ISSUE TITLE
DWSIM Autoupdate for Classic UI[Enhancement] 

### ISSUE THREAD

**Issue by pkrulz** [DanWBR/dwsim6#163]
Thanks Again Daniel for the great work !

I understand that DWSIM had an auto update feature which was removed because it worked only on Windows.

Since ClassicUI works only on Windows cant we have this feature back. DWSIM releases like 1-3 updates in a month and it would be very comfortable to auto update than download the full software everytime. I understand its not very difficult to implement auto update since it was already present.

Linux users can update easily using apt-get which is not so for windows users. 
Chocolatey is an option https://chocolatey.org/ which may be considered as well. It allows apt-get like update for windows users.

Thanks & Regards
PK

**Comment by DanWBR** [comment]
auto-update is a very resource and time-consuming task for me. I appreciate your suggestion but this will not happen in the near future.
