### ISSUE TITLE
DWSIM Gives CefSharp Error on Exit [Bug] 

### ISSUE THREAD

**Issue by pkrulz** [DanWBR/dwsim6#164]
Every time I close DWSIM on Classic UI it gives an error 
![image](https://user-images.githubusercontent.com/1046970/122393106-294cb580-cf92-11eb-9110-9c9d112dd82a.png)

Although I have VC 2015-2019 installed
x64 bit version

Windows 10 64 bit
DWSIM 6.5.2 Classic UI

**Comment by DanWBR** [comment]
@pkrulz can you check if you have CefSharp.Core.dll in DWSIM's directory?

**Comment by pkrulz** [comment]
Yes. I do.
In the C:\Users\<USERNAME>\AppData\Local\DWSIM6

![image](https://user-images.githubusercontent.com/1046970/122499762-188e5500-d00f-11eb-8721-3713a984dae7.png)

**Comment by anauta00** [comment]
Hi,

You need to install the Visual Studio 2013 C++ runtime libraries.
Here is the link:
https://support.microsoft.com/en-us/topic/update-for-visual-c-2013-redistributable-package-d8ccd6a5-4e26-c290-517b-8da6cfdf4f10

Apparently, some library needs this older version of the libraries...

Greetings,
Auke Nauta

**Comment by pkrulz** [comment]
> You need to install the Visual Studio 2013 C++ runtime libraries. Here is the link: https://support.microsoft.com/en-us/topic/update-for-visual-c-2013-redistributable-package-d8ccd6a5-4e26-c290-517b-8da6cfdf4f10
> 
This seems to work. Closed quietly after I installed that run time. Thank you !

**Comment by DanWBR** [comment]
@pkrulz CefSharp was removed in v6.7.0, DWSIM now uses Edge WebView2 and/or the standard Windows Forms WebControl.
