### ISSUE TITLE
[Bug]  Lag in updating reaction equation

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#166]
**Describe the bug**
When one changes the include checkbox of component in Reactions interface the Equation does not update quickly and one has to click inside the Equation Label to see the effect!

**To Reproduce**
1. Open DWSIM
2. Add a new reactions
3. Click the checkbox to include/exclude some components

**Expected behavior**
On checkbox click one expects to see the effect on equation rate based on stoichiometry!

**Screenshots**

![img_409_%pn](https://user-images.githubusercontent.com/830394/129678766-8aba2d8f-3ebe-4fd2-b22b-2d147fd8339d.gif)
![img_407_%pn](https://user-images.githubusercontent.com/830394/129678790-7db0b1b7-39d6-4f9f-8078-fec02046880c.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 6.6.0

**Additional context**

**Comment by DanWBR** [comment]
@kookma this is the default behavior of the Windows Forms' DataGridView control. You need to select another cell for the changes to the previous cell be committed.

**Comment by kookma** [comment]
Good! Sometimes I have to click the same label (the one shows the result) to get updated!

**Comment by DanWBR** [comment]
@kookma it is just a matter of getting used to this behavior, which is odd indeed.

**Comment by kookma** [comment]
Thank you! So I close this issue!
