### ISSUE TITLE
[Enhancement] Nonadiabatic-Nonisothermal Operation Mode for Plug Flow Reactor

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#167]
Right now DWSIM 6.6 supports three modes (type of specs) for PFR simulation:

1. Isothermic
2. Adiabatic    (e.g. Adiabatic-Nonisothermal)
3. Outlet temperature (nonisthermal but rarely reflect a real case as it uses a linear change along the reactor)

Rival simulators also support Nonisother operation e.g. nonisothermal-nonadiabatic
In this mode you can set an energy stream and reactor exchanges energy with surrounding e.g a shell side fluid.

**Comment by DanWBR** [comment]
Is this related somehow? https://sourceforge.net/p/dwsim/discussion/844528/thread/9da7825834/?limit=25#edcd

**Comment by kookma** [comment]
> Is this related somehow? https://sourceforge.net/p/dwsim/discussion/844528/thread/9da7825834/?limit=25#edcd

Not, it is not! But the question come from one of student, and I appreciate your reply and links you provided to him through email, I got the forwarded email. Thank you very much!

I actually working on materials for next semester. There are few lectures on simulation reactors in DWSIM!
My previous simulations are mainly on Hysys and Symmetry!

By the way, what I proposed is a real request for enhancement!

I would be happy to share all materials through GitHub once we finished!

**Comment by kookma** [comment]
I like to contribute but the sad news is I am not familiar with .NET, so I can provide every details for you but I cannot implement the .NET side by myself.

**Comment by DanWBR** [comment]
@kookma how should we model the energy stream calculations method? Fixed energy amounts for each section?

**Comment by kookma** [comment]
Daniel,
 I am preparing a PowerPoint to show you how other rival software do this! But it seems they use Q as input and then apply it as uniform, so in any control volume (segment) a fixed amount of energy is applied!

This is I think similar to setting outlet temperature which a linear relationship is used!

**Comment by kookma** [comment]
I send my proposal to your email! I compared with Hysys!

**Comment by kookma** [comment]
General idea:

1. PFR spec: Toutlet --> use a linear profile for T
2. PFR spec: Q   --> use a uniform head flux along the reactor

**Comment by kookma** [comment]
Some good information in this regard plus Python code can be found here:

1. https://github.com/jkitchin/f15-06625/blob/master/rxns-book/non-isothermal-pfr.org
2. http://websites.umich.edu/~elements/5e/toc/index.html


Other resource
1. https://processdesign.mccormick.northwestern.edu/index.php/Reactors

**Comment by kookma** [comment]
With the release of 7.5.6, now DWSIM  is more powerful than ever in simulating tubular reactor.
Now if this enhancement is implemented, you can use DWSIM to simulate multi-reactions multi-components tubular reactor in below modes

1. isothermal operation
2. adiabatic operation
3. nonadiabatic -nonisothermal operation

I would be happy to help in future release to add details for shell side, so you can simulate a real reactor like Methanol reactor where there is water in the shell and reactor acts like a shell & tube exchanger with reactions inside tubes.

**Comment by DanWBR** [comment]
@kookma I can prioritize this if you or someone from your team become a Sponsor: https://github.com/sponsors/DanWBR

**Comment by kookma** [comment]
Well sure! I send you some details through email!
I would also be happy to help during development and test.
