### ISSUE TITLE
[Enhancement] Pressure Drop in Plug Flow Reactor

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#168]
It is recommended to have enhancement to PFR user interface to be able

1.set explicitly pressure drop e.g. a constant like dP=0
2. distinguish where Ergune shall be used
3. If porosity is et to 1, a empty pipe solved for pressure drop

**Comment by DanWBR** [comment]
@kookma didn't the current calculation method suit your needs? Shouldn't we use Ergun for heterogeneous reactors?

**Comment by kookma** [comment]
Hi @DanWBR 
I replied in details through email, but what I mean here is


1. be able to explicitly set the pressure drop along the reactor for empty tube (PFR) and filled tube with catalyst (PBR) this is good when you have not the detailed parameters 
2. be able to use other correlations/equations for both empty and packed tube

Of course some simulator when see void volume is 1 they assume empty tube and void volume less than one they assume packed tube with catalyst!

**Comment by DanWBR** [comment]
@kookma ok, thanks!
