### ISSUE TITLE
[Enhancement] Use Rate instead of Velocity in Reaction Interface

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#171]
DWSIM 6.6 Classic UI

1. Please see below figure, In CRE we use **Rate unit** instead of **Velocity unit**
2. Also in the red box below use **unit** instead of _units_ as it shows the selected unit!

![image](https://user-images.githubusercontent.com/830394/129913553-e188921d-3bda-425a-afdd-4ec329e8ca21.png)

**Comment by DanWBR** [comment]
I agree with the Rate, but not with the 'unit'. in the rate units, we have one unit for mole amount, one for volume and another one for time, so 'units' seems more adequate.
