### ISSUE TITLE
[Bug] Solid separator not working

### ISSUE THREAD

**Issue by Greg66** [DanWBR/dwsim6#173]
**Describe the bug**
The solid separator is not working correct.

**To Reproduce**
1. Create a stream with pure water, consisting of ice and liquid water at 0°C
2. feed that stream into a solid separator unit operation
3. Both output streams are at boiling point now with a vapor fraction of 93%

**Expected behavior**
1. Liquid output stream 1 should be only water at 0°C
2. Solid output stream 2 should consist of solid only at 0°C

**Sample file**
See following file for demonstration:
[Ice production.zip](https://github.com/DanWBR/dwsim6/files/7032148/Ice.production.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/4138115/130450629-10122044-a208-4f59-8067-131335357954.png)

**Desktop (please complete the following information):**
 -DWSIM 6.6
- Windows

**Additional context**
My analysis with the debuger showed, that material streams of pure components are enforced to be calculated by PH-flash instead of the flash type defined from connected unit operation.
Here a TP-Falsh is definied from solid separator for both output streams (which is supposed to be correct here). As enthalpy of output streams is not defined from solid separator side, the result of PH flash can't be correct.
In my view this enforced PH flash should be discarded.

**Comment by DanWBR** [comment]
@Greg66 in your sample case, even with the fix, the liquid phase will have some solid due to T/P conditions and the presence of water.

**Comment by Greg66** [comment]
Hi Daniel i just issued a new commit solving the issue you mentioned.
By defining the stream enthalpy of outlet streams and the stream spec to be PH instead of TP this unit is working as expected now. Separator efficiencies of solid and liquid phases are working now as well.
Commit: #177

**Comment by DanWBR** [comment]
@Greg66 great, thanks! closing this issue then.
