### ISSUE TITLE
[Bug] Clicking on Open Python Script Editor Several Times Create Several Script Windows

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#174]
**Describe the bug**
The object editor of a custom UO shows a button **Open Python Script Editor** Each time one clicks on this button a new Script window is opened! This is error prone! as if you edit one, the other are not updated!

**To Reproduce**
See attached clip!

**Expected behavior**
Only one Script window per UO shall be opened! DWSIM can check if a the script window for a UO is opened, on clicking just brings it into focus!

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version DWSIM 6.6

![img_451_%pn](https://user-images.githubusercontent.com/830394/130996780-64b15240-2009-42e0-9afd-27e6f455321a.gif)

**Comment by DanWBR** [comment]
@kookma thanks for the report!
