### ISSUE TITLE
[Bug] Script Manager: Click on API Help Button Opens Explorer with Page Not found

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#178]
**Describe the bug**
In Script Manager click on API Help toolbar button
DWSIM opens https://dwsim.inforside.com.br/api_help57
Browser shows page not found

**Expected behavior**
Correct the address of API page. **Suggestion** If DWSIM keeps help of all versions (good idea) every DWSIM based on its version shall open proper page

**Screenshots**
![img_459_DWSIM](https://user-images.githubusercontent.com/830394/131250615-c71a4c88-1535-4e2c-bfbd-2cf2da70e811.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version DWSIM 6.6

**Comment by DanWBR** [comment]
@kookma due to webserver storage restrictions, I can only host the help contents for the latest version.

**Comment by kookma** [comment]
> @kookma due to webserver storage restrictions, I can only host the help contents for the latest version.

That makes sense! Thank you!
