### ISSUE TITLE
[Bug] API Documentation Link to View Source code are broken!

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#179]
**Describe the bug**
The DWSIM API help is very helpful when your develop python scripts. Unfortunately The links from API help pages to GitHub source code are broken!

**Expected behavior**
URLs need to be corrected.

For below screenshot I noted that if

https://github.com/DanWBR/dwsim6/blob/windows/DWSIM.Thermodynamics/Material+Stream/MaterialStream.vb#L3055

Correct to 

https://github.com/DanWBR/dwsim6/blob/windows/DWSIM.Thermodynamics/Material%20Stream/MaterialStream.vb#L3055

It will work!

**Screenshots**
![image](https://user-images.githubusercontent.com/830394/131251373-0308c6e1-1e87-4c32-8f31-411c25ef2c37.png)

**Comment by DanWBR** [comment]
the link is generated automatically, unfortunately. I don't think that there is an easy solution for it but I'll check anyway.

**Comment by DanWBR** [comment]
fixed in https://github.com/DanWBR/dwsim6/commit/78ac6ecabbbc486b6b8e510238e2e83865673224, which will reflect changes made to v6.6.1.
