### ISSUE TITLE
Issue: Wrong height of notebox and overlap with Solution Inspector Message

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#18]
**Describe the bug**
This issue has been reported before (see https://github.com/DanWBR/dwsim6/issues/13), but seems still not solved!

**Description**
Look at the below screenshots

Image 1: Notes in Object Editor is not visible with full height
![Image-015](https://user-images.githubusercontent.com/830394/90669715-51cb2c80-e267-11ea-8606-d8f4642b93df.png)

Image 2: Solution Inspector wrongly covers part of Notes in Object Editor

![Image-016](https://user-images.githubusercontent.com/830394/90669913-9fe03000-e267-11ea-92df-4062deaf8671.png)

**Expected behavior**
1. Visible Notes with full height
2. Move Solution Inspector message strip to proper position or show it as docked window!

**Desktop (please complete the following information):**
 - OS: Windows 10
 - DWSIM 6.1 Update 3
 - Classic UI

**Comment by kookma** [comment]
@DanWBR 
When the  Solution Inspector is active it can displays an icon/message on _General Info_ in **Object Editor** under _Status_!
I think this is a better place

**Comment by DanWBR** [comment]
@kookma I've solved the solution inspector bar for the material stream editor only. It is a hell of a work to fix this because each object has its own editor window, with controls manually arranged one by one. I've tried to add the bar programmatically without interfering with the other controls but it wasn't possible. please be patient as this takes a lot of time to be fixed!

**Comment by kookma** [comment]
Hi Daniel,
 Sure, no problem at all. Please prioritize these issues as you like. I am sure you have a midterm plan for DWSIM and you may have more important objectives to put your time for them.
 I may recommend to label this and if you think it worth to be resolved just keep them open!

I am reading the code and it takes to learn how your VB.NET code works, later on I may be able to submit PR and this will help you just review and accept/reject. So, it will save your time.

Thank you for all your efforts

**Comment by DanWBR** [comment]
Thanks @kookma, I have a lot to do indeed but be sure that I'm also working on fixing the bugs you're reporting, thank you very much.
