### ISSUE TITLE
[Enhancement] Outlet Energy streams for exothermic reactions

### ISSUE THREAD

**Issue by SamuWu99** [DanWBR/dwsim6#181]
Hello Daniel,

I am Samuel and actually working on my Bachelors thesis with DWSIM. All reactors in DWSIM have only one energy stream, an inlet stream. For endothermic reactions it's fine because you have to add energy. For an exothermic reaction you just get a negative value for the energystream. In my current problem I want to use the energy created in the conversion reactor (exothermic reaction) to generate steam. To do so, I add a specification block to the simulation, which could be solved easier.
Enhancement energy streams exothermic reactions.
![Enhancement energy streams exothermic reactions](https://user-images.githubusercontent.com/89941997/131792550-0e64abfd-b050-4ca8-9562-995197c9951f.jpg)
My solution would be an additional energy stream at all reactors, an outlet energy stream. So every reactor has two energy streams, an inlet stream for endothermic reactions and an outlet stream for exothermic reactions. Therefore it would be possible to directly connect the output energy stream with my heater.
![image](https://user-images.githubusercontent.com/89941997/131792786-47482ebd-8137-4096-abf7-a6e8e587372e.png)
![image](https://user-images.githubusercontent.com/89941997/131792598-b0dedaf4-5694-4054-916c-7c7999aba9c3.png)
In the case of an endothermic reaction, the outlet energy stream would be 0. In the case of an exothermic reaction, the inlet energy stream would be 0. 

Kind Regards,
Samuel

**Comment by kookma** [comment]
@Daniel
One issue here is: for an endothermic reaction we need heat (energy) and for an exothermic reaction we generate heat!
So do not you think the sign of energy stream shall be corrected?

I mean if a reactor generate heats, the energy stream needs to be positive and if it consumes it be negative!
I only not sure the direction of stream in DWSIM! 

In Hysys the energy stream for reactors is always an outlet stream! It is positive for reactor generating heat (like burning CH4) and it is negative when reactor consumes energy (like ethane cracking) I think we can follow Hysys convention!

![image](https://user-images.githubusercontent.com/830394/131808440-75767edf-7af1-431d-a2cf-37d5253f0655.png)
This is for an exothermic reaction.

**Comment by DanWBR** [comment]
changing the position of the energy stream will break all existing simulations. adding another energy port is possible.

**Comment by kookma** [comment]
@DanWBR I have not seen two energy ports on reactor, have you?

**Comment by DanWBR** [comment]
@kookma I was talking about adding another energy port to the reactors, they don't have two.

@SamuWu99 could you please attach a sample simulation?

**Comment by DanWBR** [comment]
@kookma if the energy stream is entering the reactor where an exothermic reaction occurs, then the sign of the energy flow must be negative. the current setup is correct. you need to remove energy from the reactor in order to keep it at the same temperature.

**Comment by SamuWu99** [comment]
@DanWBR I attached the file of my request. But it's on DWSIM 6.5.5 unfortunately.
[CO-Gas Verbrennung.zip](https://github.com/DanWBR/dwsim6/files/7109593/CO-Gas.Verbrennung.zip)

**Comment by Greg66** [comment]
I issued an update of Conversion Reactor UO now.
This UO has an energy outlet now instead of an energy inlet. This energy stream may be connected to further UO's like a heater. Other reactors are intendet to be modified in the same way.
See commit: #218
![Reactor Energy Output](https://user-images.githubusercontent.com/4138115/139904882-a02a6dea-cf86-42a1-bf74-093f23a5f23e.jpg)
