### ISSUE TITLE
[Bug] Controller Block- Convergence Method

### ISSUE THREAD

**Issue by SamuWu99** [DanWBR/dwsim6#182]
In the Simulation attached below I use the controller block to control the molar fraction of oxygen in the "Rauchgas" stream by varying the volumetric flow of the air inletstream "Luft".
![image](https://user-images.githubusercontent.com/89941997/131794163-592652f1-e6c4-43ca-ace2-815f961c2bfb.png)
You have 4 convergence methods in DWSIM. For some reason the "Secant" methode is not working, but the "Brent" is. So I changed the method to "Brent" to solve the problem.
![image](https://user-images.githubusercontent.com/89941997/131794729-35ca789f-922c-4f14-8778-fc5e11f0afb8.png)
The air inlet stream "Luft" is dependent of the inlet stream "CO-Gas". So everytime I am changing the volumetric flow of the 
"CO-Gas" stream, the controller block has to calculate a new value for the "Luft" stream. Normally DWSIM should now iterate with the "Brent" convergence methode, because I chose it before. But DWSIM automatically wants to iterate with "Secant" convergence methode. So it doesn't safe my settings and automatically jumps back to the "Secant" convergence methode, which leads to wrong results.
![image](https://user-images.githubusercontent.com/89941997/131796163-2b6a615a-f784-4020-8582-7f55f7ec60a9.png)

Also when i tick the "Converge/Solve with flowsheet" Button, it automatically tries to iterate with the "Secant" Methode.

![image](https://user-images.githubusercontent.com/89941997/131796999-dc8bd5b7-ebbb-4feb-a17c-25474a5870ce.png)
It would be better if DWSIM safes the methode I chose the first time on the controller block and doesn't jump back to the default methode. So in my case it should safe the "Brent" Methode.

Working on Windows, DWSIM 6.6.0

Kind Regards,
Samuel

**Comment by DanWBR** [comment]
@SamuWu99 I can fix the individual solving method selection not persisting, but when you select the Flowsheet Solver, DWSIM uses a newton method with numerical derivatives to solve all selected controllers at once.

**Comment by DanWBR** [comment]
fixed the individual solving method in https://github.com/DanWBR/dwsim6/commit/948ab4c50e89498b2c229102e2dffb1592fe4729
