### ISSUE TITLE
[Enhancement] Thicker Font in Interface

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#183]
Nowadays there are many HD display around and people use new OS like Windows 10.
The current font of UI in DWSIM (I use classic UI) is very thin! Some windows like the one is displayed when flowsheet is loading is very think! 

My suggestion is can UI use some thicker font (a little heavier)? Does UI follows the default font of the host OS?

**Comment by DanWBR** [comment]
it follows the default font... can you attach a screenshot?

**Comment by kookma** [comment]
Hi Daniel
If it uses the default Windows UI font (Segoe UI should be) then it is okay!


![image](https://user-images.githubusercontent.com/830394/131855191-02a41cf5-f4a7-46a5-9862-4688b874fadf.png)

![image](https://user-images.githubusercontent.com/830394/131854885-0fb88b71-8977-4f48-8b14-75164db3b834.png)

**Comment by DanWBR** [comment]
@kookma v6.6.2 should make things better, please let me know what you think about it.

**Comment by kookma** [comment]
@DanWBR 

![image](https://user-images.githubusercontent.com/830394/132904411-ee3b1c3b-0993-4947-9fb5-b650f670b74e.png)

See the alignment of script titles and background color! I think this happened after you changed the font size!

**Comment by DanWBR** [comment]
@kookma what are the DPI and resolution of your display?

**Comment by kookma** [comment]
@DanWBR - The image above is on a full HD monitor (1920x1080) on 15.6".
I have also tested on a HD monitor with 1600x900 on 21"

The second has a better alignment but the issue still is there! See below image
![image](https://user-images.githubusercontent.com/830394/132935956-2ee13447-e152-4d5e-8e68-03cf02e0afd6.png)

Is the issue related to not use center align the label?

**Comment by DanWBR** [comment]
@kookma I need to know the DPI too

**Comment by kookma** [comment]
Ah sorry the DPI is 141 for 1920x1080 on 15.6"
This is for the first image I sent you above!

**Comment by DanWBR** [comment]
After a few hours of trial and error... 

<img width="730" alt="Captura de Tela 2021-09-13 às 15 03 09" src="https://user-images.githubusercontent.com/2669419/133135347-95bfaa1f-d624-4365-a706-5d5ab52a7622.png">
