### ISSUE TITLE
[Bug] Unknown Error in PFR SImulation

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#184]
- OS: Win 10
- DWSIM: 6.6

Simulating a simple PFR for a first order reaction(`r=kCa`) as `CO + 0.5 O2 -> CO2` with 1 mol/s gives the below error!

![image](https://user-images.githubusercontent.com/830394/131962460-3677cbf9-bcc2-4f71-a52f-389362c95fc6.png)

**Suggestion** For steady state PFR simulation `tf=t0` has no meaning! Please consider a meaningful error message!
I think the reason is when PFR volume is set to zero (initial value by DWSIM) this error raised

**Reproduce**
Open and run the attached file!

[pfr simulation in dwsim.zip](https://github.com/DanWBR/dwsim6/files/7103840/pfr.simulation.in.dwsim.zip)

**Comment by DanWBR** [comment]
@kookma this error comes directly from the ODE solver. Should it work with V = 0? It doesn't make sense for me to add safeguards for when the volume is zero. It is the user's responsibility to set a reactor volume before running the simulation.

**Comment by kookma** [comment]
> @kookma this error comes directly from the ODE solver. Should it work with V = 0? It doesn't make sense for me to add safeguards for when the volume is zero. It is the user's responsibility to set a reactor volume before running the simulation.

You are quite right! The integrator independent variable is time (t). 

But DWSIM error message can be like "reactor volume is zero..." This will help to quickly debug the flowsheet!
A normal user cannot find the source of error with `tf=tf0!`

But if you think it is oaky, keep this as is!

**Comment by DanWBR** [comment]
@kookma right, but then the user should quickly notice that the volume is zeroed. Actually, I've never seen this error before!

**Comment by kookma** [comment]
We are preparing some material for next semester! Two graduate students are working on reactor simulation and these are the feedbacks I got from them! We would be happy to share somewhere these materials! They can be used for an undergraduate course.

**Comment by DanWBR** [comment]
@kookma I've added a default volume value of 1.0 m3 so we don't see this error anymore by accident.
