### ISSUE TITLE
[Issue] PFR with Catalyst Data: Change in Catalyst Loading

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#187]
* DWSIM 6.6
* Windows 10

It seems in DWSIM when catalyst data is given, DWSIM uses Ergun equation for pressure drop but it is not clear specially for ordinary users, how DWSIM integrates the reactor ode by weight (dF/dW = r) or by volume (dF/dV= r)

One expect to see different results when the catalyst loading is changed! BUT the interface does not show anything!

![image](https://user-images.githubusercontent.com/830394/131968079-970b302c-5338-4cdf-ba21-a87d82dfa83c.png)

## Exampel
The attached file has two fake reactions

* CO oxidation (simple kinetic)
* Ethane cracking (heterogeneous catalytic)

* When you change catalyst loading for both reactions, you see changes in conversion for ethane cracking
* It seems DWSIM uses the effect of catalyst loading for ethane cracking, but nothing happened for CO oxidation (we know it has   rate based on reactor volume)

**Suggestion**
* What if ethane cracking rate is based on volume of catalyst? do you agree to have an explicit option like Aspen Plus lets user decide to integrate versus catalyst weight or catalyst volume (e.g reactor volume)
* In simple words, DWSIM interface for PFR shall explicitly shows if calculations are based on catalyst or not!

* DWSIM simulation file 
To reproduce use the attached file

[pfr simulation in dwsim ii.zip](https://github.com/DanWBR/dwsim6/files/7104242/pfr.simulation.in.dwsim.ii.zip)

**Comment by DanWBR** [comment]
@kookma catalyst information is used only for heterogeneous reactions. this is easy to see in the source code:

https://github.com/DanWBR/dwsim6/blob/1c3b07b7159a298bc1fbe513e01e6e7620aee9b7/DWSIM.UnitOperations/Reactors/PFR.vb#L419-L427

The above is located in the function called by the ODE solver. Both reaction types are integrated in a volume basis, which is why DWSIM requires the catalyst loading in mass per volume units (kg/m3 in SI).

**Comment by DanWBR** [comment]
The pressure drop, on the other hand, is calculated differently depending if the catalyst loading is zero or not. It doesn't depend on the reactions occuring in the reactor:

https://github.com/DanWBR/dwsim6/blob/1c3b07b7159a298bc1fbe513e01e6e7620aee9b7/DWSIM.UnitOperations/Reactors/PFR.vb#L1201-L1229

**Comment by DanWBR** [comment]
I'll change the editor to disable the catalyst info boxes when there are no heterogeneous reactions in the selected reaction set.

**Comment by kookma** [comment]
> The above is located in the function called by the ODE solver. Both reaction types are integrated in a volume basis, which is why DWSIM requires the catalyst loading in mass per volume units (kg/m3 in SI).

That is a pity I do not know VB.NET, to help and prepare some PR!

By the way, I believe the catalyst packed density can be read no matter what units is used and then internally converted into SI.
I understand you always integrate in volume by internally converting r from weight basis to volume basis! It is a good practice!

**You can ignore this**: sometimes reaction is catalytic but rate is based on the volume of catalyst NOT weight! one can manually convert it to weight basis to use in DWSIM. I checked Aspen Plus and Aspen Hysys both support weight/volume basis.

**Comment by DanWBR** [comment]
@kookma catalyst loading has density units, it is not fixed to kg/m3:

https://github.com/DanWBR/dwsim6/blob/351ec302c9b93384b59ff8d76030a3ddc66c4561/DWSIM.SharedClasses/UnitsOfMeasure/SystemsOfUnits.vb#L204

**Comment by kookma** [comment]
> `resv = fpp.CalculateDeltaP(diameter * 0.0254, L, 0.0#, 0.000045, Qvin * 24 * 3600, Qlin * 24 * 3600, eta_v * 1000, eta_l * 1000, rho_v, rho_l, tens)`

For a PFR how do you calculate diameter? Is it based on the volume and length are given?
I would suggest to have clearly get the tube diameter from user! In industrial environment there are many cases you have tubular reactors (like methanol, steam reformer,...) The volume normally refers to volume of all those tubes! As I sated in another thread we can

1. get number of tube
2. get reactor volume
3. calculate tube volume by (reactor volume) / (number of tubes)
4. calculate flow in one tube (feed flow rate) /  (number of tubes)

This way DWSIM can ASSUME one tube by default! If no of tubes is given then use it
From length and ID calculate volume or get the volume and one of length/diameter

**Comment by DanWBR** [comment]
@kookma please let's slow things a little bit otherwise I'll go crazy! I woke up this morning with so many emails coming from you, from both github and Sourceforge...

**Comment by DanWBR** [comment]
@kookma please remember that I'm only one person and DWSIM is not my main occupation. If you ask too much in sequence, I will surely miss something in the middle.

**Comment by kookma** [comment]
@DanWBR okay no problem. You are right! We are three in our side working on DWSIM! You are alone! ;-)
Let us know if we can be of any help!

Thank you I will archive the cases in Tiddlywiki and when you allow us to send you and you can handle those request/bug reports/enhancement, I will share with you!

I think we should learn VB.NET to be more helpful!

**Comment by DanWBR** [comment]
@kookma updated the editor to include Diameter as an editable property.

<img width="380" alt="Captura de Tela 2021-09-03 às 09 51 03" src="https://user-images.githubusercontent.com/2669419/132008165-a0a2fae7-78c9-4477-ad58-5d04d6dd3c1d.png">
<img width="378" alt="Captura de Tela 2021-09-03 às 09 51 07" src="https://user-images.githubusercontent.com/2669419/132008170-02c72156-5c48-4bdf-915f-e5af7054e1f0.png">

**Comment by kookma** [comment]
I love the catalyst info in separate tab!

**Comment by DanWBR** [comment]
@kookma this will make my life easier when implementing the new features (tubes, adv. heat exchange)

**Comment by kookma** [comment]
> @kookma this will make my life easier when implementing the new features (tubes, adv. heat exchange)

I understand, developing new features is exciting and challenging! but writing documentation and debugging is tedious (I hate both of them ;-) )
