### ISSUE TITLE
[Enhancement] Python.NET in DWSIM and Information Window

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#188]
* DWSIM 6.6
* Windows 10

## Feature 1

1. Open Script manager
2. Create New script with `print("Hello DWSIM")`
3. Run Script, It works fine
4. Use Python.NET as interpreter
5. Run the code you get below error

![image](https://user-images.githubusercontent.com/830394/131998478-81266735-1197-4c3e-8472-d34735bce8cd.png)

I have investigated, it seems there is some issue in reading and displaying the output in Python.NET
See https://www.hellocodeclub.com/how-to-fix-typeerror-a-bytes-like-object-is-required-not-str/

It would be great if print("message") work in DWSIM/Python.NET. At the moment `Flowsheet.WriteMessage(string)` seems to work in DWSIM 6.6

## Feature 2

1. Open Script manager
2. Create New script with `x = 2`
3. Use Python.NET as interpreter
4. Run the code you get below message in Information window

![image](https://user-images.githubusercontent.com/830394/131998920-c484fab7-3e0e-47d3-9578-72e42295a8c0.png)

What is the `b"` displayed in Information windows? I think there is no need to display anything as we have no print no writing!

**Comment by DanWBR** [comment]
The 'b"' comes from Python.NET. Getting the console output from python to DWSIM doesn't happen without damage...😄
