### ISSUE TITLE
[Bug] Pressure loss on Mac version (6.6.1) not calculated correct (compared to Windows 6.6.0).

### ISSUE THREAD

**Issue by piskernik** [DanWBR/dwsim6#189]
I followed the tutorial creating a simulation on Youtube Basic Course Task 3 and could not get similar results on a Mac (6.6.1). I tried the same file on Windows 10 (6.6.0) and the results were comparable to the video (however also not identical).

Something is wrong in the pressure loss calculation of vertical pipes (see screenshots).

**Screenshots**
Windows:  
![image](https://user-images.githubusercontent.com/23580499/132105784-f36a64dc-6c2d-44f1-abf7-de84ceed972a.png)
Mac (Dark Mode):
![Bildschirmfoto 2021-09-04 um 21 24 27](https://user-images.githubusercontent.com/23580499/132106040-b9bf35b2-56e7-4ef8-88b8-547424a5a58a.png)

Here is the file for your reference.
[Pumping.dwxmz.zip](https://github.com/DanWBR/dwsim6/files/7110397/Pumping.dwxmz.zip)

**Comment by DanWBR** [comment]
Fixed in https://github.com/DanWBR/dwsim6/commit/66148417ad695b82065b53718709db313f8d40f3

**Comment by piskernik** [comment]
Many thanks! What an excellent work you are doing here!
