### ISSUE TITLE
Pressure drop for pipe give 0 as per each pipe

### ISSUE THREAD

**Issue by CPN3264** [DanWBR/dwsim6#191]
Calculating pressure drop for pipe segment give me a 0 result in the new 6.6.1 version

**Comment by DanWBR** [comment]
I'm aware of this issue and am working on a fix for the day after tomorrow.

**Comment by DanWBR** [comment]
Fixed in https://github.com/DanWBR/dwsim6/commit/66148417ad695b82065b53718709db313f8d40f3
