### ISSUE TITLE
[Bug] PFR Object Editor Dimensions - Reactor Diameter Does Not Work

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#192]
* Win 10
* DWSIM 6.6.1

The new PFR object editor and new Dimensions tab is great! There is a minor bug however

## Reactor Length 
- if you choose Sizing information= Reactor Length, you can enter reactor length, the entered number is in blue color and on pressing Enter key, Solve Flowsheet is triggered and DWSIM solves the reactor.
- The Reactor diameter input is inactive and will be updated once reactor is solved!

## Reactor Diameter
- However if you choose Sizing information= Reactor Diameter, you can enter reactor diameter, the entered number is in BLACK not in blue color and on pressing Enter key, Solve Flowsheet is NOT triggered and DWSIM do nothing.
- The Reactor length does not update
- If you manually press the Solve Flowsheet button (F5), DWSIM solves the reactor, but does NOT use the entered value for diameter, it uses the previous reactor length which its input box is inactive now and update the diameter value to its previous value

![image](https://user-images.githubusercontent.com/830394/132323221-35e453e6-31ae-44e6-b8b2-ea1ebbb08baa.png)

**Comment by DanWBR** [comment]
Fixed in https://github.com/DanWBR/dwsim6/commit/66148417ad695b82065b53718709db313f8d40f3
