### ISSUE TITLE
[Bug] 6.6.2 DWSIM crashes when using 0 hours or 0 minutes in Integrators ->Parameters Duration

### ISSUE THREAD

**Issue by piskernik** [DanWBR/dwsim6#194]
Mac OS X DWSIM 6.6.2 crashes when using 0 hours or 0 minutes in Integrators ->Parameters Duration:

<img width="404" alt="Bildschirmfoto 2021-09-07 um 20 24 38" src="https://user-images.githubusercontent.com/23580499/132395312-7e3965a3-b95d-489a-998e-96bedb69fe76.png">

Typing "0" in the field for hour or minute immediately crashes DWSIM (on a Mac).

**Comment by DanWBR** [comment]
I couldn't reproduce this issue here on my computer. Can you upload the lasterror.txt file from your Documents/DWSIM Application Data folder?

**Comment by piskernik** [comment]
Occured also in 6.6.3:
Output from last app crash:

System.ArgumentOutOfRangeException: Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks.
Parameter name: ticks
  at (wrapper managed-to-native) AppKit.NSApplication.NSApplicationMain(int,string[])
  at AppKit.NSApplication.Main (System.String[] args) [0x00040] in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.14.0.110/src/Xamarin.Mac/AppKit/NSApplication.cs:100 
  at Eto.Mac.Forms.ApplicationHandler.Run () [0x00047] in <5970afe3335542568b2416b8242cdff2>:0 
  at Eto.Forms.Application.Run (Eto.Forms.Form mainForm) [0x0002c] in <23bf6400f02d49eba883a8238fbdb959>:0 
  at DWSIM.UI.Desktop.Program.MainApp (System.String[] args) [0x0082b] in <91edf130c80648c59bf077b6ab3e404c>:0 

This is the file:
[Dynamics.dwxmz.zip](https://github.com/DanWBR/dwsim6/files/7203578/Dynamics.dwxmz.zip)

**Comment by DanWBR** [comment]
@piskernik what are your regional settings (language, number format, etc)? I still can't reproduce this issue here, I'm typing everything and it is not crashing.

**Comment by piskernik** [comment]
The Mac is German, but the number format in DWSIM is with period 0.00 (in the correct culture we would write it 0,00). But it immediately crashes already when typing a 0 (in any of the fields for second, minute or hour). (It crashes independent on the simulation, just tried it with another one). It is independent from the integrator, it's the time field in dynamics part. I can't even change the numbers with the arrows (up and down). It immediately crashes without further message, also with other numbers. I guess (I'm speculating) you calculate the entry with current culture, the result however cannot be converted to ticks (somehow).

**Comment by piskernik** [comment]
Just changed the language settings to US and all number formats are changed as well (and restarted the Mac of course), however DWSIM still crashes:-(

**Comment by piskernik** [comment]
What I do not understand is, that the values within the programm 
integ.Duration 00:10:00
IntegratorPropertiesStartValue 1/1/0001 12:10:00 AM
are not consistent with the displayed value, which is:
<img width="402" alt="Properties_Screenshot" src="https://user-images.githubusercontent.com/23580499/134805605-3f49e108-23a2-4234-afef-1fe2ae533df1.png">

**Comment by piskernik** [comment]
O.k. I found out, that this happens on any Eto Forms DateTimePicker, initialized with 00:10:00 on my Mac. It also crashes.
