### ISSUE TITLE
[Enhancement] COIN-OR and NOMAD solvers

### ISSUE THREAD

**Issue by JarlPed** [DanWBR/dwsim6#195]
Each solver provided in DWSIM is 'in-house' developed. I believe that by including an interface to other external solvers supplements the collection and that the DWSIM project overall take advantage of other open source projects.

I would like to see the external solvers being implemented as possible method, similar as that to the excel plugin OpenSolver.

**Comment by kookma** [comment]
@JarlPed - do you mean ode solver and ALE solver? (numerical solver) 
or you mean a new solver for Gibb Reactor for instance? 

Any way I support the idea!

**Comment by DanWBR** [comment]
@JarlPed the interface for external solvers is already there and ready to be used: https://github.com/DanWBR/dwsim6/blob/windows/DWSIM.Interfaces/IExternalSolver.vb

**Comment by DanWBR** [comment]
Some Unit Operations already support loading and using an external solver: Distillation Column (Non-Lin System), PFR (ODE), Gibbs Reactor (Non-Lin Min) and Equilbrium Reactor (Non-Lin System)

**Comment by JarlPed** [comment]
@kookma Sorry for not expressing myself precisely, the solvers in mind are minimization solver algorithms.

@DanWBR Thanks for the tips, I think it is likely to put the source and binaries from the COIN-OR and Nomad project in \packages\, and craft some functions based on the interfaces that can be refered to the form layouts. I'm not entirely sure how the solver selection performed for the different unit ops (in particular reactors). Considering the electrolyte NRTL model, it uses exclusively the IPOPT algorithm for solving equilibrium reactions.

The overall goal I portrayed here is to offer more options to minimization solver selections, and possibly enhance the computation time, since these algorithms are largely optimized for expensive black box problems.

**Comment by DanWBR** [comment]
> The overall goal I portrayed here is to offer more options to minimization solver selections, and possibly enhance the computation time, since these algorithms are largely optimized for expensive black box problems.

@JarlPed that's exactly the purpose of these interfaces. Speaking of which, I've tried to work with NOMAD many times before, but it seems that it needs you to "build" your problem in a separate file and then run it from a command line...

**Comment by andr1976** [comment]
Apparently shared libraries are provided it seems, though I assume it is unmanaged code 
https://nomad-4-user-guide.readthedocs.io/en/latest/LibraryMode.html#

**Comment by andr1976** [comment]
I could extend this request to include some global derivative free solvers, it seems the Nelder-Mead, Brent, BFGS, IPOPT etc are all local solvers like e.g. LibOptimization (although not active since 2020).
