### ISSUE TITLE
Error in Solving the Simulation-Reactors

### ISSUE THREAD

**Issue by HadiEbrahimiHaratameh** [DanWBR/dwsim6#2]
Dear Medeiros,
It could not possible to solve a simple steam reforming by both equilibrium and Gibbs reactors.
- First, Steam reforming with Equilibrium reactor (including reforming and water gas-shift reactions) is solved at above 20 bar, but below 10 bar, it could not be solved. 
-Second, Equilibrium reactor of steam reforming at high pressure (above 20 bar) is OK, but when I want to add a Gibbs reactor beside the flowsheet and compare the results of two reactors, it could not be solved. The same procedure was applied two other softwares, e.g. HYSYS, without any problem.
Could you please see the attached files.

![DWSim_Reforming_test](https://user-images.githubusercontent.com/51861935/88249090-8e335900-ccb8-11ea-8e4c-8a96c2526450.JPG) 
[Worksheet_DWSim_reforming.txt](https://github.com/DanWBR/dwsim6/files/4963719/Worksheet_DWSim_reforming.txt)

Yours Sincerely,
Hadi Ebrahimi

**Comment by DanWBR** [comment]
It may be required to tweak the solver parameters in the equilibrium reactor at some conditions. As for the gibbs reactor, it seems thst you did not define the element matrix as one can infer by the error message.

**Comment by HadiEbrahimiHaratameh** [comment]
It solved for both reactors.
Thank you
Hadi Ebrahimi
![DWSim_Reforming_test_OK](https://user-images.githubusercontent.com/51861935/88253253-88dd0b00-ccc6-11ea-8937-5c06a4d5445f.JPG)

**Comment by DanWBR** [comment]
Great! I kindly ask you to use the forums next time as this section is more suited for code issues.
