### ISSUE TITLE
Issue stream flowrate: all input boxes are active all the time

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#20]
**Describe the bug**
For a feed/inlet stream one can set flowrate using one of molar flow, mass flow or volumetric flow! but after setting a flowrate for example mass flowrate other input boxes e.g molar and volumetric liquid flowrate are still active and one also enter a value in those boxes.

**To Reproduce**
1. Open DWSIM
2. Create a new simulation
3. Add a material stream
4. Set flow rate e.g. molar flow
4. See issue: mass flow rate and volumetric liquid flow rate still are active

![Image-025](https://user-images.githubusercontent.com/830394/91604117-57212900-e983-11ea-8e81-85f619487406.png)

**Expected behavior**
 It is recommended when one of flowrate is set the other input boxes (flowrate) grayed out

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Classic UI
 - DWSIM 6.1 Update 4

**Comment by DanWBR** [comment]
This is not an issue. The other boxes are also editable because you can set any of them at any time and DWSIM will calculate/update the other two.

**Comment by kookma** [comment]
@DanWBR  Yes, it is not an issue, but one cannot understand which has been set and which has been calculated! If DWSIM somehow differentiates between the value entered by user and one calculated by DWSIM is better (even use different color like blue for inputs and black for calculated or other methods)! We have the same in Hysys, for example all flowrate (molar, mass, volumetric liquid) are editable as soon as you set one of them the other calculated and gray out! 

Please see examples from Aspen Hysys 11 and Aspen Plus 11

**Aspen Hysys** Note that molar flow is blue and is the one entered by user
![Image-027](https://user-images.githubusercontent.com/830394/91628016-f6b8d880-e9d0-11ea-9d93-783d36517f50.png)

**Aspen Plus** The flow basis is set by user and only one inputbox is visible at a time
![Image-026](https://user-images.githubusercontent.com/830394/91628032-25cf4a00-e9d1-11ea-9508-c3f959c429e0.png)

**Comment by DanWBR** [comment]
I really don't think that this would be an evolution for DWSIM, as in HYSYS you must delete the defined value in order to enable the other cells so they can be edited. In Aspen Plus this is even worse as you must select the flow basis before setting the flow. In DWSIM I'm highlighting the textbox for the defined flow while still keeping all of them active and ready to be edited by the user.

**Comment by kookma** [comment]
Daniel, Feel free to accept or reject proposals. If something is critical I will discuss it in more detail.

By the way here in this case: I am insisted **to distinguish between the value given by user and the one is calculated**, you may keep all of them editable.

**Comment by DanWBR** [comment]
This is how it looks in the current code, what do you think?

<img width="401" alt="Captura de Tela 2020-08-30 às 08 14 58" src="https://user-images.githubusercontent.com/2669419/91658755-0b60a380-ea99-11ea-9e54-b750afb1a16b.png">

**Comment by kookma** [comment]
Great! This way I can realize the Mass flow was given bu user! 

Just a minor comment, you should keep this consistent and that means all data are given by user shall follow the same rule.
