### ISSUE TITLE
About polymerization process simulation on DWSIM

### ISSUE THREAD

**Issue by Jackxi1024** [DanWBR/dwsim6#200]
Hello, I'm doing research on polymerization process simulation recently. I found that DWSIM is a great project. I want to complete my research based on DWSIM.
Therefore, I want to define polymers (such as polyethylene) and corresponding properties (such as number average molecular weight), which is not available on DWSIM. I need the PC-SAFT equation of state as the thermodynamic model, which is available on DWSIM.
In addition, I want to rewrite PFR reactor and CSTR reactor with Python script to calculate polymerization kinetics. I don't know if the python script in DWSIM can establish and solve differential equations.
I would appreciate it if you could provide some suggestions.

**Comment by DanWBR** [comment]
@Jackxi1024 please use the discussion section as this is not a bug nor a feature request.
