### ISSUE TITLE
Windows Classic UI (since 24-09-2021)

### ISSUE THREAD

**Issue by anauta00** [DanWBR/dwsim6#206]
Hi,

Since the 24-09-21 UI updates, the Windows application no longer shows the panels and other stuff in the right size.
Here is an example

![dwsim_screen10](https://user-images.githubusercontent.com/42865376/134909077-b330d662-c682-49b7-95f4-cf035b2a2fd5.jpg)

Could you please have a look at this?

Thanks and greetings,
Auke Nauta

**Comment by DanWBR** [comment]
@anauta00 can you tell me your screen resolution and DPI?

**Comment by anauta00** [comment]
Hi Daniel,
I am using a UHD display, the LG 31.5 inch 32UN88A model.
The screen is set to its native 3840x2160 pixels.
The resolution is 140 dpi.
Greetings,
Auke

**Comment by kookma** [comment]
Just to share my experiences with DWSIM 6.6.3
Windows 10, DPI is 141 for 1920x1080 on 15.6"

![img_535_DWSIM](https://user-images.githubusercontent.com/830394/134929295-03dc3a1d-bbf0-4c32-b959-84f5cca8a360.png)


Note that to have corrected DPI setting if you use DWSIM on windows. I use the default setting with no adjustments!

![image](https://user-images.githubusercontent.com/830394/134929562-e7b777c2-d871-4ba9-8280-48736994dd6e.png)

**Comment by DanWBR** [comment]
@anauta00 @kookma when working on v6.6.3 I've accidentally opened some windows when my display was with a High DPI setting, and then Visual Studio always breaks the window layout when the user does that... I've figured it out a few days ago, and already restored the intended layout... this is a known VS bug and has been like this for ages...

**Comment by anauta00** [comment]
Good to hear!
With your latest commit, I still have these issues though...

**Comment by DanWBR** [comment]
@anauta00 working on it, please be patient...🥲

**Comment by anauta00** [comment]
Hi Daniel,
It is looking good now, thanks!
Greetings, Auke
