### ISSUE TITLE
Mix liquid and liquid1 properties different even for single liquid [Bug] 

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#207]
**Describe the bug**
When preparing a VL mixture of gas and liquid (single liquid phase) the properties for thermal conductivity and kinematic viscosity is different for the mixed liquid phase and liquid1

**To Reproduce**
See attached DWSIM file (remove zip from file ending)
[VL_test.dwxmz.zip](https://github.com/DanWBR/dwsim6/files/7239216/VL_test.dwxmz.zip)

**Expected behavior**
When a single liquid is present it is expected that all properties for mixed liquid and liquid1 to be identical

**Screenshots**
![image](https://user-images.githubusercontent.com/58475535/134981386-f0cb420d-4ad0-470a-8f72-a74ed0798535.png)

![image](https://user-images.githubusercontent.com/58475535/134981518-8cb37924-a70a-4aea-ad3e-b22150d68ac7.png)

**Desktop (please complete the
 following information):**
 - OS: Windows,
 - Version v6.4.1

**Comment by DanWBR** [comment]
@andr1976 thanks! are you still running DWSIM v6.4.1?

**Comment by andr1976** [comment]
ha ha, noo that was the line where I did not change the example text. I am running 6.5.4 though (and latest from source via Visual Studio). I have been away from DWSIM a while and have not upgraded my "production" installation yet.

**Comment by andr1976** [comment]
@DanWBR , could this be an issue for other properties like entropy, enthalpy etc.?
