### ISSUE TITLE
Error in some mixture properties [Bug] 

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#208]
For many mixture properties like Cp, Cv (possible also, isothermal compressibility) , it seems the result shown for the mix/combined phases are a molar average like e.g. for enthalpy:

Hmix = x * Hliq + y * Hgas

But for Cp this is not the same as 

Cp_mix = x * Cp_x  + y * Cp_y

Since Cp is defined as

Cp = dH/dT

we get 

Cp = dHmix/dT = d(x * Hliq + y * Hgas) = dx/dT*Hliq + x*dHliq/dT + dy/dT*Hgas + y*dHgas/dT

Thus Cp for mixture will be higher than the molar weigted sum due to phase change. The same applies to Cv.

**Comment by DanWBR** [comment]
@andr1976 where do we have Cp for a Liq+Gas mixture in DWSIM?

**Comment by andr1976** [comment]
On the stream - I am not sure what you need it for though :-) other than actually doing this right in contrast to some MAJOR commercial process simulation packages.
![image](https://user-images.githubusercontent.com/58475535/135844171-9881c24f-4d96-469b-be1b-250860d14b3e.png)

**Comment by DanWBR** [comment]
@andr1976 heat capacity ratio for a mixture doesn't make sense...!!! I'll need to review this

**Comment by andr1976** [comment]
again I am not sure when/if you need this, but you can define it in a meaningfull way also Cv = dU/dT = d(x*Uliq + y * Ugas) / dT by differentation

**Comment by rcdpereira** [comment]
> @andr1976 heat capacity ratio for a mixture doesn't make sense...!!! I'll need to review this

When sizing PSVs, Cp/Cv is used. And if you if you have a mixture (e.g. Natural Gas), this would make sense. Please let me know if this is wrong.

**Comment by DanWBR** [comment]
@rcdpereira Cp/Cv is normally used in gas phase correlations, it doesn't make sense as an average phase property (liq+gas).

**Comment by andr1976** [comment]
I could maybe think of heat exchange calcs as a place where Cp for liquid/gas mixture could be relevant, other than that I am not sure.

**Comment by DanWBR** [comment]
@andr1976 Cp or Cv alone is ok, but a mixture Cp/Cv is weird

**Comment by andr1976** [comment]
@DanWBR agree. Cp/Cv is for gas flow applications mainly. Btw it could be cool if DWSIM would report the ideal gas Cp/Cv ratio as a stream property - this a better approximation of the isentropic exponent than real gas Cp/Cv. This is the most used property when considering control valves, PSVs, orifice flow etc.

**Comment by DanWBR** [comment]
@andr1976 I'll work on it

**Comment by DanWBR** [comment]
<img width="430" alt="Captura de Tela 2021-10-25 às 09 48 24" src="https://user-images.githubusercontent.com/2669419/138698009-520402e3-7add-4b58-8bc4-84e15133c33a.png">

**Comment by andr1976** [comment]
@DanWBR, yes sir! Looks great
