### ISSUE TITLE
[Bug] outlet temperature from splitter

### ISSUE THREAD

**Issue by Fralopez** [DanWBR/dwsim6#209]
A superheated steam stream is divided by means of a splitter into different outlet streams, but the outlet streams' temperature is the saturation temperature, instead of the inlet temperature.
![aaa](https://user-images.githubusercontent.com/45826260/136081477-a533ce6a-9be1-4efb-a62b-314990e6ed34.png)

**Comment by DanWBR** [comment]
@Fralopez could you please attach the simulation file?

**Comment by Fralopez** [comment]
how can I attach the simulation file? it says "we don't support that file type"

**Comment by Fralopez** [comment]
in the meantime I have found that maybe the problem could lie somewhere in the property package. It seems that with Steam Tables V2 I got the wrong temperature, while with Steam Tables it's ok.

**Comment by DanWBR** [comment]
@Fralopez I'll remove Steam Tables v2 from the next version as it has some serious flaws.

**Comment by Fralopez** [comment]
ok thanks Daniel.
