### ISSUE TITLE
Issue Compressor Calculation Type

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#21]
The specification or calculation type for  compressor contains:

* Pressure Increase/Decrease [Remove decrease]
* Outlet pressure
* Power required/generated [Remove generated]
* Energy stream
* Known head
* Performance curve

**Comments**

1. The first and third specifications above need correction
2. When you use Energy stream, it means you should be able to set the energy flow of an Energy Stream, but DWSIM refuses to set the energy flow of Energy Stream (this is the case when compressor was solved using other specification and then you want to use energy stream)! 
2.1. If you already run compressor with outlet pressure or other spec, DWSIM uses the old value for energy stream
2.2 If you set Compressor spec as Energy Stream when you add a new compressor, then setting energy flow, DWSIM issues an error like below: 

COMP-003: A specified or calculated property for this Unit Operation is invalid. Please check it for incorrect specifications or miscalculated values. (name: power, value: -2.96059473233375E-16)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Classic UI
 - DWSIM 6.1 update 4

**Comment by kookma** [comment]
**Known head**
This is not a common specification for compressors while it is used for pumps.

**Comment by DanWBR** [comment]
> **Known head**
> This is not a common specification for compressors while it is used for pumps.

actually this was a user request. 🤷🏻‍♂️

**Comment by kookma** [comment]
> > **Known head**
> > This is not a common specification for compressors while it is used for pumps.
> 
> actually this was a user request. 🤷🏻‍♂️


Okay keep it :-)
This is common for liquids a column of gas has no pressure (see: [Pressure head](https://en.wikipedia.org/wiki/Pressure_head#:~:text=In%20fluid%20mechanics%2C%20pressure%20head,but%20not%20static%20head%20pressure).)

**Comment by DanWBR** [comment]
I know it's weird, I've never used it too. 😄
