### ISSUE TITLE
[Enhancement] PFR Outlet temperature calculator hence (reactor temperature profile)

### ISSUE THREAD

**Issue by chinmoybasak** [DanWBR/dwsim6#210]
**Is your feature request related to a problem? Please describe.**
PFR modules only provide Adiabatic, Isothermal, and User-provided outlet temperature calculation. But this is a basic need of any PFR design for provided kinetics data to calculate reactor temperature profile (not adiabatic or exothermal case)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kookma** [comment]
@chinmoybasak - would you please correct the body of your issue!
It is an instruction how to write the issue and should not be kept!
Also clearly describe what you want and give your possible solution!

**Comment by DanWBR** [comment]
closing this as the text is not understandable and no further info was provided.
