### ISSUE TITLE
[Enhancement] Murphree efficiency for absorber and distillation columns

### ISSUE THREAD

**Issue by JarlPed** [DanWBR/dwsim6#211]
When calculating absorber and distillation columns, it's assumed that the complete vapor-liquid equilibrium is achieved at each tray section, or that the user have knowledge about the efficiency of the respective sections.
Assuming, that one only has engineering data for the columns, i.e. the geometric configuration of weir, downcomers, etc. I imagine, that it may be utilized for a best estimate for the tray efficiency.

It would be nice to have implemented expected tray section efficiency, otherwise known as the Murphree efficiency that can suffice for plant designs where pilot plants can't be constructed.
A checkbox for each tray section editing form would be nice, such that the overall equilibrium calculation is also considering coupling with efficiency. Additionally, columns with engineering data has to be provided, unless one may simplify to an uniform column tray profile.

I think an adequate correlation of the efficiency to the hydraulic profile could be implemented, using defaulted values that can be customized to whichever column design.

**Comment by DanWBR** [comment]
@JarlPed Murphree efficiencies are already implemented (default = 1.0). You can set their values in the stages editing panel.
