### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by pdenis13** [DanWBR/dwsim6#213]
[DWSIM - MAC] - Binary Enveloppe failed

**Describe the bug**

Unable to calculate or Draw the binary enveloppe of a mixture. The Phase enveloppe seems to works Welle

**To Reproduce**
1. Ethanol / Water mixture / set package properties as you want (see attach file)
2. selecte Utilities / binary Envelope
3. setup as you want
4. Clic on build enveloppe
5. No dating / no data but the following message : "Index has to be between upper and lower bound of the array."

**Screenshots**

see Screenshot.pdf

**Desktop (please complete the following information):**
 - Mac OS 
 - 11.6 (Big Sur)

**Additional context**
Add any other context about the problem here
[VLE Eau - Ethanol.dwxmz.zip](https://github.com/DanWBR/dwsim6/files/7358949/VLE.Eau.-.Ethanol.dwxmz.zip)
[Screenshot.pdf](https://github.com/DanWBR/dwsim6/files/7358958/Screenshot.pdf)

**Comment by DanWBR** [comment]
Thank you @pdenis13, fixed this issue and the NaN entropy error in your sample simulation too. v6.7.1 will be working as expected.

**Comment by pdenis13** [comment]
You’re the best ! 
thanks a lot 

Cordialement,


Pascal Denis
Responsable Scolarité Ingénieur
Enseignant Génie des Procédés
Bureau : 119 - Jetée
Tél. : 04 91 05 45 82 <tel:0491054582>
Tél. : 06 24 01 20 86 <tel:0624012086>
Centrale Marseille
Pôle de l'Étoile
Technopôle de Château-Gombert
38, rue Frédéric Joliot-Curie
13451 MARSEILLE cedex 13
https://centrale-marseille.fr <applewebdata://F004A1C1-350C-4A26-A187-E67C26A1D244/www.centrale-marseille.fr>
 <https://www.facebook.com/CentraleMarseille> <https://twitter.com/CentraleMars> <https://www.linkedin.com/school/ecole-centrale-de-marseille/> <https://www.youtube.com/user/CentraleMarseille/featured> <https://www.instagram.com/centralemarseille/>

**Comment by DanWBR** [comment]
<img width="1037" alt="Captura de Tela 2021-10-18 às 11 38 15" src="https://user-images.githubusercontent.com/2669419/137752778-aa711a36-7d42-4bae-8f83-be3b3f2d5679.png">
