### ISSUE TITLE
[Bug] - Mac OS - Objects Alignement  button get crash

### ISSUE THREAD

**Issue by pdenis13** [DanWBR/dwsim6#214]
Hello Daniel

**Describe the bug**

The use of the 5 buttons Align buttons, right, left, center, middle or the equalize vertically / Horizontally will instantly get a crash of DWSIM

**To Reproduce**
1. clic on multiselect 
2. with the mouse select at least 2 objects (material stream for example)
3. clic on Align buttons (or any other listed buttons) you get a crash of DWSIM

you can get the crash even using the buttons without selecting an object, with or without snap to grid activate, or with/without draw grid.

**Desktop (please complete the following information):**
 - Mac OS
 - Big Sur  - 11.6.1

**Comment by DanWBR** [comment]
Fixed in https://github.com/DanWBR/dwsim6/commit/49a97f1c34b768394ad82003b365753e7d58aba5
