### ISSUE TITLE
[Bug] - MacOS - Monterey - Crash 

### ISSUE THREAD

**Issue by pdenis13** [DanWBR/dwsim6#215]
**Describe the bug**

launch of DWSIM is OK, but when try to "open Existing" or "create new", DWSIM crash with the following information 

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Launcher.exec [24861]
Path:                  /Applications/DWSIM.app/Contents/MacOS/Launcher.exec
Identifier:            com.danielmedeiros.dwsim
Version:               6.7.0 (1)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2021-10-27 09:04:50.1057 +0200
OS Version:            macOS 12.0.1 (21A559)
Report Version:        12
Bridge OS Version:     6.0 (19P548)
Anonymous UUID:        95552C7B-6FB3-009D-BC36-8A43B210C73F

Sleep/Wake UUID:       E0369CD3-1236-49DA-A509-BD6AF30B3468

Time Awake Since Boot: 11000 seconds
Time Since Wake:       3306 seconds

System Integrity Protection: enabled

Crashed Thread:        0  tid_103  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [24861]

VM Region Info: 0 is not in any region.  Bytes before following region: 4487692288
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      10b7cc000-10bcb9000    [ 5044K] r-x/rwx SM=COW  ...Launcher.exec

Thread 0 Crashed:: tid_103 Dispatch queue: com.apple.main-thread
0   Launcher.exec                 	       0x10bb11f4d eglib_log_adapter + 13
1   Launcher.exec                 	       0x10bb2c64e monoeg_g_logv_nofree + 190
2   Launcher.exec                 	       0x10bb2c7cf monoeg_assertion_message + 143
3   Launcher.exec                 	       0x10b8ebcd9 mono_jit_thread_attach + 169
4   Launcher.exec                 	       0x10b7fb6c0 xamarin_switch_gchandle + 144
5   Launcher.exec                 	       0x10b7fe027 xamarin_release_trampoline + 103
6   libobjc.A.dylib               	    0x7ff802d2819f AutoreleasePoolPage::releaseUntil(objc_object**) + 167
7   libobjc.A.dylib               	    0x7ff802d25160 objc_autoreleasePoolPop + 161
8   Launcher.exec                 	       0x10b80690b xamarin_main + 1259
9   Launcher.exec                 	       0x10b807774 main + 36
10  dyld                          	       0x10ebfb4fe start + 462

Thread 1:
0   libsystem_pthread.dylib       	    0x7ff802e8900c start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	    0x7ff802e8900c start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	    0x7ff802e8900c start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	    0x7ff802e8900c start_wqthread + 0

Thread 5:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	    0x7ff802e50aba mach_msg_trap + 10
1   libsystem_kernel.dylib        	    0x7ff802e50e2b mach_msg + 59
2   CoreFoundation                	    0x7ff802f54a42 __CFRunLoopServiceMachPort + 319
3   CoreFoundation                	    0x7ff802f5311b __CFRunLoopRun + 1325
4   CoreFoundation                	    0x7ff802f5252d CFRunLoopRunSpecific + 563
5   AppKit                        	    0x7ff805aebcec _NSEventThread + 132
6   libsystem_pthread.dylib       	    0x7ff802e8d514 _pthread_start + 125
7   libsystem_pthread.dylib       	    0x7ff802e8902f thread_start + 15

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000004  rbx: 0x000000010bbcd5b0  rcx: 0x0000000000000000  rdx: 0x00007f7e8f7ac9d0
  rdi: 0x0000000000000000  rsi: 0x0000000000000004  rbp: 0x00007ff7b4733300  rsp: 0x00007ff7b4733300
   r8: 0x0000000000000000   r9: 0x000000010bbcd5d3  r10: 0x00000000000007fb  r11: 0x00007f7d83bdf488
  r12: 0x00007f7e92bb5200  r13: 0xa3a3a3a3a3a3a3a3  r14: 0x0000000000000004  r15: 0x0000000000000000
  rip: 0x000000010bb11f4d  rfl: 0x0000000000010202  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000004 (no mapping for user data read)
Trap Number:     14

Thread 0 instruction stream:
  00 00 00 48 8b 3d f9 17-23 00 48 85 ff 74 40 55  ...H.=..#.H..t@U
  48 89 e5 e8 1b 9c 01 00-48 c7 05 c0 17 23 00 00  H.......H....#..
  00 00 00 48 c7 05 bd 17-23 00 00 00 00 00 48 c7  ...H....#.....H.
  05 ba 17 23 00 00 00 00-00 48 c7 05 bf 17 23 00  ...#.....H....#.
  00 00 00 00 c7 05 bd 17-23 00 00 00 00 00 5d c3  ........#.....].
  0f 1f 00 55 48 89 e5 89-f0 4c 8b 05 a3 17 23 00  ...UH....L....#.
 [4d]8b 08 83 e6 fc 8d 4e-fc 83 f9 1c 77 20 48 8d  M......N....w H.	<==
  35 a1 56 0d 00 4c 8d 15-57 00 00 00 49 63 0c 8a  5.V..L..W...Ic..
  4c 01 d1 ff e1 48 8d 35-75 f2 0f 00 eb 38 83 fe  L....H.5u....8..
  40 74 2c 81 fe 80 00 00-00 75 09 48 8d 35 78 f2  @t,......u.H.5x.
  0f 00 eb 22 48 8d 35 c2-f3 0f 00 eb 19 48 8d 35  ..."H.5......H.5
  56 f2 0f 00 eb 10 48 8d-35 55 f2 0f 00 eb 07 48  V.....H.5U.....H

Binary Images:
       0x10b7cc000 -        0x10bcb8fff com.danielmedeiros.dwsim (6.7.0) <071d8255-1f17-30f7-9e13-4c8d51eb236e> /Applications/DWSIM.app/Contents/MacOS/Launcher.exec
    0x7ff802d1b000 -     0x7ff802d54fff libobjc.A.dylib (*) <7cfcdc89-2bee-3784-b7af-c676f60fe211> /usr/lib/libobjc.A.dylib
       0x10ebf6000 -        0x10ec61fff dyld (*) <1a6ae033-9438-33c0-8077-988fd885250a> /usr/lib/dyld
    0x7ff802e87000 -     0x7ff802e92fff libsystem_pthread.dylib (*) <29a2750e-f31b-3630-8761-242a6bc3e99e> /usr/lib/system/libsystem_pthread.dylib
    0x7ff802e50000 -     0x7ff802e86fff libsystem_kernel.dylib (*) <12bd6f13-c452-35ee-9069-51befef29f1a> /usr/lib/system/libsystem_kernel.dylib
    0x7ff802ed4000 -     0x7ff8033d6fff com.apple.CoreFoundation (6.9) <3002b545-6841-3fc8-91a2-bcfbe5872465> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff80593f000 -     0x7ff8067cbfff com.apple.AppKit (6.9) <dd0028a3-78e3-3a8a-a51b-ddd68123adef> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.3G resident=0K(0%) swapped_out_or_unallocated=1.3G(100%)
Writable regions: Total=796.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=796.2M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               384K        3 
Activity Tracing                   256K        1 
CG backing stores                 2880K        4 
CG image                          17.0M       93 
ColorSync                          244K       29 
CoreAnimation                     24.0M       75 
CoreGraphics                        12K        2 
CoreUI image data                 2144K       19 
Foundation                        1276K        6 
Image IO                          23.6M       74 
Kernel Alloc Once                    8K        1 
MALLOC                           279.9M      106 
MALLOC guard page                   32K        7 
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.0M        6 
Stack                             10.5M        6 
VM_ALLOCATE                       69.6M      407 
__CTF                               759        1 
__DATA                            39.1M      764 
__DATA_CONST                      46.9M      541 
__DATA_DIRTY                      2666K      347 
__FONT_DATA                          4K        1 
__LINKEDIT                       644.8M       10 
__OBJC_RO                         81.5M        1 
__OBJC_RW                         3120K        2 
__TEXT                           674.2M      783 
__UNICODE                          588K        1 
dyld private memory               1024K        1 
mapped file                      170.0M       31 
shared memory                      792K       19 
===========                     =======  ======= 
TOTAL                              2.5G     3342 
TOTAL, minus reserved VM space     2.1G     3342 

-----------
Full Report
-----------

{"app_name":"Launcher.exec","timestamp":"2021-10-27 09:04:50.00 +0200","app_version":"6.7.0","slice_uuid":"071d8255-1f17-30f7-9e13-4c8d51eb236e","build_version":"1","platform":1,"bundleID":"com.danielmedeiros.dwsim","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.0.1 (21A559)","incident_id":"63FC3075-EA6A-46A9-BC23-9BEF033E1C75","name":"Launcher.exec"}
{
  "uptime" : 11000,
  "procLaunch" : "2021-10-27 09:04:39.2629 +0200",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro15,1",
  "procStartAbsTime" : 11721709616979,
  "coalitionID" : 23651,
  "osVersion" : {
    "train" : "macOS 12.0.1",
    "build" : "21A559",
    "releaseType" : "User"
  },
  "captureTime" : "2021-10-27 09:04:50.1057 +0200",
  "incident" : "63FC3075-EA6A-46A9-BC23-9BEF033E1C75",
  "bug_type" : "309",
  "pid" : 24861,
  "procExitAbsTime" : 11732549224165,
  "cpuType" : "X86-64",
  "procName" : "Launcher.exec",
  "procPath" : "\/Applications\/DWSIM.app\/Contents\/MacOS\/Launcher.exec",
  "bundleInfo" : {"CFBundleShortVersionString":"6.7.0","CFBundleVersion":"1","CFBundleIdentifier":"com.danielmedeiros.dwsim"},
  "storeInfo" : {"deviceIdentifierForVendor":"930E007A-7C21-5911-B8AA-EA2EA8B61877","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.danielmedeiros.dwsim",
  "crashReporterKey" : "95552C7B-6FB3-009D-BC36-8A43B210C73F",
  "wakeTime" : 3306,
  "bridgeVersion" : {"build":"19P548","train":"6.0"},
  "sleepWakeUUID" : "E0369CD3-1236-49DA-A509-BD6AF30B3468",
  "sip" : "enabled",
  "vmRegionInfo" : "0 is not in any region.  Bytes before following region: 4487692288\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      10b7cc000-10bcb9000    [ 5044K] r-x\/rwx SM=COW  ...Launcher.exec",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000000","rawCodes":[1,0],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000000"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":24861},
  "vmregioninfo" : "0 is not in any region.  Bytes before following region: 4487692288\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      10b7cc000-10bcb9000    [ 5044K] r-x\/rwx SM=COW  ...Launcher.exec",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"queue":"com.apple.main-thread","instructionState":{"instructionStream":{"bytes":[0,0,0,72,139,61,249,23,35,0,72,133,255,116,64,85,72,137,229,232,27,156,1,0,72,199,5,192,23,35,0,0,0,0,0,72,199,5,189,23,35,0,0,0,0,0,72,199,5,186,23,35,0,0,0,0,0,72,199,5,191,23,35,0,0,0,0,0,199,5,189,23,35,0,0,0,0,0,93,195,15,31,0,85,72,137,229,137,240,76,139,5,163,23,35,0,77,139,8,131,230,252,141,78,252,131,249,28,119,32,72,141,53,161,86,13,0,76,141,21,87,0,0,0,73,99,12,138,76,1,209,255,225,72,141,53,117,242,15,0,235,56,131,254,64,116,44,129,254,128,0,0,0,117,9,72,141,53,120,242,15,0,235,34,72,141,53,194,243,15,0,235,25,72,141,53,86,242,15,0,235,16,72,141,53,85,242,15,0,235,7,72],"offset":96}},"frames":[{"imageOffset":3432269,"symbol":"eglib_log_adapter","symbolLocation":13,"imageIndex":0},{"imageOffset":3540558,"symbol":"monoeg_g_logv_nofree","symbolLocation":190,"imageIndex":0},{"imageOffset":3540943,"symbol":"monoeg_assertion_message","symbolLocation":143,"imageIndex":0},{"imageOffset":1178841,"symbol":"mono_jit_thread_attach","symbolLocation":169,"imageIndex":0},{"imageOffset":194240,"symbol":"xamarin_switch_gchandle","symbolLocation":144,"imageIndex":0},{"imageOffset":204839,"symbol":"xamarin_release_trampoline","symbolLocation":103,"imageIndex":0},{"imageOffset":53663,"symbol":"AutoreleasePoolPage::releaseUntil(objc_object**)","symbolLocation":167,"imageIndex":1},{"imageOffset":41312,"symbol":"objc_autoreleasePoolPop","symbolLocation":161,"imageIndex":1},{"imageOffset":239883,"symbol":"xamarin_main","symbolLocation":1259,"imageIndex":0},{"imageOffset":243572,"symbol":"main","symbolLocation":36,"imageIndex":0},{"imageOffset":21758,"symbol":"start","symbolLocation":462,"imageIndex":2}],"id":234265,"triggered":true,"threadState":{"r13":{"value":11791448172606497699},"rax":{"value":4},"rflags":{"value":66050},"cpu":{"value":0},"r14":{"value":4},"rsi":{"value":4},"r8":{"value":0},"cr2":{"value":0},"rdx":{"value":140181549795792},"r10":{"value":2043},"r9":{"value":4491892179},"r15":{"value":0},"rbx":{"value":4491892144},"trap":{"value":14,"description":"(no mapping for user data read)"},"err":{"value":4},"r11":{"value":140177057903752},"rip":{"value":4491124557,"matchesCrashFrame":1},"rbp":{"value":140701861098240},"rsp":{"value":140701861098240},"r12":{"value":140181604356608},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":0}},"name":"tid_103"},{"id":234280,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]},{"id":234281,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]},{"id":234292,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]},{"id":234297,"frames":[{"imageOffset":8204,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]},{"id":234358,"name":"com.apple.NSEventThread","frames":[{"imageOffset":2746,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":4},{"imageOffset":3627,"symbol":"mach_msg","symbolLocation":59,"imageIndex":4},{"imageOffset":526914,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":319,"imageIndex":5},{"imageOffset":520475,"symbol":"__CFRunLoopRun","symbolLocation":1325,"imageIndex":5},{"imageOffset":517421,"symbol":"CFRunLoopRunSpecific","symbolLocation":563,"imageIndex":5},{"imageOffset":1756396,"symbol":"_NSEventThread","symbolLocation":132,"imageIndex":6},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":3},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":3}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4487692288,
    "CFBundleShortVersionString" : "6.7.0",
    "CFBundleIdentifier" : "com.danielmedeiros.dwsim",
    "size" : 5165056,
    "uuid" : "071d8255-1f17-30f7-9e13-4c8d51eb236e",
    "path" : "\/Applications\/DWSIM.app\/Contents\/MacOS\/Launcher.exec",
    "name" : "Launcher.exec",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "x86_64h",
    "base" : 140703175913472,
    "size" : 237568,
    "uuid" : "7cfcdc89-2bee-3784-b7af-c676f60fe211",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4542390272,
    "size" : 442368,
    "uuid" : "1a6ae033-9438-33c0-8077-988fd885250a",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703177404416,
    "size" : 49152,
    "uuid" : "29a2750e-f31b-3630-8761-242a6bc3e99e",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703177179136,
    "size" : 225280,
    "uuid" : "12bd6f13-c452-35ee-9069-51befef29f1a",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64h",
    "base" : 140703177719808,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5255168,
    "uuid" : "3002b545-6841-3fc8-91a2-bcfbe5872465",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1855.105"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703222198272,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15257600,
    "uuid" : "dd0028a3-78e3-3a8a-a51b-ddd68123adef",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113"
  }
],
  "sharedCache" : {
  "base" : 140703174176768,
  "size" : 15213641728,
  "uuid" : "3d05845f-3f65-358f-9ebf-2236e772ac01"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.3G resident=0K(0%) swapped_out_or_unallocated=1.3G(100%)\nWritable regions: Total=796.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=796.2M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               384K        3 \nActivity Tracing                   256K        1 \nCG backing stores                 2880K        4 \nCG image                          17.0M       93 \nColorSync                          244K       29 \nCoreAnimation                     24.0M       75 \nCoreGraphics                        12K        2 \nCoreUI image data                 2144K       19 \nFoundation                        1276K        6 \nImage IO                          23.6M       74 \nKernel Alloc Once                    8K        1 \nMALLOC                           279.9M      106 \nMALLOC guard page                   32K        7 \nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.0M        6 \nStack                             10.5M        6 \nVM_ALLOCATE                       69.6M      407 \n__CTF                               759        1 \n__DATA                            39.1M      764 \n__DATA_CONST                      46.9M      541 \n__DATA_DIRTY                      2666K      347 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       644.8M       10 \n__OBJC_RO                         81.5M        1 \n__OBJC_RW                         3120K        2 \n__TEXT                           674.2M      783 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nmapped file                      170.0M       31 \nshared memory                      792K       19 \n===========                     =======  ======= \nTOTAL                              2.5G     3342 \nTOTAL, minus reserved VM space     2.1G     3342 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "name" : "tid_103",
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "61704e71b6f6b8421579caf8"
      },
      "deploymentId" : 240000293
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000145
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000064
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "6169fcad436117010456880e"
      },
      "deploymentId" : 240000238
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro15,1, BootROM 1715.40.15.0.0 (iBridge: 19.16.10548.0.0,0), 6 processors, 6-Core Intel Core i9, 2,9 GHz, 16 GB, SMC 
Graphics: Intel UHD Graphics 630, Intel UHD Graphics 630, Built-In
Display: Color LCD, 2880 x 1800 Retina, Main, MirrorOff, Online
Graphics: Radeon Pro 555X, Radeon Pro 555X, PCIe, 4 GB
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2400 MHz, Micron, 8ATF1G64HZ-2G6E1
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 2400 MHz, Micron, 8ATF1G64HZ-2G6E1
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x7BF), wl0: Jul 12 2021 19:26:30 version 9.30.464.0.32.5.76 FWID 01-45ccefcd
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: iPhone
USB Device: T2Bus
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.5
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.5

**Desktop (please complete the following information):**
 - Mac OS
 - Monterey - 12.0.1

**Comment by DanWBR** [comment]
You seem to have 'Hardware' selected as PFD Renderer in Global Settings.

**Comment by DanWBR** [comment]
@pdenis13 can you attach the 'errors.log' file from your Documents/DWSIM Application Data folder? thanks

**Comment by pdenis13** [comment]
Hello Daniel, 

NO it's an iMac running intel i9. 

You will find the error.log and last error.txt  below

[errors.log](https://github.com/DanWBR/dwsim6/files/7432484/errors.log)
[lasterror.txt](https://github.com/DanWBR/dwsim6/files/7432485/lasterror.txt)

**Comment by DanWBR** [comment]
`System.EntryPointNotFoundException: CGImageSourceCopyPropertiesAtIndex
  at (wrapper managed-to-native) System.Drawing.CGImageSourceExtensions.CGImageSourceCopyPropertiesAtIndex(intptr,System.nint,intptr)
  at System.Drawing.CGImageSourceExtensions.GetPropertiesSafe (ImageIO.CGImageSource imageSource, System.Int32 imageIndex) [0x0000c] in <72557f6049b84a4da6e034698e333b25>:0 
  at System.Drawing.Bitmap.Save (ImageIO.CGImageDestination dest) [0x00028] in <72557f6049b84a4da6e034698e333b25>:0 
  at System.Drawing.Bitmap.Save (System.IO.Stream stream, System.Drawing.Imaging.ImageFormat format) [0x00029] in <72557f6049b84a4da6e034698e333b25>:0 
  at (wrapper remoting-invoke-with-check) System.Drawing.Bitmap.Save(System.IO.Stream,System.Drawing.Imaging.ImageFormat)
  at System.Drawing.Image.Save (System.IO.Stream stream, System.Drawing.Imaging.ImageFormat format) [0x00014] in <72557f6049b84a4da6e034698e333b25>:0 
  at (wrapper remoting-invoke-with-check) System.Drawing.Image.Save(System.IO.Stream,System.Drawing.Imaging.ImageFormat)
  at DWSIM.UI.Shared.Common.ImageToByte (System.Drawing.Bitmap img) [0x0000d] in <4f2b0d0aff0f469ab1d68f17715ccfc7>:0 
  at DWSIM.UI.Forms.Flowsheet.InitializeComponent () [0x029ce] in <c452da6598e04ca9b33736a0c2d8f869>:0 `

This is an error in a library used by DWSIM due to a missing method in a system library - don't know if this will persist in the release version of Monterey. We'll have to wait and see what happens.

**Comment by DanWBR** [comment]
Updated the dmg container with a version that works on macOS Monterey: https://sourceforge.net/projects/dwsim/files/DWSIM/DWSIM%206.7/6.7.1/DWSIM%206.7.1.1.dmg/download

**Comment by pdenis13** [comment]
Seems to be Good Daniel !
