### ISSUE TITLE
 Problem Importing OPCUA database file in DWSIM-Classic in a UBUNTU Linux machine

### ISSUE THREAD

**Issue by jmacias552** [DanWBR/dwsim6#217]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
Importing a file with OPCUA tags saved previously does not show up in the OPC Plugin interface. However, it seems that the definitions are already there because if we save the database the file that's written is exactly the same. It seems a problem for visualizing the tags only in dwsim classic Linux machine.

**To Reproduce**
1. Open the simulation (I can provide the example)
2. Open the Plugin OPCUA
3. Import the database OPC file (I can provide one)
4. The tags definitions are not shown
5. Save the list in another file and compare, they are identical, so actually it reads, but does not show.

**Expected behavior**
The OPC data definitions from the file should be shown

**Screenshots**
screenshots and simulation files

[simulation_and_OPC_definition_file.zip]
![Capturapluginscreem](https://user-images.githubusercontent.com/28150546/139528638-20f2c115-b7b6-4721-8ebc-d307434ecb6c.PNG)
(https://github.com/DanWBR/dwsim6/files/7446235/simulation_and_OPC_definition_file.zip)

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Version [v20.04]

**Additional context**
Thanks for your help, Daniel

**Comment by DanWBR** [comment]
@jmacias552 I didn't even know that it worked on Linux. It is definitely an unsupported scenario...

**Comment by jmacias552** [comment]
Ok, Daniel. I understand. In any case, I will try to make it working and If so, I will be back to you.
Regards,
Jose

**Comment by jmacias552** [comment]
Hi, I think I know where the problem is:

When opening the OPCUA plugin, there is a message saying that the OPC certificate can not be found and since then, nothing else happened in trying to connect. Do you know how manually can I register the OPC certificate?.
Just to show you I attached the screen copy of the messages. Thanks Daniel!!!

![Captura](https://user-images.githubusercontent.com/28150546/140030463-90c4f915-ae73-427d-a000-bb053cf527d7.png)

![Captura1](https://user-images.githubusercontent.com/28150546/140030489-969a368b-3f38-40fa-94cc-b068ab9226f4.PNG)

![Captura2](https://user-images.githubusercontent.com/28150546/140030509-154a47c4-f116-4ebc-9676-1fc222d7ebbc.PNG)
