### ISSUE TITLE
Saturator Failure

### ISSUE THREAD

**Issue by Jamesincolorado** [DanWBR/dwsim6#219]
[Saturator fail.zip](https://github.com/DanWBR/dwsim6/files/7454686/Saturator.fail.zip)

The plug-in saturator fails in the latest version. 

Thanks, 

James

**Comment by DanWBR** [comment]
@Jamesincolorado what plugin? Do you mean the natural gas saturator sample?

**Comment by Jamesincolorado** [comment]
Yes, the solver fails at the saturator. 

Thanks.
