### ISSUE TITLE
[error] Error saving file

### ISSUE THREAD

**Issue by RobertoSilva11** [DanWBR/dwsim6#220]
![image](https://user-images.githubusercontent.com/93762979/140481910-459ee3bb-6c10-421c-8972-716244ff97f1.png)

Bom dia!
instalei o a versão 6.7 em 2 computadores que utilizam a plataforma do windows 10 e o problema persiste. Não consigo salvar o projeto.

Peço a gentileza de me orientar quanto a solução

Obrigado!

**Comment by DanWBR** [comment]
@RobertoSilva11 dá uma olhada aqui: https://sourceforge.net/p/dwsim/discussion/844529/thread/ae41278ca0/
