### ISSUE TITLE
[Bug] outlet temperature vs adiabatic efficiency in compressor UnitOp

### ISSUE THREAD

**Issue by Fralopez** [DanWBR/dwsim6#221]
I was simulating a compressor for a methanol synthesis application and I have noticed that the outlet temperature has a strange behaviour when changing the adiabatic efficiency. I have also set a sensitivity study (image attached).

The expected behaviour was outlet temperature decreasing when adiabatic efficiency is increasing.

1. Change adiabatic efficiency in the range 70 - 85 %
2. Look at the outlet stream temperature

[simul.zip](https://github.com/DanWBR/dwsim6/files/7507435/simul.zip)
.

**Comment by DanWBR** [comment]
@Fralopez go to the property package settings and disable Fast Mode for PH/PS Flash:

<img width="783" alt="Captura de Tela 2021-11-10 às 08 54 33" src="https://user-images.githubusercontent.com/2669419/141108632-0b03d094-69a4-4284-a4a6-9787061ce08c.png">
<img width="1039" alt="Captura de Tela 2021-11-10 às 08 54 48" src="https://user-images.githubusercontent.com/2669419/141108646-6168a936-4ae4-4908-8142-71008ccb35de.png">

**Comment by Fralopez** [comment]
Ok thanks. Are there any general rules to set these options?

**Comment by DanWBR** [comment]
the behavior you've experienced is not common, maybe it is due to hydrogen. It should have thrown an error.
