### ISSUE TITLE
[Bug] Crossplatform UI crash on object edit

### ISSUE THREAD

**Issue by einhander** [DanWBR/dwsim6#222]
**Describe the bug**
I moved to next version of debian  system and  got very strange behavior of all versions of dwsim crossplatform UI.
If I'll try to edit any object of flowsheet diagram, dwsim crash with no stack trace.

The terminal output is:
````
$mono DWSIM.UI.Desktop.exe
Latest Version: 6.7.1
Current Version: 6.7.1
Latest Version: 6.7.1
Editor Created 94727156790720
Managed Editor Created ScintillaObject
OpenTK running on X11
````

**To Reproduce**
1. Open flowsheet  
2. Click on any object 

**Expected behavior**
Open parameters in left panel

**Desktop (please complete the following information):**
 - OS: Linux Debian 12 64 bit
 - Version: any from 5.7 to 6.7.1

**Additional context**

**Comment by DanWBR** [comment]
check if you have an error file in your Documents/DWSIM Application Data folder.

**Comment by einhander** [comment]
Nope there no log or error file:
````
~/DWSIM Application Data $ ls -al
итого 92
drwxr-xr-x   4 einhander einhander  4096 мая 20 11:41 .
drwxr-xr-x 209 einhander einhander 36864 ноя 17 17:06 ..
drwxr-xr-x   2 einhander einhander  4096 мая 24 14:49 Backup
-rw-r--r--   1 einhander einhander 26835 апр 26  2021 Combustion.dwxmz
-rw-r--r--   1 einhander einhander  1340 ноя 17 16:59 dwsim.ini
-rw-r--r--   1 einhander einhander  5496 окт 27 18:53 dwsim_newui.ini
drwxr-xr-x   2 einhander einhander  4096 апр 26  2021 FOSSEE
````
````
~/Documents/Dwsim $ ls -al
итого 100
drwxr-xr-x  2 einhander einhander  4096 ноя 17 19:00 .
drwxr-xr-x 30 einhander einhander 20480 ноя 17 19:00 ..
-rw-r--r--  1 einhander einhander 33494 мая 24 20:11 combust.bk0
-rw-r--r--  1 einhander einhander 38635 мая 24 20:35 combust.hsc
````

**Comment by DanWBR** [comment]
try running it with

`MONO_LOG_LEVEL=debug dwsim`

**Comment by einhander** [comment]
> MONO_LOG_LEVEL=debug dwsim

[dwsim.log](https://github.com/DanWBR/dwsim6/files/7556184/dwsim.log)

**Comment by einhander** [comment]
I changed system mono to mono-project.com version but without success. Dwsim v7.0.0 the same as other.
The same problem if i try to open Global settings menu.
 I attached strace file, I hope this helps. 
If I can help you to deal with this bug, please say me that to do.
[trace.txt](https://github.com/DanWBR/dwsim/files/7595795/trace.txt)

**Comment by DanWBR** [comment]
@einhander it seems that Debian 12 is still in testing phase.. maybe some packages are missing from the distro?

**Comment by DanWBR** [comment]
https://www.debian.org/releases/testing/

**Comment by einhander** [comment]
> maybe some packages are missing from the distro?

But why there no error in terminal? If some packages are absent there should be errors like #147, debug and strace output should indicate that type of error.

**Comment by DanWBR** [comment]
@einhander I don't know. There was nothing on the terminal and you didn't have an errors.log file in the app data folder, which makes this very strange indeed.

**Comment by einhander** [comment]
@DanWBR I used gdb and found these segfaults:

```
Thread 1 "mono" received signal SIGSEGV, Segmentation fault.
0x00000000402b788a in ?? ()
(gdb) p (char *) mono_pmip(0x00000000402b788a)
$3 = 0x55c311b547d0 " Gtk.SpinButton:OutputSignalCallback (intptr,intptr) [{0x55c311a532f8} + 0x26a]  (0x402b7620 0x402b7944) [0x55c310073430 - DWSIM.UI.Desktop.exe]"
(gdb) c
Continuing.

Thread 1 "mono" received signal SIGSEGV, Segmentation fault.
0x00000000402ba8ca in ?? ()
(gdb) p (char *) mono_pmip(0x00000000402ba8ca)
$4 = 0x55c311b54730 " DWSIM.UI.Desktop.Editors.UnhandledExceptionView:Init () [{0x55c3117a2450} + 0x22a]  (0x402ba6a0 0x402bd700) [0x55c310073430 - DWSIM.UI.Desktop.exe]"
(gdb) c
Continuing.
```
Can it be related to https://github.com/picoe/Eto/issues/1914?

**Comment by einhander** [comment]
I tested v7.0.1 on debian 11, dwsim runs ok. I'll try to update only glib2 library to find out is it root of this bug.

**Comment by einhander** [comment]
@DanWBR Here some results of my little investigation:
I created chroot for debian 11 and install dwsim with system mono. It's run as it should.
After upgrade libc6, libc-bin, libglib2.0 to debian 12 versions, I've caught this error.
So there definitely gtk-sharp fault, as I pointed in my previous comment. I don't know if it's possible to backport patch from gtk-sharp 3 to version 2, that used in dwsim. 

Right now we have a problem with all new linux distros.
I see several paths to solve that problem. 
* use new eto version with new gtk.
* use appimage with all old libraries
* switch to a new crossplatform  framework like electron (most radical way, but more popular in these days)

**Comment by DanWBR** [comment]
@einhander using the gtk3 backend would be the easiest path. I even tried something months ago but had several problems with some controls. I'll have to make it work eventually, gtk2 is not supported anymore on new distros.

**Comment by DanWBR** [comment]
@einhander did you try the wine version? let me know if it works. It requires wine 3 and that's all.

**Comment by einhander** [comment]
@DanWBR I've tried wine version with 3.0 and 5.18 generaly it works. But there a lot of non critical errors appeared due to wine nature in tiling WMs. 
![123](https://user-images.githubusercontent.com/5439042/143690739-ef985fe8-9aa4-423d-8afa-5ad8e97b4929.png)
Or anoter one then I click on 'new chemical process model':
```
System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.Win32.NativeMethods.SetWindowThemeAttribute(IntPtr hWnd, WindowThemeAttributeType wtype, WTA_OPTIONS& attributes, Int32 size)
   at System.Windows.Forms.VisualStyles.VisualStyleRendererExtension.SetWindowThemeAttribute(IWin32Window window, WindowThemeNonClientAttributes attr, Boolean enable)
   at AeroWizard.WizardControl.ConfigureWindowFrame()
   at AeroWizard.WizardControl.parentForm_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

I did not test it quite well but native classic UI works somehow better than wine version.

**Comment by DanWBR** [comment]
@einhander that's weird, it works quite nicely here in my Ubuntu 16.04 VM:

<img width="1536" alt="Captura de Tela 2021-11-27 às 14 39 11" src="https://user-images.githubusercontent.com/2669419/143691329-8e255a93-b87b-4dd3-bebf-dca6f920e656.png">
<img width="1532" alt="Captura de Tela 2021-11-27 às 14 40 03" src="https://user-images.githubusercontent.com/2669419/143691333-feb928fc-ba93-4f1c-8d13-7b089dcce663.png">

**Comment by einhander** [comment]
Ubuntu 16.04 use unity as DE, I use tiling wm - awesome wm. Wine has problem with handling of sub windows and in tiling wm it can be shown. Because of that I prefer not to use wine. 
P.S. most of window placing problems can be bypassed by resizing to full screen.
Right now I can use classic UI and chroot environment with debian 11 to run crossplatform ui.
I'm trying to create appimage instead of chroot, but without success.

**Comment by DanWBR** [comment]
Closing this one, let's continue on #259
