### ISSUE TITLE
Negative Density /flow [Bug] 

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#225]
Changing from 6.5.4 to 6.7.1 (on WIndows 10) the following wrong result is observed after a pump (export) 

![image](https://user-images.githubusercontent.com/58475535/142779211-a182b0ad-cbe9-4681-93e5-bdec2d5d058f.png)

Expected result is positive density and vol flow. Lowering pump discharge pressure to e.g. 20 instead of 61 appears to help. 

See attached similation saved in 6.5.4. It is material stream MSTR-22 after pump 21-PA-01. Problem occurs after solving flowsheet in v 6.7.1
[optimisation.zip](https://github.com/DanWBR/dwsim6/files/7577136/optimisation.zip)

**Comment by DanWBR** [comment]
@andr1976 my Monday is already full, thanks for that 😂

**Comment by andr1976** [comment]
@DanWBR I am just warming up, better reserve tuesday as well :smiley:, Nah, don't worry it is bedtime soon here in Denmark
