### ISSUE TITLE
[Bug] Bug in Conversion reactor

### ISSUE THREAD

**Issue by Greg66** [DanWBR/dwsim6#229]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
Conversion reactor is calculating unreasonable results. Mole balance is not correct.

**To Reproduce**
See attached simulation.

**Expected behavior**
Hydrogen output is expected to be zero. Instead it is increasing.
Hydrogenation is expected to be exothermic. Reactor is calculating as endothermic.
When increasing temperature and pressure to high values as required for hydrations it is calculating as expected.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windwos
 - Version 6.7.1
[Test Hydrierung Nitril.zip](https://github.com/DanWBR/dwsim/files/7582966/Test.Hydrierung.Nitril.zip)

**Comment by DanWBR** [comment]
@Greg66 the inlet stream is mixed (V+L), is that on purpose?

**Comment by Greg66** [comment]
@DanWBR 
Yes
I have to mix educts as reactor has only a single Input.

**Comment by DanWBR** [comment]
@Greg66 can you please check if the issue was resolved?
