### ISSUE TITLE
[IDEA] Auto Numbering 

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#23]
It seems auto numbering in DWSIM is started from zero and increased by +1 when a new element is added. It is recommended to use separate numbering for different elements as below

- Material stream start from 001
- Energy stream start from 001
- Each unit operation separately start from 001 e.g
  - pumps start from 001 like PUMP-001
  - compressor start from 001 like COMP-001
  - separator start from 001 SEP-001
  - etc.

In preparing process documents like PFD and heat and material balance tables you should have _sequential number_ for material stream, pumps, valves, etc ... and it is confusing when in H&M Table your stream number are missing.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Classic UI
 - DWSIM 6.1 Update 4

**Comment by DanWBR** [comment]
It worked like that in the past and you're right about the numbering in documents... Due to some code changes I wasn't able to get it back to the way you're suggesting but now I think I can do it.

**Comment by kookma** [comment]
Daniel, that would be great if you can back it to auto number for each equipment/stream.
You should absolutely keep an eye open to engineering companies where DWSIM is used for process design.
