### ISSUE TITLE
Splitter [Bug] 

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#233]
**Describe the bug**
For a splitter using ",mass flow spec" and setting one of of two outlet streams (to 3000 kg/h) the flowheet solves and converges, but the converged solution is not equal the the mass flow spec specified  (6128.1 )

Further the mass balance in/out of the splitter is off: 

Inlet 121871 kg/h, MSTR-44
Outlet 115843 kg/h MSTR-46 and 6128.1 kg/h MSTR-56
121871 - 115843 = 6028 kg/h, i.e. off by 100 kg/h, this should be spot on with no deviation beyond machine precision/or rounding errors

**Expected behavior**
Either an error message that specs are invalid (if it shouldnt be possible just to specify n-1 out of n outlets from a stream splitter) - or that the program actually accepts the provided input and converges to the specified value. 

I would expect that obne could specify n-1 out of n streams and then stream nr. n would be calculated besed on a mass balance between inlet and n-1 outlets.

**Screenshots**
![image](https://user-images.githubusercontent.com/58475535/142933761-79c9db2c-75f2-4336-893f-ef28ba0d3245.png)

![image](https://user-images.githubusercontent.com/58475535/142933659-7e2dc8b6-1065-417d-9a4a-0714a494b8e0.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows,]
 - Version [e.g. v6.7.1]

**Additional context**

**Comment by DanWBR** [comment]
@andr1976 if you have only two outlet streams, then you can specify one the first one, the other spec will be ignored (at least it should be). DWSIM will read both specs if you have three outlet streams. the third one is calculated by the mass balance.

**Comment by andr1976** [comment]
It just seems that the specs are not met

tir. 23. nov. 2021 kl. 17.34 skrev Daniel Wagner ***@***.***>:

**Comment by DanWBR** [comment]
@andr1976 I've tested it here with the current code and the mass balance is ok... did you run it in 6.7.1?

**Comment by andr1976** [comment]
Yes, the fun thing is the spec is 3000 for the afjuster but more than 6000
in the actually stream

tir. 23. nov. 2021 kl. 18.20 skrev Daniel Wagner ***@***.***>:

**Comment by DanWBR** [comment]
@andr1976 the second spec will be ignored in your case, you only have 2 outlet streams and you've already spec'ed the first one!

**Comment by andr1976** [comment]
Yes but I speced the stream with low flow at 3000 and the other was left
blank, but the low flow stream then ended at more than 6000, and mass
balance was a little off

tir. 23. nov. 2021 kl. 18.24 skrev Daniel Wagner ***@***.***>:

**Comment by andr1976** [comment]
I have investigated a little more, and things work as expected only and only if the specification is made for the first outlet, and not the second outlet. So, for now until a more general fix is made,  setting blank specification for the first outlet should ideally raise an error (for three outlets I am not entirely sure, I assume once should specify at least 1 and 2 outlet, and leave outlet three blank - then other combinations should raise an error).

**Comment by DanWBR** [comment]
@andr1976 if you have two outlets, DWSIM will calculate the mass balance based on specification 1 only, it will ignore the second specification whatever value it has...

https://github.com/DanWBR/dwsim/blob/b6653d11eace4830a657e7796db71e09d4c007b6/DWSIM.UnitOperations/UnitOperations/Splitter.vb#L321-L344

**Comment by andr1976** [comment]
@DanWBR, maybe the box should be greyed out then for spec2, one could get the impression it is actually used (though it is not)

**Comment by DanWBR** [comment]
@andr1976 yes, I agree
