### ISSUE TITLE
Adjuster error between target and manipulated value[Bug] 

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#236]
**Describe the bug**
The error reported different places are orders of magnitude different 
The adjuster does not stop at specified tolerance

**Screenshots**
![image](https://user-images.githubusercontent.com/58475535/142940342-c51a6dcf-ff05-420b-933f-06b5bd201be2.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, 
 - Version [e.g. v6.4.1]

**Comment by DanWBR** [comment]
@andr1976 can you share your file? you have my email

**Comment by andr1976** [comment]
@DanWBR  you got mail :-)
