### ISSUE TITLE
Pump head[Enhancement] 

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#237]
It would be nice to have the head estimated and reported for pump unit op. This is often required for data sheet input

**Comment by FrankRBrownIII** [comment]
While you are fixing the Pump Calculations, look at the flowsheet object rotation and inversion properties.  I've had a he.. of a time (er difficult time) getting the streams reconnected to the pump on the flowsheet when I reverse directions, such as called for on a recycle.

**Comment by DanWBR** [comment]
> While you are fixing the Pump Calculations, look at the flowsheet object rotation and inversion properties. I've had a he.. of a time (er difficult time) getting the streams reconnected to the pump on the flowsheet when I reverse directions, such as called for on a recycle.

@FrankRBrownIII could you please elaborate on that with some screenshots?

**Comment by FrankRBrownIII** [comment]
Forget it (the comment) I just tried it and it works perfectly.  I used the Invert Horizontally, not the rotate (180) which works great on streams.
This seems to be another case of my leaping before looking.
