### ISSUE TITLE
Implement [UserDefined Table] of HeatTransferCoefficient for Thermal Profile for Pipe Segment[Enhancement]

### ISSUE THREAD

**Issue by AlexanderSemenyak** [DanWBR/dwsim6#238]
Please, implement [UserDefined Table] of HeatTransferCoefficient for Thermal Profile for Pipe Segment
(e.g., for permafrost underground interval, or for gas reservoir interval owerheated)

![UserDefinedTableForHeatTransferCoefficient](https://user-images.githubusercontent.com/42087193/143429932-de96d0f4-3506-4454-94b2-71a532d39c8b.png)

**Comment by DanWBR** [comment]
@AlexanderSemenyak in this case we would interpolate the values or use the value from the previous row until the next one?

**Comment by AlexanderSemenyak** [comment]
> @AlexanderSemenyak in this case we would interpolate the values or use the value from the previous row until the next one?

Interpolate, but for last point (if [length pipesegment] > [max length on table]) - repeat last value on table

**Comment by AlexanderSemenyak** [comment]
Thank's :)
