### ISSUE TITLE
DWSIM requiers old .Net framework

### ISSUE THREAD

**Issue by VictorNine** [DanWBR/dwsim6#239]
**Describe the bug**
Building DWsim requires .NET Framework 4.5. This is no longer available for download from Microsoft. Updating to 4.8 causes errors in many of the packages.

**To Reproduce**
Build without 4.5

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by DanWBR** [comment]
Fixed in https://github.com/DanWBR/dwsim/commit/e2bf0b98a459e4b3b836c02331153ba427447db9
