### ISSUE TITLE
Issue Pump

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#24]
* Pump can accept a gas stream as inlet and DWSIM does not complain!! This is not real behavior. In the user manual it explains you can set a parameter to ignore vapor in feed but in DWSIM 6.1 there is not such feature.

* What is the difference between power required and energy stream? These are confusing while this is not an issue. I think this needs to be discussed with Daniel in more detail.

Note that gas are compressible and the calculation method addressed in user manual cannot be used for gas stream. It seems the calculation is for constant density fluid, so in my opinion DWSIM should refuse accepting gas stream as pump inlet, but it can tolerate occurring vapor in small amount  and issue warning to warn user!

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Classic UI
 - DWSIM 6.1 Update 4

**Comment by DanWBR** [comment]
The 'Power Required' mode lets you to define the power value from the pump object, while "Energy Stream' is useful when the power comes from elsewhere through the energy stream. In the first case the power value is written to the energy stream while in the second one the value is read from the stream.

**Comment by kookma** [comment]
Thank you for explanation! You mean this way for example you can power a pump by a turbine! and DWSIM directly read the energy flow from turbine I will compare with other simulators and let know! Still I think these two can be combined!
