### ISSUE TITLE
[Enhancement] Support for Python 10

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#246]
Python 10 is now stable and the recommended version to install by python.org!
Yet, DWSIM has great support for Python specially in the recent releases!

I would suggest t add support for Python 3.10

**Comment by DanWBR** [comment]
@kookma you mean Python 3.10?

**Comment by kookma** [comment]
Hi Daniel.
Yes I mean Python 3.10 and million thanks for the update!
