### ISSUE TITLE
[Bug] Error in density/compressibility calculation (EOS) 

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#250]
**Describe the bug**
Density for 2. liquid phase wrong (> 6000 kg/m3), compressibility a factor of 10 too low,  and phase erronously mapped to 2. liquid, even being hydrocarbin rich. Water phase mapped to 1. liquid

**To Reproduce**
Rum attached simulation file 

**Expected behavior**
2. liquid phase density arond 809 kg/m3 and 1. liquid phase density around 625 kg/m3 expected

**Screenshots**
![image](https://user-images.githubusercontent.com/58475535/144872341-9e9dd813-7b99-4a01-b73b-8116040c8988.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, 
 - Version [e.g. v7.0.1]
[flashtest.zip](https://github.com/DanWBR/dwsim/files/7661711/flashtest.zip)

**Comment by andr1976** [comment]
The problem in DWSIM.Math/CubicRoots.vb, 

```
Shared Function Poly_Roots(ByVal Coeff As Double()) As Double(,)

            Return CalcRoots2(Coeff(3), Coeff(2), Coeff(1), Coeff(0))

        End Function
```` 

Switching to the older CalcRoots (numerical) fixes the problem, I think the problem is the order of roots CalcRoots2, and how it is shuffled around, because the right root is in  there :-)

**Comment by andr1976** [comment]
Hi Daniel, you're quick :-) However, the Z root for the compressible liquid phase seems to be off, enough to shift density by 50 kg/m3, let me check

**Comment by DanWBR** [comment]
github closed it automatically :)

CalcRoots() is there since forever, maybe it is the volume shift?

**Comment by andr1976** [comment]
I am using EOS density to avoid any disturbances from other things on top of the eos. Compared to my own Z = 0.46465404 compared to 0.52 something in DWSIM with CalcRoots (and CalcRoots2 third real root, it is there, just wrong root returned), so not related to one or the other. Hmmm, I think I have been carefull to use identical BIP's, so this is a little puzzling - I am not 100 % sure, but I think Z liquid1 in DWSIM is a little off, but again I cannot prove it entirely.

**Comment by andr1976** [comment]
Ok, I have checked now against two other tools Unisim and Caleb Bells thermo DWSIM compressibility and density (EOS) is spot on - I am sooooo sorry , I must messed something up in my calc / definition.

**Comment by andr1976** [comment]
@DanWBR good thing though we spotted a perculiar effect on compressibility  in our Michelsen flash algorithm
