### ISSUE TITLE
New files from 7.0.1 does not open in older DWSIm versions [Bug] 

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#253]
Simulation file saved in v7.0.1 cannot be opened in older verios of DWSIm 6.X
**Describe the bug**
![image](https://user-images.githubusercontent.com/58475535/145097095-e0e086df-e122-459f-a6dd-5754ee498008.png)

**Expected behavior**
File opens without problems

**Comment by DanWBR** [comment]
this is the price of evolution. 

just kidding, I'll see what can be done. older versions think that there is only a single file in the zip package, but now there is a database (.db) file on it too.

**Comment by andr1976** [comment]
Well a feature then :-) I guess a clean Cut could be made with respect to pre-7.0, but at least going forward in the plus-7.1 backwards compatibility could be nice up until say v7.0. Coming from Aspen HYSYS the version hell being unable to open files is making me crazy

**Comment by DanWBR** [comment]
I believe that it is possible. the db name is random and the XML file name starts with a "t". if the db name starts with u, v, x or z, it can go to the end of the queue, and then older versions will find the XML file first.

**Comment by DanWBR** [comment]
@andr1976 for backwards compatibility the user can save the file to the dwxml format.
