### ISSUE TITLE
Some included examples does not run[Bug] 

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#260]
The following examples does not run/have errors:

- Petroleum distillation with reboiler. Runs first time, second time fails
![image](https://user-images.githubusercontent.com/58475535/146648508-a5a09a6d-533b-4fa0-8279-4e6b05f84cfc.png)

- Extractive Distillation. Fails when run 2 times 
![image](https://user-images.githubusercontent.com/58475535/146648734-4d3e5590-8159-46b2-a8b9-e2dea1d67498.png)

-  Biodiesel combustion: Problem with Cantera, I assume the user needs to have a working installation of Cantera ?

**Comment by DanWBR** [comment]
@andr1976 about biodiesel combustion: yes, it does
