### ISSUE TITLE
No water from 3-phase flash and component sort by tag fails.[Bug] 

### ISSUE THREAD

**Issue by Jamesincolorado** [DanWBR/dwsim6#261]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
The attached 3-phase flash does not produce a heavy liquid stream. I attached the file along with an identical Virtual Materials Group simulation report.

**To Reproduce**

Simply unzip the file and open it. 

**Expected behavior**
Nearly all water should exit the heavy liquid stream

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS]
 - Version [e.g. v6.4.1]
 - Windows 10

**Additional context**

**Comment by andr1976** [comment]
Hi James, which version are you running? Please attach file as well.

**Comment by Jamesincolorado** [comment]
> 

How was the 3-phase flash resolved and when will the fix be available?

**Comment by andr1976** [comment]
You didnt attach any supporting files

**Comment by Jamesincolorado** [comment]
We have two bugs. 
    
    1. Regarding the 2-phase separator, the specification was for
      1.00 vapor. Consequently, the bottom stream, although zero, should
      indicate the bubble point. 
    
    2. The three-phase flash bug is a major problem. Most certainly,
      there should be a heavy phase flow as indicated by the VMG
      simulation and field operations. DWSIM shows no heavy phase.
      Either the thermo is wrong or the 3-phase flash algorithm is
      flawed. Did you get the attachments today?
    
    
      
      
      


      
        James
            Meyer, MBA/PE
        Aspen
            Engineering Services, LLC
        Golden,
            Colorado
        303-887-2032
        www.aspenesco.com
        ***@***.***
          | LinkedIn
      
    
    On 1/26/2022 3:22 PM, Anders Andreasen
      wrote:
    
    
      
      @Jamesincolorado As @DanWBR
        says it doesn't matter - the thing is that zero flow / zero
        composition is kind of a singularity, the temperature is simply
        not defined, setting the temperature to anything is wrong in any
        way it should be null, or actually you could argue it should be
        0 K m since |S| = 0 :-) sorry. What about my earlier reply, did
        you have time time to reflect on the reason for no water in the
        stream?
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
        You are receiving this because you were mentioned.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/DanWBR/dwsim/issues/267#issuecomment-1022658094",
"url": "https://github.com/DanWBR/dwsim/issues/267#issuecomment-1022658094",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by DanWBR** [comment]
@Jamesincolorado Still no file. You need to drag the file directly here in GitHub when adding a new comment, and not through an email reply

**Comment by andr1976** [comment]
Also the simulation file should be zipped - or file ending renamed to zip

**Comment by Jamesincolorado** [comment]
Here are the files. 
[bug reports.zip](https://github.com/DanWBR/dwsim/files/7951962/bug.reports.zip)

**Comment by andr1976** [comment]
@Jamesincolorado 
Flash specified as two phase - see screen dump. If you change flash specification and actually enter the same flow as in VMG you get 121.9 lbm/h water compared to 122.55 lbm/h water in VMG. Pretty damn close. Can be due to slightly different BIPs/Kijs. VMG probably have tuned their compared to the Dechema/ChemSep used by DWSIM. 
![image](https://user-images.githubusercontent.com/58475535/151414335-bd8f7e34-cca0-4e92-9989-6c49ee422ff2.png)

Which 2-phase separator are we talking about ?

**Comment by andr1976** [comment]
Please close this issue

**Comment by Jamesincolorado** [comment]
Does not solve with default equilibrium. 
![mstr-01 not solved](https://user-images.githubusercontent.com/76176708/151420207-61739f35-2892-4c1e-8153-4d01103ee34b.jpg)

**Comment by Jamesincolorado** [comment]
Does not solve with default equilibria. See file on git hub.
    
    
      
      
      


      
        James
            Meyer, MBA/PE
        Aspen
            Engineering Services, LLC
        Golden,
            Colorado
        303-887-2032
        www.aspenesco.com
        ***@***.***
          | LinkedIn
      
    
    On 1/27/2022 10:52 AM, Anders Andreasen
      wrote:
    
    
      
      @Jamesincolorado
        Flash specifies as two phase - see screen dump. If you change
        flash specification and actually enter the same flow as in VMG
        you get 121.9 lbm/h water compared to 122.55 lbm/h water in VMG.
        Pretty damn close. Can be due to slightly different BIPs/Kijs.
        VMG proably have tuned their compared to the Dechema/ChemSep
        used by DWSIM.
        
      Which 2-phase separator are we talking about ?
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
        You are receiving this because you were mentioned.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/DanWBR/dwsim/issues/261#issuecomment-1023490511",
"url": "https://github.com/DanWBR/dwsim/issues/261#issuecomment-1023490511",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by andr1976** [comment]
Please install latest version of DWSIM, it seems you're running an older version. First step when using open source software - always check latest version.

**Comment by Jamesincolorado** [comment]
Will not solve with version 7.2. 
[3-phase sep.zip](https://github.com/DanWBR/dwsim/files/7954102/3-phase.sep.zip)

**Comment by DanWBR** [comment]
@Jamesincolorado it did solve here. v7.2.0. I'm closing this issue, won't waste my time on this anymore as I have a lot of things to do already. Sorry.

<img width="749" alt="Captura de Tela 2022-01-27 às 18 13 06" src="https://user-images.githubusercontent.com/2669419/151452449-cdb7f2ca-bf81-4c4e-bc09-fd8273a453d8.png">
