### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by GenarioA** [DanWBR/dwsim6#262]
**Describe the bug**
Hi guys! I think there's a bug on the UNIFAC/MODFAC models. Aparently there are some parameters missing, so when I create a compound that contains furfural and CHO groups the simulation doesn't run. The bug is confirmed by the yellow square in the thermodinamyc properties screen (screenshots below).

**To Reproduce**
1. Create or import any compound with CHO or furfural groups (like Vanillin for example)
2. Export this compound as an .json file
3. Add it to a simulation
4. See the error

**Screenshots**
Error message:
![Screenshot](https://user-images.githubusercontent.com/86748941/146820256-a04b02cd-fa16-41b9-8961-044659cb03a2.png)
Missing constant parameters:
![Screenshot01](https://user-images.githubusercontent.com/86748941/146820310-ece72cab-5078-4025-8d84-94dbe50396ef.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 build 19043.1415
 - Version 7.1.1

Thank you, Daniel for creating such an amazing software!

**Comment by DanWBR** [comment]
@GenarioA this is not a bug. Not all UNIFAC/MODFAC interaction parameters are publicly available.
