### ISSUE TITLE
Issue Cooler/Heater with "Outlet Vapor Molar Fraction" as claculation type

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#27]
**Describe the bug**
It seems Heater / Cooler have problem when calculation type is set to _Outlet Vapor Mole Fraction_. DWSIM solves heater/cooler very quickly with outlet temperature, temperature change or heat added/removed. But for the same setting if you change calculation type to outlet vapor fraction, it fails and a failure message is appeared as below (see attached simulation file):

> "Error	COOL-006: PT/PV/TV Flash: Maximum number of iterations reached. (T = 818.66 K, P = 601,325.00 Pa, MoleFracs = { 0.333333333333333, 0.333333333333333, 0.333333333333333, })"

**To Reproduce**
1. Open attached simulation file and open the Cooler object editor
2. Note to the vapor fraction and heat added removed values
3. Change the calculation type to outlet vapor fraction
4. Run the simulation

**Important** 
The above error is true for heaters. See heater in simulation file and repeat step 2-4 above

**Another Issue**
The strange behavior is when one of the cooler or heater fails to converge I see the other equipment is red or its outlet is red! What is going wrong here?

**Expected behavior**
The same calculation result is expected with all calculation type for cooler/heater. Also it seems the convergence is very slow with outlet vapor fraction!

**Simulation file**
[issue-heater-cooler-outlet-vapor-fraction.zip](https://github.com/DanWBR/dwsim6/files/5172750/issue-heater-cooler-outlet-vapor-fraction.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Classic UI
 - DWSIM 6.1 Update 4

**Comment by DanWBR** [comment]
Outlet Vapor Fraction calculation mode triggers a saturation point flash calculation (pressure/vapor fraction), which is much slower than the more common pressure/temperature or pressure/enthalpy flashes.

**Comment by kookma** [comment]
> Outlet Vapor Fraction calculation mode triggers a saturation point flash calculation (pressure/vapor fraction), which is much slower than the more common pressure/temperature or pressure/enthalpy flashes.

Is there any way to improve this? In Hysys this is very fast but it is not clear what methodology/numerical solver they use! Do you think there is any ground to work on this part? Please advise.

**Comment by DanWBR** [comment]
What I did in 4702a89 was to provide a better initial estimate for the P-VF flash in the heater/cooler. I was using the inlet temperature as the initial estimate, which was very far from the solution in your case, and for some reason the solver became stuck in a hole and did not converge. Now, with the better estimate, it converges quickly.

**Comment by kookma** [comment]
@DanWBR  many thanks for all your efforts.
