### ISSUE TITLE
Cooler simulation does not work if vapor fraction based calculation is selected as an option . [Bug] 

### ISSUE THREAD

**Issue by kpat2022** [DanWBR/dwsim6#270]
The simulation works for varying outlet temperature manually. 

However, it doesn't work if vapor fraction is selected. Inlet is 100% vapor. Trying solve for outlet 100% liquid (0 vapor fraction). 

![image](https://user-images.githubusercontent.com/97913478/149827264-3e73b6e1-67cf-4776-8ac4-dd684c7ef5de.png)

![image](https://user-images.githubusercontent.com/97913478/149829182-914b57ad-5aad-4fbf-8258-b33d6155819f.png)

IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS]
 - Version [e.g. v6.4.1]

**Additional context**

**Comment by DanWBR** [comment]
@kpat2022 can you attach a sample file?

**Comment by kpat2022** [comment]
Please see attached.

**Comment by DanWBR** [comment]
@kpat2022 there is no attachment, you need to zip the simulation file and drag and drop it in your answer box here on GitHub.

**Comment by kpat2022** [comment]
[play.zip](https://github.com/DanWBR/dwsim/files/7927678/play.zip)

**Comment by DanWBR** [comment]
@kpat2022 the calculation fails because you've manually forced the inlet stream to be all vapor. set it back to global definition and it should work.
