### ISSUE TITLE
ChemSep column and CAPE Open unit operation information are missing from the XML results file 

### ISSUE THREAD

**Issue by mvass7** [DanWBR/dwsim6#275]
Hi, I am interesting in obtaining the DWsim results file, after running the sim, in an xml format for a project that I ll be working on. However, it is essential for me that the information (e.g operating conditions) of all unit operations are stored in this file. I realized that for the ChemSep column and I think for CAPE OPEN units in general those info are not available. 

Is it possible to somehow include similar information that are available for the other unit operations, into the dwxml simulation file?

**Comment by DanWBR** [comment]
@mvass7 are you referring to the XML results report?

**Comment by mvass7** [comment]
@DanWBR I am talking about the  DWSIM XML Simulation File (.dwxml) saving format. I basically want to access information about the ChemSep column and CAPE OPEN units through this file. Currently I can get all the information I need for the rest of the unit operations except those two types.

**Comment by DanWBR** [comment]
@mvass7 I believe that it is there, you just couldn't find it, otherwise the natural gas processing unit sample wouldn't work, as it has 3 chemsep columns.

**Comment by mvass7** [comment]
@DanWBR Sorry I should make my question more clear. I am working with XML files.

 I attached 3 images to show you how three different unit operation objects look when I open a .dwxml file in to an editor to see it in its serialized format. The first is an object of a  unit operation developed in CAPE-OPEN and used in a random sim, the second is a chemsep object  and the third is a standard  distillation column (available in dwsim). 

So my problem is that more specific information like the ones I am showing in the distillation_unit image  (reboiler duty,  cond duty etc) are not available in the chemsep_unit image as you can see. 

Therefore, I was asking if it is possible to include this "missing "information of unit operations of the same category into the .dwxml file? 

![cape-open_unit](https://user-images.githubusercontent.com/91543475/151411277-a737f42f-cded-4edc-80ea-09038938cbdc.jpg)
![chemsep_unit](https://user-images.githubusercontent.com/91543475/151411287-39a4d66e-f7ec-4425-9943-8cd168bafec5.jpg)
![distillation_unit](https://user-images.githubusercontent.com/91543475/151411291-33fcfb70-9ec8-4489-a388-71daba196abf.jpg)

**Comment by DanWBR** [comment]
@mvass7 unfortunately I don't have control of how the CAPE-OPEN object will persist its configuration state, as it can return something in an unknown binary format that only itself can understand and decode. What I do is to encode the data in Base64 string format so it can be written and read from/to the XML file.

You can find more information on the CAPE-OPEN persistence standard itself: https://www.colan.org/wp-content/uploads/2016/05/Persistence-Common-Interface.pdf

And also take a look at my implementation: 

https://github.com/DanWBR/dwsim/blob/06654702a966d7b138c94e9798ddb93546017624/DWSIM.UnitOperations/UnitOperations/CapeOpenUO.vb#L836-L906

**Comment by DanWBR** [comment]
this is how the data looks like in the DWSIM XML file:

<img width="950" alt="Captura de Tela 2022-01-27 às 16 54 41" src="https://user-images.githubusercontent.com/2669419/151442179-78f051a4-7aa6-4963-a49d-45ba30afd7ed.png">

**Comment by mvass7** [comment]
Thank you very much for your help. I will take a look at those and hopefully l make it work.
