### ISSUE TITLE
Splitter Font

### ISSUE THREAD

**Issue by Jamesincolorado** [DanWBR/dwsim6#279]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
The splitter font is too small to be useable.  See attached. 
[HX-1 RATING.zip](https://github.com/DanWBR/dwsim/files/7961122/HX-1.RATING.zip)

**Comment by DanWBR** [comment]
@Jamesincolorado what do you mean by "splitter font"? Please add a screenshot, and do not reply to this by using your email!

**Comment by Jamesincolorado** [comment]
![spliiter screen shot](https://user-images.githubusercontent.com/76176708/151607404-cf6dddf0-f778-47ad-8865-0e8e80a6dffe.jpg)

**Comment by DanWBR** [comment]
@Jamesincolorado ok, got it. thanks
