### ISSUE TITLE
[IDEA] Lets Change the order of components in a simulation

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#28]
**IDEA**
It seems DWSIM shows the components list everywhere in the order they were added to a simulation! Sometimes it is good to show them in another order like sorted alphabetically or show important components first. The suggestion is one can reorder the components in setting / compounds page!

**Another Suggestion**
In Hysys which is more a hydrocarbon processing simulator, it shows light hydrocarbon like methane ethane, ... first! It may be useful to have options in compounds page to show different components in different order, so selection and adding new components to a simulation will be much easier.

**Category**: [Enhancement]

**Comment by DanWBR** [comment]
<img width="890" alt="Captura de Tela 2020-09-04 às 13 52 05" src="https://user-images.githubusercontent.com/2669419/92271471-d8ae1500-eeb5-11ea-8c20-8b743c17e8bf.png">

**Comment by kookma** [comment]
Ah Wonderful!
Thank you Daniel!
