### ISSUE TITLE
PR EOS Failure[Bug] 

### ISSUE THREAD

**Issue by Jamesincolorado** [DanWBR/dwsim6#280]
The attached file fails at the outset with a "not execute PR EOS" at MSTR-38 using default or VLLE PR. The DWSIM file is attached. Also attached is a screenshot of the simulation with the error message and a screenshot of the "about DWSIM" window. The file does run with the VLE option selected. 

[NOT EXECUTE PR EOS.zip](https://github.com/DanWBR/dwsim/files/7964252/NOT.EXECUTE.PR.EOS.zip)

**Comment by DanWBR** [comment]
@Jamesincolorado when the usual combination of Default + Nested Loops for equilibrium calculations, you can add a second property package changing the eq calc method to Default + Gibbs Minimization, for instance, and then use this propert package in the problematic streams and unit operations. See the attached solved version of your flowsheet.

FYI, there aren't many great open source math libraries that DWSIM can use to make these calculations perform better. Things evolved during the last years but we're not quite there yet.

[EXECUTE PR EOS.dwxmz.zip](https://github.com/DanWBR/dwsim/files/7964395/EXECUTE.PR.EOS.dwxmz.zip)

**Comment by andr1976** [comment]
Hi @Jamesincolorado , another option which is speedier that the Gibbs min, is to increase max iterations for you PR VLLE PT/PV, say by a factor of 5, and then maybe reduce tolerance by an order of magnitude - then MSTR-38 solves with PR Default/VLLE and Nested Loops. The compressors with problems can be handled by PR with just VLE. It works for me
