### ISSUE TITLE
Specification blocks not updating [Bug] 

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#283]
**Describe the bug**
Changing input to a specification block does not update the output of the specification block

**To Reproduce**
Let a number of streams temperature and pressure be set by a master stream.  Specification block update temperature and pressure of slave streams. The slave streams dont get properly updated. Some does, some don't
See also attached case 

**Expected behavior**
All streams should get same pressure and temperature when the "master" stream GERG is changed 

**Screenshots**
![image](https://user-images.githubusercontent.com/58475535/152614504-dfe4edb8-0d87-46b7-84a8-0dbea8dbcd92.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, 
 - Version [e.g. v7.3.0]
[Big_sensitivity_study.zip](https://github.com/DanWBR/dwsim/files/8006720/Big_sensitivity_study.zip)

**Comment by DanWBR** [comment]
@andr1976 If the streams don't have any kind of indirect connection information, this won't work. The solver doesn't check the specification blocks to determine the calculation order.

**Comment by andr1976** [comment]
Ok so the spec block is only called once? only more if the flowsheet solver iterates through one (or more times) ? Anyway I can just use a spreadsheet, - maybe a calculation order (priority) could be nice at some point.

**Comment by andr1976** [comment]
@DanWBR, ahhh, I guess I cant either? or?

**Comment by DanWBR** [comment]
yes... I haven't touched it for many years already. When calculating a stream/unit op, the solver looks for an attached spec and then runs it, that's all.

**Comment by DanWBR** [comment]
@andr1976 we can always do some work on it, if we find a good logic for these cases

**Comment by andr1976** [comment]
Seems to work with a spreadsheet - maybe this should be and enhancement instead
