### ISSUE TITLE
Deleting streams and unit ops deletes random elements[Bug] 

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#284]
**Describe the bug**
When deleting blocks of streams and unit ops, things which is not marked is deleted, and some things marked is not deleted

**To Reproduce**
See screen dumps and atttahced file 

**Expected behavior**
Only marked things are deleted. 

**Screenshots**
Before 
![image](https://user-images.githubusercontent.com/58475535/152615062-05572f0c-bcf5-424e-8518-85d339b5fb6d.png)

Marking thinks for deletion
![image](https://user-images.githubusercontent.com/58475535/152615025-95dce128-48f0-4de3-b8bf-14ac032a3fc2.png)

After ???
![image](https://user-images.githubusercontent.com/58475535/152615116-5296ca49-5de0-4e43-bada-3c94fdb62005.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, 
 - Version [e.g. 7.3.1
[Pipeline_pressure_drop.zip](https://github.com/DanWBR/dwsim/files/8006761/Pipeline_pressure_drop.zip)

**Comment by DanWBR** [comment]
@andr1976 you have many objects with the same name, this is confusing DWSIM

**Comment by andr1976** [comment]
I see, one fix could be to not allow duplicate names/ automatically add an incremental number when copying streams - but maybe more a feature

**Comment by DanWBR** [comment]
@andr1976 I took precautions in the latest version, as the objects are now named 1, 2, 3 and so on. When renaming an object, DWSIM will check if the name already exists.
