### ISSUE TITLE
Mixer Failure [Bug] 

### ISSUE THREAD

**Issue by Jamesincolorado** [DanWBR/dwsim6#285]
The mixer in the attachedd file fails due to a PR failure. 

**Desktop (please complete the following information):**
 - OS: [Windows,]
 - Version [ v7.3.1]

[Mixer failure.zip](https://github.com/DanWBR/dwsim/files/8009074/Mixer.failure.zip)

**Comment by andr1976** [comment]
Hit F5 and solves fine in 7.3.1. on my PC
![image](https://user-images.githubusercontent.com/58475535/152794344-3b9dfaac-d769-481d-b7ac-58817626030e.png)
