### ISSUE TITLE
Global Heat Transfer[Bug] 

### ISSUE THREAD

**Issue by Jamesincolorado** [DanWBR/dwsim6#286]
I have calculated the global heat transfer coefficient three ways and obtained three different answers:

1. Direct from program: 12 btu/h/ft2/F
2. Reciprocal of the summation of the inverse of individual heat transfers: 68 btu/h/ft/F
3. U=Q/A/DTLM: 17 btu/h/ft2/F

Which is correct? DWSIM file, screenshot and Excel calculation are zipped below. 

[HEAT TRANSFER DISCREPANCY.zip](https://github.com/DanWBR/dwsim/files/8026152/HEAT.TRANSFER.DISCREPANCY.zip). 

Thank you.

**Comment by DanWBR** [comment]
@Jamesincolorado correct is 1. 2 and 3 cannot currently be calculated because there are some confusion in the code and a LMTD correction factor that is not exposed.

**Comment by Jamesincolorado** [comment]
Thanks for the quick reply. I thought 3 was correct because Q is known, A is known, and LMTD is a very simple calculation. How could 3 be wrong?

Is Q corrrect? A is certainly correct. I can calculate LMTD by hand.

**Comment by DanWBR** [comment]
@Jamesincolorado 3 should be correct if you knew the value of the LMTD correction factor that is calculated internally, but not exposed... I'll fix this confusion. My original code was modified by someone else and it seems that things became a little messy here.

**Comment by Jamesincolorado** [comment]
Just to complete the discussion, why was the inverse of the sum of 1/h so far off?

**Comment by DanWBR** [comment]
@Jamesincolorado in the next version you'll see this. The calculations are correct, only the display of the parameters is that is currently confusing you.

<img width="423" alt="Captura de Tela 2022-02-09 às 11 13 40" src="https://user-images.githubusercontent.com/2669419/153230357-a6a38268-02e6-4576-a566-98a242baa28b.png">
