### ISSUE TITLE
[Bug] Conversion reactor

### ISSUE THREAD

**Issue by pdenis13** [DanWBR/dwsim6#287]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

Same bug as #229, The mole balance is not correct. 

**To Reproduce**
See attached simulation.

**Expected behavior**
Methane output is expected to be the same as input. Instead it is increasing.
Hydrogen should decrease, instead it is increasing.

**Desktop (please complete the following information):**
 - OS: OSX & Windows
 - Version : 7.3.1

[Cyclohexane - test 03.dwxmz.zip](https://github.com/DanWBR/dwsim/files/8047929/Cyclohexane.-.test.03.dwxmz.zip)

**Comment by DanWBR** [comment]
Thank you for reporting this issue, @pdenis13 . I'll be releasing v7.3.2 with a fix very soon:

<img width="446" alt="Captura de Tela 2022-02-12 às 10 17 03" src="https://user-images.githubusercontent.com/2669419/153714922-68680b73-5302-4d66-9e99-2d0f34795f02.png">
