### ISSUE TITLE
Scrubber failure (reference bug 267) [Bug] 

### ISSUE THREAD

**Issue by Jamesincolorado** [DanWBR/dwsim6#288]
The scrubber liquid composition is incorrect because it contains almost no water . There is a problem with PR calculations for water -- water is certainly heavier than the hydrocarbons. .Changing the thermo from vle to default causes a failure using both nested loops and Gibbs minimization. Screenshots and file attached. 

[scrubber failure.zip](https://github.com/DanWBR/dwsim/files/8056097/scrubber.failure.zip)

**Comment by DanWBR** [comment]
check this.

[scrubber failure.dwxmz.zip](https://github.com/DanWBR/dwsim/files/8056376/scrubber.failure.dwxmz.zip)

**Comment by Jamesincolorado** [comment]
It solved, yes, but the solution is wrong. Water cannot exit the vapor stream at 50 F/148 psig. The PR EOS has a flaw with water. Even  with vle (i.e., not vlle) the water should leave with the liquid phase.

**Comment by DanWBR** [comment]
@Jamesincolorado, the solution seems correct indeed. The water is at equilibrium, so some water must leave in the vapor phase.

Please, avoid registering such cases as bugs, as it makes me lose my valuable time every time I need to come here to check your stuff. If DWSIM doesn't work for you, just don't use it.
