### ISSUE TITLE
Issue Shortcut Column and negative minimum refulx ratio

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#29]
**Describe the bug**
DWSIM reports negative reflux ratio. The simulation is repeated in Hysys V11 and it shows correct value!

**To Reproduce**
1. Open the attached simulation file. It shows a simple shortcut column
2. Open shortcut column object editor
3. Scroll down to Results
4. See error: negative value for minimum reflux (-0.288117)
5. Solving in Hysys 11 returns (0.031)

---

**Expected behavior**
Reflux ratio cannot be negative

**Simulation files**
[shortcut-column.zip](https://github.com/DanWBR/dwsim6/files/5173195/shortcut-column.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Classic UI
 - DWSIM 6.1 Update 4

**Comment by DanWBR** [comment]
Is this correct, feed entering at 9.9 bar, condenser pressure = 2 bar and reboiler pressure = 4 bar?

**Comment by kookma** [comment]
Hi Daniel,
 Yes, the data are not real! The condenser 3bar, reboiler 4bar and feed is 9.9 bar! But I can use real data and change it to some upper or lower limits! 
My point is to issue a warning and do not return negative values as reflux ratio.

**Comment by DanWBR** [comment]
@kookma thanks, was just checking. I'm working on this already.

**Comment by DanWBR** [comment]
Please try reproducing this case in HYSYS and let me know the calculated Rmin.

[shortcut-column.dwxmz.zip](https://github.com/DanWBR/dwsim6/files/5178748/shortcut-column.dwxmz.zip)

**Comment by kookma** [comment]
The minimum Reflux Ratio is 0.079. The full result is attached!

[Hysys-SC.zip](https://github.com/DanWBR/dwsim6/files/5179453/Hysys-SC.zip)

**Comment by DanWBR** [comment]
The distillate and bottoms temperatures in HYSYS are much lower than in DWSIM. A feed at 69 C and distillate at -106 C? Very strange. DWSIM calculates a distillate temperature of 7 C which makes more sense to me...

**Comment by DanWBR** [comment]
@kookma could you please attach a screenshot of the stream compositions? Thanks!

**Comment by DanWBR** [comment]
@kookma it seems that you've entered 4 kPa as condenser and reboiler pressures, I've did the same and now the temperatures match.

**Comment by DanWBR** [comment]
I'm getting 0.36 as minimum refluxo ratio now. Not the same as HYSYS but at least it is not negative. I've inspected the code and it seems correct according to Underwood's method as described in the Distillation Design book. Let's keep this issue opened just in case something new shows up.

**Comment by kookma** [comment]
@DanWBR Sorry for that strange mistake :-) The file I sent you was in Hysys 3.1. I checked the results with latest version V11 and I got 0.461 for minimum reflux ration very close to DWSIM simulation you sent me above!

[HysysV11.zip](https://github.com/DanWBR/dwsim6/files/5180036/HysysV11.zip)
