### ISSUE TITLE
Switching between calculation types in Heat Exchanger fails to solve[Bug] 

### ISSUE THREAD

**Issue by Shumb0** [DanWBR/dwsim6#290]
Switching between calculation types in Heat Exchanger fails to solve.

This bug can be reproduced using a simple heat exchanger setup.

![image](https://user-images.githubusercontent.com/97127676/153963685-02219549-71d2-4386-b2bc-b3d141878e8f.png)

When setting the heat exchanger using "Specify Outlet Molar Vapor Fraction of Steam 2. a UA is calculated for a vap fraction of 1.
![image](https://user-images.githubusercontent.com/97127676/153963821-b756b14d-5b44-4bbb-a85f-4ad6b6a32932.png)

If the mode is changed to Calculate Outlet Temperature (UA), the model fails to solve.

![image](https://user-images.githubusercontent.com/97127676/153963940-bd1719aa-fd67-4e92-9a9c-6723332804e1.png)

[HE Issue.zip](https://github.com/DanWBR/dwsim/files/8074581/HE.Issue.zip)

**Comment by Shumb0** [comment]
I think the issue comes with the way the Heat Exchanger solves using UA. The results from Symmetry and Hysys solving the problem with no issue, but DWSim fails.

**Comment by DanWBR** [comment]
I've just tested it here in v7.3.2 and it worked nicely.

<img width="1230" alt="Captura de Tela 2022-02-15 às 17 21 24" src="https://user-images.githubusercontent.com/2669419/154151299-cc00ab46-ca0a-4d5b-a1c8-b5a615caaf72.png">

**Comment by Shumb0** [comment]
Sorry about that Daniel. I uploaded the wrong file.
[HE Issue (2).zip](https://github.com/DanWBR/dwsim/files/8074885/HE.Issue.2.zip)

Hysys output.

![image](https://user-images.githubusercontent.com/97127676/154152962-6078f7d1-c273-4df3-8d5a-48082195a3f5.png)

Symmetry output.

![image](https://user-images.githubusercontent.com/97127676/154153427-9607ce4d-7869-4171-88e9-7b2387a010ba.png)


 DWSim Output.

![image](https://user-images.githubusercontent.com/97127676/154153640-7d0d56ad-4ae0-4eb8-b495-4706050926c4.png)

**Comment by DanWBR** [comment]
@Shumb0 the UA calculation method was implemented by @Greg66 and seems to be applicable only for single-phase heat exchange. Maybe he can propose a solution for this error.

**Comment by Shumb0** [comment]
I have tested the Cape-open heat exchanger of COCO sim on DWSim but that leads to an inaccurate result as there is no segmentation in the heat exchanger. Hopefully Greg can share some insight/solution.

**Comment by Shumb0** [comment]
Hi Daniel,

Do you think the same issue would be in the Air cooler in the Pro version (don't own the pro version). I am currently trialing software for a large energy generator and we are trialing Symmetry and DWSim. The model is nearly complete on DWSim and will test the trial to compare results, but I am worried about the heat exchanger as we will be unable to use the sizing done for the Vaporizer and Turbine Condenser.

**Comment by DanWBR** [comment]
@Shumb0 I've fixed the outlet temperature calculation modes in DWSIM. I've checked the Air Cooler code and it uses the same code for UA as in the regular heat exchanger.

I remember that the original code for this calc mode was mine, and then Gregor updated it to use the NTU method. I'll see if it is possible to revert it.

**Comment by DanWBR** [comment]
@Shumb0 I was wrong, the original code is the same from Gregor...

**Comment by Shumb0** [comment]
oh no :(

**Comment by DanWBR** [comment]
@Shumb0 maybe there is another way of calculating it... I will check but can't give you a deadline

**Comment by Shumb0** [comment]
I think even with UA calc, you will still need to segment the heat exchanger to capture the effects of phase change for accurate outlet temperatures. (Unless it is  already segemented)
