### ISSUE TITLE
[Bug] Distillation curve characterisation

### ISSUE THREAD

**Issue by the-famous-eccles** [DanWBR/dwsim6#292]
There seem to be a couple of bugs in the Distillation Curve petroleum characterisation code related to integer division

In the mol. wt. calculation here...
https://github.com/DanWBR/dwsim/blob/windows/DWSIM.UI.Desktop.Editors/Compounds/DistCurves.cs#L565
and here...
https://github.com/DanWBR/dwsim/blob/windows/DWSIM.UI.Desktop.Editors/Compounds/DistCurves.cs#L569
the exponent (1.5 in the Riazi/Al-Sahhaf equation) is specified as (3/2), which I believe is being calculated as 1 and not 1.5. This is throwing the calculation off (and subsequently also the SG and other property calculations).

There is a similar problem with the exponent - specified as (1/3) - in:
https://github.com/DanWBR/dwsim/blob/windows/DWSIM.UI.Desktop.Editors/Compounds/DistCurves.cs#L736

**Comment by DanWBR** [comment]
@the-famous-eccles thanks!

**Comment by the-famous-eccles** [comment]
No problem. Thanks for the quick fix. Hope to see the next release soon!
