### ISSUE TITLE
[Bug] The valve model gives an insanely low outlet temperature

### ISSUE THREAD

**Issue by Geron1mo38** [DanWBR/dwsim6#293]
The valve model gives me a very low outlet temperature with an inlet stream at 913.5 psig and outlet of 215 psig. If I subsitute a cooler with the same pressure drop and adjust the specified outlet temperature until I get a resulting zero heat duty then the result is much more reasonable ie +1.7 deg F vs -268 deg F.  

System contains Nitrogen, CO2, Methane.V2,C3,Ic4,nc4,ic5,nc5,c6,c7,Octane through to trace of Ethylene Glycol and water.  I am using Peng Robinson 1978 advances thermo and VLLE.
 
I am using the Windows 64 bit version.with DWSIM 7.3.3

IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS]
 - Version [e.g. v6.4.1]

**Additional context**

**Comment by DanWBR** [comment]
@Geron1mo38 could you please attach the simulation file?
