### ISSUE TITLE
Simulation fails for reactor using Automation on Python IDE

### ISSUE THREAD

**Issue by Shachi14** [DanWBR/dwsim6#295]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
When trying to run a simulation with a reactor using Python IDE, the flowsheet solves with errors. I faced no issues with the same commands for other unit operations. If I open the saved simulation manually and click on SolveFlowsheet, it converges, however, fails to do so using code.

**To Reproduce**
interf = Automation2()
sim = interf.CreateFlowsheet()
r1 = sim.AddObject(ObjectType.RCT_CSTR, 100, 50, "Reactor")

'I have then added the necessary compounds, material streams, reactions as well as reactor specifications.'

inter.CalculateFlowsheet2(sim).

I receive the following error(image attached).

**Expected behavior**
For the successful completion of flowsheet.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:Windows
 - Version [e.g. v7.3.3
![Error](https://user-images.githubusercontent.com/92026739/156047965-ee878914-aebd-4295-844b-9300f951250b.png)
]

**Additional context**

**Comment by DanWBR** [comment]
The error is in line 439 of CSTR.vb:

https://github.com/DanWBR/dwsim/blob/2af32d076012fd2fe0ffded9b20b54c9c2e1aa21/DWSIM.UnitOperations/Reactors/CSTR.vb#L439

It means that either the Reaction ID is invalid or it was not added to the list of reactions in the Flowsheet.

**Comment by Shachi14** [comment]
Yes, I believe my error was, I added the reaction to the list of reactions using the Name property and to the set of reactions using Reaction ID. Thank you!
