### ISSUE TITLE
[Bug] Inconsistent/unstable mixing/flashing behavior since v7.3.1

### ISSUE THREAD

**Issue by leastcreativeusername** [DanWBR/dwsim6#296]
**Describe the bug**
I have noticed this bug with a larger model which works fine in version v7.2.0, but that I have not been able to solve in versions later than v7.3.1 due to odd flash behavior in a specific VL separator. In v7.3.1 the VL separator flash failed after reaching T=-16 K, and in v7.3.2/v7.3.3 the entire feed vaporizes with the vapor outlet not in enthalpy balance with feed streams. 

I have narrowed the issue down to an apparent bug with mixing/flashing and reduced the model down to an example with just a few streams which demonstrates the issue in v7.3.3. The property package used is PR78 - I saw there was some notes in changelog related to PR78 since 7.2, so perhaps that may have something to do with it?

Simplified example flowsheet:

![Simplified example](https://user-images.githubusercontent.com/100643544/156079275-0236cab3-f5e0-46f2-aa40-7aef5a5199d1.png)

Stream input data & some relevant properties for streams S1 & S3 are below:

```
                                         	S1        	S3
Temperature (C)                          	23.515761	-15.62622
Pressure (bar)                          	17.8    	7.7
Mass Flow (kg/h)                        	30427.64668	24.990883
Molar Flow (kmol/h)                     	1795.897778	1.47014
Specific Enthalpy (Mixture) (kJ/kg)     	-1223.24545	-1424.998372
Molar Fraction (Vapor)                  	0.025622	0.010381
Molar Flow (Mixture) / Hydrogen (kmol/h)	15.280055	0.006469
Molar Flow (Mixture) / Nitrogen (kmol/h)	6.477561	0.004557
Molar Flow (Mixture) / Ammonia (kmol/h) 	1774.139709	1.459112
Molar Flow (Mixture) / Water (kmol/h)    	0.000453	0.000002
```

By repeatedly solving the above flowsheet  in v7.3.3 (with no changes between runs), I get either of the following outcomes:

1. The entire mixed stream S4 is vaporized, with specific enthalpy reported as approx -44 kJ/kg (out of balance with M1 inlet streams)
2. The stream S4 has vapor fraction of 0.075 with specific enthalpy reported as approx -1223 kJ/kg

It is worth noting that if I set the outlet pressure of valve V1 = 7.7 bar (same as stream S3) so that there is no pressure drop across the mixer M1 then result 2 is consistently obtained.

Screenshots of these two outcomes are shown in the section below.

**To Reproduce**
1. Set up flowsheet per above screenshot and inputs
2. Solve flowsheet, obtain one of two results
3. Solve flowsheet again (sometimes a few times), obtain the other result

**Expected behavior**
Expected result is for stream S4 to have vapor fraction of ~0.07 with enthalpy of approx -1223 kJ/kg, in balance with streams S2 & S3.

**Screenshots**
Sensible result:
![Working - highlighted](https://user-images.githubusercontent.com/100643544/156081256-3400b935-ac19-41ab-8400-a0f6a2769db4.png)

Bugged/incorrect result:
![Broken - highlighted](https://user-images.githubusercontent.com/100643544/156081295-285d0411-a026-4ada-9f4a-fafb0646fb22.png)

Result from v7.2.0 for comparison:
![v7 2 0](https://user-images.githubusercontent.com/100643544/156082760-b7cddb94-14c4-4295-b5cc-77cc6b548ae4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 & Windows 11 (tested on multiple machines)
 - Version: v7.3.3 (works as expected in v7.2.0)

**Comment by DanWBR** [comment]
@leastcreativeusername could you please attach the simulation file? thanks

**Comment by DanWBR** [comment]
@leastcreativeusername maybe this specific change is the reason? https://github.com/DanWBR/dwsim/commit/8d4b0845fcb95a2d0beab8d3856a3c9d569b05f4

Strangely, I got VF = 1 on the first runs, then after that, all solutions went to VF ~ 0.07.

**Comment by leastcreativeusername** [comment]
Hi Dan, thanks for looking into this. 

Apologies, should have thought to attach the simulation file in original post! Have attached the simulation for the initial post as "Bugged mixer - 20220228.zip".

[Bugged mixer - 20220228.zip](https://github.com/DanWBR/dwsim/files/8168177/Bugged.mixer.-.20220228.zip)

On further inspection it seems that there's more than two outcomes for this model. If you keep an eye on the specific enthalpy of stream S4 in the above file it seems to vary slightly with each run (at least on my machine). For me, it is usually around -44 kJ/kg and now seems to be only occasionally solving to give any liquid fraction at all.

I have also attached a second model "Bugged valve - 20220302.zip", which I suspect is the same bug, however this time it is seen only with flashing across a valve and with no mixer involved. 

[Bugged valve - 20220302.zip](https://github.com/DanWBR/dwsim/files/8168208/Bugged.valve.-.20220302.zip)

If you re-run this second model and keep an eye on the enthalpy/vapor fraction of stream S11, it again varies with each run, usually giving too high an enthalpy with VF=1, only occasionally solving to give enthalpy close to expected with some liquid.

I think you may be onto something with the change you highlighted - I'll admit I'm quite new to DWSIM and I'm not familiar with the codebase, but it looks to be in the right area. I'll try myself to follow what's going on in the part of the code you've highlighted later today/tonight to see if I can understand what might be going on.

Cheers!

**Comment by DanWBR** [comment]
@leastcreativeusername I've added a partial fix that solves the problem with the bugged valve. Ammonia is making everything much more difficult, DWSIM simply cannot find the bubble point of the mixture at 7.7 bar. It doesn't converge at all, even when using 3 different convergence methods...
