### ISSUE TITLE
Issue Classic UI

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#3]
OS: Windows 10
UI: Classic UI, DWSIM 6 update 7

To replicate the issue

1. Open DWSIM with double click from Windows desktop
2. From File click "New Steady-State Simulation"
3. Follow the wizard step by step and click finish in the last step

Nothing will appear, you still see the Welcome to DWSIM page! Click on cascade windows, group windows, ... has no effect and you have to save the simulation and open the newly saved file to see the simulation environment

**Comment by DanWBR** [comment]
Thanks for the report, someone else already reported this issue but I could not reproduce it in my computer. Will investigate the code to see what may be going on.
