### ISSUE TITLE
[Bug] Wrong operating pressure for gas-liquid separator on datatip window

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#314]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
The operating pressure on gas-liquid separator is always displayed zero.  This is true both for calculated vessel pressure and the specified ones.

**Expected behavior**
The correct operating pressure shall be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/830394/162605081-478940f9-0f2f-40e5-9e11-1b60cbfc138c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - DWSIM 7.5.1

**Comment by DanWBR** [comment]
@kookma these are dynamic-mode properties. did you enable dynamic mode or selected these properties explicitly?

**Comment by kookma** [comment]
> did you enable dynamic mode or selected these properties explicitly?

No, I have not! Are these activated/selected by default? How can I disable them in steady - state mode?

**Comment by DanWBR** [comment]
@kookma they should only be visible if dynamic mode is activated.

**Comment by kookma** [comment]
I check this again and will inform you!

**Comment by kookma** [comment]
Daniel,
I checked again (Win10/DWSIM7.5.1).

*  I opened the dynamic manager panel, it is not active
* I checked from DWSIM menu bar, Dynamics and made sure the `Dynamic Mode Active` is not checked

Now again I hovered mouse over the separator and still I see operation pressure 0 in the data tip window.

**Comment by kookma** [comment]
Thank you Daniel.
