### ISSUE TITLE
Compound Creator [Bug] 

### ISSUE THREAD

**Issue by nilsenmd** [DanWBR/dwsim6#316]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
There is a write error when exporting a created compound to a JSON file.

**To Reproduce**
1. Create a compound in CompoundCreator
2. Click the "View Compound" button in the lower right corner
3. In the pop up window, click the "Export to JSON File" button
4. Save the file

**Expected behavior**
If you look at the JSON file in a text editor, it ends at line 165 or 166. The remaining file has not been written. The only way to fix this is to manually paste in the missing information from a complete JSON file and change the values to match the compound you're creating. It's time consuming and prone to error. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10 PRO

**Additional context**

**Comment by DanWBR** [comment]
this issue was fixed in https://github.com/DanWBR/dwsim/commit/1cb18c22547c16dff25678f0617f85ec47d6b894

next release will work as expected.
