### ISSUE TITLE
[Enhancement] Libraries should target netstandard2.0 to be more versatile

### ISSUE THREAD

**Issue by smkanadl** [DanWBR/dwsim6#317]
**Is your feature request related to a problem? Please describe.**
dwsim.org describes 'Standalone Thermo' as one of the use-cases of DWSIM. Due to the nature of the binaries being compiled for .NET 4.6.2, the usage is restricted to projects targeting the 'full' framework.

**Describe the solution you'd like**
As a solution, one would typically try to target either netstandard2.0 or multi-target for typical LTS-versions of the various flavours of the .NET ecosystem. That way, the Thermodynamic libraries are also usable in .NET Core and .NET5/6 projects.

**Comment by DanWBR** [comment]
@smkanadl it is not so simple to do that given the current structure of the thermodynamics library and its dependencies (i.e. windows forms). Actually, I do have a netstandard version of the library (heavily modified, by the way) which I use in the mobile versions of DWSIM, but it is not free/open-source.

**Comment by smkanadl** [comment]
@DanWBR thanks for the quick response. I am aware of the implications with such a request and that it is nothing to be expected in near future.

For my potential use-case, I would not need any UI related bits but mostly the phase equilibrium/ PT flash routines. As you mentioned the netstandard version of the library is not available as open source, what would the way to get hold of it? At least for some testing/evaluation process.

Many thanks,
Kai

**Comment by DanWBR** [comment]
@smkanadl I call it "PortableDTL", and as I've mentioned before, it is used in DWSIM for Android and iOS, which are freemium apps. Making the library portable was a huge work that I was able to accomplish years ago. It is not head-to-head with the thermo library for DWSIM for desktop, there are some parts that were not updated, i.e. the flash algorithm structure.

**Comment by smkanadl** [comment]
@DanWBR that's unfortunate as the flash algorithms are exactly the ones I would need.

**Comment by DanWBR** [comment]
@smkanadl I have a .NET 6 version of DWSIM ready to release, but I set this as a target for GitHub sponsoring: https://github.com/sponsors/DanWBR

**Comment by smkanadl** [comment]
@DanWBR thank you very much for providing the information. I will talk to the project management and check if GitHub sponsoring is something we could do (With respect to company policies and stuff like that).

I assume that the 25$ tier would already give us access to the .NET 6 version (per the private repository DWSIM Core). Is that correct?

**Comment by DanWBR** [comment]
@smkanadl yes, the $25 tier gives you access to DWSIMCore repository.

**Comment by BorisGoryunov** [comment]
Hi,
@DanWBR how could I get access to the .NET 6 version ?
