### ISSUE TITLE
Issue Modal Windows Stay on Top of all Windows in Desktop

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#32]
**Describe the bug**

Some floating windows in DWSIM are modal. The issue is they stay on top of all windows opened in Windows Desktop while they should be modal and stay on top of windows opened inside DWSIM. This makes problems when for example assue you are reading data from a pdf opened in Windows desktop and you are entering them in DWSIM. 

Examples

1. Reaction Window

**Expected behavior**
A modal window shall only stay on top of opened windows in DWSIM not other windows in Desktop.

**Desktop (please complete the following information):**
 - OS: Windows 10
- Classic UI
 - DWSIM 6.1 Update 6

**Comment by DanWBR** [comment]
Unfortunately this behavior is system wide, there is no way to make the window modal only inside DWSIM.

**Comment by DanWBR** [comment]
HYSYS and Aspen Plus use a different GUI technology, more ancient and windows specific.
