### ISSUE TITLE
[Bug] There is no initial flowsheet state in DWSim 7.5.5 at the above panel

### ISSUE THREAD

**Issue by sesepsianturi** [DanWBR/dwsim6#321]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS]
 - Version [e.g. v6.4.1]

**Additional context**

**Comment by DanWBR** [comment]
closing due to the lack of information and not following the issue description rules.
