### ISSUE TITLE
Suspicious branch in Valve.vb

### ISSUE THREAD

**Issue by msakai** [DanWBR/dwsim6#322]
I'm suspicious about this conditional branch:

https://github.com/DanWBR/dwsim/blob/11d3f14fab66f908240d0a4418eeb57f36ac0876/DWSIM.UnitOperations/UnitOperations/Valve.vb#L827-L866

If the `CalcMode`  is `CalculationMode.Kv_Steam` then the first condition `CalcMode <> CalculationMode.DeltaP And CalcMode <> CalculationMode.OutletPressure` holds so that the control flow goes into the `Then` block and never reaches to the`ElseIf CalcMode = CalculationMode.Kv_Steam Then ... End If` part.

**Comment by DanWBR** [comment]
@msakai when I first read your message just after waking up, I thought that DWSIM had a virus or something like that. :)
