### ISSUE TITLE
Distillation column: reboiler pressure does not match column pressure

### ISSUE THREAD

**Issue by AlbertEmil** [DanWBR/dwsim6#326]
I tried to simulate a distillation column operated at 100 mbar and specified the pressure for both the distillation column and its feed stream. However, the reboiler pressure does not seem to be adjusted to the specified value and remains at the default value of 1013.25 mbar.

![Screenshot](https://user-images.githubusercontent.com/14151027/170365754-c8ca22ee-c448-4c1b-a6fb-d32e3fc8d0fd.png)

As I just started to explore DWSIM, there is a big chance that I just missed some input fields for the proper pressure specification. However, there as been [a similar issue a few years ago](https://sourceforge.net/p/dwsim/discussion/844529/thread/70c4d469/) which should already be fixed in a previous release some time ago. I am using DWSIM 7.5.5 64-bit on Windows 10 64-bit.

**Comment by AlbertEmil** [comment]
I did miss to specify the column pressure drop. `NaN` does not seem to be evaluated as `0`. So there was definitely an error on my side.

**Comment by DanWBR** [comment]
@AlbertEmil I've left the pressure drop as NaN to preserve pressure profiles in older simulations. Profiles on new simulations should be defined with top pressure and pressure drop.

**Comment by AlbertEmil** [comment]
> @AlbertEmil I've left the pressure drop as NaN to preserve pressure profiles in older simulations. Profiles on new simulations should be defined with top pressure and pressure drop.

Thanks for the clarification and legacy background info.
