### ISSUE TITLE
[Bug] Some column properties are not updated if set from Automation2 interface

### ISSUE THREAD

**Issue by AlbertEmil** [DanWBR/dwsim6#327]
Setting `DistillationColumn.NumberOfStages` or `DistillationColumn.CondenserPressureDrop` via `Automation2` interface from Python does not update available column stages.

The following (pseudo-)code can be used to reproduce the faulty behaviour:

```
interf = Automation2()
sim = interf.CreateFlowsheet()

column = sim.AddObject(ObjectType.DistillationColumn, 0, 0, 'column')

column.NumberOfStages = 20
column.CondenserPressure = 10000                    # Pa
column.ColumPressureDrop = 0                           # Pa

print(f'column.NumberOfStages = {column.NumberOfStages}')
# --> 20

print(f'len(column.Stages) = {len(column.Stages)}')
# --> 12

print(f'column.CondenserPressure = {column.CondenserPressure}')
# --> 10000.0

print(f'column.ColumnPressureDrop = {column.ColumnPressureDrop}')
# --> nan

interf.SaveFlowsheet(sim, str(flowhseet_path), True)

```

I might miss something like an `update()` method to apply the changed values to the `column` object. However, setting the `CondenserPressure` property does work.

When opening the saved flow sheet, the column specifications printed to the console are also given in the according forms of the GUI:

![column_general](https://user-images.githubusercontent.com/14151027/170543894-65558490-a519-4fe9-a0d3-b8882fe78247.PNG)
![column_stages](https://user-images.githubusercontent.com/14151027/170543916-4a47285b-6cd2-4e72-b79d-bb11c348df2c.PNG)

Performing a mouse click in the `General > Number of Stages` field and pressing the Enter key seems to update the specified number of stages as the `Stages` dialog is updated thereafter:

![Screenshot 2022-05-26 194344](https://user-images.githubusercontent.com/14151027/170545437-07401c94-181c-40f3-9c62-5f5edf27988f.png)

The error occurred with DWSIM 7.5.5 64-bit on Windows 10 64-bit and Python 3.7.4 64-bit

**Comment by DanWBR** [comment]
@AlbertEmil you must use **SetNumberOfStages()**:

https://github.com/DanWBR/dwsim/blob/d677a640390a95c2807e51f96621d0e7e1671e21/DWSIM.UnitOperations/UnitOperations/RigorousColumn.vb#L1870-L1910

**Comment by AlbertEmil** [comment]
Thanks. That fixed the problem. Specifying the `ColumnPressureDrop` did not work due to a typo in my code.
