### ISSUE TITLE
Bulk copy+paste stream mole fractions from the spreadsheet tab or from excel

### ISSUE THREAD

**Issue by hdavid16** [DanWBR/dwsim6#329]
I would like to create a stream and copy paste the compositions for each component in bulk. However, this fails and I can only paste one by one

**Comment by hdavid16** [comment]
Hi @DanWBR,

I would like to reopen this issue as a Bug or at least an Enhancement. I have an Excel file with the components (in the same order as the Compound Amounts tab on a Material Stream in my simulation) and their corresponding mass fractions. I want to copy and past the mass fractions over to the Material Stream in my simulation rather than entering them one by one. When I do this, I have to:

1. Select both columns on Excel (component and mass fraction)
2. Copy and click on the first component in the Compound Amounts tab on DWSIM
3. Ctrl + V to paste

This pastes all the values correctly, but then inserts a blank row at the end, causing an error when trying to click the "Accept" button.

I tried copying them over to the Spreadsheet tab on DWSIM and the copy + paste over to the stream, but this copies the entire table into the cell that I have selected.

Empty Compound Amounts:
![image](https://user-images.githubusercontent.com/9156129/180049554-0be79335-b967-4db5-b4d9-bf8079ef23fd.png)

After Copying from Excel: (empty row at bottom and RED text on top "Total: 1")
![image](https://user-images.githubusercontent.com/9156129/180049790-94daeca3-26c0-46a8-b7c7-9105e14a50d1.png)

Being able to copy and past this would really help in simulations with many components.

**Comment by DanWBR** [comment]
@hdavid16 did you try copying only the values? you should not copy and paste the compound names as the first column is read-only.

**Comment by hdavid16** [comment]
I tried copying only the values over to the editable column and it actually copies them over to the name column:

![image](https://user-images.githubusercontent.com/9156129/180057833-b2741645-45bd-466a-903c-5cecf08376ba.png)

My current workarround is to use Excel to generate python code which I then copy over to the Python console to set the stream composition in DWSIM:

![image](https://user-images.githubusercontent.com/9156129/180058189-380ca88a-3559-4918-b233-da2e572a3cc4.png)

**Comment by DanWBR** [comment]
@hdavid16 select the first cell in the Amount column, then Ctrl+V.

**Comment by hdavid16** [comment]
> @hdavid16 select the first cell in the Amount column, then Ctrl+V.

That is what I did and got the behavior in the last screenshots.
