### ISSUE TITLE
[Bug]  PVF / dew point calculation error 

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#333]
**Describe the bug**
Dewpoint calculation fails for the PVF flash for PR, SRK, GERG etc

**Expected behavior**
Identify dew point temperature of -11 / -12 C'ish at 40 barg

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. v8.0.0]

**Additional context**
See attached file 
[dewpoint_error.zip](https://github.com/DanWBR/dwsim/files/8936255/dewpoint_error.zip)

**Comment by DanWBR** [comment]
@andr1976 does it fails due to an error or wrong temperature value? just to be sure

**Comment by DanWBR** [comment]
@andr1976 initial estimates are close to the trivial solution. the algorithm conditions are satisfied in the end, even with the wrong temperature. do you have any suggestion?

**Comment by andr1976** [comment]
The calculation runs but returns a temperature which is not the dew point at the specified pressure. Far from.  Things start to go sideways above 30'something bar.

**Comment by andr1976** [comment]
![image](https://user-images.githubusercontent.com/58475535/175160355-d512fef3-acb8-419e-810a-2466da1cd168.png)

![image](https://user-images.githubusercontent.com/58475535/175160483-3dd84549-f9af-424a-9ba3-f9661df50d2d.png)

**Comment by andr1976** [comment]
Ok one is with SRK but the same applies with PR. There is apparently a regression in the stability of the PVF/TVF algorithm

**Comment by DanWBR** [comment]
@andr1976 did you check this with latest code?

**Comment by andr1976** [comment]
Sorry, no haven’t had time yet

tir. 28. jun. 2022 kl. 20.34 skrev Daniel Wagner ***@***.***>:

**Comment by andr1976** [comment]
@DanWBR , yes dew point is fine now, but the bubl-point is messed up now above 44-46 bar depending on EOS. I also think the critical point is way off. Above this pressure bubl point temperature suddenly jumps from -76 C to -10 C

**Comment by andr1976** [comment]
This is the envelope expected 
![image](https://user-images.githubusercontent.com/58475535/176441439-aecbe9ae-2224-4ea2-ae87-927fac6441c7.png)

**Comment by DanWBR** [comment]
@andr1976 the critical point is the reference to stop calculating dew and bubble points... it is very far from the correct one in this specific case

**Comment by andr1976** [comment]
Yes, I see. Thing is, this is natural gas (although a little to the heavy side), so this is something that could potentially be encountered quite often

**Comment by DanWBR** [comment]
This looks better (PR). SRK still fails to calculate the correct critical point. GERG will need a new algorithm as I don't have a general procedure to calculate critical points - only PR and SRK for now.

![image](https://user-images.githubusercontent.com/2669419/176459800-43f6ee07-be1c-4a08-8814-2a9883cf7260.png)

**Comment by DanWBR** [comment]
the chart title is wrong - it was calculated with PR.

**Comment by andr1976** [comment]
Looks way better now - I think PP is somehow defaulting to the last PP available, for the title, not for the calcs

**Comment by andr1976** [comment]
Could be nice to have Ian Bell on-board to do the critical point calculation method :-)  
https://www.nist.gov/publications/calculation-critical-points-helmholtz-energy-explicit-mixture-models

**Comment by DanWBR** [comment]
@andr1976 I have an implementation of this method for quite some time already, but I've let it aside as it is slow and was not working. I'm revisiting it to see if I can get it working.

**Comment by DanWBR** [comment]
SRK:

![image](https://user-images.githubusercontent.com/2669419/176702031-6208d18a-38f1-4f94-b7af-88c8c40afcc7.png)
