### ISSUE TITLE
Invalid cast by deserialization (dot->comma problem). Need invariant culture

### ISSUE THREAD

**Issue by AlexanderSemenyak** [DanWBR/dwsim6#34]
By open file from this link https://sourceforge.net/p/dwsim/discussion/844529/thread/d6577f67f5/ (in attach)

> Error Loading Flowsheet Graphic Objects: System.InvalidCastException: Приведение строки "59.64677" к типу "Integer" является недопустимым. ---> System.FormatException: Input string was not in a correct format.   at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)   at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)   --- End of inner exception stack trace ---   at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)   at XMLSerializer.XMLSerializer.Deserialize(Object obj, List`1 xmlprops, Boolean Fields) in C:\Users\Daniel\source\repos\DanWBR\dwsim6\DWSIM.Serializers.XML\XMLSerializer.vb:line 92   at DWSIM.Drawing.SkiaSharp.GraphicObjects.GraphicObject.LoadData(List`1 data) in C:\Users\Daniel\source\repos\DanWBR\dwsim6\DWSIM.Drawing.SkiaSharp\GraphicObjects\Base\GraphicObject.vb:line 91   at DWSIM.FormMain.AddGraphicObjects(FormFlowsheet form, List`1 data, ConcurrentBag`1 excs, String pkey, Int32 shift, Boolean reconnectinlets) in C:\Users\Daniel\source\repos\DanWBR\dwsim6\DWSIM\Forms\Main Window\FormMain.vb:line 1106
[bug.zip](https://github.com/DanWBR/dwsim6/files/5212140/bug.zip)

**Comment by DanWBR** [comment]
are you running v6.1 Update 6 already?

**Comment by AlexanderSemenyak** [comment]
fixed in newer releases
