### ISSUE TITLE
[Bug] Reboiled Absorber Input Error

### ISSUE THREAD

**Issue by hdavid16** [DanWBR/dwsim6#343]
DWSIM v8.0.2
Windows OS

When I try to setup a distillation column block with no condenser (reboiled absorber), I have the following connections:

- Feed stream (input material stream)
- Overhead vapor (output material stream)
- Bottoms (output material stream)
- Reboiler Duty (input energy stream)

I cannot run this column as I get an error that says that there are connections missing. What am I missing? I don't have a distillate stream because there is no condenser and I don't have a condenser duty.

**Comment by DanWBR** [comment]
@hdavid16 you need to connect these streams anyway.

**Comment by hdavid16** [comment]
Ok, I just created a dummy stream for the distillate and condenser duty and the error goes away.

**Comment by DanWBR** [comment]
@hdavid16 I need to revisit these connection checks...

**Comment by DanWBR** [comment]
fixed in https://github.com/DanWBR/dwsim/commit/1103a3144734b7e1f20071aae98503a5e62daf35
