### ISSUE TITLE
[Bug]  PEM Fuel Cell

### ISSUE THREAD

**Issue by WillyLund** [DanWBR/dwsim6#346]
The new Pem Fuel Cell UO creates negative compositions in the exit stream.  Easy to reproduce by over specifying the fuel cell capability vs the feed stream.  Please advise if a sample simulation file would be needed.

P.S. Thank you for the entry into renewables, this is my working domain for the past 3 years.  Hope you can find a chance to visit our website carbon280.com.  We have a very novel long duration energy storage solution.

**Comment by DanWBR** [comment]
@WillyLund thank you for reporting this issue. I should have added a check for negative molar flows. Will do it tomorrow. 🙂👍🏻
