### ISSUE TITLE
Call functions through Excel VBA

### ISSUE THREAD

**Issue by ssldkwork** [DanWBR/dwsim6#347]
**How to call a function through Excel VBA?**
For example I can call "CalcProp" function through Excel Worksheets, but can not call the same function in VBA. Is there any solution for?

**Comment by DanWBR** [comment]
Excel VBA is not supported, but you can try it as described in https://dwsim.org/wiki/index.php?title=DTL

Afetr registering the type library, it should become available on the VBA editor if you import it
