### ISSUE TITLE
[Bug] Weather toolbar at the bottom of flowsheet: UI elements get disordered - Allow Hide

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#349]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
In DWSIM 8.0.3 (I see this from 8), the Weather toolbar on opening the left side info panel gets disordered and some UI elements overlap eachother.

**Expected behavior**
1. allow user to hide them, when they are not in use
2. on opening the left side info panel UI elements should stay in correct order

**Screenshots**

- With closed left info panel

![img_1369_DWSIM](https://user-images.githubusercontent.com/830394/177367076-baf0aaee-6e0f-4023-90a1-afac384e4c2e.png)

- With open left info panel

![img_1370_DWSIM](https://user-images.githubusercontent.com/830394/177367106-ef0e3f2e-60ed-483d-8f50-c7fc0243d826.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - DWSIM 8.0.3
 - Screen: full HD (15.5 inch) 1080*1920, 60Hz  (also tested on HD screen with 1600x900, 21inch)

**Comment by DanWBR** [comment]
@kookma will be fixed in the next release, thanks!
