### ISSUE TITLE
[Bug] DWSIM : pressure changers efficiencies not adjustable

### ISSUE THREAD

**Issue by guidoc66** [DanWBR/dwsim6#350]
When using a pressure changer such as Turbine or Compressor, both the adiabatic and the isoentropic efficiencies are set to 75% by default but you can change them within the range 0-100%. The problem is that when you run the simulation, the efficiency is automatically changed to the default value (75%) before the calcs are performed. As a consequence there is no way to change the efficiencies of thiese machines.

My DWSIM is running on a  Windows 10 HP portable computer.

Does anyone has experienced the same issue? It really looks like a bug to me.
Thanks 
Guido

**Comment by WillyLund** [comment]
I am not seeing the issue with the compressor using version 8.03

**Comment by DanWBR** [comment]
@guidoc66, you must press ENTER after changing the value.

**Comment by DanWBR** [comment]
Except if you're on macOS or Linux, where the values are updated as you type them.

**Comment by guidoc66** [comment]
> @guidoc66, you must press ENTER after changing the value.

wow..it works! sorry for disturbing you fo so silly problem. Shame on me!

**Comment by hdavid16** [comment]
@DanWBR or @guidoc66 can you close the issue if it has been resolved?
