### ISSUE TITLE
[Bug] Wizard to Import a compound from Online source is buggy

### ISSUE THREAD

**Issue by hdavid16** [DanWBR/dwsim6#352]
When trying to import a compound from online sources, the following is observed:

1. The wizard starts on Step 3
2. You have to click Next and the wizard will move to Step 2
3. You have to click Back to actually go to Step 1 and search for the compound

Also, the next buttons often are greyed out and you have to use Enter on the keyboard to move forward.

**Comment by DanWBR** [comment]
@hdavid16 windows or linux/mac?

**Comment by hdavid16** [comment]
Windows OS
DWSIM 8.0.3

I am seeing this behavior on 2 different machines.

**Comment by SeifEdI** [comment]
The same problem 👍 
DWSIM version : 8.0.3
OS : windows 10 Pro. Version 10.0.10240.0, Win32NT PLatform

CLR info : .NET Framework (CLR v4.0.30319342000)
CPU Info : Intel64 Family 6 Model 60

**Comment by hdavid16** [comment]
@DanWBR did the commit referenced fix the issue? If so, feel free to close it.
