### ISSUE TITLE
Compile (build) instructions unclear

### ISSUE THREAD

**Issue by kugelpunk** [DanWBR/dwsim6#353]
Is it still irrelevant which project is used as the starting point? I get dozens of unresolved dependencies/imports either way.
https://github.com/DanWBR/dwsim/blob/windows/README.md#L87

**Comment by DanWBR** [comment]
@kugelpunk did you restore all nuget packages?

**Comment by kugelpunk** [comment]
> @kugelpunk did you restore all nuget packages?

no, that I was not aware of...

**Comment by DanWBR** [comment]
@kugelpunk it should be an automatic step on VS 2019 and 2022.

**Comment by kugelpunk** [comment]
OK thanks, I will check the log.

**Comment by kugelpunk** [comment]
> @kugelpunk it should be an automatic step on VS 2019 and 2022.

I am using VS 2019, but I see they are partly out of date. I think a lock file to pin the nuget package versions is not used, so I will try to restore them using the nuget internal mechanism (`PackageReference` I believe.).

**Comment by kugelpunk** [comment]
I think I am not getting from which entry point to build the entire DWSIM binary for Windows x64 for Debug purpose. The readme recommends to use either of the projects (s.a.). Then, there is also the `DWSIM.sln`, which seems the natural starting point. (I will try again, once my packages are updated, but I have a slow connection and wanted to ask this ahead once more.)

**Comment by DanWBR** [comment]
@kugelpunk I don't recommend updating any package. Open DWSIM.sln, then select the solution, click on "Restore NuGet Packages"... wait for it to finish, then change the build configuration to Debug/x64 or DebugNoNPM/x64, DWSIM.exe as starting point and then build it.

**Comment by DanWBR** [comment]
@kugelpunk restoring nuget packages is a common task when working with .NET projects in VS.

**Comment by kugelpunk** [comment]
> @kugelpunk I don't recommend updating any package. Open DWSIM.sln, then select the solution, click on "Restore NuGet Packages"... wait for it to finish, then change the build configuration to Debug/x64 or DebugNoNPM/x64, DWSIM.exe as starting point and then build it.

OK, I did `Restore NuGet Packages` on the `DWSIM.sln` and got
```
All packages are already installed and there is nothing to restore.
```
However, building to Debug/x64 fails with 75 missing file errors like:\
`could not find library 'C:\Users\Ben\source\repos\DWSIM\DWSIM.Thermodynamics\bin\Debug\DWSIM.Thermodynamics.dll'`

`Metadata file 'C:\Users\Ben\source\repos\DWSIM\DWSIM.FlowsheetBase\bin\Debug\DWSIM.FlowsheetBase.dll' could not be found`

I have installed Node.js on Windows and DebugNoNPM/x64 is not available as a preconfigured option, so I did not try this flag. When building Debug/x64, I also get this error:\
`The command "if not "Debug"=="NoNPMBuild" (
powershell.exe -Command "cd 'C:\Users\Ben\source\repos\DWSIM\DWSIM.UI.Web\ClientApp'; $env:CI=$false; npm install; npm run build"
)" exited with code 1.`

Apart from these error types there is only one more error of a missiing food props XML file:\
`Unable to open resource file 'DWSIM.Thermodynamics.FoodProp.xml': Could not find file 'C:\Users\Ben\source\repos\DWSIM\DWSIM.Thermodynamics\Assets\Databases\FoodProp\FoodProp.xml'.`

Therefore, I wondered whether I chose the right entry point (c like `main` program) to build from. (I had similar errors when building the `DWSIM\DWSIM.vbproj` or `DWSIM.UI.Desktop\DWSIM.UI.Desktop.csproj` projects separately.)

**Comment by DanWBR** [comment]
@kugelpunk to solve this issue, you must clone the repository (https://github.com/DanWBR/dwsim) directly from Visual Studio as FoodProp.xml is part of another project.

**Comment by kugelpunk** [comment]
> @kugelpunk to solve this issue, you must clone the repository (https://github.com/DanWBR/dwsim) directly from Visual Studio as FoodProp.xml is part of another project.

Thanks, and would I need to copy the DLL files somewhere?
I'll try either way, thanks.

**Comment by kugelpunk** [comment]
Hi @DanWBR , thanks for clarifying the `readme.md` with https://github.com/DanWBR/dwsim/commit/2298597e890fb2e8f9a6cc7fd85b4d71101fab27. However, as of now it only builds once after cloning : /

**Comment by hdavid16** [comment]
Hi @DanWBR and @kugelpunk,

Could you help define the steps to build DWSIM for someone who has never used Visual Studio?

I have installed Visual Studio 2022 and Node.js. I then cloned the DWSIM GitHub repo into Visual Studio. I don't know where to go from there...
I'm not sure what is meant by changing the build target and the steps that come after that in the README.

Thanks,

**Comment by kugelpunk** [comment]
> Hi @DanWBR and @kugelpunk,
> 
> Could you help define the steps to build DWSIM for someone who has never used Visual Studio?

I was in the same situation. Yes, we might better stress the terms found in the VS (context) menu... I will  propose something.
> 
> I'm not sure what is meant by changing the build target and the steps that come after that in the README.
> 
If you build for yourself on Windows, you probably want to compile for debug purpose, so the target is a debug binary placed in a dedicated directory. And if you have a modern PC you go for 64 bit architecture. These things are set in the build configuration. I also have general questions about building, but I would continue discussion in the sourceforge forum. You ll find me there, too.

**Comment by DanWBR** [comment]
@kugelpunk @hdavid16 apart from setting the correct build configuration, the rest are standard VS procedures... if you don't know how to do it, then you probably won't have any benefit from compiling DWSIM from the source.

For all debugging purposes, choose the **DebugNoNPM / x64** solution configuration and set DWSIM.exe as the starting project.

First step:

<img width="582" alt="Captura de Tela 2022-07-22 às 11 02 51" src="https://user-images.githubusercontent.com/2669419/180467890-1f6341a0-778a-46fd-968d-44034fcb5c16.png">

Second step:

<img width="490" alt="Captura de Tela 2022-07-22 às 11 02 36" src="https://user-images.githubusercontent.com/2669419/180467873-c9eb42eb-fd64-4661-9391-08bc3d11ecbf.png">

Then click on the "Start" button.

**Comment by kugelpunk** [comment]
An EXE is what is being (optionally) run after a build. (You can use the start button for it.) MS is not very good on docs but I trust O'Reilly in this case, which clarifies the meaning of the `startup project` as being the entry point (c like `main` file):\
https://www.oreilly.com/library/view/sams-teach-yourself/0672322870/0672322870_ch06lev1sec6.html

**Comment by DanWBR** [comment]
@kugelpunk ok then, set "DWSIM" as the startup project. That thing named "DWSIM" on the list of projects.

**Comment by kugelpunk** [comment]
@hdavid16 in my case, it all depends on the `DWSIM.Thermodynamics.dll` being build. This, in turn requires the `<path_to_repo>\DWSIM.Thermodynamics\Assets\Databases\FoodProp\FoodProp.xml` to be present. I copied it from the clone of the original into my fork. (It does not get there via `git pull`.)

**Comment by DanWBR** [comment]
@kugelpunk is everything ok now, can we close this issue?

**Comment by kugelpunk** [comment]
Hi @DanWBR , it would be great if the git submodule could be checked out inside the project, so that it can be forked. I will test if this works in github now. However, that is more relevant for forks and pull requests. Users that clone recursively will get the submodule checked out. But if you like to have the actual submodule files inside your repo, we could keep this open and try to make things easier for collaborators.

**Comment by DanWBR** [comment]
@kugelpunk I'll try to include the file directly 👍🏻
