### ISSUE TITLE
[Bug] Compound JSON not importing Viscosity Equation

### ISSUE THREAD

**Issue by hdavid16** [DanWBR/dwsim6#354]
I have used the Compound Creator Wizard to create 1-tridecene. I noticed that after loading the resulting JSON, I am getting an error that the liquid viscosity is infinite for 1-tridecene.

I did the following:

1. I looked up the liquid viscosity data online and did a regression in Excel to get the equation: `1.0442*Exp(-0.022016*T)`. 
2. I put this equation into step 5 of the compound creator wizard. 
3. I verified that the JSON has this expression stored in the line 94

When I load this new JSON, the Liquid Viscosity is still empty (infinite).

How can I load a user defined Liquid Viscosity equation for a compound?

**Comment by DanWBR** [comment]
@hdavid16 please attach the JSON file if possible. 

As a general request for new issue reports that you may eventually create, please attach all related files if possible. They help a lot and sometimes I can't do anything without them.

**Comment by hdavid16** [comment]
The JSON portion related to the liquid viscosity shows up as:
```
  "Liquid_Viscosity_Const_A": 0.0,
  "Liquid_Viscosity_Const_B": 0.0,
  "Liquid_Viscosity_Const_C": 0.0,
  "Liquid_Viscosity_Const_D": 0.0,
  "Liquid_Viscosity_Const_E": 0.0,
  "LiquidDensityEquation": "",
  "LiquidHeatCapacityEquation": "",
  "LiquidThermalConductivityEquation": "",
  "LiquidViscosityEquation": "0.004552536*Exp(764.1220309/T)",
```

Note: I have done the regression with T in K and viscosity in Pa*s as indicated in the Wizard.

Sorry for not providing the necessary information.

**Comment by hdavid16** [comment]
Ok, I had to:

1. untick the 1-Tridecene from the compound list in my simulation
2. close and reopen the simulation file
3. reload the JSON file

After doing this, the viscosity correlation is loading correctly.

Conclusion: In my opinion, the bug is that when a JSON file is loaded to import a component and that component exists, a popup shows up asking if the user wants to update the component data based on this new JSON. However the component data is not being loaded properly and requires the steps taken above.

**Comment by hdavid16** [comment]
@DanWBR Thanks for putting together the commit! Feel free to close the issue if it has been fixed.
