### ISSUE TITLE
[Bug] Reaction Set Editor Sequence

### ISSUE THREAD

**Issue by hdavid16** [DanWBR/dwsim6#356]
When adding more than 1 reaction to a reaction set, the `Seq.` column for the reactions is set to 0 by default. I think the sequence should be increased by 1 unit by default. Otherwise, if more than 1 reaction has the same sequence number, only the last one defined will be used.

So either:
1. the program should still take both reactions even if their sequence is set to 0, or
2. the program should warn the user that the reactions should have a different sequence number

By default, the sequence number should increase as reactions are added.

In the below image, I have had to set the first reaction to 1 so that it occurs after the second reaction and isn't ignored:
![image](https://user-images.githubusercontent.com/9156129/180226002-7a2e2b54-249e-4d61-991f-df362724858b.png)

**Comment by DanWBR** [comment]
@hdavid16 this is not the intended behavior. all reaction indexes default to 0 so they are considered parallel reactions.

**Comment by DanWBR** [comment]
@hdavid16 and this is not a bug.

**Comment by hdavid16** [comment]
@DanWBR, then assuming they are being considered in parallel, there might be a bug in the reporting of the conversions: the conversions in the `Conversions` tab only show the materials in the second reaction, not the first reaction.

![image](https://user-images.githubusercontent.com/9156129/180261496-65cf446f-8be2-4a4f-a198-6a6ae20727a7.png)

**Comment by DanWBR** [comment]
@hdavid16 only positive conversions will be shown in this table, that is, compounds that were consumed after all reactions have been considered.

**Comment by DanWBR** [comment]
@hdavid16 I'll check the code anyway. Thanks

**Comment by hdavid16** [comment]
So the second tab in the Results pane (`Reactions`) shows a positive conversion for both reactions, but the conversions for the components in the first reaction are not shown. So maybe just a display issue...

Thanks!

**Comment by hdavid16** [comment]
@DanWBR Ok, so I'm not seeing this behavior on a different simulation. Perhaps it's an isolated event. I'll send you the file below in case you are curious. **If you don't want to bother with this, feel free to close this issue**.

There is clearly a sequential reaction mechanism in the file below:

1. C31-C34 + H2 => C18-C30 (Hydrocracking4)
2. C18-C30 + H2 => C3-C17 (HydrocrackingMain)

If I set the sequence as shown above, then I get all components to show up in the results:
```
Component	Conversion
N-Tetratriacontane	100
N-Tritriacontane	74.7694
N-octadecane	3.28215
N-nonadecane	7.11275
N-eicosane	12.4236
N-heneicosane	20.5583
N-docosane	26.2388
N-tricosane	33.4054
N-tetracosane	40.5557
N-pentacosane	47.922
N-hexacosane	56.4751
N-heptacosane	64.9359
N-octacosane	75.1957
N-nonacosane	85.8822
N-Dotriacontane	66.3319
N-Hentriacontane	34.0036
N-triacontane	100
Hydrogen	1.82536
```

However if I set them to parallel, then only the materials from the Hydrocracking4 are shown:
```
Component	Conversion
N-Tetratriacontane	100
N-Tritriacontane	74.7694
N-Dotriacontane	66.3319
N-Hentriacontane	34.0036
Hydrogen	0.112392
```

However, a conversion is displayed for both reactions when I run them in parallel.

[reaction_sequence.zip](https://github.com/DanWBR/dwsim/files/9161218/reaction_sequence.zip)
