### ISSUE TITLE
[Enhancement]  Sort object list alphabetically

### ISSUE THREAD

**Issue by janboshoff75** [DanWBR/dwsim6#358]
When developing large simulations with DWSIM, it becomes increasingly difficult to navigate the UI since drop-down menus of streams and other objects are sorted by some internal numerical order.  

It would be great if the list is always sorted alphabetically by Object name, that way, when renaming an object, it is easy to find when using the dropdown.

Seems like an easy fix, that will vastly improve productivity when dealing with DWSIM.

Thanks for considering.

**Comment by DanWBR** [comment]
@janboshoff75 it is indeed an easy fix but can take some time due to the high number of dropdowns. 😅

it will be done for the next release. thanks for the suggestion 👍🏻
