### ISSUE TITLE
[Feature] Update Python.Net library in DWSIM

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#36]
It seems Python.NET library supports Python 3.8 (see release 2.5 and above https://github.com/pythonnet/pythonnet/releases)
I appreciate to update DWSIM with latest Python.NET library.

**Comment by kookma** [comment]
Hi Daniel,
Does it mean it is no possible to update Python.Net?

**Comment by DanWBR** [comment]
Inside DWSIM's installation directory you will find a "pythonnet" folder which contains the DLL for python 3.6, 3.7 and 3.8. Just copy the desired one back to the main directory and it should work.

**Comment by DanWBR** [comment]
I can't update it because there are other components that depend on the 3.7 version, like the Reaktoro Property Package.

**Comment by kookma** [comment]
Thank you Daniel!
Wish you a very happy new year!
