### ISSUE TITLE
[Bug] mixer not respecting 1st law

### ISSUE THREAD

**Issue by cbkiyanda** [DanWBR/dwsim6#362]
**Describe the bug**
Solving a standard Rankine cycle with a single open feedwater heater (extracting steam between two turbines and reinjecting between two pumps through a mixer), I am using an adjust/controller block to find the extracted fraction required to make the output of the mixer a saturated liquid. The optimization ends up sending all the hot fluid to the mixer. The end result of the mixer is:
Incoming streams:
2.2e-7 kg/s @ h = 340.631 kJ/kg
2kg/s @ h = 2689.9 kJ/kg
Outgoing stream:
2kg/s @ h = 504.684 kJ/kg

**To Reproduce**
See attached example.

**Expected behavior**
The mixer should respect m3*h3 + m7*hh = m30*h30 and the extracted fraction should be SR1 = 0.0698383.

**Desktop (please complete the following information):**
 - OS: linux ubuntu 20.04
 - Version 8.0.4

[ofwh_example_optimized.zip](https://github.com/DanWBR/dwsim/files/9384375/ofwh_example_optimized.zip)

**Comment by cbkiyanda** [comment]
A different example works. The only thermo difference between the two is the cooler pressure (10 kPa here, instead of 50 kPa in the case of the optimized system). This is extra puzzling to me as the optimized example I posted above was built on top of this example here, so I wouldn't be expecting any difference in behaviour between the two cases.

[ofwh_example.zip](https://github.com/DanWBR/dwsim/files/9384480/ofwh_example.zip)

**Comment by cbkiyanda** [comment]
The second (non-optimized) example works when the mixer is at 1 MPa and the cooler at 10 kPa. When the pressure in the mixer is reduced to 200 kPa and the cooler is at 50 kPa, the 1st law seems to no longer be satisfied. The specified enthalpy of stream 30 would be expected to be 819.64 kJ/kg
[ofwh_example_200kPa.zip](https://github.com/DanWBR/dwsim/files/9
![Screenshot from 2022-08-19 14-13-49](https://user-images.githubusercontent.com/454918/185682079-16a1db22-a517-442c-89f4-8c35593bd221.png)
384530/ofwh_example_200kPa.zip)
.

**Comment by DanWBR** [comment]
@cbkiyanda I believe that the issue lies in setting up the optimization process. it seems that the objective function is not continuous as there are sudden enthalpy changes in the mixer inlet depending on how the controller plays with the split ratios.

**Comment by DanWBR** [comment]
@cbkiyanda try changing the Flash Spec of Stream 7 to Pressure and Enthalpy.

**Comment by cbkiyanda** [comment]
Interesting.
First, apologies for the multiple comments in a row. It was indeed not a problem with the setup of the optimization (at least not the adjust block optimization part) since the problem was also present when the split ratios were fixed. Changing stream 7 to P-H solved this particular problem.
Maybe there should be a final check at the end of flowsheet calculation to see if the 1st law is satisfied everywhere? In this particular case, it's troubling dwsim returns a successful calculation message, but the energy balance doesn't work.

**Comment by cbkiyanda** [comment]
Using my ofwh_example_200kPa example, it seems all flash spec settings work aside from T-P, which fails every time.
I optimized the cycle so the output of 15 (stream 18) is a saturated vapour by varying the heater outlet temperature (the intermediate pressure was changed from 200 kPa to 1 MPa in this example). The boundary is at T_heater = 383.099 C. If you set flash spec of stream 7 to T-P, then the calculation succeeds if T_heater > 383.099 C and fails if T_heater < 383.099 C. I'm making a guess here, but it seems that the problem is in calculating the equation of state at stream 7 when the incoming state is a mixture and T-P does not uniquely define a state anymore. 

I'm new to dwsim, so not sure if this problem is really a mistake I'm making and I should have known to change the flash spec or whether it is a proper bug. Given that the software ends the calculation with a message of "flowsheet calculated successfully", yet has a component that breaks the 1st law, I'm tempted to say this is a software bug. Perhaps
1) there should be a last check, just before the log message is returned to check that all blocks respect the 1st law, or
2) if a recycle block outputs a mixed phase stream, but has a T-P specified stream downstream, output a warning and switch the flash spec automatically to another specification.

[ofwh_example_200kPa_limit.zip](https://github.com/DanWBR/dwsim/files/9384952/ofwh_example_200kPa_limit.zip)

**Comment by DanWBR** [comment]
A T/P spec shouldn't be used in the outlet of the recycle block if the simulation has a single compound. It wasn't your fault, though. I should have added some checks, and will investigate why the mixer didn't warn about the energy balance not being fulfilled.

**Comment by DanWBR** [comment]
> I'm making a guess here, but it seems that the problem is in calculating the equation of state at stream 7 when the incoming state is a mixture and T-P does not uniquely define a state anymore.

that's exactly the issue.

**Comment by DanWBR** [comment]
@cbkiyanda v8.1.0 contains the fix and is now available for download 👍🏻
