### ISSUE TITLE
[Bug] Heat Exchanger

### ISSUE THREAD

**Issue by ryn376** [DanWBR/dwsim6#363]
Items 1-4 are for Calculation Type  - Shell and Tubes Exchanger Rating
Item 5 is for Calculation Type  - Calculate Hot/Cold Fluid Outlet Temp

1. q_reported is 914498 btu/hr
q_calc calculated from q=U*A*F*LMTD = 1.8e6 btu/hr
calculation for outlet streams are based on the reported q

2. right clicking on HX and copying properties gives Cold Side/Hot Side/Minimum Pressure of 101325 psi. I should be 50,150,49.9

3. changing the amount of tubes does not change the change the duty

4. outlet temperatures of the HX do not match the outlet stream temps
![Screenshot_1](https://user-images.githubusercontent.com/113264736/189502068-a291948e-3fe5-4e72-8b63-9fa5e3aa422f.png)

5. The incorrect temperature is select based on dropdown, i.e. "Calculate Hot Fluid Outlet Temp" allows input of "Cold Fluid Outlet Temp"
![Screenshot_2](https://user-images.githubusercontent.com/113264736/189502253-8f94d5b9-1c3a-4e0d-ba4d-536f36ac97a5.png)

**Comment by DanWBR** [comment]
@ryn376:

2 - minimum pressures are used on dynamic simulations only
5 - to calculate hot fluid's Tout you must provide cold fluid's Tout.

could you please attach a sample file so I can use it to check the other issues?

**Comment by ryn376** [comment]
I really appreciate your response! Lol thanks about #5 that was silly... My mind was fried after working all day. Regarding #2, the two hot and cold pressures still seemed to show incorrectly. I tried to attach the file, but GitHub indicated it is not the appropriate file type. What is the best way to send the file?

**Comment by DanWBR** [comment]
@ryn376 you can try zipping the file before uploading it

**Comment by ryn376** [comment]
[Ben.zip](https://github.com/DanWBR/dwsim/files/9543313/Ben.zip)
Excellent! Thanks so much!

**Comment by DanWBR** [comment]
@ryn376 as for 4, the outlet temperatures displayed on the HX table are your inputs. I can't update them with the actual temperatures because you can loose your input, if you switch the calculation mode back to one of the "Calculate Outlet Temperature" types.

**Comment by ryn376** [comment]
Thanks for looking into this. I downloaded the newest version this morning. I am still obtaining error 1, 2, 3, 4.
![image](https://user-images.githubusercontent.com/113264736/193032291-e7bfe102-3ec6-4d57-97c3-b4afb81239ba.png)
Regarding error 4, I don't see where the outlet temperatures would be coming from if they are not coming from the exchanger duty and matching the exchanger outlet temps.
[Ben9-29-22.zip](https://github.com/DanWBR/dwsim/files/9674642/Ben9-29-22.zip)

**Comment by DanWBR** [comment]
@ryn376 I told you before that minimum pressures are properties used only in dynamic mode. (2)

1 and 4 were fixed in code yesterday. you'll have to wait for the next binary release.

and 3 is happening because your HX is at 100% efficiency, due to a higher-than-required cooling water flow rate.

**Comment by DanWBR** [comment]
fixed in v8.2.0
