### ISSUE TITLE
[Bug] Two specification blocks in the same flowsheet, only the last one is updated

### ISSUE THREAD

**Issue by cbkiyanda** [DanWBR/dwsim6#366]
**Describe the bug**
I implemented an ideal rankine cycle with an open feedwater heater. To match the pressures in the feedwater heater, the 1st stage turbine and 1st stage pump need to have the same pressure. In order to reduce the number of manipulations required to change the feedwater pressure, I created a reference state (here material stream 30) to compute a saturated liquid state at the target feedwater pressure. I then add 2 specification blocks (spec_blocks_order1):
* spec block 29 links the material stream 30 pressure to the turbine 1 outlet pressure
* spec block 31 links the material stream 30 pressure to the pump 15 outlet pressure
It's important to note that the specification blocks were created in the order listed above. When running the flowsheet, only the linking of spec block 31 is applied, i.e. the pump outlet pressure is updated, but not the turbine outlet pressure. I tried deleting the function expression in spec block 29 and dwsim does not through an error when running the spreadsheet, indicating to me that the spec block is never checked. If I delete the function expression in spec block 31, an error is thrown
"Error in '30': 31: error parsing expression - SyntaxError: Unexpected end of file Line: 1, Column: 1".

If I create the  blocks in the opposite order (spec_blocks_order2), i.e. linking the pump first and then the turbine, then the turbine outlet pressure is consistently updated, but not the pump.

Trying to daisy-chain the specification blocks (spec_blocks_daisy_chain) also does not work. The spec blocks are applied inconsistently, sometimes not at all, sometimes only one of the specifications.

Note that, in the provided example, the material stream 30 is not strictly needed, i.e. the turbine could be linked to the pump with a single specification block. However, for my use case, I believe it is needed. The ultimate goal of this computation is to optimize the stream splitter stream ratio so that the mixer/feedwater output is a saturated liquid. This is done by using a controller/adjust block and comparing to the reference state. The multiple spec blocks are thus required.

**To Reproduce**
1. Create a flowsheet with multiple spec blocks referencing the same object

**Expected behavior**
I would expect all the spec blocks to be evaluated when run.

[spec_blocks_examples.zip](https://github.com/DanWBR/dwsim/files/9571045/spec_blocks_examples.zip)

**Desktop (please complete the following information):**
 - OS: linux ubuntu 20.04.5, unix 5.15.0.46
 - Version 8.1.0

Is this bug possibly related to issue #283 ?

**Comment by DanWBR** [comment]
@cbkiyanda the specification block is a hack. It doesn't obey the normal flowsheet calculation order. Each spec block is triggered when the source object is calculated, and it will work or not depending if the target object is still to be calculated according to the calculation order.

I wouldn't say that this is a bug, but it is by design. You can either rework your flowsheet to make sure that the above condition is met or use python scripts associated with certain flowsheet events to set/transfer data (recommended).

**Comment by cbkiyanda** [comment]
Is there a rule to know in which order blocks will be calculated? I've not found where to learn this so far.

**Comment by DanWBR** [comment]
@cbkiyanda the calculation order is determined automatically by the solver.

I've replaced the specs with two python scripts that are executed right before the turbine and pump are calculated. check the attached file.

[spec_blocks_full_pyscripts.dwxmz.zip](https://github.com/DanWBR/dwsim/files/9577747/spec_blocks_full_pyscripts.dwxmz.zip)

**Comment by cbkiyanda** [comment]
Thank you very much for the example. That was quite useful to learn how to use python scripts.
