### ISSUE TITLE
[Bug] distillation column result plots size wrong

### ISSUE THREAD

**Issue by andreyotw** [DanWBR/dwsim6#369]
Version 8.1.1 classic UI 64 bit Windows

after a successful simulation, when clicking on results and "View Temperature, Pressure and Composition Profiles" the resulting XY Plot sizing is wrong (very small) (_vide_ attached file)
![dwsim-distcolumn-bug](https://user-images.githubusercontent.com/114605400/192839955-4ad2fcf4-174f-4922-b646-528afcfed2c1.png)

**Comment by DanWBR** [comment]
@andreyotw I also noticed this bug some days ago. It was fixed in https://github.com/DanWBR/dwsim/commit/df6407d6ef09bb5721ea9c2a3b71831dc8acf3f3

**Comment by andreyotw** [comment]
Thanks a lot, Daniel! Look forward to the new release! Grande abraço!
