### ISSUE TITLE
Dynamic manager - Monitored Variables - Error - Input string was not in a correct format [Bug] 

### ISSUE THREAD

**Issue by AlexanderSemenyak** [DanWBR/dwsim6#370]
Dynamic manager - Monitored Variables - Error - Input string was not in a correct format 

**Steps to reproduce the behavior:**
1. Open flowsheet test.dwxmz form attach
2. Run Shedule in Integrator controls
3. See error in Information window

**Expected behavior**
Fill spreadsheet with dynamic values without errors

**Screenshots**

**Desktop:**
 - OS: Windows 11
 - Version v 8.2.1

**Additional context**
1. Digit separator configured as **comma** (e.g. 6,25)
[test.zip](https://github.com/DanWBR/dwsim/files/9894790/test.zip)

**Comment by DanWBR** [comment]
@AlexanderSemenyak it worked for me with comma and dot as decimal separators... can you paste the full exception info?

**Comment by AlexanderSemenyak** [comment]
> @AlexanderSemenyak it worked for me with comma and dot as decimal separators... can you paste the full exception info?

Input string was not in a correct format.

System.FormatException: Input string was not in a correct format.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at DWSIM.FormDynamicsIntegratorControl._Closure$__82-0._Lambda$__1() in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM\Forms\FlowsheetComponents\FormDynamicsIntegratorControl.vb:line 319
   at System.Threading.Tasks.Task.Execute()
![exception](https://user-images.githubusercontent.com/42087193/198968792-ae661212-4b24-4ae4-9598-1998351f4bce.png)
![exception2](https://user-images.githubusercontent.com/42087193/198970161-f3d4c535-2d4a-4029-832e-bb7f3c7fb415.png)

**Comment by DanWBR** [comment]
@AlexanderSemenyak it is actually on line 319:

https://github.com/DanWBR/dwsim/blob/416262cff8a704e903c011cadd456bb8abb1ca67/DWSIM/Forms/FlowsheetComponents/FormDynamicsIntegratorControl.vb#L318-L320

I didn't expect an error on this line, even if it is a conversion from double to int.

**Comment by AlexanderSemenyak** [comment]
On line 600 error - string to double without culture invariant (type casting error)

**Comment by DanWBR** [comment]
@AlexanderSemenyak this should suffice

https://github.com/DanWBR/dwsim/blob/e0ae1c3bdafc1420d792db110b8535ab113630e8/DWSIM/Forms/FlowsheetComponents/FormDynamicsIntegratorControl.vb#L601-L612

**Comment by AlexanderSemenyak** [comment]
> @AlexanderSemenyak this should suffice
            If Not Double.TryParse(var.PropertyValue, NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, y) Then
                y = Double.NaN
            End If

**Comment by DanWBR** [comment]
> > @AlexanderSemenyak this should suffice
> 
>             If Not Double.TryParse(var.PropertyValue, NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, y) Then
> 
>                 y = Double.NaN
> 
>             End If
> 
> 

The parsing will be successful regardless of the separator if it is a double

**Comment by AlexanderSemenyak** [comment]
> The parsing will be successful regardless of the separator if it is a double

If Double.TryParse(var.PropertyValue, New Double) - use current culture for parsing double from string var.PropertyValue

But [var.PropertyValue] is string and store value in Invariant Culture (always dot separator)
In some UI Cultures (with coma decimal separators) =>  Double.TryParse (without param InvariantCulture) not parse value  var.PropertyValue

**Comment by AlexanderSemenyak** [comment]
thank's
