### ISSUE TITLE
UNIFAC Qk parameter for CH3CO subgroup

### ISSUE THREAD

**Issue by FilipeAC** [DanWBR/dwsim6#372]
**Description**
The Qk parameter for CH3CO subgroup of the original UNIFAC method seems to be a little different from the published parameter at http://www.ddbst.com/published-parameters-unifac.html. DWSIM Qk value is 1.448 and DDB Qk value is 1.488, which gives different results for activity coefficients for some mixtures containing this subgroup. Rk value is the same from DDB. I'm not sure if this is a typo or the databank is not from Dortmund.

**To Reproduce**
The value was found on:

1. New Compound Creator Study
2. Molecular structure 
3. ID 19

**Comment by DanWBR** [comment]
@FilipeAC I guess it was a typo. The UNIFAC file was taken from ChemSep unchanged.

**Comment by FilipeAC** [comment]
Thanks for the quick reply! ChemSep v8.32 UNIFAC file now uses Qk = 1,488. Guess they found the typo. Is there a way to manually change this value on DWSIM?

**Comment by DanWBR** [comment]
it is already fixed: https://github.com/DanWBR/dwsim/commit/1b9c4859b3b5f282b81ff173299c8e7503d9c167
