### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by HMG69** [DanWBR/dwsim6#374]
The calculation of the thermal effect of a chemical reaction of the type NH3+HNO3=NH4NO3 taking place in an aqueous solution does not take into account the thermal effect (with heat consumption) of the release of HNO3 from the solution and the thermal effect of dissolution of the resulting NH4NO3 in an aqueous solution (with heat consumption). This conclusion is based on a comparison of the calculation results with real process indicators.

**Comment by DanWBR** [comment]
DWSIM doesn't have an appropriate model for this specific situation, sorry.

**Comment by HMG69** [comment]
This is a fairly simple model that is based on the properties of solutions.

**Comment by DanWBR** [comment]
> This is a fairly simple model that is based on the properties of solutions.

It isn't simple from a process simulator perspective, trust me.

**Comment by HMG69** [comment]
Возможно над этим вопросом стоит подумать в будущем. Тогда DWSIM будет идеальным инструментом.
