### ISSUE TITLE
[Enhancement] Desktop files for Linux 

### ISSUE THREAD

**Issue by einhander** [DanWBR/dwsim6#376]
Linux use `*.desktop` files to launch applications. Here the content of such file for dwsim and dwsim-classic:

Dwsim.desktop
```
[Desktop Entry]
Name=Dwsim Cross-Platform UI
Comment=Chemical Process Simulation for Everyone
Exec=dwsim
Icon=dwsim
Terminal=false
Type=Application
Categories=Education;
StartupNotify=false
```
Dwsim-classic.desktop
```
[Desktop Entry]
Name=Dwsim Classic UI
Comment=Chemical Process Simulation for Everyone Classic UI
Exec=dwsim-classic
Icon=dwsim-classic
Terminal=false
Type=Application
Categories=Education;
StartupNotify=false
```

Desktop files should be placed under `/usr/share/applications/` directory.
Appropriate icons should be placed under `/usr/share/pixmaps/` directory.

**Comment by DanWBR** [comment]
@einhander does this work on all debian-based distros?

**Comment by einhander** [comment]
> does this work on all debian-based distros?

Yes. More over it should work on 95% linux.

**Comment by einhander** [comment]
The desktop files that I provided it's only a brief version with necessary lines. Little more info about desktop files present in arch wiki https://wiki.archlinux.org/title/desktop_entries and xdg specs https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

**Comment by DanWBR** [comment]
I've updated the debian installer with the shortcuts.

<img width="1026" alt="Captura de Tela 2022-11-14 às 16 52 40" src="https://user-images.githubusercontent.com/2669419/201763485-0f16604f-8e7a-4355-8e00-10506cc1a1c9.png">

**Comment by einhander** [comment]
Great!
