### ISSUE TITLE
[Bug] Compound creator error

### ISSUE THREAD

**Issue by Doni-90** [DanWBR/dwsim6#389]
**Describe the bug**
Trying to create a new compound via "new compound creator study": 4-Cl-benzotrifluoride (CAS: 98-56-6). Using UNIFAC groups the molecular weight, formula and calculated data are wrong.

**To Reproduce**
1. Go to 'new compound creator study'
2. Compile name and CAS
3. Click on 'Molecular structure'
4. UNIFAC tab
5. Select ID10x4 + ID11x1 + ID54x1 + ID74x1
6. Check ID tab: MW and formula are wrong

I tryed to check the groups on DDBST "Original UNIFAC" but UNIFAC sub group are different from the ones in DWSIM (eg: "ACH" is ID10 in DWSIM, ID9 on DDBST "Original UNIFAC").
If I try to build the molecule via Modified UNIFAC (Dortmund) no data are calculated.

Extra: is not possible to sort by ID in "molecular structrure" tab.

**Expected behavior**
MW expected is 180.55 kg/kmol (188,23 calculated), normal boiling point expected 410K (600,77 K calculated) ...

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 8.3.2 64-bit WinUI

**Additional context**
https://pubchem.ncbi.nlm.nih.gov/compound/4-Chlorobenzotrifluoride#section=Canonical-SMILES

I've been able to succesfully create the molecule via wizard "create new with wizard" in home page.

**Comment by Greg66** [comment]
Hi,
i tried to reproduce this issue - there is no error! Calculated MW is 180,55 as expected when using the group IDs you mentioned. The selected groups in DWSIM correctly represent the molecule from SMILES code.

From UNIFAC groups the Joback groups are calculated automatically. Joback groups are used to calculate physical properties. With Modified UNIFAC this is not possible as some MODFAC-groups can not be represented with JOBACK groups.
p.s. you also can click the "CAS Numer"-Link in DWSIM ID-page to get to NIST-Webbook.

**Comment by Doni-90** [comment]
> 

Thank you Gregg66,
I tryed again to create the molecule and now it work properly. 
I tryed many times the day I opened this issues but it continuosly gave me the problem I listed (wrong MW and phisical proprieties), also trying to shut down DWSIM and restarting it...
Just as well! So sorry to bother ^_^
