### ISSUE TITLE
[Improvement] Fix number of digits after decimal point in numerical input and output

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#39]
**Describe the issue**
It is recommended to have certain number of digits after decimal point in displaying the results. One case is mole and mass fractions. 
**Expected behavior**
Use certain number of digits after decimal points for mole and mass fraction

**Screenshots**

**Fig 1. DWSIM**
![DWSIM_001](https://user-images.githubusercontent.com/830394/95469870-f6e3b680-0934-11eb-818e-85a6879cb9fa.png)

**Fig 2. Other simulator**
![AspenHysys_002](https://user-images.githubusercontent.com/830394/95469958-0f53d100-0935-11eb-9ea3-d2e721f7a624.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - DWSIM 6.2
 - Classic UI

**Additional context**
It may be useful to be able to set these numbers in general setting. Other simulator has this kind of setting for example see

**Fig 3. Sample setting for numerical results**
![AspenHysys_003](https://user-images.githubusercontent.com/830394/95469934-08c55980-0935-11eb-8e2e-1d53c1896800.png)

**Comment by DanWBR** [comment]
We have this already, but not for every property independently.

<img width="761" alt="Captura de Tela 2020-10-08 às 10 33 27" src="https://user-images.githubusercontent.com/2669419/95473676-5603f400-0952-11eb-9c67-a1d07c1316a9.png">
<img width="784" alt="Captura de Tela 2020-10-08 às 10 36 53" src="https://user-images.githubusercontent.com/2669419/95473692-5a301180-0952-11eb-9eea-4ab26e4fd9b0.png">

<img width="389" alt="Captura de Tela 2020-10-08 às 10 33 20" src="https://user-images.githubusercontent.com/2669419/95473643-4edce600-0952-11eb-9ff6-8a4e56e561d4.png">

**Comment by DanWBR** [comment]
https://docs.microsoft.com/en-US/dotnet/standard/base-types/standard-numeric-format-strings

**Comment by kookma** [comment]
Thank you Daniel. So, one can set number of digits after decimal point for mole/mass fractions per simulation! Can we have it also in general setting to have some default format for all simulations? I would also recommend similar formatting for some important properties like temperature, pressure, flows, ...
