### ISSUE TITLE
[Bug] Linux Crossplatform UI Master table edit crash

### ISSUE THREAD

**Issue by einhander** [DanWBR/dwsim6#394]
**Describe the bug**
Crash if double click master table

**To Reproduce**
1. Add Master table to flowsheet
2. Double click on it 
3. Crash with no debug output

**Expected behavior**
Edit Master table properties

**Desktop (please complete the following information):**
 - OS: Debian Testing 64-bt
 - Version 8.3.2

**Additional context**
See attache file for full launch with MONO_LOG_LEVEL=debug
[1.txt](https://github.com/DanWBR/dwsim/files/10135733/1.txt)

**Comment by DanWBR** [comment]
@einhander I couldn't reproduce the issue in Ubuntu. Could you please attach your Documents/DWSIM Application Data/errors.log in here?

**Comment by einhander** [comment]
The is no Documents/DWSIM Application Data folder. I have $HOME/DWSIM Application Data, but there is no errors.log there, only ini files and backup folder.

**Comment by DanWBR** [comment]
> The is no Documents/DWSIM Application Data folder. I have $HOME/DWSIM Application Data, but there is no errors.log there, only ini files and backup folder.

Ok, that is the correct folder. Do you have lasterror.txt on it?

**Comment by einhander** [comment]
> lasterror.txt

no

**Comment by DanWBR** [comment]
@einhander then it is a pure mono crash...

**Comment by einhander** [comment]
>pure mono crash...

I have gdb and valgrind installed, if you can provide an example command, I can  send you an output of this tools.
