### ISSUE TITLE
Specification block not updated / solved

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#395]
**Describe the bug**
When using specification block, these are not (always) updated with the solver.  Some are , some are not

**Expected behavior**
All specification blocks should update when solver is invoked

**Screenshots**
![image](https://user-images.githubusercontent.com/58475535/205584165-29f18ac4-2b98-428f-9424-a4f4b0bf31cb.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, 
 - Version [e.g. v8.32]

See attached file
[Hydrogen_density.zip](https://github.com/DanWBR/dwsim/files/10151910/Hydrogen_density.zip)

**Comment by DanWBR** [comment]
@andr1976 the spec is a **hack**. It is triggered **after** the source object is calculated. The final result will depend on the calculation order and how the specs are connected. I do not recommend using specs (I don't do it).

**Comment by andr1976** [comment]
Uhh, what a shame - I find this the only simple way of avoiding too many independent specs in a flowsheet

**Comment by andr1976** [comment]
I still think this is a bug since the behaviour is unpredictable and not as expected - with a specifier you actually expect the specification to be set after the solver has been called, but this is not always the case apparently.

**Comment by DanWBR** [comment]
> I still think this is a bug since the behaviour is unpredictable and not as expected - with a specifier you actually expect the specification to be set after the solver has been called, but this is not always the case apparently.

It depends. When I had the idea to add the spec, I thought that the user would want to set a property of an object far away and ahead of the source in a well-defined flowsheet but, of course, people are using the spec for everything you can imagine. Your sample is a total hack and unexpected use case, but I understand what you want to do.

Again, python scripts are perfectly suited for what you want but I also understand that you don't want to use them. 🙂

**Comment by DanWBR** [comment]
a script triggered after "1" finishes calculating would do the trick:

```
ms1 = Flowsheet.GetObject("1")
ms2 = Flowsheet.GetObject("2") 
ms3 = Flowsheet.GetObject("3") 
ms4 = Flowsheet.GetObject("4") 
ms5 = Flowsheet.GetObject("5") 

P = ms1.GetPressure()

ms2.SetPressure(P)
ms3.SetPressure(P)
ms4.SetPressure(P)
ms5.SetPressure(P)
```

**Comment by andr1976** [comment]
Ok I get your point, believe me I do want to use Python scripting :-)

**Comment by DanWBR** [comment]
@andr1976 I've added a new field to flowsheet settings, it should suit your needs.

<img width="1070" alt="Captura de Tela 2022-12-13 às 12 19 15" src="https://user-images.githubusercontent.com/2669419/207390893-c2f60514-b7f2-43a8-acf0-2fc6ac2c01fb.png">

**Comment by andr1976** [comment]
Wuhuuu, thats just awesome Daniel :-)

**Comment by andr1976** [comment]
Now I am just being greedy here, could something similar be applied to the spreadsheet, that any imported/exported properties are updated after the solver finishes, before a final solver run to ensure everything has been updated? I know this is a separate topic.

**Comment by DanWBR** [comment]
> Now I am just being greedy here, could something similar be applied to the spreadsheet, that any imported/exported properties are updated after the solver finishes, before a final solver run to ensure everything has been updated? I know this is a separate topic.

@andr1976 maybe, if you reconsider your recent patreon decision... 🧐 👀 you know I have a lot of DWSIM and non-DWSIM stuff to do.

**Comment by andr1976** [comment]
Or maybe just consider moving to DK and come work with me - we will do great things my friend, my ramblings and your ingenuity :-)

**Comment by DanWBR** [comment]
> Or maybe just consider moving to DK and come work with me - we will do great things my friend, my ramblings and your ingenuity :-) 

@andr1976 pay me 10K €/month and I'll be there ✈️🚀

**Comment by andr1976** [comment]
I don't see that option on Patreon, ah haha - maybe DM is better if we should continue this conversation :-)

**Comment by DanWBR** [comment]
> I don't see that option on Patreon, ah haha - maybe DM is better if we should continue this conversation :-) 

@andr1976 just kidding. I'll see what I can do about th spreadsheet 😄👍🏻
