### ISSUE TITLE
[Bug] Material stream mapper

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#396]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
Material stream mapper set to transfer / specify TP flash, but still PH flash used, thus source and target streams are forced to have the same specific enthalpy even for different EOS/fluid package, which is exactly what you wanted to avoid I my opinion 

**Expected behavior**
Program respected temperature and pressure and performed a PT flash instead of PH flash with specified enthalpy. Still PH flash is also an option. 

**Screenshots**
![image](https://user-images.githubusercontent.com/58475535/205657568-352c84ed-004a-4ad0-b65d-80fa16ec13f5.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, ]
 - Version [e.g. v8.3.2]

**Additional context**
See attached file

[Hydrogen_density_2.zip](https://github.com/DanWBR/dwsim/files/10154846/Hydrogen_density_2.zip)

**Comment by DanWBR** [comment]
@andr1976 actually I wanted to use the mapper to copy the stream composition and conditions - I didn't go specifically to that point

**Comment by andr1976** [comment]
It seems enthalpy is copied somehow, and that overrides temperature due to a PH flash maybe?

**Comment by DanWBR** [comment]
@andr1976 when there is a single compound, PH Flash takes precedence on any other spec, but there is a property that I can use to disable this. I'll close this issue because it is fixed and the source is in another closed repo.
