### ISSUE TITLE
Issue: Plug flow reactor and negative concentration

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#4]
OS: Windows 10
DWSIM: Version 6 update 7

To reproduce:

1. Open the attached simulation file in DWSIM 6 update 7
2. Change the feed flowrate from 3600 kg/h to 100 kg/h
3. DWSIM issues an error: "ODE solver calculated negative molar flows at volume step 0.041/1 m3"

It seems using low flowrate results in high residence time and then full consumption of main reactant hence results in negative values for component molar flow. One suggestion is to use Events in ODE solver to recognize when one of the reactant has been finished and then ODE Solver use zero for reaction rate!

**Another issue**

The reaction in this simulation is irreversible "N2+3H2 -> 2NH3" DWSIM strangely calculates conversion for NH3 as 1.30516E+13. 
The reaction rate is r=k*Ca where k=0.004 and the reverse reaction has been set to zero (both RO and A' and E')

----

Simulation file has been attached

[PFR-Ammonia Synthesis - Issue Report.zip](https://github.com/DanWBR/dwsim6/files/4964524/PFR-Ammonia.Synthesis.-.Issue.Report.zip)

**Comment by DanWBR** [comment]
Hi,

Since this is a modeling issue, could you please use the support forums and create a new post in there? GitHub issues is more suited for code compilation issues as very few people come here.

**Comment by DanWBR** [comment]
The ODE solver comes from another open source library (https://github.com/DanWBR/dwsim6/tree/windows/DWSIM.Math.DotNumerics/ODE). I've already had this problem in other situations. Can you attach the simulation file which leads to this error?

**Comment by kookma** [comment]
> Hi,
> 
> Since this is a modeling issue, could you please use the support forums and create a new post in there? GitHub issues is more suited for code compilation issues as very few people come here.

@DanWBR 
Do you mean the Sourceforge forum?

**Comment by kookma** [comment]
> you attach the simulation file

@DanWBR 
The original post (first one in this page) has the simulation file attached!

**Comment by DanWBR** [comment]
> > Hi,
> > Since this is a modeling issue, could you please use the support forums and create a new post in there? GitHub issues is more suited for code compilation issues as very few people come here.
> 
> @DanWBR
> Do you mean the Sourceforge forum?

Yes! It has more visibility than this page.
