### ISSUE TITLE
[Feature Request] Complex kinetics using Python script

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#40]
**Is your feature request related to a problem? Please describe.**
Adding complex kinetics and non standard reaction rate is impossible or error prone and tedious using the current Kinetics and Heterogeneous Kinetics interfaces.

**Describe the solution you'd like**
Use Python Scripts for complex kinetics as Kinetic script or Kinetic procedure or Advanced kinetic

**How to implement**

- Add new reaction from Reaction tab
- Use for current interfaces: Kinetic / Heterogenous Catalytic
- Complete the components and stoichiometry section
- Select between GUI / Advanced  or Kinetic Procedure or Kinetic Script or Advanced Kinetic
- Advanced Kinetic shall have its own new tab
- On selection an edit box let to enter the scripts

More details and supporting documents will be emailed.

**Comment by kookma** [comment]
Hi Daniel, I am eagerly looking forward for this feature! I am ready to help with test and evaluation once the feature is added!

**Comment by DanWBR** [comment]
<img width="399" alt="Captura de Tela 2020-11-20 às 15 19 41" src="https://user-images.githubusercontent.com/2669419/99841225-36144280-2b44-11eb-9952-3388fa6eec54.png">
<img width="644" alt="Captura de Tela 2020-11-20 às 15 19 53" src="https://user-images.githubusercontent.com/2669419/99841232-37de0600-2b44-11eb-8154-4e3a93f14776.png">
<img width="693" alt="Captura de Tela 2020-11-20 às 15 21 36" src="https://user-images.githubusercontent.com/2669419/99841236-39a7c980-2b44-11eb-948e-17c816b2443c.png">
<img width="410" alt="Captura de Tela 2020-11-20 às 15 21 42" src="https://user-images.githubusercontent.com/2669419/99841244-3b718d00-2b44-11eb-9553-8efe1be3b405.png">

**Comment by kookma** [comment]
Hi Daniel,
 Thank you! This is amazing! I know only Schlumberger Symmetry (VMGSim) has such a feature!

I like to give a try! If you push a new release I will go through details and will submit the result and comments.

**Comment by DanWBR** [comment]
Actually, you can access almost everything as there are other variables available like **Flowsheet**, **Reaction** and **Reactor**.

**Comment by kookma** [comment]
This is a great improvement in writing very complex multi step reactions for multi component - multi reactions system!

**Comment by kookma** [comment]
Hi Daniel,
 I have installed the new version and tried to implement a simple example like below
 CO + 1/2 O2 --> CO2

with r = 0.5 * R1

but I could not get any conversion. Would you please add an example to see how it works?

Thank you

**Comment by DanWBR** [comment]
@kookma can you attach your sim file?

**Comment by kookma** [comment]
Hi Daniel,

See attached file. I played and seems I could get a conversion in isothermal operation but failed in adiabatic mode! Seems the reaction set works and issue is because flash calculation.

By the way I would very pleased to receive any example by you and also I may recommend to add few examples to be distributed with DWSIM.

[test_rxn_python.zip](https://github.com/DanWBR/dwsim6/files/5579034/test_rxn_python.zip)

**Comment by DanWBR** [comment]
You're using the script exactly as expected, except that

- You've defined a Liquid-only reaction with non-condensable gases
- You're using a CSTR with a 100% vapor inlet stream.

**Comment by kookma** [comment]
Hi Daniel,

-  I modified the code by replacing the reactor with a PFR one
- I changed the reaction to be occurred in vapor/gas phase

I cannot get a converge! 

[test_rxn_python.zip](https://github.com/DanWBR/dwsim6/files/5579586/test_rxn_python.zip)

**Comment by kookma** [comment]
Hello again Daniel,
I understood the issue is with Plug Flow ODE solver. It seems it is a non-stiff ODE solver so for `r=0.5C` it cannot integrate the ODES. I changed `r` to `0.005C` and also implemented basic kinetic reaction and compared the two PFRS

- A PFR with simple kinetics `r=0.005Ca`
- A PFR with Python script for advances kinetics `r=0.005Ca`

No both converge, but the second at lower speed. You can check my third version of simulation.

[test_rxn_python_R03.zip](https://github.com/DanWBR/dwsim6/files/5579624/test_rxn_python_R03.zip)

**Comment by DanWBR** [comment]
Now both converge or don't? Using the script will be much slower because it is called a zillion times by the ode solver.

**Comment by kookma** [comment]
Daniel, well both of them converged! How we can improved this? 
The computation time is considerable!

**Comment by DanWBR** [comment]
There is some room for improvement. Stay tuned

**Comment by DanWBR** [comment]
Is there something that we could do about the issue with the ODE solver?

**Comment by kookma** [comment]
> Is there something that we could do about the issue with the ODE solver?

I have not good at VB.Net  so I did not understand how ODE solvers have been implemented, but I may have few suggestions:

1. If ODEsolver used in DWSIM is not a stiff solver then it will try to solve a stiff ODE by decrease the step size ans so computation takes more and if solver is called many times then we see a considerable computation time to solve a PFR
2. If DWSIM has stiff solver then item 1 is not correct here and may be having ode solver in VB.NET makes it slow

I think if DWSIM can use Python why not to use Scipy DLLs and use of robust solvers in SciPy? I also think we can use other libraries as DLL like Fortran ones which are very fast and then write a wrapper in VB.NET to able use them with minimum friction.

What do you think?

**Comment by DanWBR** [comment]
Using Scipy would be much, much slower. Also, about the fortran libs, it is hard to write the wrapper, and it may crash frequently.

DWSIM uses the DotNumerics library which contains these ODE solvers: http://www.dotnumerics.com/NumericalLibraries/DifferentialEquations/Default.aspx

Currently using **OdeImplicitRungeKutta5** in the PFR.

**Comment by kookma** [comment]
I have worked with Fortran and its reliable, but have no experience to write wrapper in VB.NET.
I will have a look at DotNumerics! But OdeImplicitRungeKutta5 is a good choice here.

**Comment by DanWBR** [comment]
The wrapper depends on the library. I've written many C++/Fortran wrappers for DWSIM already. It is the communication bridge between VB/C# and Fortran that is prone to crashes.

**Comment by AdrianDietz** [comment]
HI,

I do not know what the dotnumerics library is worth, looks like a translation to c# from fortran. I any case the reference for solving problems that requires numerical integration is the suite sundials with cvode that is written in c (https://computing.llnl.gov/projects/sundials). I have tested (comparing against their fortran equivalent) and used it in the past, I do not now whether the license is compatible with gpl.

Kind regards,

Adrian
