### ISSUE TITLE
[Bug] CoolProp Incompressible mixture not working with pressure changers

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#408]
**Describe the bug**
When an incompressible mixture is put thorugh a pressure changer the follwoing error occurs: 
<HTML>
<BODY>
<TABLE><TR><TD> </TD><TD>2</TD><TD>14/12/2022 14:05:29</TD><TD>Error</TD><TD>Error in '13': Error calculating saturation pressure at 321.471099529453 K for INCOMP::MEG[0.100015975560416] - CoolProp returned Psat = 0 Pa (PropertyPackage.vb, 2307)</TD><TD>+ Info</TD></TR></TABLE>

</BODY>
</HTML>
**To Reproduce**
See file

**Expected behavior**
Outlet stream calculated

**Screenshots**
![image](https://user-images.githubusercontent.com/58475535/207603453-47bedab9-9578-4f9a-b3b9-9dee16ef204a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, ]
 - Version [e.g. v8.3.X]

**Additional context**
See attached file 
[File1.zip](https://github.com/DanWBR/dwsim/files/10228039/File1.zip)

**Comment by DanWBR** [comment]
@andr1976 it seems to be a bug with CoolProp. I've tried to download its latest version but the shared library on SourceForge wasn't compiled with C# exports, so it doesn't work with DWSIM.

**Comment by DanWBR** [comment]
https://github.com/CoolProp/CoolProp/discussions/2208

**Comment by andr1976** [comment]
It seems CoolProp returns Psat (Q=0) as 0 also in latest version for MEG. Some incompressibles return a Psat and some 0, and some fail it seems
```
P = PropsSI('P','Q',0,'T',321,'INCOMP::MEG[0.100015975560416]')
```

**Comment by andr1976** [comment]
I have added a bug report, not really sure if this is by design or not 
https://github.com/CoolProp/CoolProp/issues/2209

**Comment by AlexanderSemenyak** [comment]
> [CoolProp/CoolProp#2208](https://github.com/CoolProp/CoolProp/discussions/2208)

Hi, Daniel! Try this build CoolProp 6.5.0 x64 with C# support.
[CoolProp6.5.0.zip](https://github.com/DanWBR/dwsim/files/11712066/CoolProp6.5.0.zip)
