### ISSUE TITLE
[IDEA] Number of Inlets / Outlets Ports

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#41]
In the current version some elements have more than one inlet port. For example separator has six inlet port (why six inlets?)
Mixer has six inlets while splitter has two outlet ports.

I may suggest

[1] Only keep the required inlet/outlet port for example separator can have one inlet. To do this few equipment needs modifying
[2] If it is required to have several inlet/outlet ports like mixer (inlet) and splitter (outlet), it would be great to be able to dynamically able to add new ports from UI. This is the case in Hysys for separator, mixer, splitter. But I think having one inlet port and using a mixer for several feed stream is preferred.

* DWSIM 6.2 update 4
* Classic UI
* Windows 10

**Comment by AdrianDietz** [comment]
I do not necessary agree on that, in practice one equipment can have more that one feed, even if temporary, secondly this feature allows adding a a mixer and the unnecessary additional flash computation, when doing RTO or even Dynamics you reduce as much as possibles flashes that bring up non useful information. I have seen model with up to 15 inlets in a separator. By the way the hysys interface is far from perfect, not the same for the engine that is one of the industry references.
My statement would rather be, please allow more than six..

**Comment by AdrianDietz** [comment]
I do not necessary agree on that, in practice one equipment can have more that one feed, even if temporary, secondly this feature allows adding a a mixer and the unnecessary additional flash computation, when doing RTO or even Dynamics you reduce as much as possibles flashes that bring up non useful information. I have seen model with up to 15 inlets in a separator. By the way the hysys interface is far from perfect, not the same for the engine that is one of the industry references.
My statement would rather be, please allow more than six..

**Comment by kookma** [comment]
@AdrianDietz I agree!

But what I mean is you can have minimum required input on the UI with an optional add extra inlet or outlet.

Now the UI is not tidy. Some unit ops have x inputs the other have y inputs. To have a more consistent UI we have to show semantic number of ports (this is the minimum) and then a button to add any number of ports as required.
