### ISSUE TITLE
Incompressible fluid PH flash with any PR EOS does not work

### ISSUE THREAD

**Issue by mohamedmovahed** [DanWBR/dwsim6#410]
Incompressible fluid PH flash with any PR EOS does not work. Returns error that compressibility factor can not be calculated. Was fine in previous versions.

**Comment by DanWBR** [comment]
@mohamedmovahed I need more details and a sample file, if possible.

**Comment by mohamedmovahed** [comment]
Hi Daniel,

Thanks for the prompt response. Two input files are attached for your
review.

   1. blanket gas_backup. As you can see , the simulation is converged in
   the previous DWSIM version (all blue). When I try to run it on the new
   version, it goes red downstream of the pump.
   2. The second file is also a simple MEG injection pump that doesn't
   converge.

MEG pumping is a standard stuff in the projects and PR78 is usually used to
calculate temperature rise downstream of the pump and spillback valve (MEG
has a negative JT coefficient). The results from the previous version of
DWSIM (8.3.2) matched the results of both HYSYS PR and PVTsim PR78
(Peneloux - HV). In the first file, you would also note that the phase for
the compressed MEG is shown as vapour, which is not correct.

Regards,
Mohamed

**Comment by DanWBR** [comment]
@mohamedmovahed please attach the file directly here using a browser and not by replying to the notification email. you need to zip the simulation file before uploading it.

**Comment by mohamedmovahed** [comment]
[Issue#410_Incompressible fluid PH Flash with PR EOS_Samples.zip](https://github.com/DanWBR/dwsim/files/10283412/Issue.410_Incompressible.fluid.PH.Flash.with.PR.EOS_Samples.zip)

**Comment by mohamedmovahed** [comment]
Here they are

**Comment by mohamedmovahed** [comment]
Done.

**Comment by DanWBR** [comment]
@mohamedmovahed thanks, I was able to find and fix the issue. It will work in the next release 👍🏻

**Comment by mohamedmovahed** [comment]
Thanks Daniel. May be a good idea to consider adding the SRK based CPA to your suite of EoS’. This has become pretty standard equation for water saturation, MEG and Methanol in gas-condensate production.
Merry Christmas and Happy New Year.
