### ISSUE TITLE
[Bug] "Excel spreadsheet reporting tool" crash

### ISSUE THREAD

**Issue by MichaelUBJ** [DanWBR/dwsim6#411]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
I have made a flowsheet with an equilibrium reactor. I want to export the data and figured that the plugin "Excel spreadsheet reporting tool" could do that. 

**To Reproduce**
Just click on the menu item under "plugins"

**Expected behavior**
I would expect a popup screen. I cant comment on expected behaviour as the program crashes

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 8.3.3

**Additional context**
I dont have excel installed on my Mac M1 but I have libreoffice.

**Comment by DanWBR** [comment]
@MichaelUBJ I've removed this tool from latest version as it is not supported anymore.
