### ISSUE TITLE
[Enhancement] Export possibility from Mac version

### ISSUE THREAD

**Issue by MichaelUBJ** [DanWBR/dwsim6#413]
**Is your feature request related to a problem? Please describe.**
The windows version of DWSIM has a possibility to export the results to XML. Can the same possibility be added to the Mac version? There is no other way to export data from the Mac version?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DanWBR** [comment]
@MichaelUBJ in the Results tab you have a handful of results exporting options:

<img width="1071" alt="Captura de Tela 2023-01-05 às 10 32 46" src="https://user-images.githubusercontent.com/2669419/210791841-b61eddc2-479d-4f62-87e0-cb2761497101.png">
