### ISSUE TITLE
[Bug] UNIFAC Parameter display error?

### ISSUE THREAD

**Issue by YW-chemeng** [DanWBR/dwsim6#415]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
properties package : UNIFAC 

Styrene’s UNIFAC group : ACH = 5, AC = 1, CH2=CH = 1
AMS’s UNIFAC group : CH3 = 1, ACH = 5, AC = 1, CH2=C = 1

I also check the UNIFAC groups in the Configure Property Package window.

AC is not shown in the Configure Property Package window.
And the ACH group’ count of both compounds is wrong.

Is group contribution method calculation done correctly?
It may be a display issue only. Please check.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/117691159/210476059-2af1b4a8-c6ad-44c4-a58b-1b585b819860.png)

![image](https://user-images.githubusercontent.com/117691159/210476089-58bd9dff-de7c-4005-9504-43920836cf60.png)

![image](https://user-images.githubusercontent.com/117691159/210476132-ae42ca64-50d2-474d-9b92-30b7399c26c6.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version v8.3.3

**Additional context**

**Comment by DanWBR** [comment]
This bug seems to be coming directly from ChemSep's compound database, which DWSIM uses without modifications. This is for styrene:

<img width="367" alt="Captura de Tela 2023-01-04 às 10 12 13" src="https://user-images.githubusercontent.com/2669419/210562530-96a9c013-cbb1-4d92-95b3-fb2c8501e744.png">

I believe that it should be 5, 9 and 10 instead of 5, 10 and 11 for UNIFAC. MODFAC seems ok.

Could you please contact ChemSep developers and report this error? http://www.chemsep.org/about.html

**Comment by YW-chemeng** [comment]
Thank you for your checking.
I understood Styrene UNIFAC Group incorrectlly imported from the ChemSep.
I also checked Styrene's UNIFAC Group count below.
I will contact ChemSep developers.
![image](https://user-images.githubusercontent.com/117691159/210705684-7730b9c8-8619-4832-a0ce-6750ad1780e5.png)


I have another concern. 

On DWSIM, there is a discrepancy between the count of UNIFAC group displayed in pure compound property window and the count of UNIFAC group displayed in the configure property package window. 
For example, styere's ACH count is 5 in the pure compound property window, but styrene' ACH count is 51 in the configure property package window.

I was wondering if there was a problem with the activity coefficinet calculation by UNIFAC on DWSIM. 

Or if it is a display problem in DWSIM, I would like you to fix the display to be fixed.

I hope you also check this concern.
Thank you.

**Comment by DanWBR** [comment]
@YW-chemeng it is showing correctly for me in the property package window. please check your decimal and thousands separators, if they are the same then DWSIM will not work correctly.

**Comment by YW-chemeng** [comment]
Thank you for your checking.
I am sorry. I was wrong. 
I understand that the UNIFAC parameters are displayed grouped by Main Group. I misunderstood that it was displayed for each Sub Group.
I checked that decimal and thousands separators is not same. 

Finally, an additional question.
Are the UNIFAC sub group id of DDBST and the UNIFAC id of DWSIM different number systems?
（I understand that DWSIM's UNIFAC id is equivalent to DDBST's UNIFAC sub group id.）

For example, UNIFAC ACH's sub group id in DDBST is "9" . UNIFAC ACH's id in DWSIM is "10".

Styrene's UNIFAC count in DWSIM may be correct. In my case, alpha-methylstyrene may be wrong because I used UNIFAC group count from DDBST directly.

![image](https://user-images.githubusercontent.com/117691159/210942772-a60b5a23-e65e-431b-a8a1-96f08ca72490.png)

![image](https://user-images.githubusercontent.com/117691159/210942981-3bab7ed7-622b-4b78-be9c-89bb7e8097cd.png)

![image](https://user-images.githubusercontent.com/117691159/210942923-bca30eeb-9e87-4b28-8ec3-7feaa81e4036.png)

Styrene's Modified UNIFAC group count in DWSIM may also be correct.

![image](https://user-images.githubusercontent.com/117691159/210943197-561673cb-9108-4f42-896f-078d3d1c9a29.png)

![image](https://user-images.githubusercontent.com/117691159/210943149-57d390a5-67b4-48e3-9258-087546ddf8f7.png)

![image](https://user-images.githubusercontent.com/117691159/210943106-7a50ba82-86a7-44f9-95d7-750a47de86cd.png)

**Comment by DanWBR** [comment]
@YW-chemeng this is the UNIFAC config file used by DWSIM. It was also taken from ChemSep. https://github.com/DanWBR/dwsim/blob/windows/DWSIM.Thermodynamics/Assets/unifac.txt

**Comment by YW-chemeng** [comment]
Thank you for information about UNIFC cofig used by DWSIM.
