### ISSUE TITLE
Phase envelope and hydrate curve not working with PR

### ISSUE THREAD

**Issue by mohamedmovahed** [DanWBR/dwsim6#416]
Phase envelope worked in the previous version (8.3.2). Sample file based on
[Phase Envelope and Hydrate Curve_Simple Hydrocarbon Mixture.zip](https://github.com/DanWBR/dwsim/files/10359011/Phase.Envelope.and.Hydrate.Curve_Simple.Hydrocarbon.Mixture.zip)
 a simple hydrocarbon mixture is attached.

**Comment by DanWBR** [comment]
@mohamedmovahed your case didn't work in v8.3.2 either... it is not handling water in the mixture - it got broken somewhere in the middle

**Comment by mohamedmovahed** [comment]
Thanks Daniel. Phase envelope doesn't appear to return sensible results on dry basis either. I have removed water from the simple mixture and you can see the results in the attached sample file.
Hydrate dissociation curve is a different matter, as it is function of water content when mixture is undersaturated with water
[Simple HC Mixture Dry Basis Phase Envelope & wet basis hydrate curve_PR78.zip](https://github.com/DanWBR/dwsim/files/10366044/Simple.HC.Mixture.Dry.Basis.Phase.Envelope.wet.basis.hydrate.curve_PR78.zip)
. Once water is included in the mixture, DWSIM does not converge on either hydrate curve or phase envelope.

**Comment by DanWBR** [comment]
@mohamedmovahed I'll have to work on this as soon as possible.

**Comment by mohamedmovahed** [comment]
Phase envelope still does not seem to work with any PR EoS variation, but works with SRK. See attached. The problem is that if phase envelope does not converge, then any flash with PR may not be reliable.
[Simple Dry HC Mixture Phase Envelope with PR.zip](https://github.com/DanWBR/dwsim/files/10578057/Simple.Dry.HC.Mixture.Phase.Envelope.with.PR.zip)

**Comment by DanWBR** [comment]
> Phase envelope still does not seem to work with any PR EoS variation, but works with SRK. See attached. The problem is that if phase envelope does not converge, then any flash with PR may not be reliable. [Simple Dry HC Mixture Phase Envelope with PR.zip](https://github.com/DanWBR/dwsim/files/10578057/Simple.Dry.HC.Mixture.Phase.Envelope.with.PR.zip)

@mohamedmovahed the problem, in this case, is in the critical point calculation. I'll take a look.

I'm sorry but your conclusion about the flash with PR is not correct. doing a single flash calculation is much simpler than building an entire phase envelope. there are many different procedures to build a phase envelope - I chose to calculate the critical point using a separate procedure and then use it as the endpoint for the dew and bubble curves. If you check your case with PR, you'll see that the curves were calculated correctly - they just didn't know where to stop:

<img width="701" alt="Captura de Tela 2023-02-03 às 08 24 19" src="https://user-images.githubusercontent.com/2669419/216603052-aa2bad2c-92a7-4452-bdca-1584857bad3e.png">

**Comment by mohamedmovahed** [comment]
Thanks very much Daniel for the clarification. I am somewhat familiar with theoretical basis for both density-based and volume-based phase envelope construction methods. I got the attached output, which probably if I reduced the pressure scale, I would get the same plot as yourself. However, as you can see in the plot in the attached file, the critical point is so off the mark that I assumed there is a convergence issue with K value or density calculations at very low vapour fraction (bubble point curve) or very low liquid fraction (dew point curve), and hence the comment regarding stability of flash calculations with PR. 
[Output.zip](https://github.com/DanWBR/dwsim/files/10579122/Output.zip)

**Comment by DanWBR** [comment]
@mohamedmovahed yes the CP is very off. The weird thing is that if you reduce the propane amount just a little bit it is able to calculate the correct CP.

The CP calculation is totally different from flash calculations... it is very prone to round-off errors, though I can put some fail-safe checks to avoid the issues we are discussing here. Here's the reference paper if you're interested: https://aiche.onlinelibrary.wiley.com/doi/abs/10.1002/aic.690260510

And here is my implementation: https://github.com/DanWBR/dwsim/blob/windows/DWSIM.Thermodynamics/PropertyPackages/Models/TrueCriticalPoint.vb#L31

**Comment by DanWBR** [comment]
Critical Point calculation added for PR78 and fixed for PR/SRK in https://github.com/DanWBR/dwsim/commit/b7dd0742368ab9dbdda345dad1c6876644178097

**Comment by mohamedmovahed** [comment]
Hi Daniel, 
Still struggling with phase envelope. It just doesn't run. See attached. I have used a simplified composition.
[Phase envelope_FPSO Simplified Export Gas.zip](https://github.com/DanWBR/dwsim/files/11010740/Phase.envelope_FPSO.Simplified.Export.Gas.zip)

**Comment by DanWBR** [comment]
@mohamedmovahed you have some customization options to play with:

<img width="1087" alt="Captura de Tela 2023-03-19 às 16 19 42" src="https://user-images.githubusercontent.com/2669419/226206709-4294c82c-9d1f-431b-864e-b56b1e719d8d.png">
