### ISSUE TITLE
Inert compound that reacts

### ISSUE THREAD

**Issue by mjparra** [DanWBR/dwsim6#418]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
There is a conversion reactor (isothermic).  One of the compounds is Nitrogen, it doesn't appear in any of the reactions, but in the outlet stream, Nitrogen is only 43% of the one that enter.
There is another issue: The heat load obtained is NaN, must it not be 0?

**To Reproduce**

**Expected behavior**
The amount of Nitrogen must be the same in the outlet stream.
The heat load must be zero, since is isothermic.
[issueN2.pdf](https://github.com/DanWBR/dwsim/files/10502642/issueN2.pdf)

**Screenshots**
![image](https://user-images.githubusercontent.com/123581700/214655691-457f423f-3802-4f1b-9f04-1f6458b2fa15.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS]
 - Version [e.g. v6.4.1]

**Additional context**

**Comment by mjparra** [comment]
The version I'm using is v8.3.4 for Windows.
The best way you can review the problem is sending the file from dwsim, but I didn't find how to send it.

**Comment by kookma** [comment]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).
There you can upload a zipped version of your DWSIM simulation

**Comment by DanWBR** [comment]
@mjparra you can zip the simulation file and drag it here to attach.

**Comment by mjparra** [comment]
I already post my question in sourceforge, according to a suggestion I
received.  But I attach the file here, this is a file that shows only the
part with the problem.

I appreciate ;your help.


Martha Parra

**Comment by mjparra** [comment]
When I check the third stream,that it must be zero, I found, that it appear
a very small negative number for mass flow, and  -infinite for molar flow,
then it is impossible to calculate heat load:

Master Property Table
Object 16 15 14
Temperature 577 577 577 C
Pressure 204.75 204.75 204.75 kPa
Mass Flow -3.35E-16 1.51069 1.51069 kg/h
Molar Flow #¿NOMBRE? 0.157284 0.0852586 kmol/h
Volumetric Flow 0 1.51E-20 2.94432 m3/h
Molecular Weight (Mixture) 0 9.60482 17.7189 kg/kmol
Specific Enthalpy (Mixture) 0 0 1520.04 kJ/kg
Molar Flow (Mixture)  /  Nitrogen NaN 0.00035446 0.00062562 kmol/h
Molar Flow (Mixture)  /  Hydrogen NaN 0.105696 0 kmol/h
Molar Flow (Mixture)  /  Water NaN 0 0.019428 kmol/h
Molar Flow (Mixture)  /  Carbon monoxide NaN 0.0359574 0 kmol/h
Molar Flow (Mixture)  /  Carbon dioxide NaN 0.00079934 0.00141083 kmol/h
Molar Flow (Mixture)  /  Methane NaN 0.0135867 0.0598689 kmol/h
Molar Flow (Mixture)  /  Ethane NaN 0.00084879 0.00374016 kmol/h
Molar Flow (Mixture)  /  Propane NaN 4.20E-05 0.00018513 kmol/h
Energy Flow 0 -1493.59 -2153.09 W

Martha Parra

**Comment by DanWBR** [comment]
@mjparra I've already fixed the issue, it was an error in the overall mass balance. https://github.com/DanWBR/dwsim/commit/aac6d31c1222d20e0dccfae7521fe231c019d3c7

it will work in the next update/version.

**Comment by mjparra** [comment]
I appreciate your dedication to solve the issue.  When can we get an update
on this topic?

Thanks a lot,

Martha Parra
