### ISSUE TITLE
Energy calculation in mixer

### ISSUE THREAD

**Issue by mjparra** [DanWBR/dwsim6#419]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
There is a mixer, where there are 3 inlet streams: water (L @ 25C), C7_lights (C1 to C7) (L @ 75C) and lightgas (V @ 25C). The oullet stream has a temperature of -181.7C, that it's not logical, considering the temperatures of the inlet streams.  There is a problem with the stream enthalpies, because when the energy flow of the mixer is calculated you get 1576 W, it must be zero.
Thermodynamic package PR adv.
**To Reproduce**

**Expected behavior**
Outlet temperature must be a positive value.  
Energy flow through the mixer must be zero.
**Screenshots**
![image](https://user-images.githubusercontent.com/123581700/215164837-b07c817a-f7cf-4a24-a038-3bfd88dd496b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version v8.3.4

**Additional context**

[issueMixer.zip](https://github.com/DanWBR/dwsim/files/10521998/issueMixer.zip)

**Comment by DanWBR** [comment]
@mjparra this is not a bug but rather a flowsheet misconfiguration: you set the global phase definition override to Vapor, forced the inlet stream phases to Liquid, Liquid and Vapor respectively, and left the mixed stream to "global definition", that is, vapor. If you leave everything as it is, without overrides, it will calculate the stream correctly.

the phase override is a "hack" for some very specific situations, you should not change that as stated in a message right below the selection box.

<img width="738" alt="Captura de Tela 2023-01-27 às 14 53 06" src="https://user-images.githubusercontent.com/2669419/215171265-e36bf2ac-79aa-42ca-8d3a-12cebafa349e.png">

**Comment by mjparra** [comment]
Thanks a lot for your quick response.  I thought I needed to force the fase
of each stream. I appreciate you take the time to explain me.
Martha Parra

**Comment by mjparra** [comment]
I appreciate if you let me know price to have dwsim pro, I haven't used it,
but I need to know its cost; since I could need it for a prospective
project to simulate several processes.

Best regards,


Martha Parra

**Comment by DanWBR** [comment]
@mjparra for more info about DWSIM Pro, please visit https://simulate365.com/landing-pages/dwsim-pro/
