### ISSUE TITLE
[Bug] NRTL parameter estimation seems random 

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#420]
**Describe the bug**
When using different estimation methods for the "Configure property package" screen, different results for A12/A21 are returned for each click. Maybe also relevant for UNIQUAQ etc. 

Also when using the data regression utility the interactiona paramters estimated differ from the ones in the property package configuration

**Expected behavior**
Same result each time

**Screenshots**
![image](https://user-images.githubusercontent.com/58475535/215338277-f9464c23-be0f-4881-9d9b-b4e4d1fa4929.png)

![image](https://user-images.githubusercontent.com/58475535/215338574-23a6def2-5b8b-42e5-9276-3c76897b08ae.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows,
 - Version [e.g. v8.3 latest]
[cooling_medium - Copy.zip](https://github.com/DanWBR/dwsim/files/10530200/cooling_medium.-.Copy.zip)

**Comment by DanWBR** [comment]
It is random, and not wrong, but I do recommend checking it with a binary envelope.

**Comment by andr1976** [comment]
The UNIFAC estimates look OK, even for different values. In the data regression utility the randomness is not present

**Comment by DanWBR** [comment]
The data regression uses a different and fixed path. These BIPs are naturally random, they don't have any theoretical background.

**Comment by andr1976** [comment]
So not a bug, a feature :-)
