### ISSUE TITLE
[Bug] Air cooler

### ISSUE THREAD

**Issue by HMG69** [DanWBR/dwsim6#421]
to calculate the air cooler, the values of the inner and outer diameter of the tubes must be entered in the source data menu for the tubes. but the program perceives the entered values as the total area of all the tubes. also, the value is not correct when entering the source data in the space between the tube parameter

**Comment by DanWBR** [comment]
@HMG69 can you help me help you by attaching a file or providing more information?

**Comment by HMG69** [comment]
Good afternoon, thank you for taking the time to consider my question.I have the following problem. In the "specify tube geometry" air cooler calculation mode, there is an error in the "tubes" menu in the order of setting the outer and inner diameter. I also see a problem with the units of measurement for the "tube spacing" parameter on the same tab. Отправлено из приложения "Почта" для Windows От: Daniel WagnerОтправлено: 18 февраля 2023 г. в 15:10Кому: DanWBR/dwsimКопия: HMG69; MentionТема: Re: [DanWBR/dwsim] [Bug] Air cooler (Issue ***@***.*** can you help me help you by attaching a file or providing more information?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
