### ISSUE TITLE
[Bug] Error in CoolProp PH flash 

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#422]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
Control valve / PH flash fails for CoolProp for pure CO2 (havent checked others) - enthalpy is not preserved. Results are right in python/CoolProp, giving -12 C after the PH flash from 30 to 1 bar. See screenshot and attached file 

**Expected behavior**
PH flash has same enthalpy before after flash

**Screenshots**
![image](https://user-images.githubusercontent.com/58475535/215997485-15faeac3-6b1c-4b0b-a862-ed8587919d9a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, ]
 - Version [e.g. v8.3.4]

[CoolProp Error.zip](https://github.com/DanWBR/dwsim/files/10555163/CoolProp.Error.zip)

**Comment by DanWBR** [comment]
@andr1976 CoolProp is telling DWSIM that the minimum pressure for CO2 is 517 kPa. CoolProp can be annoying at times, and is very good on making DWSIM look bad on the picture because it simply "works on Python"

<img width="641" alt="Captura de Tela 2023-02-01 às 10 34 22" src="https://user-images.githubusercontent.com/2669419/216072196-172c5d00-93a2-4102-a7a8-b3f4028ef20d.png">

**Comment by DanWBR** [comment]
"ApplicationException: For now, we don't support p [100000 Pa] below ptriple [517964 Pa] when T [196.256] is less than Tmin [216.592]"

**Comment by DanWBR** [comment]
CoolProp doesn't have continuity in the calculations. Everything has a narrow valid range. It is hard to work with this approach in the context of a process simulator.

**Comment by andr1976** [comment]
So it seems the VB interface behaves different from the python interface?

**Comment by DanWBR** [comment]
@andr1976 no, it has nothing to do with the interface, but rather with the calculation procedure.
