### ISSUE TITLE
[Bug]  PR-series EoS not working properly after 8.3.3

### ISSUE THREAD

**Issue by alberto-bueno** [DanWBR/dwsim6#426]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
I reported a bug were it was not possible to add the Kij to the PRSV2-M and PRSV2-ML, the follow up versions started showing the following  bug. 

Now in version 3.3.4 and 3.3.5 the PR-series EoS (at least) is not working properly throwing an error  "Unable to calculate compressibility factor..." and  "Collection was modified....".

**To Reproduce**
I am attaching two files saved with version 8.3.3 and 8.3.5. Just run the simulation. In version 8.3.3 it runs as expected but in 8.3.5 only works with PRSV2-M and PRSV2-ML.

[DWSIM_PR_Error.zip](https://github.com/DanWBR/dwsim/files/10667505/DWSIM_PR_Error.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 8.3.3 and 8.3.5

**Comment by DanWBR** [comment]
@alberto-bueno what happens if you remove all packages and re-add them?

**Comment by alberto-bueno** [comment]
Same behavior. Starting from scratch (New File) behaves also the same.

**Comment by DanWBR** [comment]
@alberto-bueno it works here. Can you repeat the process and send me the file?

**Comment by alberto-bueno** [comment]
@DanWBR  I unistall DWSIM 8.3.5 and reinstall it and now is working...... Sorry the false bug.
