### ISSUE TITLE
[Build the solution] 

### ISSUE THREAD

**Issue by 44East** [DanWBR/dwsim6#428]
Hi, I ran into a problem compiling a solution.
I do everything according to the instructions and consistently get 5 errors in the build solution, below will be a screenshot.
I used the .NET Framework 4.8 and 4.6.2/4.6.1
VS19 and VS22, and always get the same result.
Compilation Configurations I Choose
Debug/X64, DebugNoNPM/64
![2023-02-09_17-43-43](https://user-images.githubusercontent.com/102745770/217847139-f8b17ae8-cae4-4b70-8371-325948d5f98c.png)

**Comment by DanWBR** [comment]
@44East can you attach the full build log?

**Comment by 44East** [comment]
> @44East can you attach the full build log?

Yep!
[Output-Build.txt](https://github.com/DanWBR/dwsim/files/10699471/Output-Build.txt)

**Comment by DanWBR** [comment]
@44East try again please

**Comment by 44East** [comment]
> @44East try again please

When I builded the solution, I received new problems, but the App started!

![image](https://user-images.githubusercontent.com/102745770/217913007-c4081dc8-88e4-4610-9765-b338240c510b.png)


[Output-Debug.txt](https://github.com/DanWBR/dwsim/files/10700666/Output-Debug.txt)
