### ISSUE TITLE
Allow INDICATORS in DWSIM to report values in %, not just fractions.

### ISSUE THREAD

**Issue by bonzoboy2000** [DanWBR/dwsim6#43]
**Is your feature request related to a problem? Please describe.**
All of the quantitative data (for gaseous species) are limited to presentation in molar or mass fractions.  In some cases, such as the concentrations of gases, providing the data in vol% is very helpful.

**Describe the solution you'd like**
As an option, the INDICATORS provided in DWSIM should allow for display values in the % range (mole fraction * 100).  This is much more consistent with what operators see on an instrument cluster

**Describe alternatives you've considered**
None.  I just have to realize that the values on the display are molar fractions, instead of volume %.

**Additional context**

**Comment by DanWBR** [comment]
<img width="997" alt="Captura de Tela 2020-10-30 às 14 00 14" src="https://user-images.githubusercontent.com/2669419/97741016-7e49c300-1ab8-11eb-8ac0-e4efd160a66e.png">

**Comment by DanWBR** [comment]
Is this ok, Bruce?

**Comment by bonzoboy2000** [comment]
That looks great
