### ISSUE TITLE
[Bug]  v8.3.5 Spreadsheet with IronPython raises: Cross-thread operation not valid

### ISSUE THREAD

**Issue by alberto-bueno** [DanWBR/dwsim6#431]
**Describe the bug**
When trying to interact with Spreadsheet with the Interactive IronPython Console or Script manager with certain function raises the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: Cross-thread operation not valid: Control '' accessed from a thread other than the thread it was created on.

This happens when the Spreadsheet.CreateWorksheet or Spreadsheet.RemoveWorksheet are used. All other methods such as Name, AddWorkSheet, SetCellData, etc work fine.

An important observation is that it works in a cyclic pattern in both the Interactive Console and the Script Manager.  For example 10 calls work perfectly and the following 5 the error message appears.

The error is more prone to appear when you navigate from tab to tab or these calls are part of a larger code.

**To Reproduce**
1. Open Interactive IronPython Console
2. Write the following:
      Spreadsheet.CreateWorksheet()
      or
     Spreadsheet.RemoveWorksheet(sheet_idx)

   Also tried by first importing:
   import DWSIM
   from System import Array

5. See error

**Expected behavior**
Return of a sheet instance or bool message.

**Screenshots
Interactive Console (Hitting enter every 2 seconds)
![image](https://user-images.githubusercontent.com/26026514/219499075-204cfd31-f859-4bcb-8b3a-4b20295b9750.png)

Script Manager (Running Async every 2 seconds) Look a the error timestamps.
![image](https://user-images.githubusercontent.com/26026514/219499757-e9409152-1ead-4ce9-af55-5d4b6b94bf22.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version Classic UI v.8.3.5

**Comment by DanWBR** [comment]
This is not a bug. IronPython scripts run in a different thread. If you're accessing GUI objects then you should use Flowsheet.RunCodeOnUIThread():

`Flowsheet.RunCodeOnUIThread(lambda: Spreadsheet.CreateWorksheet())`

**Comment by alberto-bueno** [comment]
Understood. I will post this info in the forum so other people can find it easier.
