### ISSUE TITLE
data from python is changed in dwsim 

### ISSUE THREAD

**Issue by mjparra** [DanWBR/dwsim6#435]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
For the simulation of methanation, the data of mole fraction calculated with Python script is transfered correctly to the outlet, but the values of mole flow and mass flow are different.

**To Reproduce**
1. Go to attached file
2. Check the python script & the results
3. See error in mass flow and mole flow.

**Expected behavior**
Mole flow 3.9775 kmol/h (vs 14.319 kmol/h)
Mass flow must be the same as the feed's.

**Screenshots**
![image](https://user-images.githubusercontent.com/123581700/221094128-de724630-3fd1-4a52-b026-1255addded2c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version 8.3.5

**Additional context**
[metanacion1.zip](https://github.com/DanWBR/dwsim/files/10820735/metanacion1.zip)

**Comment by DanWBR** [comment]
@mjparra this is not a bug. your script is not correct. you must set the composition vector in the same order as the components appear in the material stream editor and set the overall molar flow in mol/s, not kmol/h.
