### ISSUE TITLE
Programme miscalculating power load on compressor 

### ISSUE THREAD

**Issue by kushnubian** [DanWBR/dwsim6#44]
Simulator is calculating power demand for a pure CO2 using SRK to be 74kW at 70% adiabatic efficiency. Inlet conditions: 60C , 1 atm, pressure increased by 10 bar. This is different from the 65kWe calculated before the update and the result from alternative process simulators
[201030-CO2_compressor.zip](https://github.com/DanWBR/dwsim6/files/5478674/201030-CO2_compressor.zip)

**Comment by DanWBR** [comment]
DWSIM is giving a very similar result to COCO/COFE, it doesn't seem to be wrong:

<img width="1009" alt="Captura de Tela 2020-11-02 às 20 32 08" src="https://user-images.githubusercontent.com/2669419/97933991-bec06f80-1d4a-11eb-9168-e0822006c873.png">
<img width="1356" alt="Captura de Tela 2020-11-02 às 20 33 01" src="https://user-images.githubusercontent.com/2669419/97933997-c3852380-1d4a-11eb-9fad-bb1f813d9540.png">

<img width="944" alt="Captura de Tela 2020-11-02 às 20 35 23" src="https://user-images.githubusercontent.com/2669419/97934240-89685180-1d4b-11eb-88d4-02767dd97b96.png">
<img width="886" alt="Captura de Tela 2020-11-02 às 20 39 27" src="https://user-images.githubusercontent.com/2669419/97934281-9edd7b80-1d4b-11eb-9144-c456902a030f.png">

**Comment by DanWBR** [comment]
[201030-CO2_compressor.dwxmz.zip](https://github.com/DanWBR/dwsim6/files/5478736/201030-CO2_compressor.dwxmz.zip)
[co2compression.fsd.zip](https://github.com/DanWBR/dwsim6/files/5478737/co2compression.fsd.zip)

**Comment by kushnubian** [comment]
I compared simulation to ChemCad because the result had changed with the latest update. The ChemCad Simulation result is very similar to the DWSIM result before the latest update over the weekend. 

![CO2 Chemcad sim](https://user-images.githubusercontent.com/73860047/97959363-1c82a500-1da7-11eb-90a7-4ba60c3366bf.jpeg)

**Comment by andr1976** [comment]
Using the same input as Daniel in HYSYS I get more or less similar results to DWSIM. Chemcad must be wrong :-) 

![image](https://user-images.githubusercontent.com/58475535/98646160-44d44b80-2333-11eb-9b14-80b275e9f22c.png)

**Comment by kushnubian** [comment]
Apparently so. Thank you
