### ISSUE TITLE
[Bug] Large temperature drop across splitter.

### ISSUE THREAD

**Issue by artsinli** [DanWBR/dwsim6#446]
**Describe the bug**
Large temperature drop across splitter.

**To Reproduce**
1. Create a splitter with the CoolProp package
2. I set my temperature to 34.9 Celcius and 3.01 bar pressure
3. Splitter temperature should be around -17 Celcius

**Expected behavior**
The temperature and phase should stay constant across the splitter as per v8.3.4

**Screenshots**
![image](https://user-images.githubusercontent.com/30050694/225386700-4c4770e0-a796-4298-8900-65c3c8f812ad.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version v8.4.1

**Comment by DanWBR** [comment]
@artsinli please attach the flowsheet file

**Comment by artsinli** [comment]
@DanWBR 
[Splitter Bug.zip](https://github.com/DanWBR/dwsim/files/10983068/Splitter.Bug.zip)
