### ISSUE TITLE
Flash calculation gives spurious results

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#45]
DWSIM 6.3u3 Windows 10 x64
Flash calculation returns spurious phase split with water present

**Steps to reproduce the behavior:**
1. Include components. Water, Methane, Propane, i-Butane, N-butane, N-decane, molefrac: 0.2,0.2,0.1,0.1,0.1,0.3
2. Set stream T=94 C
3. Set stream P= 25 bar
4. Inspect results and observe that only gas phase exists. 

**Expected behavior**
Expected to see vapour, liquid1, and Liquid2 phase, with approx. phasefraction 0.2 (slightly less) of liquid2 as water 
However, when water is reduced and methane increased first a split into vapour, liquid1 and then to vapour, liq1, liq2 and molefrac water of 0.1 and methane molefrac 0.3

[flashtest - Copy.zip](https://github.com/DanWBR/dwsim6/files/5507095/flashtest.-.Copy.zip)

**Additional context**
Attached is DWSIm file and the expected output from a 3-phase flash (free water) by Michelsen
![2020-11-08_21-17-21](https://user-images.githubusercontent.com/58475535/98483352-e0689d80-2207-11eb-8d12-0247d693ff66.png)

**Comment by DanWBR** [comment]
I've got this with a simulation created by me:

<img width="537" alt="Captura de Tela 2020-11-08 às 18 00 12" src="https://user-images.githubusercontent.com/2669419/98485399-84445000-21ec-11eb-848d-53bc0780035e.png">

Your sim file before running

<img width="512" alt="Captura de Tela 2020-11-08 às 18 01 33" src="https://user-images.githubusercontent.com/2669419/98485410-8efee500-21ec-11eb-8c6f-0c6f014d9195.png">

And after running it here

<img width="551" alt="Captura de Tela 2020-11-08 às 18 01 45" src="https://user-images.githubusercontent.com/2669419/98485414-94f4c600-21ec-11eb-9ade-155083783657.png">

Perhaps you're having issues with IPOPT?

**Comment by andr1976** [comment]
Just installed DWSIM 6.3u3 ipopt is certainly in the install folder. Hmmm, thats strange, then again when the water is reduced, suddenly the calculation shows a pahse split. I am not sure how I can investigate this, any good hints?

**Comment by DanWBR** [comment]
It seems that when IPOPT doesn't work as expected, the calculation still goes on and returns a result while it should throw an exception and break the calculation. I wasn't expecting that. Investigating as we chat.

**Comment by andr1976** [comment]
Great

**Comment by DanWBR** [comment]
Fixed in DTL v6.3.7617. You must copy the two IPOPT files to Windows\System32, at least for now. The definitive fix for DWSIM will be in v6.3 Update 4. https://github.com/DanWBR/dwsim6/commit/44dbfdacfedbaa0a64eb89e2d758ee16995be6df and https://github.com/DanWBR/dwsim6/commit/e3598d1e79b99b52661853c3574448b51176e5d4

**Comment by andr1976** [comment]
Now for the above example I get similar results as you - now when lowering water moelfrac to 0.1 and increasing methane to 0.3, I get an all vapour phase (expected VLLE, withh all three phases present)

**Comment by DanWBR** [comment]
> The definitive fix for DWSIM will be in v6.3 Update 4.

👆🏻

**Comment by andr1976** [comment]
Just trying again with DWSIM 6.3 update 4 with the following composition again: 
Include components. Water, Methane, Propane, i-Butane, N-butane, N-decane, molefrac: 0.1,0.3,0.1,0.1,0.1,0.3 it gives three phases but still spurious: 2nd liquid phase is containing water but only 6%, rest is to a large extent methane 
 
![image](https://user-images.githubusercontent.com/58475535/100116754-66295180-2e74-11eb-8f68-a9ca846660aa.png)

When stability test under flash is ticked, then a single liquid phase is returned.

![image](https://user-images.githubusercontent.com/58475535/100117048-b7394580-2e74-11eb-8252-0da977df50c8.png)

**Comment by andr1976** [comment]
Here is my file 
[flashtest2.zip](https://github.com/DanWBR/dwsim6/files/5591048/flashtest2.zip)

**Comment by DanWBR** [comment]
The algorithm is having difficulties determining if the phase is vapor or liquid because the cubic equation is giving only one root at the specified conditions...

**Comment by DanWBR** [comment]
I've messed up the flash algorithm in this update. Sorry about that. Already fixed it. https://github.com/DanWBR/dwsim6/commit/1e61d2b37c927b6b3bf20c6a82791774f61e9e45

**Comment by andr1976** [comment]
Blazingly fast .. did you update the version included with the installer also?

**Comment by DanWBR** [comment]
Not yet, working on other parts of the simulator

**Comment by andr1976** [comment]
I just ran a check with v6.3 update 5 
include components. Water, Methane, Propane, i-Butane, N-butane, N-decane, molefrac: 0.1,0.3,0.1,0.1,0.1,0.3 
The mix split to V-L, but a 2 liquid/water should exist i.e VLL. The flash fails to find the 2. liquid phase. 

![image](https://user-images.githubusercontent.com/58475535/100349411-b3c6cb00-2fe8-11eb-9107-4b1e82370eab.png)

Another thing: I have generally notices that when a separate water phase/liquid2 is found, the amount of water is generally higher than expected in the HC/liquid1 phase. Just a consideration.

**Comment by DanWBR** [comment]
> Another thing: I have generally notices that when a separate water phase/liquid2 is found, the amount of water is generally higher than expected in the HC/liquid1 phase. Just a consideration.

This can be adjusted with a BIP. DWSIM doesn't use any while HYSYS uses 0.5, for instance. I have no bibliographic reference for doing that so I left it as it is.

**Comment by andr1976** [comment]
Yeah, already tried that with no significant change in the behaviour

**Comment by andr1976** [comment]
Ok, this has certainly done some good. Compiled from source and I now get a phase split as expected (at least using my own/HYSYS BIPs for all compunds), Setting water BIPs to 0.5 does not get me there, the HC-HC BIPs also need to be altered. Not sure all are necessary.  - However, there is still some perculiar behaviour. 

For instance if setting the BIP for i/n-butane to zero, there is suddenly no liquid2/water phase after recalculating flowsheet (actually after a few recalcs). Ressetting this BIP may then result in a water phase, sometimes, sometimes not. Then changing the temp down and up may enable the phase in being identified. 
First, I would not expect the iso/n-butane BIP to any effect in a water phase or not (also confirmed by my Michelsen Flash), secondly it seems that updated BIPs are not always re-read. I am still setting things up, in terms of debugging, and navigating the code, but if this can give you some hints, that would be great

[flashtest.zip](https://github.com/DanWBR/dwsim6/files/5605002/flashtest.zip)

**Comment by andr1976** [comment]
Very very strange - if setting flash to force VLLE, then every second time called the liquid2 phase is there, and then its not. 

![image](https://user-images.githubusercontent.com/58475535/100393218-3e371b00-3039-11eb-9d21-d0fb4ba71a45.png)

I am not sure I am doing this right, but when inspecting the PP.MAT_KIJ is Nothing, both for the Universal flash and VLLE, everytime I look, still this does not fully explain the on/off behaviour

**Comment by andr1976** [comment]
Every second time the StabTest2(T, P, Vx1, PP.RET_VTC, PP) returns 0

**Comment by DanWBR** [comment]
Maybe because the trial compositions are random. I think we need to include a fixed set of trial compositions to make sure that one gets caught.

**Comment by andr1976** [comment]
Trial compositions?

**Comment by DanWBR** [comment]
Yes, the compositions to test for stability of the liquid phase. The current composition may not be unstable so we need to try different ones until we find one which is unstable, in order to get an initial estimate for the composition of the second liquid phase.

**Comment by DanWBR** [comment]
This is Michelsen's stability test.

**Comment by andr1976** [comment]
Much better now, testing your commit from yesterday - at least testing 10-30 repetitive flash recalcs, and get the same phasesplit everytime

**Comment by DanWBR** [comment]
Changed the random number generator to get a wider range of compositions. 

Random number generation is an art itself.

**Comment by andr1976** [comment]
@DanWBR should this one be closed now? or are you still working on this?

**Comment by DanWBR** [comment]
Will you do further testing?

**Comment by andr1976** [comment]
No not at the moment - over time one could think of a broad test case with varying compositions and properties. I might open at a later stage if I run into issues. What I have seen for now seems promising
