### ISSUE TITLE
[Bug] Overriding enthalpy calculation breaks heat exhcanger calculations routine

### ISSUE THREAD

**Issue by alberto-bueno** [DanWBR/dwsim6#450]
**Describe the bug**
When overriding enthalpy or K calculation routines using a custom script the unit operation heat exchanger cannot be calculated. Removing the override script solves the problem.

**To Reproduce**

Starting from the example: Peng-Robinson EOS Fugacity and Enthalpy override, add a heat exchanger and add three materials streams to populate all the ports.

1. Run the simulation
2. See error:  'HX-1' Object reference not set to an instance  of an object

**Expected behavior**
When overriding enthalpy or K functions the heat exchanger routine should be calculated successfully.

**Desktop (please complete the following information):**
 - OS: Windows11
 - Version 8.3.5 and 8.4.2
[Peng-Robinson EOS Fugacity and Enthalpy Override w HE.zip](https://github.com/DanWBR/dwsim/files/11029412/Peng-Robinson.EOS.Fugacity.and.Enthalpy.Override.w.HE.zip)

**Comment by alberto-bueno** [comment]
The error originates in DWSIM.UnitOperations.HeatExchange Lines 1307 and 1322:

`tmpstr.PropertyPackage = StInHot.PropertyPackage.Clone`
`tmpstr.PropertyPackage = StInCold.PropertyPackage.Clone`

When PropertyPackage is cloned the `OverrideEnthalpyCalculation = True` is cloned succesfully but not the function to override it, raising an error of no object instantiated.

Of course not clonning the PropertyPackage solves the problem but then the PropertyPackage of both the cold and hot streams and the PropertyPackage of the tmpstr are the same object.

I tried adding the function after cloning as:
`tmpstr.PropertyPackage.EnthalpyCalculationOverride = StInHot.PropertyPackage.EnthalpyCalculationOverride`
The problem is the same, the object is not initialized!

**Comment by DanWBR** [comment]
fixed in https://github.com/DanWBR/dwsim/commit/0e1adf2e06db943c72b7428d9cb9ed58de5dde41
