### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by eliasjr70** [DanWBR/dwsim6#451]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
Specific enthalpy/entropy calculations result in Nan with PRSV2-VL

**To Reproduce**
1. Create a steady-state simulation with Carbon Dioxide as single compound
2. Select Peng-Robinson-Stryjek-Vera 2 (PRSV2-VL) equation of state as thermodynamic model
3. Create a material stream and run the simulation
4. See error in Specific Enthalpy and Specific Entropy calculations

**Expected behavior**
Any other equation of state display numeric values.

**Desktop (please complete the following information):**
 - OS: MS Windows 10
 - Version 8.4.2.

**Additional context**
The problem was absent in DWSim 8.3.4.
Please see attached file and image.
![image](https://user-images.githubusercontent.com/79600458/226728720-11d98f13-d69a-4c8f-8265-d86925e8f6de.png)

**Comment by DanWBR** [comment]
[Peng-Robinson EOS Fugacity and Enthalpy Override w HE - next.zip](https://github.com/DanWBR/dwsim/files/11055307/Peng-Robinson.EOS.Fugacity.and.Enthalpy.Override.w.HE.-.next.zip)

you'll need to run this updated script when the next DWSIM version is released.
