### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by HMG69** [DanWBR/dwsim6#456]
for the heat exchanger model, an error occurs in the properties output table with the dimension of the parameters (the dimensions of the casing and pipes). In the property table, the values are increased by 1000 times. It is also necessary to check the correctness of the calculation of the flow volume in the pipes and shell
![problem heat exchanger](https://user-images.githubusercontent.com/117921346/230005480-275316ea-4f36-4100-960e-3ae3ba58a551.jpg)

**Comment by DanWBR** [comment]
@HMG69 why do you think that the flow calculations are wrong? Do you have any flowsheet and/or experimental data that I could check?
