### ISSUE TITLE
v8.4.3 MacOS freezes

### ISSUE THREAD

**Issue by jkittrell** [DanWBR/dwsim6#458]
Installed v8.4.3 MacOS version today on two computers, app seems to freeze upon any screen click, have to Force Quit.  Portion of error report below.  If there is another section more helpful, lemme know and I'll forward.  Thx

Date/Time:        2023-04-10 18:34:14.434 -0500
End time:         2023-04-10 18:38:27.381 -0500
OS Version:       macOS 13.3 (Build 22E252)
Architecture:     arm64e
Report Version:   40
Incident Identifier: 2D983504-537D-487E-94CB-B1A89A97AB53

Data Source:      Stackshots
Shared Cache:     581A6955-D455-3735-973B-5233BD5DD16E slid base address 0x1941f8000, slide 0x141f8000 (System Primary)
Shared Cache:     4056C3C5-5FF8-380B-89E4-5EB59DAB70B2 slid base address 0x19ea38000, slide 0x1ea38000 (DriverKit)
Shared Cache:     D56E3916-43B7-3708-AA0A-46B8D0B0441C slid base address 0x7ff80a91c000, slide 0xa91c000 (Rosetta)

Command:          Launcher.exec
Path:             /Applications/DWSIM.app/Contents/MacOS/Launcher.exec
Identifier:       com.danielmedeiros.dwsim
Version:          8.4.3 (1)
Team ID:          UDCRF4S539
Is First Party:   No
Architecture:     x86_64 (translated)
Parent:           launchd [1]
PID:              803
Time Since Fork:  280s

Event:            hang
Duration:         252.95s
Duration Sampled: 2.00s (process was unresponsive for 251 seconds before sampling)
Steps:            20 (100ms sampling interval)

Hardware model:   Macmini9,1
Active cpus:      8
HW page size:     16384
VM page size:     16384

Time Since Boot:  1322s
Time Awake Since Boot: 760s
Time Since Wake:  133s

**Desktop (please complete the following information):**
 - OS: macOS v13.3

**Comment by DanWBR** [comment]
@jkittrell I couldn't reproduce this issue, probably because I have an Intel MacBook Pro...

please open a terminal window and run this command - you'll have to adjust the path depending on where you put the app:

`DWSIM.app/Contents/MacOS/Launcher.exec
`

See if you can get a hint about the reason why it is freezing. Hopefully you'll see some text regarding an exception on the terminal.

**Comment by jkittrell** [comment]
Thx, Terminal session attached.  DWSIM opens fine, simulations open fine, appears the hangup occurs when selecting an object for editing on flowsheet, e.g. material stream.  It took upwards of 5mins for the object to appear in editor screen with mac color wheel in play during that time. Force Quit shows app as not responding.  I don't see any activity in the terminal session while this was occurring though.  Same behavior on two machines with different hardware:
MacMini on Apple M1 chip / MacOS 13.3
MacBook Air on Intel i5 chip / MacOS 11.7.4
[DWSIM 8.4.3 Terminal Session.pdf](https://github.com/DanWBR/dwsim/files/11200941/DWSIM.8.4.3.Terminal.Session.pdf)

**Comment by DanWBR** [comment]
weird. try this, let's go a little deeper.

`MONO_LOG_LEVEL=debug DWSIM.app/Contents/MacOS/Launcher.exec`

**Comment by jkittrell** [comment]
oooh, that got bit.  I selected an object from within a flow sheet and it kept writing to the log, hoping something was repeating you can spot.  Attaching 1st 15pages, i killed the process but it goes on and on
[DWSIM Debug.pdf](https://github.com/DanWBR/dwsim/files/11202245/DWSIM.Debug.pdf)

**Comment by DanWBR** [comment]
@jkittrell can you try 8.4.2 or an earlier version to see what happens?

**Comment by jkittrell** [comment]
sure, it was running fine under 8.3.1 so I went back to that version, no issues.  8.3.2,.3,.4 all work with no issues.  Seems to be a change at 8.3.5, application opens but opening a simulation hangs up.  Tried 8.4.0 as well, no improvement.

**Comment by DanWBR** [comment]
@jkittrell can you send me the flowsheet that you were trying to work with?

**Comment by jkittrell** [comment]
several behaving similarly, but try this one, thx
[iCARD_THF_recycle.dwxmz.zip](https://github.com/DanWBR/dwsim/files/11279049/iCARD_THF_recycle.dwxmz.zip)

**Comment by DanWBR** [comment]
@jkittrell thanks for the file. I was able to reproduce the issue. What is happening is that NRTL is trying to estimate missing binary interaction parameters and that is taking longer than expected. I also forgot to add an option to disable this feature in the macOS version, sorry about that. in the meantime you can remove NRTL/UNIQUAC from your simulation and use Modified UNIFAC, it should work.

I'll get this right in the next update. Thanks!

**Comment by jkittrell** [comment]
Super, appreciate that!  So i've reinstalled 8.4.3 and confirm that removal of NRTL and replaced by Modifed UNIFAC (NIST) eliminated slow response time issue.  Reran sim but hit a new "Error calculating excess enthalpy from activity coefficients. If this error persists, try changing the Enthalpy Calculation Mode in Property Package settings".  Selected a different simulation, also based on NRTL and previously solving in earlier versions, leaving thermo property unchanged and got the same excess enthalpy error.  Is there something else perhaps in the thermo package settings i'm now hitting?

**Comment by DanWBR** [comment]
@jkittrell yes... in the current version, by default liquid phase enthalpy is calculated based on an excess term which is, in turn, calculated from activity coefficients. you can change this behavior in the property package settings.

**Comment by jkittrell** [comment]
ok, very good, thank you for persistance in tracing this back

Best,
Jeff
