### ISSUE TITLE
When pumping steam, pump element generates false result without throwing error.

### ISSUE THREAD

**Issue by c4rnot** [DanWBR/dwsim6#460]
I am doing an example from the DWSIM course available on Udemy.  One of the examples is pumping water.

Inlet conditions (143 °C, 2,69 bar abs:  which is steam - I think the Udemy course creator made a mistake here).  Pumping 1500 kg/h water/steam (IF-97) to 6,9 bar abs.

DWSIM calculates this, throwing no error, but shows 0 kW pump power, and an exit stream with the same enthalpy as the inlet stream, at the specified outlet pressure (which results in an outlet entropy lower than the inlet entropy which is a physical impossibility)

Given that this has not calculated correctly, it should throw an error rather than providing an apparent, but absolutely incorrect solution.

(version is 8.4.3 Windows.  .dwxmz file attached)

[pump_missing_error.zip](https://github.com/DanWBR/dwsim/files/11222508/pump_missing_error.zip)

![Messages](https://user-images.githubusercontent.com/54359278/231772511-879f98d7-f10e-4e9d-b762-5ecb30ceebb5.PNG)

**Comment by DanWBR** [comment]
@c4rnot you are trying to pump steam, there is a fundamental error here. I'm not the author of the udemy course.

**Comment by c4rnot** [comment]
With all due respect, the issue is not that the Udemy course is wrong, but that DWSIM claims to have solved a flowsheet when it has not.

**Comment by DanWBR** [comment]
@c4rnot I understand, but I don't have the resources to catch all the user input errors. I believe that it is the user's responsibility to review their own input. You can't blame me for letting the user feed a vapor stream into a pump. Are we dealing with kids or engineers?

**Comment by Spogis** [comment]
Is this really real? Are you wanting to use a pump to pump STEAM? This is not a DWSIM error, but a very serious engineering error!

**Comment by c4rnot** [comment]
Imagine, for example that the inlet to the pump is the outlet of another component, and therefore the result of a calculation.

The fact that the pump is being provided with a stream with vapour may be an important output of the tool, rather than an input.  Maybe the flowsheet designer needs to add a flash vessel to make the actual process work for example.

**Comment by DanWBR** [comment]
> Imagine, for example that the inlet to the pump is the outlet of another component, and therefore the result of a calculation.
> 
> The fact that the pump is being provided with a stream with vapor may be an important output of the tool, rather than an input. Maybe the flowsheet designer needs to add a flash vessel to make the actual process work for example.

that's exactly the reason why the pump doesn't check for vapor on its inlet - it used to do it some time ago. In some cases, the equilibrium calculation would give a very small vapor fraction (0.0001) that would trigger the error message, even if the amount of vapor wouldn't do any harm. I decided to remove this check and let the user do it for himself.

You have the option to force the stream to always be in the liquid phase. In real-life plants, you will not have to deal with this situation. In the flowsheet model, you can face this if you did something wrong in the process upstream of the pump.

**Comment by Spogis** [comment]
So @c4rnot , please re-write your first question please! You blame DWSIM also writing about entropy problems! 

If you ask @DanWBR to put a check and inform you that you are trying to pump a vapor or a misture of gas / liquid, ok, but that's really not the point that you suggest on your first Bug report.

**Comment by c4rnot** [comment]
Hi @Spogis I've opened a request to add a warning as as an enhancement request.

Best Regards
Martin
