### ISSUE TITLE
[Enhancement] add a warning if the pump element is attempting to pump media with vapour phase components

### ISSUE THREAD

**Issue by c4rnot** [DanWBR/dwsim6#461]
Would it be possible to add a warning if the pump element is attempting to pump media with vapour phase components.

**Comment by DanWBR** [comment]
![image](https://user-images.githubusercontent.com/2669419/231819701-a6db6172-36da-472b-9a4f-562e30df1151.png)

**Comment by c4rnot** [comment]
@DanWBR Thanks!

**Comment by DanWBR** [comment]
@c4rnot you're welcome, and thank you very much for the donation 👍
