### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mauriciozago** [DanWBR/dwsim6#462]
**Describe the bug**
I just installed DWSIM for the first time in v8.4.3. As I tried to execute dwsim-classic and dwsim, I experienced the following errors.

**To Reproduce**
![image](https://user-images.githubusercontent.com/64398635/232802518-3fa5dacc-72d3-4242-b147-bbb3721bb963.png)
![image](https://user-images.githubusercontent.com/64398635/232810595-5e86c791-7bf8-4c45-9cb4-f05efcb19b58.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/64398635/232802006-ce3f08a7-8552-4796-a11d-047586149db6.png)
![image](https://user-images.githubusercontent.com/64398635/232810419-5b0d6e3a-6c14-4eb2-9a05-05d4e71d6d0a.png)

**Desktop:**
 - OS: Linux Ubuntu
 - Version 20.04

**Comment by DanWBR** [comment]
@mauriciozago for dwsim (not classic) to look better, try changing your theme
