### ISSUE TITLE
[Bug] English not available in the language selection drop down menu

### ISSUE THREAD

**Issue by jubra97** [DanWBR/dwsim6#463]
**Describe the bug**
I tried to switch the gui language from german to english. In the drop down menu some different langauges are listed but english is missing. 

**To Reproduce**
1. Install DWSIM 8.4.3 on windows.
2. Start it and everything is german.
3. Click on the language selection drop down menu
4. English is missing

**Expected behavior**
English is availabe in the drop down menu and you can select english as the gui language.

**Screenshots**
![image](https://user-images.githubusercontent.com/72612593/233572885-4e562f0e-84ec-4ed9-a5e3-e30160645221.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 8.4.3
 - From Germany

Thank you for your help!

**Comment by DanWBR** [comment]
@jubra97 this is not a bug, just disable the translator by unchecking the green button just before the "Beton" text.
