### ISSUE TITLE
[Bug]  - Conversion Reactor

### ISSUE THREAD

**Issue by pdenis13** [DanWBR/dwsim6#464]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

Despite using  a 100 % conversion  for benzene hydrogenation, only 86% is calculated

**To Reproduce**

PLEASE ATTACH THE ZIPPED FLOWSHEET FILE and/or inform the steps to reproduce the behavior:

1. Unzip test_Cyclohexane.dwxmz.zip
3. use test_Cyclohexane.dwxmz
4. Verify the reaction : 
- base compound : Benzene
- Conversion expression : 100
6. run flowsheet
7. look at conversion reactor 
  Reaction conversion : 100 % 
  Compound conversion Benzene : 43.50 % 

Where I Make a mistake ?

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.3.1

**Additional context**
Works correct with esterification.dwxmz from Fossee
[test_Cyclohexane.dwxmz.zip](https://github.com/DanWBR/dwsim/files/11336279/test_Cyclohexane.dwxmz.zip)
[esterification.dwxmz.zip](https://github.com/DanWBR/dwsim/files/11336324/esterification.dwxmz.zip)

**Comment by DanWBR** [comment]
@pdenis13 please check the reaction phase.
