### ISSUE TITLE
Energy stream mixer

### ISSUE THREAD

**Issue by petroconsulting** [DanWBR/dwsim6#465]
Supplying 2 or more streams to the energy mixer does not provide a combined exit stream value (Status: not calculated), unless the mixer is subject to debug object. 

Additionally, is there a way to get the value of the balancing inlet energy stream, when supplying another inlet energy stream value plus the value of the exit energy stream?  Thanks. Thanks.

**Comment by DanWBR** [comment]
@petroconsulting could you please attach a sample flowsheet?

**Comment by petroconsulting** [comment]
Hi Daniel: thanks for replying.
The file attached does not work with recalculate, but only with the debug option.  Additionally, it would be great to implement the energy mixer with calculation of an inlet energy stream when the output is known. Thanks.

[Energy mixer bug.zip](https://github.com/DanWBR/dwsim/files/11400053/Energy.mixer.bug.zip)

**Comment by DanWBR** [comment]
@petroconsulting thanks for the file. I can't implement that function because the solver is sequential modular, it needs all inputs calculated to calculate the unit operation, then the output gets calculated. You can use a controller block to do that.

**Comment by DanWBR** [comment]
@petroconsulting this was not a bug, the solver didn't work because you didn't add any compound or a property package to the simulation. Please add one of each even if you will not use them.

**Comment by petroconsulting** [comment]
Correct. It is not a bug. Thanks for your prompt advise.
