### ISSUE TITLE
[Bug] Some Components Present in the Flowsheet are not Part of Open Source Core of DWSIM

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#468]
Opening a simulation works fine in DWSIM 8.3.5 using PR/LK for a calculation conversion of below reaction in a simple PFR

`CH2CH2 + 2HCl + 0.5O2 <--> CH2ClCH2Cl + HOH `

raise the below error!

![image](https://github.com/DanWBR/dwsim/assets/830394/5d32d8b8-9100-467d-9fb4-a1233d788344)

Does this means some of Property Packages / Some of components have been moved into Pro version?

**Comment by DanWBR** [comment]
@kookma I thought that it was redundant to have so many variations of PR and SRK Property Packages, but I'll reactivate them anyway.

**Comment by kookma** [comment]
Hi Daniel,
Thank you for your prompt reply! I did not realize what is the source of that error! But with your explanation now I understand I can change the PR and it will work! May be a note in ChangeLog is enough!
So, one option is to deprecate redundant PRs, that's mean users will be notified when they use some PRs. A short not states that: this PR will be removed from 8.6 or 8.7, ...

Thank you again!

**Comment by DanWBR** [comment]
@kookma, yes, I admit that I was reckless and rushed in this regard. sorry

**Comment by kookma** [comment]
Don't mention it!
Thank you for all your efforts and your kind support! Much appreciated!
