### ISSUE TITLE
[Bug] Reactions not visible for PFR

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#471]
In version 8.4.4 when cliking a PFR (or maybe others too) the attached reaction set is not visible and not possible to add/delete

![image](https://github.com/DanWBR/dwsim/assets/58475535/2dd846b8-26f1-4512-b1c2-fea785278210)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 8.4.4

**Comment by DanWBR** [comment]
@andr1976 this tab displays some reaction info after the reactor is calculated, and the table is read-only.

**Comment by andr1976** [comment]
@DanWBR  so where to assign reactions to a certan reactor among those defined in settings?

**Comment by andr1976** [comment]
SHoot me, forget my last message - I am apparently getting blind.
