### ISSUE TITLE
[Bug] Mouse button stuck on version 8.4.4

### ISSUE THREAD

**Issue by Sergey82K** [DanWBR/dwsim6#472]
I have a problem with like mouse button stuck in the pressed state on the flowsheet diagram window.
After I first click on any point of the flowsheet diagram window button like as stuck in a pressed state. When I move the mouse over the flowsheet diagram window, there is diagram drag such as I pressed the mouse button and dragged the scheme.
If I click the right button at any point of the flowsheet diagram there are context menu shows and the mouse pointer moves without diagram drag, but if I click in any space to close the context menu the mouse button is stuck again and the diagram drag with mouse pointer.
I try to press the ESC button on the keyboard but no effect to.
This is like the "Mouse button released" event for the flowsheet window ignored.

DWSim v.8.4.4.
Windows 10 v10.0.19045.0

**Comment by DanWBR** [comment]
@Sergey82K is this happening with every flowsheet you try?

**Comment by Sergey82K** [comment]
> is this happening with every flowsheet you try?

Yes. Including a new flowsheet. 
I downloaded a portable version of DWSIM v8.4.3 and its works fine.

**Comment by DanWBR** [comment]
@Sergey82K Unfortunately I can't reproduce it here, I installed v8.4.4 from the website and it is working normally.

**Comment by Sergey82K** [comment]
I localized the problem point - it's OpenGL render. 
The bug is represented when I switch the Rendering engine to "Hardware (OpenGL)".
When I switch back to "Software (CPU)" its works normally.
To apply this setting, it is necessary to restart the DWSim application after the render engine option was changed.
