### ISSUE TITLE
[Bug] Dwsim 8.4.6 [Linux ClassicUI] Flowsheet cannot be saved

### ISSUE THREAD

**Issue by einhander** [DanWBR/dwsim6#478]
Flowsheet made  in CrossPlatformUI  cannot be save on linux using ClassicUI. Save buttons are always grey. The error shown, on flowsheet close, after click save button in dialog.

Error on file open:
![2](https://github.com/DanWBR/dwsim/assets/5439042/caf541ed-4e38-444c-957a-5fce792f166f)

Error on file save:
> System.MissingMemberException: Attempted to access a missing member.
>   at Microsoft.VisualBasic.CompilerServices.LateBinding.LateGet (System.Object o, System.Type objType, System.String name, System.Object[] args, System.String[] paramnames, System.Boolean[] CopyBack) [0x000bb] in <f6a313cf04e64a29b6bbd63d49445f98>:0 
>   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.LateGet (System.Object Instance, System.Type Type, System.String MemberName, System.Object[] Arguments, System.String[] ArgumentNames, System.Type[] TypeArguments, System.Boolean[] CopyBack) [0x00001] in <f6a313cf04e64a29b6bbd63d49445f98>:0 
>   at DWSIM.SharedClasses.Utility.CheckSimulationForMobileCompatibility (DWSIM.Interfaces.IFlowsheet fs) [0x00081] in <ad72f2c90c2d49ee8f16b60c874f63d9>:0 
>   at DWSIM.FormMain.SaveMobileXML (DWSIM.Interfaces.IVirtualFile handler, DWSIM.FormFlowsheet form, System.String simulationfilename) [0x00023] in <b38fee9382bf49c785790252a968f8a8>:0 
>   at DWSIM.FormMain.SaveFile (System.Boolean saveasync, System.Boolean dashboardpicker) [0x00187] in <b38fee9382bf49c785790252a968f8a8>:0 
>   at (wrapper remoting-invoke-with-check) DWSIM.FormMain.SaveFile(bool,bool)
>   at DWSIM.FormFlowsheet.FormChild2_FormClosing (System.Object sender, System.Windows.Forms.FormClosingEventArgs e) [0x00087] in <b38fee9382bf49c785790252a968f8a8>:0 
>   at System.Windows.Forms.Form.OnFormClosing (System.Windows.Forms.FormClosingEventArgs e) [0x00019] in <28e46de2d20c496895000ef0abfc2106>:0 
>   at System.Windows.Forms.Form.FireClosingEvents (System.Windows.Forms.CloseReason reason, System.Boolean cancel) [0x0001b] in <28e46de2d20c496895000ef0abfc2106>:0 
>   at System.Windows.Forms.Form.RaiseCloseEvents (System.Boolean last_check, System.Boolean cancel) [0x0002d] in <28e46de2d20c496895000ef0abfc2106>:0 
>   at System.Windows.Forms.Form.WmClose (System.Windows.Forms.Message& m) [0x00095] in <28e46de2d20c496895000ef0abfc2106>:0 
>   at System.Windows.Forms.Form.WndProc (System.Windows.Forms.Message& m) [0x000de] in <28e46de2d20c496895000ef0abfc2106>:0 
>   at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <28e46de2d20c496895000ef0abfc2106>:0 
>   at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <28e46de2d20c496895000ef0abfc2106>:0 
>   at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x00085] in <28e46de2d20c496895000ef0abfc2106>:0

**Comment by DanWBR** [comment]
@einhander saving flowsheet on Linux/Classic UI in XML for Android and iOS is not supported.

**Comment by einhander** [comment]
I use Linux not android, and tried to open flowsheet created in Cross platform Ui in ClassicUi on the same PC. It worked ok in version 8.3. The latest version creates backup file after I kill dwsim, it can be opened and saved ok

**Comment by einhander** [comment]
The sample flowsheet can be taken from #480

**Comment by DanWBR** [comment]
> I use Linux not android, and tried to open flowsheet created in Cross platform Ui in ClassicUi on the same PC. It worked ok in version 8.3. The latest version creates backup file after I kill dwsim, it can be opened and saved ok

I know you don't use Android, but this specific call

_at DWSIM.SharedClasses.Utility.CheckSimulationForMobileCompatibility (DWSIM.Interfaces.IFlowsheet fs) [0x00081] in :0
at DWSIM.FormMain.SaveMobileXML (DWSIM.Interfaces.IVirtualFile handler, DWSIM.FormFlowsheet form, System.String simulationfilename) [0x00023] in :0_

means that the file was saved or tried to save with the XML extension which is the format for mobile versions.

I would kindly ask you to stop using the Classic UI version on Linux and try the wine version instead. I don't have the resources required to maintain this version anymore. It requires too much effort and workarounds and it is just not worth it anymore for me to keep working on it.

**Comment by einhander** [comment]
>try the wine version instead.  I don't have the resources required to maintain this version anymore.

I'll be happy to use CrossPlatformUI not wine version, but I got your point.
