### ISSUE TITLE
[Bug] [Linux Crossplatform UI] Kinetic reaction editor UI bugs

### ISSUE THREAD

**Issue by einhander** [DanWBR/dwsim6#479]
Text input boxes are smaller than entered text. See screenshot.
Also the no description field like in ClassicUI

![1](https://github.com/DanWBR/dwsim/assets/5439042/bf12dfa1-f460-425a-8190-3e50787f8ebc)

**Comment by DanWBR** [comment]
@einhander set the UI Scaling Factor to something lower in Global Settings.

**Comment by einhander** [comment]
The original sceenshot made with 1,05 Scaling Factor

These made with 0,5 scaling factor. As you can see the problem getting worse.
![2](https://github.com/DanWBR/dwsim/assets/5439042/8f428d78-ee4c-403d-b5ab-b33fc63285d0)
![1](https://github.com/DanWBR/dwsim/assets/5439042/e7f7e941-9281-46ac-98dc-11010e28bd63)

This made with 1,5 scaling factor. It's still not enough, but whole interface is to big. 
![3](https://github.com/DanWBR/dwsim/assets/5439042/0050fbc7-e001-48d3-9827-5cefe6330ffd)

**Comment by DanWBR** [comment]
@DanWBR changing font size then?

**Comment by einhander** [comment]
> changing font size then?

I think that real solve of this issue is increase width of textblocks to 5 or 6 symbols, or set it dynamically to it's content.
Also there whole kinetic block is too narrow and right border should be moved right. Note the last textblock of Carbon dioxyde (see the pic).
![4](https://github.com/DanWBR/dwsim/assets/5439042/a4ef3579-d68c-4057-8a4d-505d39efd011)

**Comment by DanWBR** [comment]
@einhander this is how it looks for me on Linux and macOS. Same UI code, so the problem is definitely not the width of the textboxes.
 
<img width="950" alt="Captura de Tela 2023-06-04 às 12 04 38" src="https://github.com/DanWBR/dwsim/assets/2669419/c241ac19-eb85-426c-b5a5-3a78ff23a215">
<img width="964" alt="Captura de Tela 2023-06-04 às 12 05 36" src="https://github.com/DanWBR/dwsim/assets/2669419/42633489-6b58-49ec-bc77-4294edbf465f">

**Comment by einhander** [comment]
Here the screenshot of kinetic window in fullscreen.
![5](https://github.com/DanWBR/dwsim/assets/5439042/b6d5f5be-94ab-41a1-8f48-5443a63b1be7)

**Comment by DanWBR** [comment]
<img width="1119" alt="Captura de Tela 2023-06-04 às 12 47 52" src="https://github.com/DanWBR/dwsim/assets/2669419/834b9503-c61f-4448-8830-cc22b9dccd1c">
