### ISSUE TITLE
[Feature request] A way to enter create Hypos/pseudo components in a table like manner

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#48]
**Existing way of defining hypos/pseudos**
In the current state hypotheticals/pseudocomponents are entered one by one, which is tedious

**Suggestion for improvement**
Allow entering/defining a number of components at once in a table style where each hypo is entered with name and a minimum required input e.g. boiling point, density or molecular weight, and optional additional input. In case optional input is not given, these properties are estimated with known methods e.g. Density, molecular weight, Pc, Vc, Tc, accentric factor etc.

Using a table input - hypos defined in other programs can easily be copy pasted 

See example below 

![image](https://user-images.githubusercontent.com/58475535/98586419-f4c09f00-22c8-11eb-95ff-c86706b0fff0.png)

**Comment by DanWBR** [comment]
implemented in v8.2.0
