### ISSUE TITLE
[Bug] [Linux Crossplatform UI] Mono process use 100% CPU after solver failed to calculate 

### ISSUE THREAD

**Issue by einhander** [DanWBR/dwsim6#480]
Mono process use 100% CPU after solver failed to calculate and time limit reached. Only workaround is recalculate flowsheet with different parameters that solver can finish calculations. Closing flowsheet didn't helps.

**Comment by DanWBR** [comment]
@einhander no sample flowsheet?

**Comment by einhander** [comment]
Here
[Gasification3-1.dwxmz.txt](https://github.com/DanWBR/dwsim/files/11645925/Gasification3-1.dwxmz.txt)

**Comment by einhander** [comment]
The abort button works, thanks! I think the abort action should be executed after timeout reached.
