### ISSUE TITLE
[Bug] [Linux CrossPlatformUI] Slowdown of UI after  few hours of work

### ISSUE THREAD

**Issue by einhander** [DanWBR/dwsim6#484]
After few hours of work the whole UI gets very slow. For example Edit/View docked window shows after 15 seconds, after an hour of work this action completes after 45 seconds. The issue not limited to Edit/view action, but a whole UI.

Dwsim v8.4.6 Linux CrossPlatformUI

**Comment by DanWBR** [comment]
@einhander debugging this kind of issue is almost impossible as it seems to be GUI/Eto related and I can't do performance analysis on systems other than Windows. I suggest you save your work once you notice the slowdown, then close DWSIM and reopen it.
