### ISSUE TITLE
Infinity Loop on Calc Critical Point in PR78[Bug] 

### ISSUE THREAD

**Issue by AlexanderSemenyak** [DanWBR/dwsim6#487]
Infinity Loop on Calc Critical Point in PR78

1. Open flowsheet
2. Open in MaterialStream 1 attached utility PhaseEnvelope1
3. Calc curve
4. Infinite Loop on PR78 and at universal routine for calc true point (PCP/TCP for another PP's)

**Expected behavior**
Draw Phase Envelope Curve and Critical points

**Screenshots**

![TestCriticalPoint](https://github.com/DanWBR/dwsim/assets/42087193/b3e1586f-bb06-4906-90b6-3e8572cfdee2)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 8.4.7

[N75_new_CP_flowsheet.zip](https://github.com/DanWBR/dwsim/files/11683490/N75_new_CP_flowsheet.zip)

**Comment by DanWBR** [comment]
@AlexanderSemenyak very badly written code ancient ages... thanks for the report
