### ISSUE TITLE
[Enhancement] [Linux Crossplatform UI] Reaction window usability

### ISSUE THREAD

**Issue by einhander** [DanWBR/dwsim6#493]
**Is your feature request related to a problem? Please describe.**
The Classic UI Reaction window have reaction equation but Crossplatform UI is not
![1](https://github.com/DanWBR/dwsim/assets/5439042/f7c8e681-1036-43e9-a733-335d756f9f8f)
![2](https://github.com/DanWBR/dwsim/assets/5439042/79f41ebc-c94c-4413-8883-93ca87f0bd82)
The Classic UI Reaction Edit window have balance stoichiometry button but Crossplatform UI is not.
Also there is the description field, which is absent in Crossplatfom UI.
![3](https://github.com/DanWBR/dwsim/assets/5439042/b3644d20-8ae9-487e-a9df-4ddf54e0771f)
![4](https://github.com/DanWBR/dwsim/assets/5439042/93c69d9f-990c-4eb1-a382-8a56534433c9)

**Describe the solution you'd like**
The equation in square brackets after a reaction name will be enough. But uniform look for both UI (as far as its possible) will be better.
Add balance button and description field to Reaction Edit window in Crossplatform UI.

**Comment by DanWBR** [comment]
@einhander I added the description field. Due to limited resources, the rest will not be worked on unless someone pays for it.

![image](https://github.com/DanWBR/dwsim/assets/2669419/6bf5f767-31cf-4009-b5d1-d86f5c4914fc)

**Comment by einhander** [comment]
@DanWBR Thank you for your efforts!
