### ISSUE TITLE
Need clone ForcePhase for ShallowCopy MaterialStream? [Bug] 

### ISSUE THREAD

**Issue by AlexanderSemenyak** [DanWBR/dwsim6#497]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
Calculate Pipe with overrided ForcePhase (e.g. for Gas) - use liquid phase (not overrided phase for calculate pipe) in Pipe MS

**To Reproduce**
1. Override Phase to Gas for MS
2. Calculate Pipe -> use Gas and Liquid, but need Gas only

**Screenshots**
![image](https://github.com/DanWBR/dwsim/assets/42087193/f11f2b10-b242-43b8-a468-d007313734fe)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 8.4.7

**Comment by DanWBR** [comment]
@AlexanderSemenyak thanks!
