### ISSUE TITLE
The initial guess

### ISSUE THREAD

**Issue by magnuscarlsen** [DanWBR/dwsim6#499]
https://github.com/DanWBR/dwsim/blob/37488558fdd03e1a0eb167a33dfd20ec45537d45/DWSIM.UnitOperations/UnitOperations/HeatExchanger.vb#L1931

Not sure I'm writing this in the right place/way but the initial guess doesn't seem correctly defined, shouldn't it say T20, not T21. 
(The reason why I'm looking is that i calculate the massflow/*heat cap/*deltaT and it doesn't match with the heat transfer in the heat exchanger, first of all I'm not sure I get it, secondly I'm not sure I get the code completely. But if felt odd that the initial guess isn't defined until the following row.)

**Comment by DanWBR** [comment]
@magnuscarlsen T21 not having a value at this point doesn't affect the calculation because it is used only as an initial estimate.

DWSIM uses enthalpy to calculate heat balances, not heat capacities. If the temperature difference is considerable, then Cp also changes a lot depending on the fluid.
