### ISSUE TITLE
Issue in CSTR: Simple esterification reaction

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#50]
The attached file shows a simple second order esterification in a CSTR.

Acetic Acid + Etahnol -> Ethyl Acetate + Water

```
A + B = C + D

-rA = k.Ca.Cb,   k=0.005
```
PP: NRTL

```
T=70C
P=1 bar
F=3600 kg/hr
```

This is an example taken from FOSSE spoken tutorial.

It works fine in DWSIM 6 but in 6.1 and above returns error. I think this example is a very simple from numerical point of view but DWSIM returns: `maximum number of iteration reached !`

I assume DWSIM fails in flash calculation as CSTR is a simple algebraic equation here and solver should not fail.

Some interesting findings:

* change water DO from 0 to 1 in reaction definition, DWSIM solves the flowsheet.
* change DO for Acetic acid from 1 to 0.5, DWSIM solves the flowsheet

what is the problem? Is there any issue with numerical solver!

[cstr-estrification-issue.zip](https://github.com/DanWBR/dwsim6/files/5535816/cstr-estrification-issue.zip)

**Comment by DanWBR** [comment]
Fixed in https://github.com/DanWBR/dwsim6/commit/549ae8bdfc56b1eb057423b112421752f0834e76 and https://github.com/DanWBR/dwsim6/commit/496c536e16364964e65e9e1223ce5bde4397b35b

**Comment by kookma** [comment]
Thank you Daniel! I will wait for next release to give a try!

**Comment by kookma** [comment]
Daniel, I think the issue has gone in new release. Please close this issue if so.
