### ISSUE TITLE
[Enhancement] Define profile segment from tabular data input Length/Elevation (from file with inclinometry data e.g.)

### ISSUE THREAD

**Issue by AlexanderSemenyak** [DanWBR/dwsim6#500]
Define profile segment from tabular data input Length/Elevation (from file with inclinometry data e.g.)

1. Each segment with tabular data definition for increments (length/elevation)
2. Increments can be of different lengths (from tabular data)

![image](https://github.com/DanWBR/dwsim/assets/42087193/7c5aa810-d552-4d58-b30a-1d1268eeff03)

**Comment by DanWBR** [comment]
@AlexanderSemenyak we would need to define a standard format for this data.

**Comment by AlexanderSemenyak** [comment]
e.g. this -> for each segment (tubing type only) - add cell with button for define profile (also, load from file with this structure -> header with tabular data)

![image](https://github.com/DanWBR/dwsim/assets/42087193/c1433d1d-53bf-4ea8-80f8-134b0b4479e1)

PS: if tabular data defined for [SEGMENT]-> 
1) [SEGMENT] increments ignored, quantity ignored, 
2) material from [SEGMENT] defined for all  in tabular data subsegments
3) int.diameter, ext.diameter, increments, rugosity, therm.conduct (without support formula) - optionally overrided from tabular data (if greater, than 0), or requested from [SEGMENT] if 0
4) after define tabular data for [SEGMENT]- calculations for [SEGMENT] in code replaced with prepared new tabular data for [SEGMENT] 

[RESULT]: [segments with tabular data] and [simple segments without tabular data] define pipe hydraulic profile.

PS2: [SEGMENT] is segment column in DWSIM (with defined tabular data)

**Comment by DanWBR** [comment]
@AlexanderSemenyak this should work well for both of us, not too heavy on my side while still being able to get all possible inputs:

![image](https://github.com/DanWBR/dwsim/assets/2669419/4b8ac539-5266-44b2-8cc4-7b69df46b324)
