### ISSUE TITLE
Molar Free Gibbs Energy is rather low, see water at 25ºC and 1 bar should be ca. 237 kJ/mol and with Peng-Robinson is 9 kJ/mol

### ISSUE THREAD

**Issue by sgarciarodriguez81** [DanWBR/dwsim6#504]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
Gibbs Energy is rather low, see water at 25ºC and 1 bar should be ca. 237 kJ/mol and with Peng-Robinson is 9 kJ/mol

**To Reproduce**

Pure water stream at 25ºC and 1 bar with Peng Robinson, the result of the Molar Free Gibbs Energy is ca. 9 kJ/mol

**Expected behavior**
The correct value of the pure water stream at 25ºC and 1 bar of the Molar Free Gibbs Free Energy should be ca. 237 kJ/mol

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MW 10 and MW 11
 - Version [e.g. v8.2.2] and 8.4.3

**Additional context**

**Comment by DanWBR** [comment]
@sgarciarodriguez81 is there a "correct" value for absolute enthalpies, entropies and gibbs energies? I don't think so. It depends on the reference state.
