### ISSUE TITLE
distillation column - tab Estimates more than 20 stages disallow view of Reboiler values

### ISSUE THREAD

**Issue by ingDoc** [DanWBR/dwsim6#506]
While redoing the example of the pressure swing distillation column from the help file (page 178 ff) the estimates are used to calculate the temperature profile for 61 stages. Unfortunately it is not possible to scroll down to the reboiler in oder to control your the temperature (it can be added without seeing it of course). After the calculation an error with the feed-stage occurs although its set.
It works well with up to 20 stages - adding a higher number of stages at first and the reducing them later on leads to calculation errors.

portable and installed dwsim version 8.5.0 on windows 10 with 16'' und 26'' screens (even changing the width and length didn't help)
![bug_distillation_column_estimates](https://github.com/DanWBR/dwsim/assets/50383603/11472c7f-d4dc-4f45-b715-29dd1aaa5121)

**Comment by DanWBR** [comment]
@ingDoc I couldn't reproduce this issue on my computer. could you please share a screenshot of the whole screen?

**Comment by ingDoc** [comment]
Of course - I am trying myself to find a mistake I might have made. Here are to scrennshots with attached and unattached window on the 26'' screen with the portable version.

![bug_whole_screen_unattached_window](https://github.com/DanWBR/dwsim/assets/50383603/e95380b6-ff1a-41c5-9e95-c7fdebad2861)
![bug_whole_screen_attached_window](https://github.com/DanWBR/dwsim/assets/50383603/43c78eae-b943-4c55-9bd7-dd3f348bcfcb)

**Comment by DanWBR** [comment]
@ingDoc this is weird. it shows up correctly here 
![image](https://github.com/DanWBR/dwsim/assets/2669419/721583bc-705c-47f8-b49a-c62577d3a90b)

**Comment by DanWBR** [comment]
@ingDoc I know I'm using a high DPI configuration but I tried it with 100% scaling and it also showed up correctly.

**Comment by ingDoc** [comment]
This is really weird - because the screen I sent you came from the third computer I was working with. And each time the same result - even from 8 people I showed the problem. We all got the same download from github and we work with windows 10 computers (laptops, standalone computers).

**Comment by ingDoc** [comment]
Are you working with the pro-version? It looks like an issue in placing the window. At first I thought there is not enough space reserved to show the table - something wrong with the height definition in the frame. But now it looks like something windows does.

**Comment by DanWBR** [comment]
@ingDoc mine is Windows 11. It might be a windows thing.

**Comment by DanWBR** [comment]
@ingDoc can you try it with 200% scaling?

**Comment by ingDoc** [comment]
I will - I reply after restarting the computer.

**Comment by ingDoc** [comment]
I am back and yes it got worse - would it help to work with an older version of dwsim? I would like to use the dynamic simulation.
![bug_whole_screen_200percent](https://github.com/DanWBR/dwsim/assets/50383603/8924ed84-52f5-4db0-b4ac-2ae4a52174bb)

**Comment by DanWBR** [comment]
@ingDoc what is your screen resolution?

**Comment by ingDoc** [comment]
At the moment 2560X1440 - on the other two computers with the same issue 1920x1440. One of the other users had 1920x1200
and 1920x1080 - same issue differing number of disappearing stages
