### ISSUE TITLE
Issue in Equilibrium Reactor: Partial oxidation reaction

### ISSUE THREAD

**Issue by Kouessan** [DanWBR/dwsim6#51]
I have attached a **testfile1** with three reactions in a equilibrium reactor:

 (1):   CH4 + H2O <-> CO + 3H2
 (2):   CH4 + CO2 <-> 2CO + 2H2
 (3):   2CH4 + O2 <-> 2CO + 4H2

PP: Peng-Robinson

Running the simulation is possible without errors. 
However, increasing the temperature or the pressure of the feed does not change the product composition or the conversion rates in any way. The same behaviour repeates itself if only partial oxidation of methane is simulated.

**Expected behavior**
As far as i know, any reaction which results in a change of moles in gas phase, shold be at least dependent on pressure.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - DWSIM 6.3 Update 2
 - Classic UI

**Additional context**
This behaviour seems to be connected with the presence of O2 within the equation of reaction. I have created 3 further testfiles.

-Testfile2 just contains a comparision between the global and the single three reactions of testfile1 within the equilibrium reactor. (The gibbs reactor is just for further comparisons)

-In Testfile3 i have created a similar setup as in Testfile 1. However, the reactions are carried out based on Methanol instead of Methane. The result is basically the same as in Testfile 1. No change depending on pressure and/or temperature.

[Testfiles_Kouessan.zip](https://github.com/DanWBR/dwsim6/files/5542794/Testfiles_Kouessan.zip)

**Comment by DanWBR** [comment]
What's messing everything is the calculated equilibrium constant for the POM reaction, which is about 1.06E+23, and the solver is having a hard time dealing with such a high value. Not sure if this is correct, can you check?

<img width="519" alt="Captura de Tela 2020-11-15 às 21 24 59" src="https://user-images.githubusercontent.com/2669419/99203503-2cc45800-2789-11eb-8391-773897bb02e8.png">

**Comment by Kouessan** [comment]
I guess that this might be the cause of the problem.
However, how can i access this version of the debug-mode?

**Comment by DanWBR** [comment]
Do you have the expected results from another simulator?

**Comment by Kouessan** [comment]
I just received these values for the equilibrium constant for the reaction from AspenPlus. They are also calculated with Gibbs Minimization.
So these high values seem to be quite usual. Since the reaction is also actually irreversible, it also makes sense that Keq is quite high.


![aspenpartialox](https://user-images.githubusercontent.com/74502636/99260014-27175280-281b-11eb-8f43-3d5e318b8652.PNG)

**Comment by DanWBR** [comment]
Sure! They aren't wrong at all. I've modified the objective function to use natural log and it worked. I just would like to know what are the expected results before releasing the update.

**Comment by DanWBR** [comment]
Results with the fixed code:

<img width="947" alt="Captura de Tela 2020-11-16 às 10 55 18" src="https://user-images.githubusercontent.com/2669419/99267380-42be3100-27fa-11eb-9713-60f86c26885d.png">

**Comment by Kouessan** [comment]
This already looks way better now, thank you
 So the fixed code will be released with the next update, right?

**Comment by DanWBR** [comment]
> This already looks way better now, thank you
> So the fixed code will be released with the next update, right?

Yes, in v6.3 Update 4
