### ISSUE TITLE
More engineering units

### ISSUE THREAD

**Issue by tomas789** [DanWBR/dwsim6#513]
**Is your feature request related to a problem? Please describe.**
I'm analysing an investment decision of the local power plant. Engineers, at least in my geographical area, use metric tonnes per hour for the mass flow. DWSIM only has kg/h. This conversion is very simple but it would help when I'd be able to work in the same units as the engineers. For that reason, I'd like to see support for t/h for mass flow.

**Describe the solution you'd like**
Add support for t/h unit in mass flow.

**Describe alternatives you've considered**
I'm a developer myself so if you point me in the correct direction I can try to implement the change myself and make a PR.

**Comment by DanWBR** [comment]
@tomas789 it will be available in the next release.
