### ISSUE TITLE
Delete object with backspace

### ISSUE THREAD

**Issue by tomas789** [DanWBR/dwsim6#514]
**Is your feature request related to a problem? Please describe.**
Removing an object from flowsheet can be done by pressing delete or by right clicking. I'm using DWSIM in Windows on my MacBook Pro 16". Macbooks don't have a dedicated delete key. The delete is triggered by pressing fn+backspace. They are both on oposit side of the keyboard so one has to use both hands.

**Describe the solution you'd like**
Delete selected object by pressing backspace.

**Describe alternatives you've considered**
I don't see any reasonable alternatives.

**Additional context**
If you point me in a right direction, I can implement the change myself and make a PR.

**Comment by DanWBR** [comment]
@tomas789 you can also use the context menu and select Delete, two fingers in the touch bar are enough.
