### ISSUE TITLE
[Bug] Visible properties layout scroll issues

### ISSUE THREAD

**Issue by MichaelUBJ** [DanWBR/dwsim6#516]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
Cross platform UI (on a MACBOOK M1)
Go to flowsheet settings -> visible properties
Select "material stream"
-> It is not possible to select/deselect from the list of properties as the window is not large enough for all the properties 
Solution is to be able to scroll the list

**To Reproduce**

**Expected behavior**
To be able to scroll the list of properties

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 8.5

**Additional context**

**Comment by DanWBR** [comment]
@MichaelUBJ aren't you getting this scrollbar on the right?

<img width="808" alt="Captura de Tela 2023-07-25 às 11 05 59" src="https://github.com/DanWBR/dwsim/assets/2669419/53b28d28-19ee-4082-803b-dd6412de6326">

**Comment by MichaelUBJ** [comment]
No.. See below screen shot:
<img width="809" alt="Screenshot 2023-07-25 at 17 10 07" src="https://github.com/DanWBR/dwsim/assets/72048329/c44692b7-2752-415c-bd13-4563f2c7cb5c">

Also despite having deselected some properties for unit operations it shows up in the anchored properties anyway. See below (I have excluded everything below calculation mode):
<img width="303" alt="Screenshot 2023-07-25 at 17 10 23" src="https://github.com/DanWBR/dwsim/assets/72048329/89fd6dbc-adff-4d5e-acfe-34e881b0ba0f">
