### ISSUE TITLE
[Bug]  Chemsep flowsheet mouse hover issue

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#520]
In version 8.5.1 when hovering the mouse over a chemsep column the following appears
![image](https://github.com/DanWBR/dwsim/assets/58475535/d601a394-53a4-4912-8534-476c970bfd49)

**Comment by DanWBR** [comment]
too many properties exposed, some very long strings.

**Comment by andr1976** [comment]
👍
