### ISSUE TITLE
[Bug] Component Properties View: Liquid Phase Missing Property Displays

### ISSUE THREAD

**Issue by WillyLund** [DanWBR/dwsim6#521]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**

I am currently running V8.5 but did not notice this in the release notes for 8.5.1.  When examining component properties, in particular liquid phase, the display is missing the Thermal Conductivity graph and the Data Tables displays.  Again, this is for liquid phase only.   I have tried this with 4 different simulations, no change in behavior.

Additional Data:  8.5.0 is running on Win 11 Pro and where I am seeing the issue.  I have 8.3.5 on Win 10 Pro and it does not exhibit the abnormality.

Thank you.

**Comment by DanWBR** [comment]
@WillyLund have you tried to resize the window?

**Comment by WillyLund** [comment]
I sincerely apologize, yes, it is a Windows font size/magnification issue.  It was just quite strange that it was limited to the liquid properties only and that is what drew me to conclude there may be an application matter.

Thank you.

**Comment by DanWBR** [comment]
@WillyLund I was going to write a resizing command after the window appears but ended up forgetting about it...
