### ISSUE TITLE
[Bug] CAPE-OPEN property package

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#525]
**Describe the bug**
When trying to add CAPE-OPEN property package, when choosing configure for the added CAPE-OPEN PP the following exception occurs (see screenshot)

Further, (closing the exception window) a newly created CAPE-OPEN property package from Neqsim is visible both in Unisim and COFE/COCO

**Screenshots**
![image](https://github.com/DanWBR/dwsim/assets/58475535/0cf63e82-257c-4fd4-b103-06ea0e4c65a6)

In DWSIM:
![image](https://github.com/DanWBR/dwsim/assets/58475535/5b8ffb24-4258-481b-ad8b-88aeec4beea9)

In Unisim:
![image](https://github.com/DanWBR/dwsim/assets/58475535/05fbc4e4-30d4-4015-9d26-7ddc67c70d53)

In COFE:
![image](https://github.com/DanWBR/dwsim/assets/58475535/18b68031-8a0f-4005-a008-9a56e0ddadd5)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 8.5.1

**Comment by DanWBR** [comment]
@andr1976 what is the added CAPE-OPEN PP? I can only test this feature with COCO/COFE PPs and it works for them.

**Comment by andr1976** [comment]
It's the free / open source NeqSim property package:  
https://github.com/equinor/neqsimExcelCapeOpen/releases
Needs installation of the msi and the neqsimexcel.zip for setting up the fluid package configuration. 
https://github.com/equinor/neqsimExcelCapeOpen/wiki/Getting-started-with-NeqSim-in-Excel

**Comment by andr1976** [comment]
Also when I try with TEA, OATS etc, the property package selection is empty although I did create one 
![image](https://github.com/DanWBR/dwsim/assets/58475535/c3568616-0009-495a-b087-1a7b73d552ad)

**Comment by andr1976** [comment]
OK, strange after having select CAPE-OPEN as the first PP in a new simulation, at least TEA / OATS works, but still no NeqSim

**Comment by DanWBR** [comment]
@andr1976 maybe they're using a different approach that I'm missing. I'll check it.

**Comment by andr1976** [comment]
Maybe not a bug per se, but still I get the exception when creating CAPE-OPEN PP as second PP

**Comment by andr1976** [comment]
Anyway NeqSim has some interesting  pp one is the CPA-electrolyte, but really really slow (for good reasons), it does come with a .Net interface so something to consider for future features

**Comment by DanWBR** [comment]
@andr1976 I don't know what I did wrong but installed NeqSim, both msi and excel package, but nothing shows up for DWSIM
