### ISSUE TITLE
[Enhancement] Implement Heat Exchanger Profile for CPUI

### ISSUE THREAD

**Issue by rskempf** [DanWBR/dwsim6#526]
I can view heat exchanger enthalpy plots/curves in the classic user interface only when using minimum pinch temperature difference as the heat exchanger solution method. Can you enable this feature for other exchanger solution methods and in the cross-platform interface?

This feature is at the bottom of the heat exchanger object editor, with the caption "View Temperature vs Heat Exchanger Profile."

This is a standard plot for heat exchanger design. I believe adding this feature will increase the value of DWSIM. Please let me know if you need more information. By the way, the existing plot provided with minimum pinch is quite good regarding format and content.

In the case of a temperature cross or pinch violation, an error message with a plot that shows the hot and cold curves touching would be a bonus. 

Thanks, and many blessings. Rick

**Comment by DanWBR** [comment]
@rskempf sorry Rick, I was on vacation and had other things going on, now I think I'll be able to look at this, please remind me if for some reason I forget about it.
