### ISSUE TITLE
[Bug] Debug Object on Expander shows "Conversion Error"

### ISSUE THREAD

**Issue by HarryLLevinson** [DanWBR/dwsim6#527]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
Debugging object "Expander" shows error on method ToDouble. Note all other objects debugged OK.

**To Reproduce**

PLEASE ATTACH THE ZIPPED FLOWSHEET FILE and/or inform the steps to reproduce the behavior:

1. Open 'Expander Debug Object Error Test'
2. Click on 'X-1'
3. Debug Object via right click

**Expected behavior**
Object OK

**Screenshots**
ERROR: exception raised on file , method ToDouble, line 0:

Conversion from string "" to type 'Double' is not valid.

See Screen Shot also

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro Version 10.0.22621.0
 - DWSIM: 8.5.1 and also in 8.4.7 (or previous version)

**Additional context**
[Expander Debug Object Error Test.zip](https://github.com/DanWBR/dwsim/files/12254621/Expander.Debug.Object.Error.Test.zip)

![image](https://github.com/DanWBR/dwsim/assets/94945597/35afad8d-81b5-40c7-8544-7f8defb5f871)

**Comment by DanWBR** [comment]
@HarryLLevinson the inlet stream must be calculated before debugging a unit operation.
