### ISSUE TITLE
Multi loop control issue

### ISSUE THREAD

**Issue by AliAghaa** [DanWBR/dwsim6#53]
I have a dynamic simulation for controlling the gas pressure and liquid level of a vapor-liquid separator.

Pressure loop reaches set point and become steady.

But at the second loop, level crosses the set point and seems that controller has no effect on it so level keeps increasing.

I also tried to manually open the liquid outlet valve (%100 OP) but even this didn't help and liquid level continues increasing.

How can I fix this issue?

[Level_Pressure Control.zip](https://github.com/DanWBR/dwsim6/files/5599088/Level_Pressure.Control.zip)

**Comment by andr1976** [comment]
Is the valve (Cv) big enough to make a difference?

**Comment by AliAghaa** [comment]
I think so. Incresing of valve Cv doesn't help solving the issue.

**Comment by AdrianDietz** [comment]
Not investigated why yet but at :
![image](https://user-images.githubusercontent.com/34543041/102095589-fcbdb280-3e23-11eb-818b-e66c2598eb88.png)
rho appears as NaN
![image](https://user-images.githubusercontent.com/34543041/102095756-31ca0500-3e24-11eb-8033-c3efbca30e6b.png)

**Comment by AdrianDietz** [comment]
Then you get Wi equals to zero and you separator keeps filling indifinetly...

**Comment by DanWBR** [comment]
This doesn't seem to be a code issue but rather a simulation issue. I'll close this for now, if you still have issues then create a topic on the forums.
