### ISSUE TITLE
Python.net User Models doesnt work in Version 8.6.0 [Bug] 

### ISSUE THREAD

**Issue by HaSchneider** [DanWBR/dwsim6#534]
Python.net scripts are not working in the new version 8.6.0 (with Windows).
Ironpython still works, and in version 8.5.1 the same Python Script User Model with Python.net works as well.

I tested it with a  basic script and one output material flow:
`oms1.SetMassFlow(value=100)`

I get the Error:

> This error was raised during the calculation of a Unit Operation or Material Stream.
> 
> System.InvalidOperationException: This property must be set before runtime is initialized
>    at DWSIM.GlobalSettings.Settings.InitializePythonEnvironment(String pythonpath) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.GlobalSettings\Settings.vb:line 209
>    at DWSIM.UnitOperations.UnitOperations.CustomUO.Calculate(Object args) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.UnitOperations\UnitOperations\PythonScriptUO.vb:line 303
>    at DWSIM.SharedClasses.UnitOperations.BaseClass.Solve() in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.SharedClasses\BaseClass\SimulationObjectBaseClasses.vb:line 465
>    at DWSIM.FlowsheetSolver.FlowsheetSolver.CalculateObjectAsync(Object fobj, CalculationArgs objArgs, CancellationToken ct) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.FlowsheetSolver\FlowsheetSolver.vb:line 316
>    at DWSIM.FlowsheetSolver.FlowsheetSolver.ProcessQueueInternalAsync(Object fobj, CancellationToken ct) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.FlowsheetSolver\FlowsheetSolver.vb:line 662

Component: Water
Property package: IAPWS-IF97

**Comment by DanWBR** [comment]
@HaSchneider for some reason Python initialization failed... what is your Python version? did you double-check if the path to the python3 DLL is correct?

**Comment by HaSchneider** [comment]
Today it works, probably the restart of DWSIM made it. I am sorry, I thought I tested it proper before.
