### ISSUE TITLE
[Bug] PNET-1 Free Network designer not working on 8.6.0

### ISSUE THREAD

**Issue by ghola2023** [DanWBR/dwsim6#535]
Using Network designer 1.3.1
On DWSIM 8.5.1, it works great.
On 8.6.0, when i click on an element, it just  ultra-zooms in, not opening the dialog box
![image](https://github.com/DanWBR/dwsim/assets/143087177/e34670b2-22e2-4b0f-922e-b794f8201329)

**Comment by DanWBR** [comment]
@ghola2023 it is fixed in DWSIM v8.6.1.
