### ISSUE TITLE
[Bug] Object Editor: Results Never Updates

### ISSUE THREAD

**Issue by tlorance** [DanWBR/dwsim6#539]
I am trying to use DWSIM to simulate LLE (I know, that's not what it's designed for, but it does seem to be capable).  I am doing this by setting up a material feed, setting the appropriate mole fractions in the Object Editor: Properties, then updating to calculate the flowsheet.  I then look at Object Editor: Results to see what happened, but I notice that many (but not all!) of the fields have not updated since I first set the mole fractions: resetting and recalculating does not update the entire Results tab.  For example, the feed composition updates, but the mole fractional compositions of each phase do not.
I tried looking at the Material Stream output instead; this updates more properties (but not all; for example, it updates the mixture mole fractions, but not the overall liquid mole fractions).
Additionally, when computing a 0.5:0:0.5 mole fraction mixture of water-acetone-dichloromethane, the Results show that there is a small quantity of acetone in each phase.  That is probably just an artifact of the UNIFAC method and the equilibrium solver.

**Comment by DanWBR** [comment]
@tlorance please provide more details as requested (operating system, DWSIM version, etc) and a sample file if possible.
