### ISSUE TITLE
[Bug] Controller Logic Block - Manipulated Object Selection

### ISSUE THREAD

**Issue by Arock94** [DanWBR/dwsim6#540]
**Describe the bug**
When selecting the to be manipulated object in the Controller Logic Block the drop down list is not in alphabetical/numerical order which makes it very difficult to find the right stream in bigger flowsheets.

**To Reproduce**
Problem should be the same for all flowsheets.

**Expected behavior**
Please update DWSim so it shows the drop down list in order.

**Screenshots**
Tried to provide a screenshot, but list disappears everytime I try to print or screenshot the screen.

**Desktop (please complete the following information):**
Windows 10, DWSim v8.4.6

**Comment by DanWBR** [comment]
@Arock94 it should be ordered alphabetically in v8.6.1, did you try it?

**Comment by Arock94** [comment]
Just updated my version and it is in order now. Sorry! And thanks for the quick reply :)
