### ISSUE TITLE
Calculation error on conversion equation set

### ISSUE THREAD

**Issue by rlrb1** [DanWBR/dwsim6#541]
Hello Daniel
as reported before the problem is in the unit Brenner. When I change the reaction sets "Verbrennung" with "Verbrennung neu" I get different energy results. The only difference in my eyes is, that I use a specific sequence for the "Verbrennung neu" reaciton set. Please check and correct.

**Comment by rlrb1** [comment]
Dear Daniel,
I see that the case is closed, however, I do not understand the result. Do I have to install an update?
Best regards
Roland

--
Dr.-Ing. Roland Berger
___________________________________
[ef-logo]
e-flox GmbH - Dornierstr. 14 - 71272 Renningen
Tel.: +49 (0)7159 18086-51
Mobile: +49 (0)162 2455537
e-mail: ***@***.******@***.***>

Amtsgericht Stuttgart – HRB 253351
Geschäftsführer: Dr. Roland Berger, Dr. Joachim G. Wünning

Von: Daniel Wagner ***@***.***>
Gesendet: Mittwoch, 4. Oktober 2023 15:31
An: DanWBR/dwsim ***@***.***>
Cc: Roland Berger ***@***.***>; Author ***@***.***>
Betreff: Re: [DanWBR/dwsim] Calculation error on conversion equation set (Issue #541)


Closed #541<https://github.com/DanWBR/dwsim/issues/541> as completed.

**Comment by DanWBR** [comment]
@rlrb1 the code was fixed and it will be included in the next release.

**Comment by rlrb1** [comment]
OK, thank you!!

--
Dr.-Ing. Roland Berger
___________________________________
[ef-logo]
e-flox GmbH - Dornierstr. 14 - 71272 Renningen
Tel.: +49 (0)7159 18086-51
Mobile: +49 (0)162 2455537
e-mail: ***@***.******@***.***>

Amtsgericht Stuttgart – HRB 253351
Geschäftsführer: Dr. Roland Berger, Dr. Joachim G. Wünning

Von: Daniel Wagner ***@***.***>
Gesendet: Mittwoch, 4. Oktober 2023 20:03
An: DanWBR/dwsim ***@***.***>
Cc: Roland Berger ***@***.***>; Mention ***@***.***>
Betreff: Re: [DanWBR/dwsim] Calculation error on conversion equation set (Issue #541)


@rlrb1<https://github.com/rlrb1> the code was fixed and it will be included in the next release.
