### ISSUE TITLE
[Bug] mono-vbnc is not available in Debian 12

### ISSUE THREAD

**Issue by Irvise** [DanWBR/dwsim6#544]
**Describe the bug**
The provided `.deb` installation package cannot be installed in Debian as it depends on the package `mono-vbnc`. Here is the full log:

```
sudo dpkg -i dwsim_8.6.1-amd64.deb
Selecting previously unselected package dwsim.
(Reading database ... 74058 files and directories currently installed.)
Preparing to unpack dwsim_8.6.1-amd64.deb ...
Unpacking dwsim (8.6.1) ...
dpkg: dependency problems prevent configuration of dwsim:
 dwsim depends on mono-vbnc (>= 4.0); however:
  Package mono-vbnc is not installed.

dpkg: error processing package dwsim (--install):
 dependency problems - leaving unconfigured
Processing triggers for mailcap (3.70+nmu1) ...
Errors were encountered while processing:
 dwsim
```

The other requirements (such as `mono-complete`) are available.

**To Reproduce**

1. Go to a Debian 12 OS
2. Download the latest `.deb` installation media from Github. At the time of writing this issue, it is version 8.6.1
3. Run `sudo dpkg -i dwsim_8.6.1-amd64.deb`
4. `dpkg` complains that `mono-vbnc` could not be installed and that the installation may be broken. It leaves DWSIM unconfigured.
5. Launch DWSIM with `dwsim`. The GUI opens, however, if any Sample is selected the following error appears:

```
Could not load file or assembly 'Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
```

This may be expected as the VisualBasic compiler was not installed. However, `mono` has a "new" VB compiler that could be utilised, see https://github.com/mono/mono/blob/89f1d3cc22fd3b0848ecedbd6215b0bdfeea9477/scripts/vbc.in#L2

**Expected behavior**
DWSIM should install and run as expected. However, due to unavailable dependencies, it is unable to run

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux, Debian 12
 - Version v8.6.1

**Additional context**
I have seen that the Ubuntu repositories do have `mono-vbnc` available. Is DWSIM's `.deb` Ubuntu only?

Thank you for your time and work on DWSIM! It is a really nice piece of software!
Best regard,
Fernando

**Comment by einhander** [comment]
@Irvise you can use mono-vbnc deb package from older debian distribution.

**Comment by Irvise** [comment]
Hi. I downloaded `libmono-cecil-vb0.9-cil_4.7-0xamarin3+debian10b1_all.deb`, `libmono-microsoft-visualbasic10.0-cil_4.7-0xamarin3+debian10b1_all.deb` and `mono-vbnc_4.7-0xamarin3+debian10b1_all.deb` from Mono's repositories `https://download.mono-project.com/repo/debian/pool/main/m/mono-basic/`. I installed them and it now seems to work without issues :)

However, it seems that even the Mono project no longer supports these packages, as the latest builds are from 2020. The packages I downloaded are for Debian 10, no Debian 11 or Debian 12 packages are available. The latest packages for Ubuntu are 20.04.

Maybe there is an updated Mono packages that replaces `vbnc` which can be used instead as a dependency :)

Cheers,
Fer

P.S: feel free to close this issue if you deem it worthy.

**Comment by DanWBR** [comment]
@Irvise mono will soon become unsupported on all platforms. DWSIM will eventually switch to .NET 7 or 8 in the future.

**Comment by einhander** [comment]
>DWSIM will eventually switch to .NET 7 or 8 in the future.

@DanWBR what UI library will be used in this case?

**Comment by DanWBR** [comment]
@einhander I would have to create a new UI from scratch... using MAUI maybe?

**Comment by einhander** [comment]
@DanWBR MAUI doesn't work on Linux systems. AvalonoaUI https://github.com/AvaloniaUI/Avalonia has support of all modern OS and browser support and said to be similar to WPF.
