### ISSUE TITLE
[Bug]  Issues with SetExtraProperty and AddExtraPropertyValue 

### ISSUE THREAD

**Issue by Elliott-Kingston** [DanWBR/dwsim6#545]
Hi, 

I have some code in a python.NET object that uses the  SetExtraPropertyValue and AddExtraProperty commands. This code was very reliable in the 7.5.1 version, but no longer works in 8.6.1.

The AddExtraProperty does create the new variable, but SetExtraPropertyValue does not give it a value. So when I export data, or just copy the process data, the new property is there, but does not have a value associated with it. I can access the property with the value in the python.NET script, but can't seem to access it anywhere else. Additionally, it no longer shows up using the hover zoom function. 

```
def add_or_set_property(stream, property_name, value):
    try:
        stream.AddExtraProperty(property_name, value)
    except:
        pass
   
    stream.SetExtraPropertyValue(property_name, value)

    return stream
```

**Comment by DanWBR** [comment]
@wraithsmovefast It might be an issue with python.net as I didn't change anything on both functions...

https://github.com/DanWBR/dwsim/blob/a35e616731c8b70fd19aa9783dbb769bb39c7501/DWSIM.SharedClasses/BaseClass/SimulationObjectBaseClasses.vb#L159-L169

try removing the "try" block to see if you get an exception or get the stream as an object to be able to access all its members.

`stream = stream.GetAsObject()`
