### ISSUE TITLE
[Bug] при добавлении к модели с ректификационной колонной на основе ChemSep дополнительного аппарата AirCooler программа дает сообщение об ошибке следующего содержания: "Check input parameters. If this error keeps occurring, try another Property Package and/or Flash Algorithm".

### ISSUE THREAD

**Issue by HMG69** [DanWBR/dwsim6#546]
при добавлении к модели с ректификационной колонной на основе ChemSep дополнительного аппарата AirCooler программа дает сообщение об ошибке следующего содержания: "Check input parameters. If this error keeps occurring, try another Property Package and/or Flash Algorithm".
![bug aircooler](https://github.com/DanWBR/dwsim/assets/117921346/986e7096-36fb-4f8a-a624-fa3adbf9e729)

**Comment by einhander** [comment]
@HMG69 напиши по английски, пожалуйста. Write in English please.

**Comment by DanWBR** [comment]
@HMG69 This is not a generic error and depends on your thermo settings. Try changing the equilibrium calculation parameters adding and using a new property package if required.

**Comment by HMG69** [comment]
Good afternoon Daniel! Unfortunately, your advice to change the package of thermodynamic properties did not work. As before, adding an air cooler to the distillation column model gives an error when performing the calculation. Without an air cooler, the calculation is performed. If you run the model of an air refrigerator in a separate file with the same package of properties, then everything works too. it doesn't work together.  I attach the file.
________________________________
От: Daniel Wagner ***@***.***>
Отправлено: 13 октября 2023 г. 17:33
Кому: DanWBR/dwsim ***@***.***>
Копия: HMG69 ***@***.***>; Mention ***@***.***>
Тема: Re: [DanWBR/dwsim] [Bug] при добавлении к модели с ректификационной колонной на основе ChemSep дополнительного аппарата AirCooler программа дает сообщение об ошибке следующего содержания: "Check input parameters. If this error keeps occurring, try anot...


@HMG69<https://github.com/HMG69> This is not a generic error and depends on your thermo settings. Try changing the equilibrium calculation parameters adding and using a new property package if required.

**Comment by DanWBR** [comment]
@HMG69 I would like to try to reproduce this issue, can you share a flowsheet with just the air cooler and the connected streams?

**Comment by HMG69** [comment]
good day! I am sending a file with a model of an air refrigerator and a file of a distillation column and an air refrigerator that are not connected by technological flows. in the version of the air refrigerator only, everything works. there is an error in the column + air cooler option.


________________________________
От: Daniel Wagner ***@***.***>
Отправлено: 10 ноября 2023 г. 3:30
Кому: DanWBR/dwsim ***@***.***>
Копия: HMG69 ***@***.***>; Mention ***@***.***>
Тема: Re: [DanWBR/dwsim] [Bug] при добавлении к модели с ректификационной колонной на основе ChemSep дополнительного аппарата AirCooler программа дает сообщение об ошибке следующего содержания: "Check input parameters. If this error keeps occurring, try anot...


@HMG69<https://github.com/HMG69> I would like to try to reproduce this issue, can you share a flowsheet with just the air cooler and the connected streams?

**Comment by DanWBR** [comment]
@HMG69 you'll need to come to github and attach the file (zipped) here directly

**Comment by HMG69** [comment]
Added a file demonstrating an error in the interaction of the distillation column model and the air cooler.
[column +air cooler.zip](https://github.com/DanWBR/dwsim/files/13325129/column.%2Bair.cooler.zip)
