### ISSUE TITLE
Pump curves are not being correctly saved [Bug] 

### ISSUE THREAD

**Issue by ghola2023** [DanWBR/dwsim6#548]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
When i insert a pump curve and save the file, when i open it again, it returns crazy numbers. 

**To Reproduce**

PLEASE ATTACH THE ZIPPED FLOWSHEET FILE and/or inform the steps to reproduce the behavior:
![Pump curve](https://github.com/DanWBR/dwsim/assets/143087177/c0d6407d-93b6-4edb-9e6a-767bbbe06a5a)

**Expected behavior**

**Screenshots**
[Curva da bomba.zip](https://github.com/DanWBR/dwsim/files/13031374/Curva.da.bomba.zip)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS]
 - Version [e.g. v6.4.1]

**Additional context**

**Comment by DanWBR** [comment]
@ghola2023 please use dot as decimal separator for this specific tool.

**Comment by DanWBR** [comment]
@ghola2023 in the next update you will be able to use your system-defined decimal separator.
