### ISSUE TITLE
Redundant Kij for Water and CO2

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#55]
DWSIM 6.3 update 5 (and latest from source)
[test_ogsp.zip](https://github.com/DanWBR/dwsim6/files/5612784/test_ogsp.zip)

When editing binary interaction parameters water-co2 is represented both as co2-water and water-CO2 and with different values
![image](https://user-images.githubusercontent.com/58475535/100552330-e0980e00-3286-11eb-8f3b-7078030e60b1.png)

It does not seem to be a problem for other pairs, but haven't made a thorough check

**Comment by DanWBR** [comment]
I couldn't reproduce this issue with the latest code, but don't remember exactly when and if I did something to fix it. 😅

**Comment by andr1976** [comment]
It is still here - in this one for water and N-decane

![image](https://user-images.githubusercontent.com/58475535/103447889-a8268e00-4c91-11eb-807c-c62eca73da0c.png)


[flashtest.zip](https://github.com/DanWBR/dwsim6/files/5759556/flashtest.zip)

**Comment by DanWBR** [comment]
If you create a new simulation, does it happen too? I've tested with a new one. Existing files will have both kijs, unfortunately.

**Comment by andr1976** [comment]
Only for existing ones, for a new one it seems fine

**Comment by DanWBR** [comment]
<img width="688" alt="Captura de Tela 2021-01-01 às 19 54 25" src="https://user-images.githubusercontent.com/2669419/103448119-43f0d380-4c6b-11eb-963f-30402a866039.png">
