### ISSUE TITLE
[Bug] Fuel Cell UO, Python Error

### ISSUE THREAD

**Issue by WillyLund** [DanWBR/dwsim6#551]
Daniel,

I upgraded to 8.6.5 based on your note during the last Sim365 User Group Meeting that H2/O2 streams were now separate in the electrolyser.  I ran into an issue with the Fuel Cell in my simulation.  I decided see if the sample electrolyzer model works and it does not for me.  The following is the debug information from the sample simulation.  Thanks in advance.  Willy

Here are images of the sample simulation.
![image](https://github.com/DanWBR/dwsim/assets/108375143/316bd302-e04c-4baf-8b32-387ffc2840bb)
![image](https://github.com/DanWBR/dwsim/assets/108375143/9ff904ca-b7e1-4e9e-9a3b-5938e880a32e)

This is the Event Information
![image](https://github.com/DanWBR/dwsim/assets/108375143/51871437-cd79-424e-bc76-0991eac51801)

Event Type: Error (Exception)

Description:
This error was raised during the calculation of a Unit Operation or Material Stream.

System.Exception: Please define the path to a valid Python 3.7-3.9 distribution in General Settings and try again.
   at DWSIM.GlobalSettings.Settings.InitializePythonEnvironment(String pythonpath) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.GlobalSettings\Settings.vb:line 219
   at DWSIM.UnitOperations.UnitOperations.PEMFC_Amphlett.Calculate(Object args) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.UnitOperations\UnitOperations\CleanEnergies\PEMFC_Amphlett.vb:line 82
   at DWSIM.SharedClasses.UnitOperations.BaseClass.Solve() in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.SharedClasses\BaseClass\SimulationObjectBaseClasses.vb:line 465
   at DWSIM.FlowsheetSolver.FlowsheetSolver.CalculateObjectAsync(Object fobj, CalculationArgs objArgs, CancellationToken ct) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.FlowsheetSolver\FlowsheetSolver.vb:line 316
   at DWSIM.FlowsheetSolver.FlowsheetSolver.ProcessQueueInternalAsync(Object fobj, CancellationToken ct) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.FlowsheetSolver\FlowsheetSolver.vb:line 662

Location:
Code Location: InitializePythonEnvironment (file 'C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.GlobalSettings\Settings.vb', line 219)

Calling Method: Calculate (file 'C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.UnitOperations\UnitOperations\CleanEnergies\PEMFC_Amphlett.vb', line 82)

Mitigation Actions:
Check input parameters. If this error keeps occurring, try another Property Package and/or Flash Algorithm.

**Comment by DanWBR** [comment]
@WillyLund do you have a python environment in your system? you need one

**Comment by WillyLund** [comment]
Hello Daniel,

Thanks for the very quick response.

The short answer is no.

I just reviewed the install instructions/notes and did not see this as a prerequisite.  In fact, I am seeing on the 8.5.0 notes the removal of python environment package dependency.

Perhaps that is something to make more obvious and/or have the installer check for that as a prerequisite (and/or error messaging indicating the need?).  Early versions of the Fuel Cell UO, did not need this so I am finding this as a "surprise".

Obviously as this is a prerequisite, I will take care of that at my end.

Best Regards,

Willy Lund
Carbon 280 Pty Ltd  ACN 634 760 606
+1 (732) 600 3975 (mobile) USA
***@***.******@***.***>
 www.carbon280.com<http://www.carbon280.com/>
         ***@***.***

**Comment by DanWBR** [comment]
@WillyLund earlier versions had that separate python environment but it was unnecessarily too big. What I did in recent versions is to include the required modules as part of DWSIM and then you only need to tell it where your python environment is. I don't include a python env because most users don't need it and it would more than double the installer file size.

You should have seen this in the error panel: "Please define the path to a valid Python 3.7-3.9 distribution in General Settings and try again." I thought it was clear enough.
