### ISSUE TITLE
[Enhancement] Encrypted modelfile

### ISSUE THREAD

**Issue by KnarfSkidbacke** [DanWBR/dwsim6#552]
Can all files related to a specific model be stored in a separate directory which can be compressed and/or encrypted using a password/pin code (minlength 6 char).
The password must be given every time the modle is used, thus the compressed/emcrypted file must be unlocker & unpacked on the fly upon use, and zipped/compressed after use.

The idea is to have  a single file to send via email to various parties.

**Comment by DanWBR** [comment]
Go to Simulation Settings > Information:

![image](https://github.com/DanWBR/dwsim/assets/2669419/feca250c-4169-405e-b36a-0c58942a797a)
