### ISSUE TITLE
[Bug] Energy Mixer default dimensions

### ISSUE THREAD

**Issue by seawasp2** [DanWBR/dwsim6#554]
**Describe the bug**
When you insert an "Energy Mixer" to the Flowsheet from the Object Pallet, the default dimensions are Length 40, Height 40. The default sizes for other objects are Length 20, Height 20.

**Screenshots**
![Energy Mixer](https://github.com/DanWBR/dwsim/assets/28864463/4388eca9-9f3e-4dc8-9c45-c07956d8840c)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 8.6.5 (Classic UI 64 bit) and earlier

**Additional context**
Only a minor bug :-). Thank you

**Comment by DanWBR** [comment]
@seawasp2 are you a Patron?

**Comment by seawasp2** [comment]
I am now, and it's about time. 
:-)

**Comment by DanWBR** [comment]
Oh @seawasp2 I'm really sorry. I thought that this unit op was a patron exclusive and just wanted to check who you could be... Thanks anyway! 😅

**Comment by seawasp2** [comment]
No worries, you gave me the kick I've needed
