### ISSUE TITLE
[Bug] Phase envelope issues

### ISSUE THREAD

**Issue by petroconsulting** [DanWBR/dwsim6#555]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
The calculation of bubble and dew points in proximity to the critical point seems flawed (using SRK). 

**To Reproduce**

PLEASE ATTACH THE ZIPPED FLOWSHEET FILE and/or inform the steps to reproduce the behavior:

[Gas phase envelope.zip](https://github.com/DanWBR/dwsim/files/13356693/Gas.phase.envelope.zip)

**Expected behavior**
A continuous bubble point line, the critical point, and a continuous dew point line.

**Screenshots**
![image](https://github.com/DanWBR/dwsim/assets/80123827/44f3536d-d50e-42a5-9eb7-222da9ffea39)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 10.0.19045 Build 19045

**Additional context**

**Comment by DanWBR** [comment]
@petroconsulting this is the best I could get with these custom settings. I'll check why the dew line isn't continuing further to the critical point.

<img width="702" alt="Captura de Tela 2023-11-16 às 09 50 37" src="https://github.com/DanWBR/dwsim/assets/2669419/111cb9d1-5efb-4a23-9ff1-2015f49a74dc">

<img width="350" alt="Captura de Tela 2023-11-16 às 09 50 49" src="https://github.com/DanWBR/dwsim/assets/2669419/9cf4641a-1e01-4f0c-990a-4adc5e7b9002">

<img width="356" alt="Captura de Tela 2023-11-16 às 09 51 01" src="https://github.com/DanWBR/dwsim/assets/2669419/94bc78a8-3a60-48b4-abbb-36819c624b21">

**Comment by petroconsulting** [comment]
Daaniel: Many thanks for your response. Please check the stability limit curve as well. Thanks

**Comment by DanWBR** [comment]
> Daaniel: Many thanks for your response. Please check the stability limit curve as well. Thanks

@petroconsulting why, is it wrong?

**Comment by petroconsulting** [comment]
Daniel: I am not familiar with the concept of stability limit within a phase envelope. However, I read the following concept: "The stability limit in a phase envelope is a concept in thermodynamics that refers to the maximum range of compositions for which a mixture of two or more components is stable in a given phase". The orange curve depicted in the figure above seems to indicate a very limited domain of potential two-phase stable states, is not it?
