### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Mike-Groves** [DanWBR/dwsim6#559]
**Describe the bug**
I am trying to model the gas phase ammonia oxidation of the Ostwald process for manufacturing nitric acid. 
The Conversion Reactor runs properly if the reactions NH3 -> NO and NH3 -> N2 are activated, but if additionally the reaction NH3 -> N2O is activated the calculation fails with "Errror in 'Name of Reactor': Tried to calculate equilibrium with invalid mixture composition: { NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, } {PropertyPackage.vb, 2460 }"
In Settings | Thermodynamics the Phase Equilibria Calculation Type is set to "Don't Calculate" and the Fail-Safe Procedure is set to "Do Not Calculate Equilibrium".
I have tried several Thermodynamic Property Packages - Raoult's Law, PR, PR/LK, but the problem was not solved.

**To Reproduce**
Two flowsheet files are attached, the one with the N2O reaction deactivated runs correctly, the other one with the N2O reaction activated reproduces the problem when run.

**Expected behavior**
The Conversion Reactor should provide a solution even with the N2O formation reaction active. The outlet temperature should be roughly 900°C

**Screenshots**
Screenshots not supplied.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 22H2 (Build 19045.3693)

**Additional context**
[ConversionReactor_N2O_Problem_20231130_DWSIM-InputFiles.zip](https://github.com/DanWBR/dwsim/files/13515800/ConversionReactor_N2O_Problem_20231130_DWSIM-InputFiles.zip)

Thanks for any help with this issue.

**Comment by DanWBR** [comment]
@Mike-Groves the N2O reaction phase is set to Liquid. 🤧

**Comment by Mike-Groves** [comment]
Thanks! I'm a donkey for not seeing that.
