### ISSUE TITLE
Multiple dependent controller blocks doesn't work correct in simultaneous mode

### ISSUE THREAD

**Issue by buchbema** [DanWBR/dwsim6#562]
![image](https://github.com/DanWBR/dwsim/assets/121129465/194b00d1-6d88-4796-930d-02b7def2aa23)

Multiple dependent controller blocks doesn't converge correctly. I have to set one controller inactive, or solve one manually.

It seems that dependent controller doesn't recalculate until the setpoint is reached.

**Comment by DanWBR** [comment]
fixed in https://github.com/DanWBR/dwsim/commit/81bc3f0b76213e6eacd87993e2773fe54cf00107
