### ISSUE TITLE
"What's New in DWSIM" dialog hides "Update Available" dialog[Bug] 

### ISSUE THREAD

**Issue by davetow** [DanWBR/dwsim6#567]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
"What's New in DWSIM" dialog hides "Update Available" dialog.  This makes it impossible to use DWSIM, because you can't move/dismisss the "What's New in DWSIM" dialog until you click "OK" or "Cancel" on the obscured "Update Available" dialog.  Only a problem with screen sizes less than 1600x1024.  Also deselecting "Check for Updates" doesn't help.

**To Reproduce**

1. Change screen resolution to something smallish (say 1280x1024)
2. run DWSIM
3. try to close the "What's New in DWSIM" or Cancel update.

**Expected behavior**
Proceed to DWSIM and create a project or load an existing one.  Can't easily access anything because the "What's New in DWSIM"

**Desktop (please complete the following information):**
 - Windows 10 x64
 - Version 8.6.6 now that there is a 8.6.7 was a problem with 8.6.5

**Comment by DanWBR** [comment]
@davetow please re-download the installer and try again.
