### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#57]
When creating hypo/pseudo components for an already characterised fluid (say from PVTsim or other fluid characterisation software) Tc, Pc, omega, Vc/Zc may already be known in addition to NBP, MW and SG. It could be nice to be able to enter these manually in the Tools/petroleum C7+ characterisation and then avoid those being estimated - including MW, SG and NBP. 

This is a variation of a former feasture request.

**Comment by DanWBR** [comment]
<img width="615" alt="Captura de Tela 2021-05-12 às 09 58 14" src="https://user-images.githubusercontent.com/2669419/117987704-bbfd9300-b308-11eb-8836-1e11937a03c0.png">
<img width="792" alt="Captura de Tela 2021-05-12 às 09 58 37" src="https://user-images.githubusercontent.com/2669419/117987717-be5fed00-b308-11eb-94aa-132ae152e79b.png">

**Comment by andr1976** [comment]
Alright @DanWBR, very nice. Will look forward to testing it. Is it required to enter all data? or can existing correlations already present in DWSIM be used to automatically estimate "blank" fields ?

**Comment by DanWBR** [comment]
@andr1976 the idea is that you can edit all values in the table after they were calculated. you can choose to edit what you want. before creating the stream I check if the table was edited in order to update the compound properties.
