### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by vishakha-618** [DanWBR/dwsim6#574]
Hii Daniel

There is a inbuilt sample project with the name of "Petroleum distillation".

I just try to run. It is showing error.
![Screenshot 2024-01-16 185735](https://github.com/DanWBR/dwsim/assets/156805573/3371da75-88a5-4acd-a119-bd5451cfe068)

**Comment by DanWBR** [comment]
@vishakha-618 sorry but this is not the file that is included as a sample. it looks like you modified it.

and please, if it is something that you need help with, create a discussion topic, not a bug report.
