### ISSUE TITLE
[Bug] Dynamic Simulation Broken

### ISSUE THREAD

**Issue by aishkumar-iitkgp** [DanWBR/dwsim6#578]
**Describe the bug**
Dynamic Simulation appears to be broken in Version 8.6.7

**To Reproduce**

1. Go to Samples
2. Scroll down and click on "Dynamic Simulation - Water Tank Level Control"
3. Follow Instructions:
             3.1 - Enable Dynamic Mode
             3.2 - Open the Integrator Controls Panel
             3.3 - Run the Schedule
     

**Expected behavior**
A new trend should form and the Results spreadsheet should populate with new data.

**Actual behavior**
Nothing happens, no warning or error. No data gets updated/calculated.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - DWSIM Version 8.6.7

**Additional context**
Dynamic Simulation was working fine in Version 8.6.5

**Comment by DanWBR** [comment]
@aishkumar-iitkgp it works as expected, v8.6.7 on Windows 11:

<img width="1536" alt="Captura de Tela 2024-01-17 às 12 25 51" src="https://github.com/DanWBR/dwsim/assets/2669419/a7b8eeea-5056-4671-b805-cdbddf36d9aa">

**Comment by Naheulf** [comment]
This bug is UI dependent. I got it with with DWSIM 8.8.0 **Cross-Platform UI** but not with the legacy UI.
