### ISSUE TITLE
Steady-State: Heat exchanger is well calculated but if the simulation is run again, the answer changes

### ISSUE THREAD

**Issue by svidille** [DanWBR/dwsim6#593]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
First time, the heat exchanger was well calculated. However, when one runs the simulation again the cold side outlet changes.

**To Reproduce**

PLEASE ATTACH THE ZIPPED FLOWSHEET FILE and/or inform the steps to reproduce the behavior:

1. Open file
2. See cold side outlet temperature
3. Run the simulation again
4. See cold side outlet temperature

**Expected behavior**
The temperatures should be kept, no matter how many times the simulation is run.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 8.6.8

[8.Heat_Exchanger - copia.zip](https://github.com/DanWBR/dwsim/files/14110834/8.Heat_Exchanger.-.copia.zip)

**Comment by DanWBR** [comment]
@svidille did you replace the property package at some point before cutting this HX from the bigger flowsheet?

Also, the U and A for this HX don't seem realistic.

**Comment by DanWBR** [comment]
@svidille found the issue, thanks!
