### ISSUE TITLE
[Bug] Error with CSTR : Mass getting generated/consumed for non-participating compounds

### ISSUE THREAD

**Issue by nayakpriyam** [DanWBR/dwsim6#598]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
the mass of components that are not part of the reaction system changes after going through the CSTR. For example, in the attached file, in Stream 6, there is 3600 kg/h of methane and 400 kg/h of N-nonadecane, which doesn't participate in the reaction, but after going through the CSTR, there is 220.88 kg/h of methane and 420.22 kg/h of N-nonadecane.

**To Reproduce**
Run the attached DWSIM File

**Expected behavior**
The mass of non-reacting compounds before and after going through CSTR should remain same.

**Screenshots**
![image(1)](https://github.com/DanWBR/dwsim/assets/34299789/a0c03c10-4479-43ab-bd27-4060465be263)

**Desktop (please complete the following information):**
 - Windows OS
 - DWSIM v8.6.8

**Additional context**

[IssueCSTR.zip](https://github.com/DanWBR/dwsim/files/14322737/IssueCSTR.zip)

**Comment by DanWBR** [comment]
fixed on https://github.com/DanWBR/dwsim/commit/82e708091ef770d727be0db9cdf45a22ca339f36
