### ISSUE TITLE
[Bug] Component wise mass balance not getting satisifed in Distillation Column

### ISSUE THREAD

**Issue by nayakpriyam** [DanWBR/dwsim6#599]
**Describe the bug**
Although the distillation column's overall mass balance is satisfied, the component-wise balance is not satisfied. For example, there is 1200 kmol/hr of phenol in feed, whereas distillate has 200 kmol/hr and bottoms has 1200 kmol/hr. Also, other components in the feed, like toluene and MCH, are not present in distillate and bottoms.

**To Reproduce**
Run the attached DWSIM File : 
[DC-Error.zip](https://github.com/DanWBR/dwsim/files/14436322/DC-Error.zip)

**Expected behavior**
Component-wise mass balance should be satisfied.

**Screenshots**
![DC-Error](https://github.com/DanWBR/dwsim/assets/34299789/6f985d9a-1ef8-4871-ad88-bfbe572ba52f)

**Desktop (please complete the following information):**
 - Windows OS
 - DWSIM v8.6.8

**Comment by DanWBR** [comment]
@nayakpriyam in the next release it will work with the napthali-sandholm solver + NRTL. UNIFAC is slow. Bubble Point algorithm converges to a wrong solution because of the strong non-indeality of the system. I'll add an additional mass balance check for all compounds.
