### ISSUE TITLE
Compressor does not provide results although calculates (blue) then resets to default values

### ISSUE THREAD

**Issue by CKapp-slrconsulting** [DanWBR/dwsim6#600]
I have a simple suction line, compresser and discharge line. Everything is complete and I can hit the solve button and the diagram turns blue as it should, however my input values (flow, pressures, temps efficiency) turn to default, they actual values are not saved (trying to go from 500 PSIG and add another 1,000 PSIG.  The purpose of my calculation is to determine gas properties to LKP and estimate horsepower and discharge conditions.

My computer is windows 11 Dell laptop.

**Comment by DanWBR** [comment]
@CKapp-slrconsulting you need to press enter to confirm the new values

**Comment by CKapp-slrconsulting** [comment]
Thans Daniel. That simple and yes that worked. Chris


Christean Kapp
Principal Engineer - 
Air Quality
M
+1 832-349-2703
E
***@***.***
SLR International Corporation
Houston 
TX 
United States 

 

​Confidentiality Notice and Disclaimer
​This communication and any attachment(s) contain information which is confidential and may also be legally privileged. It is intended for the exclusive use of the recipient(s) to whom it is addressed. If you have received this communication in error, please e-mail us by return e-mail and then delete the e-mail from your system together with any copies of it. Any views or opinions are solely those of the author and do not represent those of SLR International Corporation, or any of its subsidiaries, unless specifically stated.
