### ISSUE TITLE
[Bug] Mass flow rate through heat exchanger stuck at 1kg/s regardless of settings

### ISSUE THREAD

**Issue by python50** [DanWBR/dwsim6#603]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
Looping the output of the heat exchanger to the input causes the mass flow to always equal 1kg/s. No parameter change appears to be able to change it.

For example if the mass flow of the feeding material stream is set to 0kg/s, or 1234kg/s, the resulting flow rate is always 1kg/s. Cutting the loop connection to the heat exhanger causes the bug to go away.

**To Reproduce**
Set mass flow rate of IN to any value.
Run simulation
Look at actual flow rate in results tab, it will always unexpectedly be 1kg/s when the loop is intact, and it will be the expected value if the loop is cut.

flow file, remove suffix .zip from filename
[test he loop.dwxmz.zip](https://github.com/DanWBR/dwsim/files/14627693/test.he.loop.dwxmz.zip)

**Expected behavior**
Flow rate should changed based on parameter changes to input material stream

It should not matter if the loop is cut or not.

**Screenshots**
see below
![mass flow](https://github.com/DanWBR/dwsim/assets/654209/c7259736-1d18-4d83-801f-e7346f228773)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version see version screenshot, latest version downloaded from website
 - 
![version](https://github.com/DanWBR/dwsim/assets/654209/842b8b67-07c4-400e-82df-8338cadffe54)

**Additional context**
Application: simulating heat recovery (for example, in a high efficiency distillation/water desalination system)

example of cutting/breaking the "loop"
![broken loop](https://github.com/DanWBR/dwsim/assets/654209/a71720dc-676c-4ff2-b36e-a30564f9864e)

**Comment by DanWBR** [comment]
@python50 you need a recycle block in the loop

**Comment by python50** [comment]
Would it be reasonable for me to reframe this bug report into "it should generate a warning or error message in this particular case"?

**Comment by DanWBR** [comment]
@python50 a message should be displayed in v8.7.0 already (latest release)
