### ISSUE TITLE
[Bug] Flowsheet view is reduced after deactivating contol panel mode. 

### ISSUE THREAD

**Issue by fairol1988** [DanWBR/dwsim6#607]
**Describe the bug**
In flowsheet. Display looks normal. Activated control panel mode and then deactivate it results in the flowsheet display view reduced into half. 

**To Reproduce**

PLEASE ATTACH THE ZIPPED FLOWSHEET FILE and/or inform the steps to reproduce the behavior:
[Dynamic Tutorial Level and pressure change.zip](https://github.com/DanWBR/dwsim/files/14737810/Dynamic.Tutorial.Level.and.pressure.change.zip)

1. Go to Flowsheet. You will see flowsheet view is normal
2. Click on Control Panel Mode. Control panel mode view is normal
3. Click again on Control Panel Mode to return to flowsheet. Now view display is reduced to half

**Expected behavior**
The flowsheet view is reduced to half despite dwsim is maximized. Closing and reopening dwsim and file results in the view becoming back to normal. 

**Screenshots**
![image](https://github.com/DanWBR/dwsim/assets/164822807/c1f6b872-17c7-4702-821a-e47f49416039)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [e.g. v8.7.0]

**Others
 - My Laptop is configured to have 3 monitors in extended display mode.

**Comment by DanWBR** [comment]
@fairol1988 thanks for reporting!
