### ISSUE TITLE
[Bug] Extra property values not showing in hover tooltips in DWSIM versions >8.2.1

### ISSUE THREAD

**Issue by alamarche** [DanWBR/dwsim6#610]
**Describe the bug**
_Not sure if this is necessarily a bug, but it seems to be one to me_

Upon attempting to upgrade from v8.2.1 to v8.7.0, we've noticed that added extra property values no longer show by default in the hover tooltips. I'm able to verify that the extra property values are set via "Display Anchored Property Lists" in v8.7.0, but the tooltips remain empty for both objects:

![image](https://github.com/DanWBR/dwsim/assets/20865894/a4c80aba-5e21-4ee8-b884-3737bcd1900c)

Here's the expected result in v8.2.1, where the properties appear in the hover tooltips:

![image](https://github.com/DanWBR/dwsim/assets/20865894/aa253a94-e7c8-44d1-a32f-5b0f9fe5daa5)

![image](https://github.com/DanWBR/dwsim/assets/20865894/0a883e2a-b969-46ea-b9fe-842c17f10819)

**To Reproduce**
See the attached .dwxml. All that's needed to understand the difference in behavior between the versions is to run the flowsheet.
[test.zip](https://github.com/DanWBR/dwsim/files/14764989/test.zip)

**Expected behavior**
Defined ExtraProperties for an object inheriting from [BaseClass](https://dwsim.org/api_help/html/T_DWSIM_SharedClasses_UnitOperations_BaseClass.htm) to appear in DWSIM hover tooltips

**Screenshots**
See bug description.

**Desktop (please complete the following information):**
 - Windows 11
 - DWSIM v8.7.0

**Additional context**
A key usability feature of DWSIM for me and the folks in my organization is the ability to quickly look at process values by hovering over material/energy streams and unit operations. Given what we're trying to achieve and the amount of CustomUOs we use, we often rely on [Extra Properties](https://dwsim.org/api_help/html/P_DWSIM_SharedClasses_UnitOperations_BaseClass_ExtraProperties.htm) (and their visibility upon hover) to achieve this.

**Comment by DanWBR** [comment]
@alamarche thanks for reporting
