### ISSUE TITLE
DWSIM 8.5.1 Region 5 Steam tables weird answers [Bug] 

### ISSUE THREAD

**Issue by nettenergy** [DanWBR/dwsim6#613]
Specifying a temperature above 800C on a heater when only using water as single component gives temperature of 1700C in return.
Below 800C I get the same temperature back.
Using the steam tables.
Please check code

**Comment by DanWBR** [comment]
@nettenergy This is a limitation of the steam tables implementation in DWSIM. https://github.com/DanWBR/dwsim/blob/windows/DWSIM.Thermodynamics/PropertyPackages/Models/SteamTables_IAPWS_IF97.vb

You can try to use CoolProp or Raoult's Law instead.

**Comment by nettenergy** [comment]
Hi Daniel,


Wow you are quick!


Weird in earlier docs I saw that you implemented region 5 in the steam tables.

 

Best regards, met vriendelijke groeten

Rob Vasbinder
Director
Burgemeester Colijnstraat 81
2771 GH Boskoop
The Netherlands
+31 172 232223
+31 6 42937974
 ***@***.***> ***@***.***
www.nettenergy.com <http://www.nettenergy.com/>

**Comment by DanWBR** [comment]
@nettenergy it didn't work, I guess

**Comment by nettenergy** [comment]
Coolprop did, thx

 

Best regards, met vriendelijke groeten

Rob Vasbinder
Director
Burgemeester Colijnstraat 81
2771 GH Boskoop
The Netherlands
+31 172 232223
+31 6 42937974
 ***@***.***> ***@***.***
www.nettenergy.com <http://www.nettenergy.com/>
