### ISSUE TITLE
[Bug] Cannot save DWSIM files with embedded flowsheet unit operations - null BsonValue `id` passed

### ISSUE THREAD

**Issue by alamarche** [DanWBR/dwsim6#617]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
While flowsheet unit operations work as expected in DWSIM v8.6.7 and v8.7.0, it is not possible to save them

**To Reproduce**
Unfortunately, I cannot provide the file embedding the base flowsheet - it's simple enough to recreate however.
1. Create simulation with methane and ethane (defaults for everything else is fine
2. Add DWSIM Flowsheet Unit Operation, add Material Streams connected to Inlet Stream 1 and Outlet Stream 1 (default stream conditions are fine. 
3. Reference external file [testembed.zip](https://github.com/DanWBR/dwsim/files/14843221/testembed.zip)
4. Open Control Panel in the Flowsheet Unit Operation, initialize material flows as follows
![image](https://github.com/DanWBR/dwsim/assets/20865894/ada3d35f-d4d3-4229-aa4a-ad42a57e3fbf)
5. Verify compound mapping is correct
6. Exit control panel
7. Run simulation (should run successfully
8. Attempt to save
9. Get the following error in the Information panel:

> Value cannot be null.
> Parameter name: id
> 
> System.ArgumentNullException: Value cannot be null.
> Parameter name: id
>    at LiteDB.LiteCollection`1.FindById(BsonValue id)
>    at LiteDB.LiteStorage`1.FindById(TFileId id)
>    at DWSIM.FileStorage.FileDatabaseProvider.ExportFile(String filename, String exportpath) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.FileStorage\FileDatabaseProvider.cs:line 64
>    at DWSIM.UnitOperations.UnitOperations.Flowsheet.SaveData() in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.UnitOperations\UnitOperations\FlowsheetUO.vb:line 1131
>    at DWSIM.FormMain.SaveXML(IVirtualFile handler, FormFlowsheet form, String simulationfilename) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM\Forms\MainWindow\FormMain.vb:line 3653
>    at DWSIM.FormMain.SaveXMLZIP(IVirtualFile handler, FormFlowsheet form) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM\Forms\MainWindow\FormMain.vb:line 3965
>    at DWSIM.FormMain.SaveFile(Boolean saveasync, Boolean dashboardpicker) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM\Forms\MainWindow\FormMain.vb:line 4544
>    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Expected behavior**
Successful file save

**Screenshots**
![image](https://github.com/DanWBR/dwsim/assets/20865894/d76df79c-79c5-4d12-81e3-0dea1dc2f413)

**Desktop (please complete the following information):**
 - OS: Windows
 - Tested on versions 8.6.7 and 8.7.0 - same behavior on both

**Additional context**
N/A

**Comment by DanWBR** [comment]
@alamarche thanks for reporting this issue 👍
