### ISSUE TITLE
[Enhancement] Improved DWSIM compilation instructions in README.md

### ISSUE THREAD

**Issue by alamarche** [DanWBR/dwsim6#619]
**Is your feature request related to a problem? Please describe.**
Over the years, I've occasionally gotten the itch to try and pursue DWSIM development. I'm usually stopped when the compilation steps don't result in a successful build of the SW.

**Describe the solution you'd like**
Sufficiently detailed instructions to result in successful builds. The general procedure I've been following has been:

1. Install VS Community Edition 2022 with the addons listed at the end of the feature request
2. Install required versions of the .NET Framework Developer Packs (4.6.1, 4.6.2, 4.8)
3. Reboot so VS Community recognizes that relevant versions of .NET Framework are detected
4. Open DWSIM.sln
5. Select build target to Release|x64
6. Restore Nuget packages (successfully)
![image](https://github.com/DanWBR/dwsim/assets/20865894/8ab264ed-a054-4c1a-80ab-ac86a9b4bd20)
7. Attempt to build
8. Get lots of errors

The most prominent error to me is the following, which occurs frequently.

> Reference required to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' containing the type 'IList(Of )'. Add one to your project.

This old bug report seems relevant, but unclear since I'm newer to .NET Framework
https://github.com/dotnet/standard/issues/542

**Describe alternatives you've considered**
I'm primarily a Linux user, and strangely I appeared to have better levels of success building using JetBrains Rider + Mono on that system (11 build errors vs. 210 on Win+VS). I had 8 of the same error cited above, but for the DWSIM.GlobalSettings package. I'll respond with the bug report from that machine.

**VS Community Install Info**

> Microsoft Visual Studio Community 2022
> Version 17.7.1
> VisualStudio.17.Release/17.7.1+34009.444
> Microsoft .NET Framework
> Version 4.8.09037
> 
> Installed Version: Community
> 
> Visual C++ 2022   00482-90000-00000-AA400
> Microsoft Visual C++ 2022
> 
> ASP.NET and Web Tools   17.7.266.26423
> ASP.NET and Web Tools
> 
> Azure App Service Tools v3.0.0   17.7.266.26423
> Azure App Service Tools v3.0.0
> 
> C# Tools   4.7.0-3.23403.2+09841218a495cafad75ba163350d1e8949d8e5d6
> C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Microsoft JVM Debugger   1.0
> Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
> 
> NuGet Package Manager   6.7.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/
> 
> NVIDIA CUDA 12.3 Wizards   12.3
> Wizards to create new NVIDIA CUDA projects and source files.
> 
> NVIDIA Nsight Visual Studio Edition   2023.3.1.23311
> NVIDIA Nsight Visual Studio Edition provides tools for GPGPU and graphics development.  Copyright © NVIDIA 2010 - 2023.
> •Direct3D® and DirectX® are registered trademarks of Microsoft Corporation in the United States and/or other countries.
> •Microsoft Detours is used under the Professional license (http://research.microsoft.com/en-us/projects/detours/).
> •Gardens Point Parser Generator Copyright 2005 Queensland University of Technology (QUT). All rights reserved.
> •Icons from Axialis Software used under the licensing terms found here: www.axialis.com
> •NLog Copyright © 2004-2006 Jaroslaw Kowalski (jaak@jkowalski.net)
> •zlib and libpng used under the zlib/libpnc license (http://opensource.org/licenses/Zlib) 
> •Breakpad Copyright ©2006, Google Inc. All rights reserved.
> •The OpenGL Extension Wrangler Library
> Copyright ©2008-2016, Nigel Stewart (nigels@users.sourceforge.net), Copyright ©2002-2008, Milan Ikits (milan.ikits@ieee.org), Copyright ©2002-2008, Marcelo E. Magallon (mmagallo@debian.org), Copyright ©2002, Lev Povalahev. 
> All rights reserved. 
> •LIBSSH2 Copyright ©2004-2007 Sara Golemon (sarag@libssh2.org), Copyright ©2005,2006 Mikhail Gusarov (dottedmag@dottedmag.net),Copyright ©2006-2007 The Written Word, Inc.,Copyright ©2007 Eli Fant (elifantu@mail.ru),Copyright ©2009-2014 Daniel Stenberg., Copyright ©2008, 2009 Simon Josefsson.
> All rights reserved. 
> •xxHASH Library Copyright ©2012-2014, Yann Collet. All rights reserved. 
> •FMT Copyright ©2012 - 2016, Victor Zverovich 
> •Font Awesome Copyright 2018 Fonticons, Inc. 
> •ELF Definitions Copyright (c) 2010 Joseph Koshy, All rights reserved.
> •Boost, used under the  Boost Software License (https://www.boost.org/users/license.html)
> •gsl-lite, The MIT License (MIT), Copyright (c) 2015 Martin Moene, Copyright (c) 2015 Microsoft Corporation. All rights reserved. 
> •Protocol Buffer, Copyright 2008 Google Inc.  All rights reserved.
> •ThreadPool, Copyright (c) 2012 Jakob Progsch, Václav Zeman
> 
> The full text of the license for the OSS components used in this product is available as part of the Nsight Visual Studio Edition EULA (https://docs.nvidia.com/nsight-visual-studio-edition/eula/index.html).
> 
> Warning: This computer program is protected by copyright law and international treaties. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law.
> 
> NVIDIA Nsight Visual Studio Edition - CUDA support   2023.3.1.23311
> NVIDIA Nsight Visual Studio Edition - CUDA support provides tools for CUDA development and debugging.
> 
> Test Adapter for Boost.Test   1.0
> Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.
> 
> Test Adapter for Google Test   1.0
> Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.
> 
> TypeScript Tools   17.0.20628.2001
> TypeScript Tools for Microsoft Visual Studio
> 
> Visual Basic Tools   4.7.0-3.23403.2+09841218a495cafad75ba163350d1e8949d8e5d6
> Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Visual Studio IntelliCode   2.2
> AI-assisted development for Visual Studio.

**Detailed list of compile errors**

[Book.xlsx](https://github.com/DanWBR/dwsim/files/14897656/Book.xlsx)

**Comment by alamarche** [comment]
Supplemental information from attempted build on Linux (probably out of scope for the ticket - not sure if you really support building from linux):

**System Information**
- Pop!-OS 22.04 LTS (Ubuntu)

**Mono Information**
```shell
$ apt list mono-* | grep installed | grep -v automatic

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

mono-complete/stable-focal,now 6.12.0.200-0xamarin2+ubuntu2004b1 amd64 [installed]
``` 

**Build Log Output (Errors)**
[readme.md](https://github.com/DanWBR/dwsim/files/14897718/readme.md)

**Comment by DanWBR** [comment]
@alamarche building on Linux is not supported. On Windows you missed installation of NET Core 2.1, I guess. I usually install the whole NET dev environment so I don't know exactly what packages are required.

**Comment by einhander** [comment]
@DanWBR can you provide instructions to build Linux version on Windows system?

**Comment by DanWBR** [comment]
@einhander first build **ReleaseWin**, then **ReleaseLinux** config, then check DistPackages/Linux

**Comment by alamarche** [comment]
Thanks, Dan. Figured building on Linux wasn't supported, mostly provided it as informative since I was surprised to get less errors. Installed .NET Core 2.1 and included some more package sets from the VS Installer. Built without error.

I'm going to close this out. I might write-up a few extra steps to the compiling section of README.md to help clarify for folks going forward.

**Comment by s1ntecs** [comment]
> Thanks, Dan. Figured building on Linux wasn't supported, mostly provided it as informative since I was surprised to get less errors. Installed .NET Core 2.1 and included some more package sets from the VS Installer. Built without error.
> 
> I'm going to close this out. I might write-up a few extra steps to the compiling section of README.md to help clarify for folks going forward.

Hello.

Please tell me what other packages you installed from VS Installer?

**Comment by DanWBR** [comment]
@s1ntecs you need mainly .NET 4.6.x, 4.7.x Targeting Packs and .NET Core 2.1, and the latest .NET Framework version (4.8.something)

**Comment by s1ntecs** [comment]
> @s1ntecs you need mainly .NET 4.6.x, 4.7.x Targeting Packs and .NET Core 2.1, and the latest .NET Framework version (4.8.something)


Thank you so much, out of 200 errors there are 8 left, now I will solve them 🙏
