### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by emerim** [DanWBR/dwsim6#624]
I'm not sure that here is the right place since it isn't a bug, but I didn't find wherelse to put it, but there is a mistake on the brazilian portuguse translation.
The "load file" is still in english. I think maybe "carregar arquivo" or "abrir arquivo" could be good translations.
![image](https://github.com/DanWBR/dwsim/assets/72926462/251213b1-cccd-4987-951d-b03893d8ad9c)

**Comment by DanWBR** [comment]
@emerim fixed in https://github.com/DanWBR/dwsim/commit/2b041b724826d7931e7b2d46e5fb3e3367612d8c

thanks!

**Comment by emerim** [comment]
Also, it says Windows instead of Janelas! In the upper menu bar

I can help with the translation also
