### ISSUE TITLE
[Bug]  Kinetics expression not interpreted correctly

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#629]
**Describe the bug**
Entering a kinetics expression engineering/scientific notation is not read properly:

The following expression for the nominator gives wrong results:
```
(17900*exp(-10475/T) * (R2*R1^1.5)/P1 - 2.57*10^16*EXP(-23871/T)*P1/(R1^1.5))
```
This gives the right results
```
((17900*EXP(-10475/T) * (R2 * R1^1.5)/P1) - (2.57*10000000000000000*EXP(-23871/T)*P1/(R1^1.5)))
```

When the notation 
```
e16
```
is used an error is thrown, since it is not interpreted, but no error is given for 

```
10^16
```

**To Reproduce**
See screenshots and attached simulation file

**Expected behavior**
The two PFR reactors should give identical results

**Screenshots**
![image](https://github.com/DanWBR/dwsim/assets/58475535/9e6ec09e-e41b-4bfd-958f-ad8343ff0381)

This expression gives wrong results (backward rate)
![image](https://github.com/DanWBR/dwsim/assets/58475535/ef23ff55-c4dd-425c-988e-7d266bdd7622)

This expression gives correct results:
![image](https://github.com/DanWBR/dwsim/assets/58475535/46733c28-76ff-4333-b878-6dec7fdf7fb1)

**Desktop (please complete the following information):**
 - OS:  Windows, 
 - Version 8.6.8

[Kinetics.zip](https://github.com/DanWBR/dwsim/files/15139194/Kinetics.zip)

**Comment by DanWBR** [comment]
@andr1976 the correct expression for 10^14 is 10E14

**Comment by andr1976** [comment]
RIght, of course works fine. Maybe an error message to be shown when using ^?  The error message for "1e4" like notation is also not very informative. Thanks a lot. I will close this one shortly

**Comment by DanWBR** [comment]
@andr1976 the parser is an external library (Ciloci.Flee)
