### ISSUE TITLE
[Enhancement]  User selected solver for PFR reactor (DotNumerics)

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#630]
Currently the implicit Runge-Kutta solver from DotNumerics is applied. However, the system is not necessarily stiff e.g. for single reaction systems. In that case the explicit Runge-Kutta is faster.  E.g. the two reactors in #629 solves twice as fast with the explicit method

![image](https://github.com/DanWBR/dwsim/assets/58475535/c48bcd34-c04f-41eb-95d5-81dafd4f4353)

![image](https://github.com/DanWBR/dwsim/assets/58475535/d2ead517-c4a3-4d6e-b107-9044a24632a2)

**Comment by DanWBR** [comment]
![image](https://github.com/DanWBR/dwsim/assets/2669419/78634dc4-5190-4ae9-8f24-2f4e5100062f)

**Comment by andr1976** [comment]
@DanWBR thanks man! 👍
