### ISSUE TITLE
Compressor doesn't calculate Discharge Temperature correctly [Bug]

### ISSUE THREAD

**Issue by CKapp-slrconsulting** [DanWBR/dwsim6#638]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug

I am calculating a simple propane (100%) compressor going from -38F 13 PSIG to 146 PSIG and the discharge temperature wants to be lower than the suction temperature, the E3 horsepower surprisingly seems right, the power numbers for suction and discharge seem to be wrong or misleading. see attachment-

 
<img width="272" alt="Screenshot 2024-05-08 142530" src="https://github.com/DanWBR/dwsim/assets/162160991/58d38d5b-fff1-4e6c-9a49-b805caba5adf">
 which is wrong. 

**To Reproduce**

PLEASE ATTACH THE ZIPPED FLOWSHEET FILE and/or inform the steps to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS]
 - Version [e.g. v6.4.1]

**Additional context**

**Comment by DanWBR** [comment]
@CKapp-slrconsulting what thermo model are you using? can you zip the file and attach it here?

**Comment by CKapp-slrconsulting** [comment]
Is this what you need, Dan?



Christean Kapp
Principal Engineer - 
Air Quality
M
+1 346-749 0356
E
***@***.***
SLR International Corporation
Houston, 
TX, 
United States 

 

​Confidentiality Notice and Disclaimer
​This communication and any attachment(s) contain information which is confidential and may also be legally privileged. It is intended for the exclusive use of the recipient(s) to whom it is addressed. If you have received this communication in error, please e-mail us by return e-mail and then delete the e-mail from your system together with any copies of it. Any views or opinions are solely those of the author and do not represent those of SLR International Corporation, or any of its subsidiaries, unless specifically stated.

**Comment by DanWBR** [comment]
@CKapp-slrconsulting please attach the zipped flowsheet file, and do not reply directly from the email, please come to github website to attach the file.

**Comment by CKapp-slrconsulting** [comment]
The github site did not allow me to attach the flowsheet file with that extension


Christean Kapp
Principal Engineer - 
Air Quality
M
+1 346-749 0356
E
***@***.***
SLR International Corporation
Houston, 
TX, 
United States 

 

​Confidentiality Notice and Disclaimer
​This communication and any attachment(s) contain information which is confidential and may also be legally privileged. It is intended for the exclusive use of the recipient(s) to whom it is addressed. If you have received this communication in error, please e-mail us by return e-mail and then delete the e-mail from your system together with any copies of it. Any views or opinions are solely those of the author and do not represent those of SLR International Corporation, or any of its subsidiaries, unless specifically stated.

**Comment by DanWBR** [comment]
@CKapp-slrconsulting you need to zip the simulation file

**Comment by CKapp-slrconsulting** [comment]
[Chiller.zip](https://github.com/user-attachments/files/15956514/Chiller.zip)
](url)

**Comment by DanWBR** [comment]
@CKapp-slrconsulting the attached flowsheet doesn't have a compressor named C-NGL

**Comment by andr1976** [comment]
@CKapp-slrconsulting the suction state is all liquid, and the energy stream is negative in the compressor. Something is wrong. However if you change the equation of state to pure Peng-Robinson the results look sane. I don't know why Lee-Kessler causes problems in the compressor calc (which effectively should be equal to a pump calc for liquid fluid).

**Comment by andr1976** [comment]
@DanWBR check-out the attached file. It shows the problem with discharge temperature for liquid propane for PR/LK vs PR

[Chiller2.zip](https://github.com/user-attachments/files/15957115/Chiller2.zip)

**Comment by CKapp-slrconsulting** [comment]
Many Thanks Dan for your detective work
