### ISSUE TITLE
Rugosity and thermal conductivity not displayed for default materials

### ISSUE THREAD

**Issue by AdrianDietz** [DanWBR/dwsim6#64]
**Describe the bug**
Rugosity and thermal conductivity not displayed for default materials

**To Reproduce**
1. Add a pipe to the flowsheet
2. Add a segment to the pipe
3. Select the type to straight tube section
4. Pick a default material

**Expected behavior**
see which rugosity and thermal conductivity will be used

**Screenshots**
See below

**Desktop (please complete the following information):**
 - Windows
 
**Additional context**
NA

![image](https://user-images.githubusercontent.com/34543041/102331721-791ed580-3f8b-11eb-85b7-f320aefa82ac.png)

**Comment by andr1976** [comment]
I can confirm the behaviour in the crossplatform gui 6.3 update 5. In Classic gui the values are visible, but only after placing the cursor and cliking in the boxes where the number is

**Comment by DanWBR** [comment]
<img width="441" alt="Captura de Tela 2021-01-01 às 19 22 43" src="https://user-images.githubusercontent.com/2669419/103447834-cb881380-4c66-11eb-9349-87923d1282d4.png">
