### ISSUE TITLE
Bug with Reaktoro property package

### ISSUE THREAD

**Issue by Strohkopf68** [DanWBR/dwsim6#644]
Hello,

I downloaded today the latest version of DWSIM.

I wanted simple to heat a NaOH solution with Reaktoro  property package.

Following message is coming:

System.Exception: Please define the path to a valid Python 3.7-3.9 distribution in General Settings and try again.
   at DWSIM.GlobalSettings.Settings.InitializePythonEnvironment(String pythonpath) in C:\Users\danie\source\repos\DanWBR\dwsim\DWSIM.GlobalSettings\Settings.vb:line 229
   at DWSIM.Thermodynamics.ReaktoroPropertyPackage.ReaktoroFlash.Flash_PT(Array Vx, Double T, Double P) in C:\Users\danie\source\repos\DanWBR\dwsim\DWSIM.Thermodynamics.ReaktoroPropertyPackage\ReaktoroFlash.vb:line 122
   at DWSIM.Thermodynamics.ReaktoroPropertyPackage.ReaktoroPropertyPackage.DW_CalcEquilibrium(FlashSpec spec1, FlashSpec spec2) in C:\Users\danie\source\repos\DanWBR\dwsim\DWSIM.Thermodynamics.ReaktoroPropertyPackage\ReaktoroPP.vb:line 143

Could you help me?

Alex

**Comment by DanWBR** [comment]
@Strohkopf68 This is not a bug, please read the message carefully:

**Please define the path to a valid Python 3.7-3.9 distribution in General Settings and try again**

**Comment by Strohkopf68** [comment]
Hello,

Many thanks for your reply !

I am very sorry for bothering you…

Nevertheless I don’t understand how to fix the problem…

How should I do to define the path to a valid Python 3.7-3.9 distribution in General Settings ?

Thanks for your help.

Alex

 

 

Best regards,

Alexandre STEHLIN

Founder

 

Mobile  +33 7 70 05 49 50

Email     ***@***.*** ***@***.***> 

Web       https://www.chem-eng.ch <https://www.chem-eng.ch/> 

 



 




Bitte denken Sie an die Umwelt bevor Sie diese E-Mail drucken!


Please think about the environment before you print this email!

 

 

 

 

 

De : Daniel Wagner ***@***.***> 
Envoyé : lundi 27 mai 2024 13:01
À : DanWBR/dwsim ***@***.***>
Cc : Strohkopf68 ***@***.***>; Mention ***@***.***>
Objet : Re: [DanWBR/dwsim] Bug with Reaktoro property package (Issue #644)

 

@Strohkopf68 <https://github.com/Strohkopf68>  This is not a bug, please read the message carefully:

Please define the path to a valid Python 3.7-3.9 distribution in General Settings and try again

**Comment by DanWBR** [comment]
![image](https://github.com/DanWBR/dwsim/assets/2669419/8eeef091-d846-4457-81e2-ba22b318c855)

**Comment by Strohkopf68** [comment]
Hi,

 

Many thanks for your help… I don’t know if am stupid but I don t manage to fix the problem….

 



I tried to give the link to the reaktoro py3.x package (from the file of DWSIM) but I have always this error

 



I tried reaktoro 3.7, 3.8 and 3.9…. always the same error…

 

So I downloaded from github

 



 

But I don’t see where it is extract…

 

Can you help me ? I am completely lost….

 

Alex

 

 

 

De : Daniel Wagner ***@***.***> 
Envoyé : lundi 27 mai 2024 13:30
À : DanWBR/dwsim ***@***.***>
Cc : Strohkopf68 ***@***.***>; Mention ***@***.***>
Objet : Re: [DanWBR/dwsim] Bug with Reaktoro property package (Issue #644)

 

image.png (view on web) <https://github.com/DanWBR/dwsim/assets/2669419/8eeef091-d846-4457-81e2-ba22b318c855>
