### ISSUE TITLE
[Bug] Property Override in Heat Exchangers with saltwater is very slow

### ISSUE THREAD

**Issue by magnuscarlsen** [DanWBR/dwsim6#646]
I need to model water saltier than 12% by mass. At lower salinities I have dealt with this with the seawater module, for higher salinities have added property overrides for density and heat capacity in "overallLiquid" based on pressure, temperature and salinity of the water. The water temp is up to 90 degC. If I run a model without a HX, the calculation takes a few seconds. If I add a heat exchanger to the model, then DWSIM freezes for 20-30 minutes, then it wakes up and calculates the flow sheet in a few seconds. Same flow sheet without property overrrides is also very fast. I think there is a bug in the HX with property overrides. 

You can replicate the error if you: Run the flow sheet to see the time it takes, if you remove the HX and the streams associated you'll see that it takes a few seconds. If there is an error in the code for the property override or in the flow sheet (like 0 flowrate, which causes the pipe calc to fial) the sheet calculates very quickly). 

I would have expected the flow sheet to be calculated in roughly the same amount of time as a flowsheet without exchangers. But I might have done something wrong in the setup?

**Desktop:**
 - OS: Windows 11, RAM 16,0 GB, Processor: 12th Gen Intel(R) Core(TM) i7-1260P   2.10 GHz
 - Version v8.7.1
[BaseModelShareable.zip](https://github.com/DanWBR/dwsim/files/15470643/BaseModelShareable.zip)

**Comment by andr1976** [comment]
@DanWBR would you have time to look at this - highly appreciated :-)

**Comment by DanWBR** [comment]
@magnuscarlsen create a new script and do this

![image](https://github.com/DanWBR/dwsim/assets/2669419/60edc9ac-229f-49e8-9ee5-9662183a597e)

**Comment by andr1976** [comment]
@magnuscarlsen can you confirm that this is a fix ?

**Comment by magnuscarlsen** [comment]
yes, it seems to work 👍 Thanks very much!
