### ISSUE TITLE
Pipe Schedule and Pipe Class

### ISSUE THREAD

**Issue by AdrianDietz** [DanWBR/dwsim6#65]
**Is your feature request related to a problem? Please describe.**
Currently it is required for a pipe section to introduce the inner and outer diameter, this is error prone, requires to look up in tables, etc.. 

**Describe the solution you'd like**
There are standards for diameter and schedules. These tables could be introduced while always keeping the possibility of custom. 

**Describe alternatives you've considered**
NA

**Additional context**
Pipe classes should also be available.

![image](https://user-images.githubusercontent.com/34543041/102332679-b33ca700-3f8c-11eb-9070-82a9475d6b59.png)

**Comment by andr1976** [comment]
Good point, I am currently working on the pipe segment, and will put this on the to-do list

**Comment by DanWBR** [comment]
The editors for the Cross-Platform UI are coded in C#. The Pipe Section editor is this one: https://github.com/DanWBR/dwsim6/blob/windows/DWSIM.UI.Desktop.Editors/UnitOperations/PipeSection.cs
