### ISSUE TITLE
Compound separator generates mass

### ISSUE THREAD

**Issue by rlrb1** [DanWBR/dwsim6#652]
Dear Daniel,
In the attached model (tested with versions 8.6.1, 8.7.0 and 8.7.1 the Biogas upgrader (left side) does not close the mass balance. The inlet streem is less than the two outlet streams. Maybe I make an error, but after two days trying to sort out I just hope that you can help me. 
[BTH400 22 HP_Met.zip](https://github.com/user-attachments/files/15928181/BTH400.22.HP_Met.zip)

Thank you in advance

**Comment by DanWBR** [comment]
@rlrb1 it will work in the next release, thanks for reporting!

**Comment by rlrb1** [comment]
Thank you Daniel, Look for ward for 8.8.
