### ISSUE TITLE
[Bug] General Settings tab is not opening

### ISSUE THREAD

**Issue by IgorLim98** [DanWBR/dwsim6#653]
**Describe the bug**
I'm trying to define the path to a python distributor in the geneal settings tab. However, when I try to open it, it doesn't appears anything, only a small window on the left as shown below.

 - OS: Windows
 - Version 8.7.1

![Capturar](https://github.com/DanWBR/dwsim/assets/67347893/e3ff67c3-0e16-41c5-8bc6-29db53d52015)

**Comment by DanWBR** [comment]
@IgorLim98 please redownload the installer and try again

**Comment by IgorLim98** [comment]
Hello, @DanWBR . I tried what you mentioned and uninstalled DWSIM, then downloaded the installer again. However, I still have the same error. When I click on the General Settings option, the window does not open correctly.
 
Could you tell me what should I try next?
