### ISSUE TITLE
[Bug] KDB/CHERIC compound import failing

### ISSUE THREAD

**Issue by jkittrell** [DanWBR/dwsim6#655]
**Describe the bug**
Importing online compounds from KDB/CHERIC appears not to work, although Chemeo seems to be working.

**To Reproduce**
Classic UI, v8.7.1, File\New Compound Creator
From Compound menu, Import from online sources, selected KDB/CHERIC
At the dialog box, entered CAS for furan (110-00-9) and error dialog box pops up:
"DWSIM could not retrieve the compound data from the online source.  either the compound is not present in the source or an unknown error occurred".

**Expected behavior**
I've checked from within CHERIC, i can locate the compound from this CAS.  I can also import from Chemeo from within the compound creator, although the compounds available are more limited than CHERIC, not all that I need are available there.

**Desktop (please complete the following information):**
 - OS: WIN10

**Comment by DanWBR** [comment]
fixed in 8.8.0

**Comment by jkittrell** [comment]
Thank you
