### ISSUE TITLE
Valve Behaviour

### ISSUE THREAD

**Issue by AdrianDietz** [DanWBR/dwsim6#66]
I am not sure wheter this is a bug or an improvement request, here below I will develop:

First, I am using :
![image](https://user-images.githubusercontent.com/34543041/102536851-7666d200-40aa-11eb-8032-bea1b802ba50.png)

I am solving this extremely simple flowsheet:
![image](https://user-images.githubusercontent.com/34543041/102536981-a57d4380-40aa-11eb-858c-39fdeffb315c.png)

having only water as compound:
![image](https://user-images.githubusercontent.com/34543041/102537110-d2315b00-40aa-11eb-9fd0-1e92e2eaae1c.png)

And using IAPWS-97:
![image](https://user-images.githubusercontent.com/34543041/102537173-e9704880-40aa-11eb-903a-47654d0888c1.png)

When for the inlet stream I specify T, P, Q
![image](https://user-images.githubusercontent.com/34543041/102537278-0d338e80-40ab-11eb-8f0f-475392520ab9.png)

The option to compute the CV appears grayed:
![image](https://user-images.githubusercontent.com/34543041/102537410-32c09800-40ab-11eb-9246-d7834ed8a0d3.png)

Given that I know the Flowrate and the pressure drop or the outlet pressure I should be able to compute the corresponding CV.

Now I go to the option known CV (I tried many CVs):
![image](https://user-images.githubusercontent.com/34543041/102537970-f80b2f80-40ab-11eb-9da2-b5e008ccc058.png)
I get
![image](https://user-images.githubusercontent.com/34543041/102538013-06594b80-40ac-11eb-8b61-e5538aa85463.png)

And when trying (just in case as it is pure water)
![image](https://user-images.githubusercontent.com/34543041/102538108-2ee14580-40ac-11eb-94ab-95c5e5b38be5.png)
I get:
![image](https://user-images.githubusercontent.com/34543041/102538189-43254280-40ac-11eb-84b5-03ff6140b27f.png)

I had similar results when setting the stream temperature to a value high enough to have steam but for the shake of simplicity I will not develop here.

**Comment by AdrianDietz** [comment]
When managing to calculate something:
![image](https://user-images.githubusercontent.com/34543041/102540903-03605a00-40b0-11eb-9ed7-d3a058a55aee.png)
I do not know what exactly is going on as pressures are changed.
Moreover the flowsheet does not solve with similar to previous post results.

**Comment by AdrianDietz** [comment]
In the appears as the oulet pressure is known, something that I can not actually enter in the flowsheet:
Public Sub CalculateKv()

            Dim Ti, P1, Hi, Wi, ei, P2, rho, volf, rhog20, v2 As Double

            Dim ims As MaterialStream = Me.GetInletMaterialStream(0)
            Dim oms As MaterialStream = Me.GetOutletMaterialStream(0)

            Me.PropertyPackage.CurrentMaterialStream = ims
            Me.PropertyPackage.CurrentMaterialStream.Validate()

            Ti = ims.Phases(0).Properties.temperature.GetValueOrDefault
            P1 = ims.Phases(0).Properties.pressure.GetValueOrDefault
            Hi = ims.Phases(0).Properties.enthalpy.GetValueOrDefault
            Wi = ims.Phases(0).Properties.massflow.GetValueOrDefault
            ei = Hi * Wi
            rho = ims.Phases(0).Properties.density.GetValueOrDefault
            volf = ims.Phases(0).Properties.volumetric_flow.GetValueOrDefault

            **P2 = oms.Phases(0).Properties.pressure.GetValueOrDefault**

            If CalcMode = CalculationMode.Kv_Liquid Then
                Kv = Wi * 3600 / (1000.0 * rho * (P1 - P2) / 100000.0) ^ 0.5
            ElseIf CalcMode = CalculationMode.Kv_Gas Then
                ims.PropertyPackage.CurrentMaterialStream = ims
                rhog20 = ims.PropertyPackage.AUX_VAPDENS(273.15, 101325)
                If P2 > P1 / 2 Then
                    Kv = Wi * 3600 / 519 * (Ti / (rhog20 * (P1 - P2) / 100000.0 * P2 / 100000.0)) ^ 0.5
                Else
                    Kv = Wi * 3600 / 259.5 / P1 * (Ti / rhog20) ^ 0.5
                End If
            ElseIf CalcMode = CalculationMode.Kv_Steam Then
                If P2 > P1 / 2 Then
                    v2 = 1 / ims.PropertyPackage.AUX_VAPDENS(Ti, P2)
                    Kv = Wi * 3600 / 31.62 * (v2 / ((P1 - P2) / 100000.0)) ^ 0.5
                Else
                    v2 = 1 / ims.PropertyPackage.AUX_VAPDENS(Ti, P1 / 2)
                    Kv = Wi * 3600 / 31.62 * (2 * v2 / (P1 / 100000.0)) ^ 0.5
                End If
            End If

        End Sub

**Comment by andr1976** [comment]
If you solve with a specified pressure drop first, and then switch to Liquid service Kv and press calculate, then you should get the required Cv for the given flow inlet, and dP (assuming 100% open). Only use Kv for Steam if the stream is actually steam and not liquid water. The high Cv may cause problems converging the pressure out.

**Comment by AdrianDietz** [comment]
Hello, thanks, I tested again following your exact steps and I got the expected result, I do notknow why or rather how I messed up my previous model (I tested in a little more complex situation now). I agree with the steam test. 
This works well in simple situations, but when sizing a control valve you give the allowed dp (as here) for a given opening lets say 75-80%, and an opening type usually equal percent. where all this is supposed to be implemented? I write plugins for myself by maybe a proper sizing feature should be available.

**Comment by andr1976** [comment]
No problem, also a small caveat, if you have sized the valve (from a specified outlet pressre) and then apply with a Kv calc, and you have ticked the "Use opening %" and the default of 50% is used, you get into trouble because now the valve is too small.

**Comment by AdrianDietz** [comment]
Yes, this is why in a plugin I just size the cv taking into account the right opening, but at the end I am writing some c# as I wrote vba into excel. the idea is to have something general and tested.

**Comment by AdrianDietz** [comment]
They look really ugly but I get what I am looking for...
![image](https://user-images.githubusercontent.com/34543041/103143436-3771f580-4716-11eb-92d5-ad47d2ebe25a.png)

**Comment by andr1976** [comment]
Btw the sizing in DWSIM is not the full ANSI/ISA/IEC method, but close to under the right conditions, choked conditions are not treated (yet).

**Comment by AdrianDietz** [comment]
It looks like the size and the opening percent was introduced to allow the dynamic mode.

**Comment by andr1976** [comment]
Closing this one for now, please reopen if you find other issues
