### ISSUE TITLE
[Bug] No módulo "Separador Gás-líquido", a saída de líquido leve está descrito como "Fluxo de Líquido de Luz"

### ISSUE THREAD

**Issue by ghola2023** [DanWBR/dwsim6#660]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**

**To Reproduce**

PLEASE ATTACH THE ZIPPED FLOWSHEET FILE and/or inform the steps to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS]
 - Version [e.g. v6.4.1]

**Additional context**

**Comment by DanWBR** [comment]
@ghola2023 esse é um erro da tradução automática. você pode sugerir correções pelo painel de tradução localizado na barra de botões.

![image](https://github.com/DanWBR/dwsim/assets/2669419/873a3b93-7db7-4654-a881-38bf8d8165f9)
