### ISSUE TITLE
[Enhancement] CAPE-OPEN using DWSIM property package manager from other simulator

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#666]
**Is your feature request related to a problem? Please describe.**
When using DWSIM from another simulator e.g. COFE, it is possible to select all the various available property packages in DWSIM which is fantastic. However only a few default components are preselected, and the components cannot be selected/specified by the by the user

**Describe the solution you'd like**
When selecting the desired property package it could be nice to be able to select any components in the DWSIM database

**Comment by DanWBR** [comment]
maybe you missed this 
![image](https://github.com/user-attachments/assets/db25d4e7-662c-4c65-9089-9a460ba398eb)
