### ISSUE TITLE
App Crashes when opening Control Panel

### ISSUE THREAD

**Issue by Mann-3107** [DanWBR/dwsim6#668]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
I have a flowsheet in which I need to add a Controller Block and a distillation column is already there in the flowsheet. For finding the correct value of the parameter unknown, I have to open the Control Panel of the controller from its Object Editor Panel. Whenever I click on the "Open Control Panel" button, the app first stops responding and then it crashes. I have tried the same thing multiple times, but the app crashes every time I try to open.

**To Reproduce**

PLEASE ATTACH THE ZIPPED FLOWSHEET FILE and/or inform the steps to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: v8.8.0

**Additional context**

**Comment by DanWBR** [comment]
@Mann-3107 unfortunately the control panel stopped working on macOS. I still have to fix it.

**Comment by DanWBR** [comment]
the control panel will work in the next release (8.8.1)

![image](https://github.com/user-attachments/assets/b593572d-55fd-4bae-a594-9fed88b30964)
