### ISSUE TITLE
[Bug]  Critical code regression/bug for CO2 depressurisation

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#669]
**Describe the bug**
When doing depressurisation of a CO2 stream in 8.8.0, from say 40 C and 200 bar via a valve the resulting temperature at ambient pressure is 1726 C. In a previous version (8.3), the stream is correctly at -78 C at with gas/solid

[test_CO2_depressurisation.zip](https://github.com/user-attachments/files/16664769/test_CO2_depressurisation.zip)

**Comment by andr1976** [comment]
Also occurs in v8.5

**Comment by andr1976** [comment]
In 8.3 it works using SRK and GERG, but CoolProp has the error mentioned above. In v8.5 and later it is a problem for all three EOS

**Comment by andr1976** [comment]
It seems it occurs only for solids

**Comment by DanWBR** [comment]
@andr1976 is this the expected result (V = 0.74 and S = 0.26)?

![image](https://github.com/user-attachments/assets/e1f7e69b-e373-481b-beff-734d58c655f0)

**Comment by andr1976** [comment]
Yes indeed

**Comment by andr1976** [comment]
Thanks a lot @DanWBR , cant wait to take it for a spin in the next release 👍

**Comment by andr1976** [comment]
and confirmed fixed in 8.8.1
