### ISSUE TITLE
[Bug] Wrong diameter in pipe unit operation code?

### ISSUE THREAD

**Issue by HaSchneider** [DanWBR/dwsim6#679]
In the [pipe unit operation](https://github.com/DanWBR/dwsim/blob/windows/DWSIM.UnitOperations/UnitOperations/Pipe.vb#L1473) the outer diameter seems to be calculated by:
```
(Dext + esp_isol)
```
Shouldnt it be:
```
(Dext + 2* esp_isol)
```
Because esp_isol is the thickness of the isolation and Dext the external diameter of the pipe.

**Comment by DanWBR** [comment]
you're right! thank you for reporting

**Comment by HaSchneider** [comment]
There are actually some more lines in the file where the incorrect diameter expression is used. For example [1488](https://github.com/DanWBR/dwsim/blob/windows/DWSIM.UnitOperations/UnitOperations/Pipe.vb#L1488), 1520, 1526, 1529, 1542, ...

**Comment by DanWBR** [comment]
@HaSchneider ok, I'll check the entire code after finishing some stuff here

**Comment by DanWBR** [comment]
https://github.com/DanWBR/dwsim/commit/a018cdc9b74e7275deb913166b772cdd5665550d
