### ISSUE TITLE
Separator Report Error

### ISSUE THREAD

**Issue by Jamesincolorado** [DanWBR/dwsim6#68]
The temperature and pressure in the separator report are incorrect.

**Comment by DanWBR** [comment]
Please follow the guidelines for reporting a bug, with steps to reproduce it and a simulation file sample, if possible.

**Comment by Jamesincolorado** [comment]
**Describe the bug**
The separator report does not show any calculated values. 

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'Results'
2. Click on 'Separators'
3. Scroll down to 'SEP-05'
4. Click "View Report
4. See error

**Expected behavior**
Separator T, P and stream should appear. 
![Separator report preparation](https://user-images.githubusercontent.com/76176708/103181662-e3275c80-4860-11eb-93cd-a6f6a93112b7.jpg)
![Separator report](https://user-images.githubusercontent.com/76176708/103181663-e4588980-4860-11eb-816b-702e6aba7f31.jpg)
[test of pseudo saturator.zip](https://github.com/DanWBR/dwsim6/files/5745403/test.of.pseudo.saturator.zip)




**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by DanWBR** [comment]
The values of temperature and pressure on the report refer to the override values, but they only have a meaning If you are using them. Actual separation conditions are determined by the inlet streams.
