### ISSUE TITLE
[Bug] sensitivity study starts with 2nd item of independent variable in version 8.8.2

### ISSUE THREAD

**Issue by CorinnaBusse** [DanWBR/dwsim6#681]
Since the update the sensititivy study is buggy as it shows the second item of the iteration and twice the last one
![image](https://github.com/user-attachments/assets/7b83c918-0f20-422b-b6ea-a8744bfd6a64)
![image](https://github.com/user-attachments/assets/3a74e514-303a-4657-9a68-b65dc7a68687)

**Comment by ddathayde** [comment]
Hi! 

I'm having the same issue with version 8.8.2. It seems like the column showing the independent value is mistakenly starting with the second value and the last value is repeating twice at the end, whereas the column showing the dependent value is correct.

I have a simple simulation file where I'm teaching the Haber-Bosh synthesis of ammonia. In the sensitivity analysis, the pressure of the reactor is changed from 260 bar to 280 bar to check how it influences the conversion of the reactor for ammonia synthesis. The outcomes are as follows: 

![image](https://github.com/user-attachments/assets/38b9f2cb-7a15-463f-8562-145efaf2df4b)

**Comment by DanWBR** [comment]
@ddathayde @CorinnaBusse please attach a sample flowsheet

**Comment by CorinnaBusse** [comment]
Here is an example flowsheet
[SO2_GGW.zip](https://github.com/user-attachments/files/17702430/SO2_GGW.zip)

**Comment by DanWBR** [comment]
@CorinnaBusse thanks for the flowsheet, I was able to fix the issue:

![image](https://github.com/user-attachments/assets/a1a88892-15ab-4848-940d-fa1666fd1622)

**Comment by CorinnaBusse** [comment]
Perfect looking forward to the next release :)
