### ISSUE TITLE
Liquid is a solid

### ISSUE THREAD

**Issue by magnuscarlsen** [DanWBR/dwsim6#682]
We are running a simulation which includes water with a high concentration of salt and a pump, and we are running into the issue that the model sees the water as a solid, and therefore the pump calculation fails.

It fails if we use Flash Spec “Temperature and Pressure” to set the temperature to 10 degC & 25 bar and then swap to pressure and enthalpy. The specific enthalpy is calculated as 60 kJ/kg.
When we look in the results, the liquid is now interpreted as a solid. How does DWSIM determine whether it is a solid or a liquid? In our understanding, it should still be a liquid under these conditions.

I have attached the model. Note: We use the” IAWPS-08 Seawater (2) PropOver” property package where we make alternative calculations for water density and viscosity due to the high salinity.
[TestCase_send.zip](https://github.com/user-attachments/files/17456374/TestCase_send.zip)

**Comment by DanWBR** [comment]
@magnuscarlsen looks like there is a discontinuity in the enthalpy-temperature curve, in the meantime you can force the stream to be a liquid.

**Comment by magnuscarlsen** [comment]
@DanWBR Hi Daniel, Thanks for the reply, unfortunately the forcing stream to be a liquid doesnt seem to fix the problem.
