### ISSUE TITLE
[Bug] Refresh Energy - Convertion Reactor - Calculate mode

### ISSUE THREAD

**Issue by cris07x** [DanWBR/dwsim6#683]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
When use the convertion reactor and change from Isothermic to Adiabatic calculation mode, the Heat Load don't change.
Change the operations conditions and the Heat load don't change, but change from Adiabatic to Isothermic again and the Heat load refresh.

**Expected behavior**
The energy stream must to be update in every change of value of calculation mode.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version DWSIM 8.8.2

**Additional context**

**Comment by DanWBR** [comment]
@cris07x it shouldn't, as the reactor doesn't record a history of what parameters were changed either automatically or by the user. this is by design.
