### ISSUE TITLE
[Bug] Optimization does not allow reaction conversion to be an independent variable

### ISSUE THREAD

**Issue by CorinnaBusse** [DanWBR/dwsim6#688]
**Describe the bug**
If I choose the reaction property conversion as independent variable in the optimization, I'm getting an error.

**Expected behavior**
If it is okay to choose the variable it should be ok to use it as an independent variable for the optimizatio

**Screenshots**
![image](https://github.com/user-attachments/assets/cdd7bfc3-dfe3-4c23-a499-dfe61d81250e)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 8.8.2

**Comment by DanWBR** [comment]
"If it is okay to choose the variable it should be ok to use it as an independent variable for the optimization"

it is not ok. not all variables are writable, as many of them are a result of the calculation.

**Comment by CorinnaBusse** [comment]
Hi Daniel thank you for reply. But one follow up question the conversion should be an indepent variable as it is writeable or not?

**Comment by DanWBR** [comment]
@CorinnaBusse can you explain what is the error?

**Comment by CorinnaBusse** [comment]
Hi Daniel I get the following message "Object reference not set to an instance of an object." if I want to save the simulation with the optimization it does not work and the configured optimization is gone. So not sure how I can best transfer this issue properly to you. BR Corinna
