### ISSUE TITLE
Heat of Combustion

### ISSUE THREAD

**Issue by Jamesincolorado** [DanWBR/dwsim6#69]
The heat of combustion in units of BTU/#MOL are incorrect.

**Comment by DanWBR** [comment]
Please follow the guidelines for reporting a bug, it will help to save my precious time.

**Comment by Jamesincolorado** [comment]
**Describe the bug**
The heat of combustion for methane is indicated to be 55,000 BTU/lb. It is, in fact, 23,000 BTU/lb

**To Reproduce**
Steps to reproduce the behavior:
1. Go to "Pllugin/heat of combustion calculator"
2. Click on 'MSTR-27'
3. Scroll down to 'BTU/LB'
4. See error

**Expected behavior**
23,000 BTU/lb

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 87

**Additional context**
[Heat of Combustion error.zip](https://github.com/DanWBR/dwsim6/files/5745362/Heat.of.Combustion.error.zip)
![Heat of Combustion error](https://user-images.githubusercontent.com/76176708/103181076-216d4d80-485a-11eb-8ebc-1f6cbed3ad58.jpg)


Add any other context about the problem here.

**Comment by andr1976** [comment]
For the moment the only units supported in this plugin is SI.
