### ISSUE TITLE
[Bug] Adjust missing in Logical Blocks

### ISSUE THREAD

**Issue by byryepez** [DanWBR/dwsim6#692]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
It is mentioned in the documentation (v. 8.8.0) that DWSIM has an Adjust logical operation available. I'm using DWSIM v. 8.8.2, and the mentioned block does not appear in the Logical Block menu. The Adjust block is still available (DWSIM.UnitOperations/LogicalBlocks/Adjust.vb)

**To Reproduce**

1. Open a simulation in DWSIM
2. Open Logical BLocks menu 
3. No "Adjust Block" is present

**Expected behavior**
Having a 'Adjust block" available

**Screenshots**

![image](https://github.com/user-attachments/assets/66babb8e-0726-4a65-a0f5-e41766791df7)

**Desktop (please complete the following information):**
 - OS: Windows (Clasic UI)
 - Version 8.8.2

**Additional context**

**Comment by DanWBR** [comment]
@byryepez it has been renamed to "Controller Block", the third on the list.
