### ISSUE TITLE
Compound Creator: Cheric Failure

### ISSUE THREAD

**Issue by WillyLund** [DanWBR/dwsim6#699]
Hello Daniel,

Cheric.org seems to have disappeared from the internet.  From the US. I am not able to resolve the IP.  I also tried a Brazil VPN with no success.  In checking the internet archive, the last time a snapshot was recorded was June.  

When the on-line importer encounters this situation, it seems be a fatal error and does not proceed onward to the alternate sources.

![image](https://github.com/user-attachments/assets/c6caff02-1978-456f-b399-7c4bca4fc08b)

Thank you
Willy Lund

**Comment by DanWBR** [comment]
@WillyLund unfortunately I'll have to disable this data source for now, let's hope it can be back soon.
