### ISSUE TITLE
[Bug] Phase envelope

### ISSUE THREAD

**Issue by petroconsulting** [DanWBR/dwsim6#701]
[Gas envelope.zip](https://github.com/user-attachments/files/18219991/Gas.envelope.zip)
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
Bubble point line is wrong
**To Reproduce**

PLEASE ATTACH THE ZIPPED FLOWSHEET FILE and/or inform the steps to reproduce the behavior:

**Expected behavior**
Continuous line on both sides of critical point

**Screenshots**
![image](https://github.com/user-attachments/assets/806b3895-8b25-429b-b51e-df1b51e2d64a)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS]  Windows 11
[Gas envelope.zip](https://github.com/user-attachments/files/18219995/Gas.envelope.zip)

 - Version [e.g. v6.4.1]

**Additional context**

**Comment by DanWBR** [comment]
@petroconsulting please try building the envelope using different initialization procedures, they are available in different tabs.
