### ISSUE TITLE
Heat Exchanger Spec

### ISSUE THREAD

**Issue by Jamesincolorado** [DanWBR/dwsim6#72]
**Describe the bug**
The cold outlet specification is reversed when the cold side is on the shell side. The spec incorrectly is applied to the hot side.

**Comment by DanWBR** [comment]
Please follow the guidelines for reporting a bug, with steps to reproduce it and a simulation file sample, if possible.

**Comment by Jamesincolorado** [comment]
I tried to upload a simulation file but it was not allowed.

James Meyer, MBA/PE
Aspen Engineering Services, LLC
Golden, CO
303-887-2032
www.aspenesco.com
jmeyer@aspenesco.com

**Comment by AdrianDietz** [comment]
It is always possible to add a link to a cloud file such as google drive or others

**Comment by andr1976** [comment]
@Jamesincolorado, if you zip the file you can drag and drop it into the comment field

**Comment by Jamesincolorado** [comment]
**Describe the bug**
A hot outlet temperature is selected for a heat exchanger specification. However, only the cold side outlet can be entered. 

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'HE-03'
2. Click on 'HE-03'
3. Scroll down to 'Calculation type'
4. See error

**Expected behavior**
The outlet temperature value should be highlighted

**Screenshots**
Added

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 78
[NGL Pro-2 with NGL heater.zip](https://github.com/DanWBR/dwsim6/files/5745378/NGL.Pro-2.with.NGL.heater.zip)
[HX spec.pdf](https://github.com/DanWBR/dwsim6/files/5745379/HX.spec.pdf)



**Additional context**
Add any other context about the problem here.

**Comment by DanWBR** [comment]
This is not an issue. First calculation mode means "Calculate Hot Outlet Temperature", not "Specify Hot Outlet Temperature". This will be more obvious in v6.4.
