### ISSUE TITLE
Separator Streams

### ISSUE THREAD

**Issue by Jamesincolorado** [DanWBR/dwsim6#74]
The three stage separator for a natural gas stream sends the water to the light liquid phase. Sometimes no separation occurs even though free water is assured.

**Comment by AdrianDietz** [comment]
Is it possible to have the file with at least one stream where the flash calculation fails?

**Comment by Jamesincolorado** [comment]
File is attached. Please let me know what you think.
    
    
      
      
      


      
        James
            Meyer, MBA/PE
        Aspen
            Engineering Services, LLC
        Golden,
            Colorado
        303-887-2032
        www.aspenesco.com
        jmeyer@aspenesco.com
          | LinkedIn
      
    
    On 12/23/2020 4:09 PM, Adrian wrote:
    
    
      
      Is it possible to have the file with at least one stream where
        the flash calculation fails?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DanWBR/dwsim6/issues/74#issuecomment-750537156",
"url": "https://github.com/DanWBR/dwsim6/issues/74#issuecomment-750537156",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Jamesincolorado** [comment]
**Describe the bug**
Water exits the light liquid stream in a 3-phase separator

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'MSTR-31'
2. Click on 'MSTR-31'
3. Scroll down to 'Compound Amounts'
4. See error

**Expected behavior**
Water should be in stream MSTR-32
[Water in light liquid.pdf](https://github.com/DanWBR/dwsim6/files/5745388/Water.in.light.liquid.pdf)


**Screenshots**
Attached.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 78

**Additional context**
Add any other context about the problem here.

**Comment by andr1976** [comment]
Please check for binary interaction paramters fro HC-Water, all should be set at 0.5 if not already.

**Comment by Jamesincolorado** [comment]
Yes, they are all 0.5. 
    
    
    
    
      
      
      


      
        James
            Meyer, MBA/PE
        Aspen
            Engineering Services, LLC
        Golden,
            Colorado
        303-887-2032
        www.aspenesco.com
        jmeyer@aspenesco.com
          | LinkedIn
      
    
    On 12/29/2020 5:55 AM, Anders Andreasen
      wrote:
    
    
      
      Please check for binary interaction paramters fro HC-Water, all
        should be set at 0.5 if not already.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DanWBR/dwsim6/issues/74#issuecomment-752065500",
"url": "https://github.com/DanWBR/dwsim6/issues/74#issuecomment-752065500",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by DanWBR** [comment]
Fixed in https://github.com/DanWBR/dwsim6/commit/a599035e3fc66f78d1ae63c427ff18b5e6ced019
