### ISSUE TITLE
EditingForm_OrificePlate and commit [bug fix conversion from mm to m] - bug divide 1000

### ISSUE THREAD

**Issue by AlexanderSemenyak** [DanWBR/dwsim6#76]
**Description** 

1) before commit  [bug fix conversion from mm to m]:
  EditingForm_OrificePlate.tbOrificeDiameter.Text = 55.4 mm
  EditingForm_OrificePlate.tbIntPipeDiameter.Text = 100 mm
2) after commit  [bug fix conversion from mm to m]:
  EditingForm_OrificePlate.tbOrificeDiameter.Text = 55400 
  EditingForm_OrificePlate.tbIntPipeDiameter.Text = 100000

**Expected behavior**

     EditingForm_OrificePlate.tbOrificeDiameter.Text = 55.4 mm
     EditingForm_OrificePlate.tbIntPipeDiameter.Text = 100 mm

**Comment by DanWBR** [comment]
Unfortunately you'll have to update the values manually for previously saved simulations.

**Comment by AlexanderSemenyak** [comment]
Confirmed (after commit fix to OrificePlate, thank's )
