### ISSUE TITLE
Adding French Language

### ISSUE THREAD

**Issue by AdrianDietz** [DanWBR/dwsim6#80]
**Is your feature request related to a problem? Please describe.**
Adding french language will make the tool available to more people, specially African countries where French is their second language and English comes third.  

**Describe the solution you'd like**
There are currently four languages in resource section, BR (that is not PG), EN, ES and DE, just add FR.
I can contribute with the translation, I am not french native but I have many years living and speaking the language, but I am not the owner neither a contributor to start the job, respect the architecture, the map-road, etc.

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.

**Comment by DanWBR** [comment]
Translating DWSIM is huge work. You would need to manually translate every single form (window) from the Classic UI, not just the Strings.resx and Properties.resx files. Portuguese BR is the base language and currently only English is up-to-date, as German and Spanish translations have not been maintained by the original authors. Also, the Cross-Platform UI is hard-coded in English, as this enables faster development and release.

**Comment by AdrianDietz** [comment]
Well, this post was about bringing up the discussion, based on my experience adding French and Russian will bring up a lot of new users.

I still believe that there is a lot of people ready to contribute if a proper way (i.e. using resources) is available and accepting partial advancements (you will be surprised about the quality of the french translation of the .net documentation by Microsoft in french for example, and still is better for some people than reading English).

I understand that making every single string a resource is time consuming.

I still believe that is worth the effort, at least worth to give a try, just leting the user know when installing in another language that is a work in progress and that some "strings" (messages) could still appear in English.

By the way, I can also give a hand to keep up to date with Spanish, in German I am not good enough, and for Russian other that the Cyrillic and a few words I am completely blind...

wkr,

Adrian

**Comment by DanWBR** [comment]
See, I'm just saying that it is a hell of a work, not that I don't want to do it. Of course, the more languages DWSIM supports, the better. It is also hard to maintain the translations with my development method as I don't wait for anyone else when I want to add a new feature. Imagine how things would slow down if I had to wait for others to update their translations in order to release an update... that's what was happening with german and spanish translations, so I've decided to remove them from the list.

An automated solution would be more feasible and elegant, I think.

**Comment by DanWBR** [comment]
I knew I had written a translation tutorial years ago: https://web.archive.org/web/20160330042206/http://dwsim.inforside.com.br/wiki/index.php?title=Translating

**Comment by AdrianDietz** [comment]
I have had a quick look to the tutorial and it is the way I expected it to be. Yes is a huge amount of work, but nobody is expecting you to have it all done.
Lets say that en and pt-br are fully supported as developing languages and the others are partial translations, moving behind but trying to keep updated.  Do not expect any translation to be done for release purposes, just release and while awaiting for translation the en message should be displayed. this sometimes happens for commercial tools with Russian, the translation is updated/completed each time a new project come form there. I also dealt with a korean project and translation of part of the software for example.
Remember that most of the users, average ones, uses only a limited set of capabilities (basic ones) and for them the translation will not change in time.
Maybe a way for contributing should be put in place, people saying something not yet translated instead of allow them just to complain maybe give them the opportunity to propose the translation.

**Comment by AdrianDietz** [comment]
I followed the guidelines, forking, cloning... creating rex files, and I am getting the first string translated into the forms, from now it would just be a matter of free time.
By the way why not bringing back the job done in spanish and deutsch in order just preventing that the translation is partial, this will maybe motivate people to do the remaining job.

**Comment by AdrianDietz** [comment]
I am getting the first results for an user form, and the main difficulty I am facing is that the string does not fit in the allocated space. Forms compared to XAML are less flexible for this purpose. Will keep translating during my free time.

**Comment by DanWBR** [comment]
Yes, that's one of the main issues. You have to manually relocate textboxes and other controls in order for labels to fit in the available space.

**Comment by AdrianDietz** [comment]
Is there the possibility to do this when loading the form, for example a switch base on the language that relocate some controls to make room for the corresponding text?
Can the translation be included in the official release or I need to create and maintain a fork of the project?

**Comment by DanWBR** [comment]
It is technically possible. I'm going to create a plugin to translate the opened forms automatically and see if it works as expected. Unfortunately, it will have to be paid or patron-only because I'm going to use Microsoft Azure Cognitive Services ($$$) with my Azure account.

**Comment by AdrianDietz** [comment]
I think making this paid will miss the target, the ones that will have the money to afford are also the ones that had the money for an English education during the childhood, in other words a solution to those that don't need it, maybe I am wrong.
How should I decide whether a fork maintained by myself is the right way, having several distribution as in the Linux world is maybe not the right path.

**Comment by DanWBR** [comment]
I agree. I was able to capture most strings, including the main Properties and String resource files and translate them from English to many languages using Microsoft Translation Service with my Azure account. 

The translation file is https://github.com/DanWBR/dwsim6/tree/windows/DWSIM.SharedClasses/Translations/Translations.json

I haven't added the machinery to do the actual translation to the main branch yet, but you can (if you wish) start checking the French translations on the JSON file already. Many of them won't make sense in the context of a chemical process simulator, but the file itself is much easier to handle than having to do the translation manually for each form/window.

Create a branch, modify the JSON file and do a pull request, it can't be easier than that!

**Comment by DanWBR** [comment]
Changed the file location to https://github.com/DanWBR/dwsim6/blob/windows/PlatformFiles/Common/data/translations/translations.json

**Comment by AdrianDietz** [comment]
I do not know exactly what you actually means, I have had a quick look to the existing json file, and for "fr" there are some hit and miss translations in some places and nothing somewhere else(english instead), looks like some auto translation, I get the same mistakes with the first raw auto translation with google or something else....

**Comment by DanWBR** [comment]
It is an auto translation, I wrote above that I've used an Azure service. I meant that you can use that translation as a starting point, and modify/update the JSON file with actual meaningful translations. Later, I will read the file and update the text in the forms/windows automatically. If you're willing to translate DWSIM to French, then you just have to update the JSON file, review it from time to time to see if new automated translations were added and that's all.

**Comment by AdrianDietz** [comment]
Well I have started doing it the why you stated in the previous messages : https://web.archive.org/web/20160330042206/http://dwsim.inforside.com.br/wiki/index.php?title=Translating
and I have spent several hours on it, taking everything back form the resx file to the json is not that simple.

**Comment by DanWBR** [comment]
Ok, sorry about that.

**Comment by dalbitresb12** [comment]
@DanWBR Hi there! What's needed to translate DWSIM to Spanish? I noticed there are some files for the Spanish translation, but they are old (5 years old), so I guess they have been disabled. If I wanted to start translating the software, should I update these files? I noticed you have also created the JSON file with some translations from the Microsoft Translation Service, so I'm not sure where to start for translating this awesome project.

_Context: My dad is learning DWSIM and he's going to teach it at the university where he works. We're from Peru so a Spanish translation would be awesome. I'm definitely willing to help translating what I can._

Edit: I wasn't sure if I should create another issue, that's why I replied here. I can create another one if you prefer it that way.

**Comment by DanWBR** [comment]
@dalbitresb12 it is the same process as described in https://web.archive.org/web/20160330042206/http://dwsim.inforside.com.br/wiki/index.php?title=Translating

The existing files must be updated.

**Comment by DanWBR** [comment]
I've updated the Translation article to reflect the current code: https://dwsim.inforside.com.br/wiki/index.php?title=Translating

**Comment by DanWBR** [comment]
@AdrianDietz I don't have the resources to work on the translation to French. For now I'll close this issue, we can reopen it in the future is something comes up.

**Comment by DanWBR** [comment]
@AdrianDietz, v8.3.3 includes machine-translated French sentences. They can be reviewed/corrected by a human being.
