### ISSUE TITLE
Recycle does not solve

### ISSUE THREAD

**Issue by Jamesincolorado** [DanWBR/dwsim6#81]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
Compressor COMP-1 will not solve when, in fact, it is fully specified. ERROR: COMP-1 contains no elements

**To Reproduce**
1. Unzip attached file
2. Run simulator
4. See error message. 

**Expected behavior**
COMP-1 is fully specified and should execute to begin the solving process. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS] Windows 10
 - Version [e.g. v6.3 Update 5] 73
[NGL PR0 WITH RECYCLE.zip](https://github.com/DanWBR/dwsim6/files/5748385/NGL.PR0.WITH.RECYCLE.zip)
![COMP-1 sequence contains no elements](https://user-images.githubusercontent.com/76176708/103234832-df95e300-48fd-11eb-808c-ffad0d7e4b9c.jpg)

**Additional context**

**Comment by andr1976** [comment]
The VLLE/SVLLE Flash algorithm is a little slow, if you can live with a two-phase/VLE flash then simply changing this under settings -> Thermodynamics -> Flash and select VLE, then it solves the flowsheet with recycles very fast.

**Comment by Jamesincolorado** [comment]
Yes, it solves well with two-phase. DWSIM has problems with
      three-phase calculations and separators (water comes out of
      hydrocarbon port). 
    
    A few questions if you don't mind:
    What is default flash phase equilibria type (where you can select
      VLE or VLLE)? 
    
    What does the error message "sequence contains no elements" mean?
    What do the error messages in the attachment mean?
    I have found that the only cubic equations of state that work are
      SRK and PR (basic). Is that a known issue?
    Thank you. 
    
    
      
      
      


      
        James
            Meyer, MBA/PE
        Aspen
            Engineering Services, LLC
        Golden,
            Colorado
        303-887-2032
        www.aspenesco.com
        jmeyer@aspenesco.com
          | LinkedIn
      
    
    On 12/29/2020 5:48 AM, Anders Andreasen
      wrote:
    
    
      
      The VLLE/SVLLE Flash algorithm is a little slow, if you can
        live with a two-phase/VLE flash then simply changing this under
        settings -> Thermodynamics -> Flash and select VLE, then
        it solves the flowsheet with recycles very fast.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DanWBR/dwsim6/issues/81#issuecomment-752063680",
"url": "https://github.com/DanWBR/dwsim6/issues/81#issuecomment-752063680",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Jamesincolorado** [comment]
Also, what is the difference between "main thread" and
      "background thread." The solver failed when I switched to main
      thread. See attached. 
    
    
      
      
      


      
        James
            Meyer, MBA/PE
        Aspen
            Engineering Services, LLC
        Golden,
            Colorado
        303-887-2032
        www.aspenesco.com
        jmeyer@aspenesco.com
          | LinkedIn
      
    
    On 12/29/2020 5:48 AM, Anders Andreasen
      wrote:
    
    
      
      The VLLE/SVLLE Flash algorithm is a little slow, if you can
        live with a two-phase/VLE flash then simply changing this under
        settings -> Thermodynamics -> Flash and select VLE, then
        it solves the flowsheet with recycles very fast.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DanWBR/dwsim6/issues/81#issuecomment-752063680",
"url": "https://github.com/DanWBR/dwsim6/issues/81#issuecomment-752063680",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by DanWBR** [comment]
I just ask you to be a little patient as I fix most flash issues for v6.4. Also, if possible, please add new comments directly on GitHub site as it seems that it includes some code from the email.

**Comment by Jamesincolorado** [comment]
Do you mean the bug report site?

James Meyer, MBA/PE
Aspen Engineering Services, LLC
Golden, CO
303-887-2032
www.aspenesco.com
jmeyer@aspenesco.com

**Comment by DanWBR** [comment]
Yes, please comment directly here instead of replying to the email notification that you get, if possible.
