### ISSUE TITLE
Binary Envelope - Flash algo not suitable for LLE

### ISSUE THREAD

**Issue by Greg66** [DanWBR/dwsim6#83]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
Binary envelope utility issues an error message stating the the flash algorithm is not suitable for LLE calculation

**To Reproduce**
1. Create simulation with components Aniline and Water
2. create stream and call utility
3. Check LLE to calculate the full diagram
4. first part with VLE calculations works well. Second part with LLE calculations issues error

**Expected behavior**
This should work again :-)

**Screenshots**
Bug issued during calculation - debugger view
![image](https://user-images.githubusercontent.com/4138115/103315814-00a62300-4a27-11eb-9e3b-dac0f9ca85a9.png)

**Desktop (please complete the following information):**
Actual version from GitHub (29.12.2020)

**Additional context**
-

**Comment by DanWBR** [comment]
this is because there is now a high-level algorithm called Universal Flash. the "If" condition must be removed as it doesn't make sense anymore.

**Comment by Greg66** [comment]
Hi Daniel,
there seems to be more to this. I deleted that if condition as suggested. But now other errors occure somewhere else. I will have to leave this to you.

Gregor

**Comment by Greg66** [comment]
Hi Daniel,
this is working now again. Thanks for your quick action!

p.S. We still need some tweaking of flash algorithms. Light and heavy liquid phases are swapping:
![image](https://user-images.githubusercontent.com/4138115/103319302-9f378180-4a31-11eb-966a-2c9a98e110cb.png)

**Comment by Greg66** [comment]
Hi Daniel,
irregular phase swapping is resolved now. ->ok
But the curves still don't look as they should:

- Boiling point temperature is reduced in two phase region (purple). It should be like the red line in the diagram
- LLE curves need to go up to boiling temperature -> green lines

![image](https://user-images.githubusercontent.com/4138115/103365368-3519ed80-4ac0-11eb-98ac-99b171c46199.png)

For comparison the same diagram with NRTL as property package:
- Phase swapping here ok as well
- But: the curves run back and forth like crazy in LLE region. This shows that NRTL parameters are only optimized for VLE calculations. In contrast to ModFac (NIST) where parameters are optimized for VLE, LLE and SLE equilibria. 
![image](https://user-images.githubusercontent.com/4138115/103365716-02bcc000-4ac1-11eb-9e5b-34009289f06e.png)

**Comment by DanWBR** [comment]
ok, I had noticed that already. It will have to wait as I have other priorities right now.

**Comment by Greg66** [comment]
Ok, thats not a problem. I will go on testing other issues.

**Comment by Greg66** [comment]
Hi Daniel,
i just committed some new code for LLE flash, which solves the problem for the too low boiling point in two phase region:
![image](https://user-images.githubusercontent.com/4138115/103414159-0746ae80-4b7d-11eb-8971-a3090d777e24.png)
![image](https://user-images.githubusercontent.com/4138115/103414963-66f28900-4b80-11eb-9fd8-12978d7cc767.png)

But there is another issue in `Flash_PT_3P` of `NestedLoops3PV3`. Under certain circumstances instabilities occur as a vapor phase is calculated despite being well below boiling point. This stops executing the if clause and dose not run the SimpleLLE-flash inside it. Only a single liquid will be left.

![image](https://user-images.githubusercontent.com/4138115/103415514-ac17ba80-4b82-11eb-8419-ba1579d4f37c.png)

To further demonstrate it, see following pictures at different temperatures, which are all below boiling point @ 99°C:
![image](https://user-images.githubusercontent.com/4138115/103415191-5858a180-4b81-11eb-911a-09347637286c.png)

![image](https://user-images.githubusercontent.com/4138115/103415232-863de600-4b81-11eb-8bef-22e9a5472abf.png)

![image](https://user-images.githubusercontent.com/4138115/103415253-a1a8f100-4b81-11eb-8d26-c9a2e83ec502.png)

This 3P-PT-Flash basically is still the very old code from DWSIM3/4 working with a matrix calculation which i don't understand. I guess we need to adopt a different approach, similar PV-3P flash.

**Comment by DanWBR** [comment]
The code is old but I have a reference! 😄

Perhaps I missed something while translating the algorithm to code?

[Equations and procedures for VLLE calculations.pdf](https://github.com/DanWBR/dwsim6/files/5757594/Equations.and.procedures.for.VLLE.calculations.pdf)

**Comment by DanWBR** [comment]
Where is your commit or pull request? I can't see it.

**Comment by Greg66** [comment]
Maybe i didn't in the right way?
At least my GitHub-Programs shows that this code was committed:
![image](https://user-images.githubusercontent.com/4138115/103416453-2e09e280-4b87-11eb-8622-c2a4fbe831d6.png)

Edit: Apparently I created a new fork. Now i issued a pull request for main project.

**Comment by DanWBR** [comment]
Got it now. After committing you must push your changes to the server.

**Comment by DanWBR** [comment]
@Greg66 can you create a new issue for the Flash_PT_3P instability of NestedLoops3PV3?

**Comment by Greg66** [comment]
Ok, i will do that.
I am already checking the code and discovered some issues already in LLE flash. But i am not finished yet.

Gregor

**Comment by Greg66** [comment]
New issue dealing with Flash_3P_PT will be issued for follow up.

**Comment by DanWBR** [comment]
@Greg66 just waiting for the ticket in order to send a tentative fix. 🤠
