### ISSUE TITLE
SLE-Flash phase composition not 100%

### ISSUE THREAD

**Issue by Greg66** [DanWBR/dwsim6#86]
**Describe the bug**
In Default-flash and SVLLE-flash the phase composition in liquid phase is not correct. It is not a total of 100%

**To Reproduce**
1. open attached file, containing water and a component showing solid solubility
[Test_Solid_Solubility.zip](https://github.com/DanWBR/dwsim6/files/5754290/Test_Solid_Solubility.zip)
 
2. SVLE flash is giving correct values
![image](https://user-images.githubusercontent.com/4138115/103353635-9aaeaf80-4aa9-11eb-9c53-8ab3f2b60d40.png)

![image](https://user-images.githubusercontent.com/4138115/103353682-bd40c880-4aa9-11eb-95ce-1447a8718124.png)

3. switch to "Default" or "SVLLE" flash. Liquid phase composition gives not a total of 100%
![image](https://user-images.githubusercontent.com/4138115/103353793-11e44380-4aaa-11eb-9c8f-bfd1862bc929.png)

**Expected behavior**
Liquid component fractions should sum up to 100%

**Comment by DanWBR** [comment]
is this with the latest code? I've thought I had fixed this a day ago.

**Comment by Greg66** [comment]
Yes, this is the latest code available on GitHub
