### ISSUE TITLE
PVF and TVF flash - no solid phase

### ISSUE THREAD

**Issue by Greg66** [DanWBR/dwsim6#87]
**Describe the bug**
As with SVLLE flash reported earlier, a similar issue occurs with SLE flash calculations.
I specified a mixture with water and my TestSolid-Component to check all kinds of flash calculations.
It turned out, that PT and PH flash calculations work well, giving a solid phase. With same conditions PVF and TVF flash don't create a solid phase.

**To Reproduce**
1. Load Simulation
2. Run through all flash types for stream without changing any data
3. Check existing phases and compositions 
4. Check all flash types (Default, SVLE, SVLLE) -> no difference between types, always the same behavior
5. PVF and TVF give no solid phase. TP, PH and PS flash are ok

**Expected behavior**
PVF and TVF should calculate solid phase.

**Screenshots**
TP-Flash
![image](https://user-images.githubusercontent.com/4138115/103372520-8af79100-4ad2-11eb-8381-d625b44ed019.png)
![image](https://user-images.githubusercontent.com/4138115/103372577-a4004200-4ad2-11eb-8c57-5d197fcae0ad.png)

PH-Flash
![image](https://user-images.githubusercontent.com/4138115/103372617-c1351080-4ad2-11eb-9d93-7540cb5d0a86.png)
![image](https://user-images.githubusercontent.com/4138115/103372657-da3dc180-4ad2-11eb-87be-8c8ae1974ac4.png)

PVF-Flash
![image](https://user-images.githubusercontent.com/4138115/103372691-f8a3bd00-4ad2-11eb-8255-f79d28d3ca2b.png)
![image](https://user-images.githubusercontent.com/4138115/103372734-1ffa8a00-4ad3-11eb-90cc-da31557e90cf.png)

TVF-Flash
![image](https://user-images.githubusercontent.com/4138115/103372772-3f91b280-4ad3-11eb-95ae-3a5ec3b0b956.png)
![image](https://user-images.githubusercontent.com/4138115/103372810-5932fa00-4ad3-11eb-91c9-20d54b9b33d4.png)

**Version (please complete the following information):**
 - actual GitHub Version 30.12.2020
 
**Additional context**
DSWIM-Simulation
[Test_Solid_Solubility.zip](https://github.com/DanWBR/dwsim6/files/5755237/Test_Solid_Solubility.zip)

**Comment by DanWBR** [comment]
in this case, would be enough an SLE flash on the resulting liquid, or would we need a special calculation?

**Comment by Greg66** [comment]
Just give it a try. I think this could work, at least with my Testcomponent, as i designed it without a vapor pressure.

**Comment by Greg66** [comment]
Sorry, at first glance i thought this would be such an easy calculation as suggested by you - but it probably will be more difficult!

I suggest the following:
1. run VLE flash
2. run SLE flash with remaining liquid
3. go back to 1 until everything is constant

This kind of iteration will be necessary as precipitation of solids is changing remaining liquid composition. This new liquid composition again will show different vapor pressures -> new VLE flash necessary

Regards
Gregor

**Comment by DanWBR** [comment]
I think that, if we consider that the solid vapor pressure is low, there is no need for an iterative procedure.

**Comment by Greg66** [comment]
Yes, solid vapor pressure might be considered as low and doesn't need to be taken into account.
(Solid would need a separate vapor pressure correlation for sublimation = SVE equilibrium, which is not available in DWSIM to my knowledge)
But what i tried to explain an above post:
1. run VLE flash (no solid existing yet)
2. now you execute SLE flash. This changes liquid composition due to removal of solids by precipitation.
3. We need to run step 1 with a VLE flash again, as liquid composition will not be the same as before.
4. You will need to run this loop until everything will be constant below a specified tolerance.


good look

Gregor

**Comment by Greg66** [comment]
I reworked Universal flash to call the correct Property package due to results of phase heuristics test. I also created a new TVF flash for SVLE calculations. This flash type was still missing.
