### ISSUE TITLE
Hydrates and Methanol

### ISSUE THREAD

**Issue by Jamesincolorado** [DanWBR/dwsim6#88]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
Hydrate formation does not account for methanol

**To Reproduce**
1. Go to 'Utilities'
2. Click on 'SEP-1  L-1B"
4. See error: HYDRATES: YES

**Expected behavior**clear and concise description of what you expected to happen.
Hydrates are indicated regardless of the amount of Methanol is added to stream MEOH L

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS] Windows 10
 - Version [e.g. v6.3 Update 5] 73
[Hydrates and MeOH.pdf](https://github.com/DanWBR/dwsim6/files/5755578/Hydrates.and.MeOH.pdf)
[Hydrate and MeOH.zip](https://github.com/DanWBR/dwsim6/files/5755579/Hydrate.and.MeOH.zip)

**Additional context**

**Comment by DanWBR** [comment]
The only method which supports Methanol is Klauda and Sandler, but the results were not validated.

**Comment by DanWBR** [comment]
This utility will be removed in v6.4.
