### ISSUE TITLE
Welcome Panel does not work correctly

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#9]
**Describe the bug**
Welcome Panel is not shown when the DWSIM main window is empty while the Welcome Panel under Menu-bar/View is selected!

**To Reproduce**
1. Open DWSIM on Windows 10
2. You see a nice Welcome Panel
3. Open a simulation file or create one. Welcome Panel is disappeared
4. Close all simulation files. DWSIM window is empty nothing is shown
5. Open View from menu bar
5.1. You see Welcome Panel checkbox is activated, BUT Welcome Panel is NOT shown
5.2 Uncheck (de-select) the Welcome Panel
5.3. Toggle (select) the Welcome Panel again, you will see Welcome Panel again

**Expected behavior**
1. Toggle checkbox to show Welcome Panel should work correctly
2. On DWSIM empty window, Welcome Panel shall be displayed

**Comment by kookma** [comment]
The issue has not gone in DWSIM 6 Update 1 of August 5th, 2020

**Comment by DanWBR** [comment]
Fixed (hopefully)! Please re-download the installer 👍🏻

**Comment by kookma** [comment]
Yes, When the window is empty one can click on View/Welcome Panel and open it again!

Thank you

**Comment by kookma** [comment]
**Another Issue**

If you open DWSIM after a crash for example restart Windows while a simulation file is opened in DWSIM. A message is shown to recover the last saved copy of that simulation file. If you recover the file you cannot see it in DWSIM and you may confuse.
If you go to Toolbar/View and uncheck Welcome Panel then you see the file is opened underneath of welcome panel!!
