### ISSUE TITLE
[Bug] Instability in VLLE calculations 

### ISSUE THREAD

**Issue by Greg66** [DanWBR/dwsim6#94]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
There are several instabilities occurring during VLLE flash calculations under certain conditions. 

**To Reproduce**
1. Create new simulation with water (1) and toluene (2) and ModFac (NIST) as PP
2. Run Binary Envelope utility 
3. at 0.95 molar fraction of water an error will be issued
4. Near azeotropic point the calculated dew point is below boiling point 
5. Just some degrees below boiling point inside LLE region no phase split is detected anymore
6. Instabilities in LLE region below boiling point (Aniline / water system)
7. In system water/toluene there is still a liquid phase swap experienced

**Expected behavior**
1. No errors during calculations
2. Dew temperature always above boiling temperature
3. Stable LLE results up to boiling temperature

**Screenshots**
(4) Dew point below boiling point:
![image](https://user-images.githubusercontent.com/4138115/103461353-144ed380-4d1e-11eb-88d8-5ba990e36820.png)

(4) This issue was resolved in meantime
![image](https://user-images.githubusercontent.com/4138115/103461854-aa382d80-4d21-11eb-9a62-5c22ac1b3dcf.png)

(5) no LLE phase split anymore some degree below boiling point 
(7) Liquid Phase swap (only toluene/water system)
![image](https://user-images.githubusercontent.com/4138115/103461401-950dcf80-4d1e-11eb-8cd3-db6285c5189c.png)

(6) Instabilities in LLE calculation (Aniline / water)
![image](https://user-images.githubusercontent.com/4138115/103461569-94296d80-4d1f-11eb-9c46-81fb2fb109ee.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS]
 - Version [e.g. v6.3 Update 5]

**Additional context**
* Errors during calculations already resolved and committed ("Some Bugfixes for VLLE  calculation") 
* Dew point below boiling point already resolved and committed

**Comment by Greg66** [comment]
I was able to reach some progress:
Just below boiling point in two phase region a gap was occurring (see Nr. 5 of description). Instead a vapor phase was calculated.
This issue was resolved now.
![image](https://user-images.githubusercontent.com/4138115/106188903-da031580-61a7-11eb-8148-8110a9335246.png)

Other issues of instabilities in LLE calculation of aniline/water system and phase swapping in toluene/water system still exist.

**Comment by Greg66** [comment]
Issues with instability are resolved now.
I created a new version of VLLE-PT-Flash:

Diagram calculated by ModFac(NIST)
![image](https://user-images.githubusercontent.com/4138115/106371475-162fa500-6365-11eb-9cd3-0808bc78eab8.png)

And with NRTL Property Package:
![image](https://user-images.githubusercontent.com/4138115/106371489-4119f900-6365-11eb-862f-4a166a34dbaf.png)

**Comment by Greg66** [comment]
Issues are resolved now.

**Comment by DanWBR** [comment]
Great work, @Greg66!
