### ISSUE TITLE
[Enhancement] 

### ISSUE THREAD

**Issue by Jamesincolorado** [DanWBR/dwsim6#96]
**Is your feature request related to a problem? Please describe.**
I would like to see the vapor fraction in stream reports.

**Comment by DanWBR** [comment]
You can see it as a property of the vapor phase.

**Comment by Jamesincolorado** [comment]
Yes, but not in the report.
    
    
      
      
      


      
        James
            Meyer, MBA/PE
        Aspen
            Engineering Services, LLC
        Golden,
            Colorado
        303-887-2032
        www.aspenesco.com
        jmeyer@aspenesco.com
          | LinkedIn
      
    
    On 1/13/2021 1:53 PM, Daniel Medeiros
      wrote:
    
    
      
      You can see it as a property of the vapor phase.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DanWBR/dwsim6/issues/96#issuecomment-759733100",
"url": "https://github.com/DanWBR/dwsim6/issues/96#issuecomment-759733100",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by DanWBR** [comment]
Please avoid answering items through your email client as it adds a lot of garbage text. As I've said, the molar fraction is there in the phase properties:

<img width="735" alt="Captura de Tela 2021-01-13 às 17 14 45" src="https://user-images.githubusercontent.com/2669419/104511406-096c2c80-55c3-11eb-9bed-448cbf71310a.png">
