### ISSUE TITLE
[Bug] Chemeo Import failing

### ISSUE THREAD

**Issue by Greg66** [DanWBR/dwsim6#97]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
In some cases import of a component from Chemeo-DB is not working. If there is only a single component in database matching search criteria nothing is imported. 

**To Reproduce**
1. Go to Component creator utility
2. Click on Import component from Chemeo Databas
3. Enter "Ethanol" and search component
4. A list of several components is displayed. Ethanol may be selected an can be imported.
5. Enter "64-17-5", which is the CAS-number of ethanol
6. No list of components is displayed as only a single component is matching this criteria. Nothing can be imported.

**Expected behavior**
Data should be imported

**Screenshots**
![image](https://user-images.githubusercontent.com/4138115/103768893-993e3380-5023-11eb-8bd6-4d54726a6306.png)
![image](https://user-images.githubusercontent.com/4138115/103768833-83307300-5023-11eb-9b1e-868acdbcacb1.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS]
 - Version [e.g. v6.3 Update 5]

**Additional context**

**Comment by jfkonecn** [comment]
I was able to reproduce the issue on the latest commit.

Looks like there's a parsing error on the ChemoParser.vb line 66
https://github.com/DanWBR/dwsim6/blob/windows/DWSIM.Thermodynamics.Databases.ChemeoLink/ChemeoParser.vb#L66

It might be easier to solve the problem by using the API chemo offers
https://www.chemeo.com/api/v1/
